### ISSUE TITLE
unity package

### ISSUE THREAD

**Issue by IgorPanchenko-azur** [EvilMindDevs/hms-unity-plugin#1]
Hi! thank you for your work!

Are you plan to update links to unity package in readme?

**Comment by EvilMindDevs** [comment]
Hello! Thanks for your support.

Yes, we are doing a major refactoring to make the integration easier y just after that we will update all the README with more detailed information and the new unitypackage.

**Comment by EvilMindDevs** [comment]
Hi Igor,

We updated the README with more detailed info, and you can find the first version of the unitypackage under the releases section. Hope it helps.

We would keep updating with new features and improvements. Stay tuned.

**Comment by EvilMindDevs** [comment]
Closed due to in activity
