### ISSUE TITLE
Ads

### ISSUE THREAD

**Issue by HoangPV97** [EvilMindDevs/hms-unity-plugin#102]
I followed every step but the demo isn't working ,help me:

Exception: Field currentActivity or type signature not found
UnityEngine._AndroidJNIHelper.GetFieldID (System.IntPtr jclass, System.String fieldName, System.String signature, System.Boolean isStatic) (at <38f5bf63e91b4a34816606844fee3a05>:0)

**Comment by gmYusuf** [comment]
You should use:
unity 2020, 2019 or 2018.
Android SDK min 21 Net 4.x.

**Comment by HoangPV97** [comment]
Thanks !!!!!!
