### ISSUE TITLE
HMSContentProvider - Cannot install the 2nd game 

### ISSUE THREAD

**Issue by nqnhat1988** [EvilMindDevs/hms-unity-plugin#103]
Background:
I have 2 games, both of them use your plugin.
I installed 1st game succesfully.
I installed 2nd game and an error occured
![image](https://user-images.githubusercontent.com/17852328/103078523-a5c69300-4604-11eb-83cb-f1b644da55c7.png)

Root causes: Conflicting provider
Temp solution: Change the provider into unique provider.

I wonder whether it is a bug or ....

**Comment by HaseebDev** [comment]
Mainly Caused due to bad manifest file try disabling the manifest file. if it is the problem then you have to delete it and then re configure through huawie configure tab.

**Comment by nqnhat1988** [comment]
@HaseebDev yes it is. I modified the manifest file - rename the provider to unique one, or simply remove that provider.

**Comment by HaseebDev** [comment]
is it solved?

**Comment by nqnhat1988** [comment]
Yes, as I mentioned, modify the manifest could fix the issue. But I suggest to do it in the plugin instead.

**Comment by sametguzeldev** [comment]
Seems like this issue has been solved. Closing it.
