### ISSUE TITLE
IAP Problems

### ISSUE THREAD

**Issue by HaseebDev** [EvilMindDevs/hms-unity-plugin#105]
The IAP demo has 2 scripts entirely commented and I really can't see how to set up things as well, As the demo isn't working due to this issue! Under the shop----> Shopitem-----> Product1, Product2, Product3, Product4 has their scripts missing.
Ads Demo has adManager prefab missing and some scripts are missing from the demo scene as well. However, I was able to work around it because it wasn't that difficult but the IAP is what I can't get about, if I'm doing something wrong kindly, Correct me or if you know that this issue prevails you should let me know whether you will be fixing it or you just stopped working on this project.
Thanks, Btw great effort :)

**Comment by gmYusuf** [comment]
Hi, you check latest codes with downloading source as a ZIP.

**Comment by HaseebDev** [comment]
i may sound stupid but can you point me in the direction by providing the link to "Latest codes"?

**Comment by gmYusuf** [comment]
![image](https://user-images.githubusercontent.com/8115505/103279378-b39e5e80-49de-11eb-9d68-49f520ae9d60.png)

This one is source code, you can directly drag and drop to your project, under thar Assets folder.
Normally we are advising package one.

**Comment by sametguzeldev** [comment]
Hello @HaseebDev. Were you able to solve your issue or do you still need assistance about this topic ?

**Comment by HaseebDev** [comment]
> 
> 
> Hello @HaseebDev. Were you able to solve your issue or do you still need assistance about this topic?
I Wasnt able to do anything as it was exerting errors and not even the test ads would show up! the purchaser was all commented so I stopped using it. Currently, I dropped that Project just because of this :(

**Comment by sametguzeldev** [comment]
Sad to hear that. We are updating the plugin at the moment which will have a smooth implementation for all kits. But if you wish to require more assistance, I am happy to help you :)

**Comment by HaseebDev** [comment]
> 
> 
> Sad to hear that. We are updating the plugin at the moment which will have a smooth implementation for all kits. But if you wish to require more assistance, I am happy to help you :)

Once you guys are done :) ill give it a try :) Thank You anyways for reaching out after all that time :) i'd be looking forward to update. Is there anyway that I could know when you guys update the plugin?

**Comment by sametguzeldev** [comment]
> > Sad to hear that. We are updating the plugin at the moment which will have a smooth implementation for all kits. But if you wish to require more assistance, I am happy to help you :)
> 
> Once you guys are done :) ill give it a try :) Thank You anyways for reaching out after all that time :) i'd be looking forward to update. Is there anyway that I could know when you guys update the plugin?

This repo will be updated. I think it'll be released fully in April :)

**Comment by AndresCuicui** [comment]
> The IAP demo has 2 scripts entirely commented and I really can't see how to set up things as well, As the demo isn't working due to this issue! Under the shop----> Shopitem-----> Product1, Product2, Product3, Product4 has their scripts missing.
> Ads Demo has adManager prefab missing and some scripts are missing from the demo scene as well. However, I was able to work around it because it wasn't that difficult but the IAP is what I can't get about, if I'm doing something wrong kindly, Correct me or if you know that this issue prevails you should let me know whether you will be fixing it or you just stopped working on this project.
> Thanks, Btw great effort :)

Sounds like the same issue I ran into long ago. Check here: https://github.com/EvilMindDevs/hms-unity-plugin/issues/38#issuecomment-655369213
Basically uncomment, change all referencest to IAPManager to IAPDemoManager, reassign scripts and you are good to go.

**Comment by sametguzeldev** [comment]
We've released 2.x version which solves this problem.
