### ISSUE TITLE
Missing Prefabs In all Scenes.

### ISSUE THREAD

**Issue by YashVakil96** [EvilMindDevs/hms-unity-plugin#106]
Unity Version : **2018.2.10f1**
Plugin version : **HMS Unity Plugin v1.1**
Scripting Backend : **Mono** 
![image](https://user-images.githubusercontent.com/20059419/103205557-cef66480-491f-11eb-8aed-b4845c78bd52.png)
![image](https://user-images.githubusercontent.com/20059419/103205572-d9186300-491f-11eb-877a-7bdf24b4fad0.png)
![image](https://user-images.githubusercontent.com/20059419/103205583-e2a1cb00-491f-11eb-9fe8-3ea9e9b5cad4.png)
![image](https://user-images.githubusercontent.com/20059419/103205593-e9304280-491f-11eb-930b-03c9c2e6423f.png)
![image](https://user-images.githubusercontent.com/20059419/103205619-f4836e00-491f-11eb-86d0-06cb0824572a.png)
![image](https://user-images.githubusercontent.com/20059419/103205635-fe0cd600-491f-11eb-9271-45d2a9e102bc.png)

As in the above attached images, In some Scene there are missing objects too!

**Comment by sametguzeldev** [comment]
> Unity Version : **2018.2.10f1**
> Plugin version : **HMS Unity Plugin v1.1**
> Scripting Backend : **Mono**
> ![image](https://user-images.githubusercontent.com/20059419/103205557-cef66480-491f-11eb-8aed-b4845c78bd52.png)
> ![image](https://user-images.githubusercontent.com/20059419/103205572-d9186300-491f-11eb-877a-7bdf24b4fad0.png)
> ![image](https://user-images.githubusercontent.com/20059419/103205583-e2a1cb00-491f-11eb-9fe8-3ea9e9b5cad4.png)
> ![image](https://user-images.githubusercontent.com/20059419/103205593-e9304280-491f-11eb-930b-03c9c2e6423f.png)
> ![image](https://user-images.githubusercontent.com/20059419/103205619-f4836e00-491f-11eb-86d0-06cb0824572a.png)
> ![image](https://user-images.githubusercontent.com/20059419/103205635-fe0cd600-491f-11eb-9271-45d2a9e102bc.png)
> 
> As in the above attached images, In some Scene there are missing objects too!

Hello there. Did you solve your issue or still having problems ?

**Comment by YashVakil96** [comment]
> > Unity Version : **2018.2.10f1**
> > Plugin version : **HMS Unity Plugin v1.1**
> > Scripting Backend : **Mono**
> > ![image](https://user-images.githubusercontent.com/20059419/103205557-cef66480-491f-11eb-8aed-b4845c78bd52.png)
> > ![image](https://user-images.githubusercontent.com/20059419/103205572-d9186300-491f-11eb-877a-7bdf24b4fad0.png)
> > ![image](https://user-images.githubusercontent.com/20059419/103205583-e2a1cb00-491f-11eb-9fe8-3ea9e9b5cad4.png)
> > ![image](https://user-images.githubusercontent.com/20059419/103205593-e9304280-491f-11eb-930b-03c9c2e6423f.png)
> > ![image](https://user-images.githubusercontent.com/20059419/103205619-f4836e00-491f-11eb-86d0-06cb0824572a.png)
> > ![image](https://user-images.githubusercontent.com/20059419/103205635-fe0cd600-491f-11eb-9271-45d2a9e102bc.png)
> > As in the above attached images, In some Scene there are missing objects too!
> 
> Hello there. Did you solve your issue or still having problems ?
I just reimported the missing scripts and deleted the Missing Prefabs.
It works

**Comment by sametguzeldev** [comment]
Okay then closing it since it is resolved.
