### ISSUE TITLE
any plan to support native ads format?

### ISSUE THREAD

**Issue by springrider** [EvilMindDevs/hms-unity-plugin#109]
a friend told me that native ads income are a lot higher than others :)

**Comment by gmYusuf** [comment]
Hi, thank you for your feedback. For now, it's not on our road map but we will discuss this.

**Comment by ozan029** [comment]
Hi, 
are there any updates regarding the support of native ads? When will they be integrated?
Thank you

**Comment by sametguzeldev** [comment]
Hello there. I believe they will be integrated on April.

**Comment by ozan029** [comment]
Is the integration of native ads still on your to do list? If yes when will we see it in the plugin.
Thank you for your work.

**Comment by eozdemir90** [comment]
Hi there! Native ads will be ready at the beginning of December with the new version. 
Thank you for your interest in our project. You may give a star to support us and follow up on the project. You can also join our discord channel to follow changes and ask any kind of question about the plugin, gaming ecosystem, etc. You may access it from here : https://discord.io/hmsunityplugin
Thank you and stay tuned!
