### ISSUE TITLE
Need Updated Readme

### ISSUE THREAD

**Issue by EstebanVargasR** [EvilMindDevs/hms-unity-plugin#11]
Hi!

We try to implement in app purchases in our Unity Game, but we can't due to lack of information.

Could you please update Readme file in order to make a succesful purchase?

For example, there are in Readme file a method called `GetProductDetail(string productID);` but by the time I import the plugin in Unity I don't have such method.

![image](https://user-images.githubusercontent.com/22586184/82441928-06a25180-9a9f-11ea-87d6-21fdd9cc7364.png)

**Comment by m0skit0** [comment]
Hello Esteban! Sorry for the super late answer, I thought this was answered :/
IapManager does not need this method anymore, ObtainProductInfo will already return a list of ProductInfo with all available information for that product through a callback.
