### ISSUE TITLE
status.StartResolutionForResult((androidIntent)... never gets called

### ISSUE THREAD

**Issue by SteliosDaVitzi** [EvilMindDevs/hms-unity-plugin#111]
Hi!The code block "status.StartResolutionForResult((androidIntent)..." in BuyProduct method in IapManager never gets called.I've debugged most of the stuff in result, but i couldn't figure that out.
result.ErrMsg : success
result.PaymentData : null
result.PaymentSignature : null
result.ReturnCode: 0
result.Status: HuaweiMobileServices.Base.Status

payload varible is "test".Don't know what i'm supposed to use there.

![Screenshot_9_1](https://user-images.githubusercontent.com/35687170/103404102-0dc42e80-4b5b-11eb-8b32-b4953c16424e.png)

**Comment by sametguzeldev** [comment]
Hello there.
Are you still having this issue?
