### ISSUE TITLE
[HMSPlugin] SignIn failed. Exception of type 'HuaweiMobileServices.Utils.HMSException' was Thrown 

### ISSUE THREAD

**Issue by j4m4lk** [EvilMindDevs/hms-unity-plugin#113]

**Comment by Kinogoblin** [comment]
Hello, have you solved the problem?

**Comment by j4m4lk** [comment]
> Hello, have you solved the problem?

nope still no response from the devs

**Comment by Kinogoblin** [comment]
I have no error when building on my mobile

**Comment by j4m4lk** [comment]
> I have no error when building on my mobile

yea i fixed my issue somehow and now inapps are working

**Comment by j4m4lk** [comment]
> > I have no error when building on my mobile
> 
> yea i fixed my issue somehow and now inapps are working
