### ISSUE TITLE
[HMS] Interstitial ad clicked but still not loaded

### ISSUE THREAD

**Issue by j4m4lk** [EvilMindDevs/hms-unity-plugin#114]
i have integrated the SDK and fixed all issues but when i click on ShowInterstitialAd()  function it displays this message.. any help would be apreciated.

**Comment by gmYusuf** [comment]
Are testing with ads test id ? Can you share your device informations?

**Comment by admdni** [comment]
I have this problem too

HMS installed on my device
I used cloud debug.
but neither test ads nor real ads work
I have made the app gallery and adkit setup.

Unity 2019 4.18
I am using ICCP.

log image
https://ibb.co/GMvhx6h

**Comment by j4m4lk** [comment]
> Are you testing with ads test id ? Can you share your device informations?

yes i am using test ids and i am testing on huawei cloud testing.

**Comment by gmYusuf** [comment]
You should test on device which is have HMS services.

**Comment by j4m4lk** [comment]
> You should test on device which is have HMS services.

i have tested it on a hms device and it sometimes shows the test ads but sometimes it gives this error without having any changes to the code or the scene. its happening randomly most of the time .

**Comment by sametguzeldev** [comment]
> > You should test on device which is have HMS services.
> 
> i have tested it on a hms device and it sometimes shows the test ads but sometimes it gives this error without having any changes to the code or the scene. its happening randomly most of the time .

Can you provide a screenshot of the error or logs ?

**Comment by j4m4lk** [comment]
> > > You should test on device which is have HMS services.
> > 
> > 
> > i have tested it on a hms device and it sometimes shows the test ads but sometimes it gives this error without having any changes to the code or the scene. its happening randomly most of the time .
> 
> Can you provide a screenshot of the error or logs ?

it just show this same error "[HMS] Interstitial ad clicked but still not loaded" and some times it just loads properly will try to post the screens later

**Comment by sametguzeldev** [comment]
> > > > You should test on device which is have HMS services.
> > > 
> > > 
> > > i have tested it on a hms device and it sometimes shows the test ads but sometimes it gives this error without having any changes to the code or the scene. its happening randomly most of the time .
> > 
> > 
> > Can you provide a screenshot of the error or logs ?
> 
> it just show this same error "[HMS] Interstitial ad clicked but still not loaded" and some times it just loads properly will try to post the screens later

So that means you are trying to show the ad before it gets loaded. Are you getting any errors triggering this method OnAdFailed ?

**Comment by sametguzeldev** [comment]
> > > > You should test on device which is have HMS services.
> > > 
> > > 
> > > i have tested it on a hms device and it sometimes shows the test ads but sometimes it gives this error without having any changes to the code or the scene. its happening randomly most of the time .
> > 
> > 
> > Can you provide a screenshot of the error or logs ?
> 
> it just show this same error "[HMS] Interstitial ad clicked but still not loaded" and some times it just loads properly will try to post the screens later

Also about the randomness, do you get this error on your first ad or does it happen when you try to show it on second or third time ? Be sure to call LoadNextInterstitialAd() method after ad closes. OnAdClosed() can help you with that.

**Comment by j4m4lk** [comment]
> > > > > You should test on device which is have HMS services.
> > > > 
> > > > 
> > > > i have tested it on a hms device and it sometimes shows the test ads but sometimes it gives this error without having any changes to the code or the scene. its happening randomly most of the time .
> > > 
> > > 
> > > Can you provide a screenshot of the error or logs ?
> > 
> > 
> > it just show this same error "[HMS] Interstitial ad clicked but still not loaded" and some times it just loads properly will try to post the screens later
> 
> Also about the randomness, do you get this error on your first ad or does it happen when you try to show it on second or third time ? Be sure to call LoadNextInterstitialAd() method after ad closes. OnAdClosed() can help you with that.

it was just happening due to the ads not available i think since sometimes the ads might not load cuz they arent available to display, i figured it out. Thank you for your time
