### ISSUE TITLE
[HMS] Interstitial ad clicked but still not loaded

### ISSUE THREAD

**Issue by admdni** [EvilMindDevs/hms-unity-plugin#115]
Hello, Thank you for developing this ecosystem.

HMS installed on my device
I used cloud debug.
but neither test ads nor real ads work
I have made the app gallery and adkit setup.

Unity 2019 4.18
I am using ICCP.
I am using Last HMS Plugin 
log image
https://ibb.co/GMvhx6h

**Comment by sametguzeldev** [comment]
> Hello, Thank you for developing this ecosystem.
> 
> HMS installed on my device
> I used cloud debug.
> but neither test ads nor real ads work
> I have made the app gallery and adkit setup.
> 
> Unity 2019 4.18
> I am using ICCP.
> I am using Last HMS Plugin
> log image
> https://ibb.co/GMvhx6h

Hello there. We can't really help with this log because this seems to be executed on Unity Editor. Can you provide something more for us so we can work on that ?

**Comment by sametguzeldev** [comment]
Closed due to inactivity. Please re-open if the issue still persists.
