### ISSUE TITLE
AccountManager issue

### ISSUE THREAD

**Issue by pascpaul** [EvilMindDevs/hms-unity-plugin#116]
Hello, I'm trying to implement the login using the Huawei ID. I've made all the integration steps but we get the 'AndroidJavaException: java.lang.ClassNotFoundException: org.m0skit0.android.hms.unity.GenericBridgeCallback' error when calling the login() on AccountManager. Also, when we first load the scene and call AccountManager.GetInstance() we also get 'AndroidJavaException: java.lang.ClassNotFoundException: org.m0skit0.android.hms.unity.GenericBridge' error generated by the HuaweiIdAuthManager.GetService(authParams) call from AccountManager's awake function. 

Unity version: 2019.4.4f1
Plugin version: HMS Unity Plugin v1.2.0

We also use a custom proguard file.

**Comment by pascpaul** [comment]
I came back with an update, the problem was caused by the proguard file. Deactivating it solves it but we would like to keep using proguard. Is that possible? If so, what exceptions should we add to the proguard file to prevent him from touching the classes from this plugin? We added '-keep class org.m0skit0.android.hms.unity { *; }' since that is the package where the classes GenericBridge and GenericeBridgeCallback seem to be located but that doesn't help.

**Comment by sametguzeldev** [comment]
Hello there. It is because of proguard for sure. I'll test it myself and come back to you with results.

**Comment by pascpaul** [comment]
Hello again, I've solved this by adding in the proguard file the following:
-keep class org.m0skit0.android.hms.unity.** {*;}

After adding this, the error regarding the GenericBridge vanished but another one popped up(I don't have the stacktrace anymore) which I've solved with:
-keep class com.huawei.hmf.** {*;}

**Comment by sametguzeldev** [comment]
Did you had all of our kits implemented in your project ?

**Comment by sametguzeldev** [comment]
Closed due to inactivity. Please re-open if the issue still persists.

**Comment by dmichalke2** [comment]
Hello, I wanted to re-open this if possible, because we are having the same issue now.

Since 1 week, our huawei build fails again because of this error

` java.lang.ClassNotFoundException: org.m0skit0.android.hms.unity.base.StatusBridge`

Unity version: 2021.1.28f1
Plugin version: HMS Unity Plugin v2.2.4

We do NOT use a custom proguard file.

But we also tried to activate use custom proguard file and add the lines that the issue creator mentioned


```
-keep class org.m0skit0.android.hms.unity.** {*;}
-keep class com.huawei.hmf.** {*;}

```

in both cases  the error of the screenshot attached appears.

![Screenshot_20220829_144127_de spielepalast whistpalace huawei](https://user-images.githubusercontent.com/103567574/187205960-a2f30073-314c-421d-ab60-8108600e55a0.jpg)

**Comment by alihan98ersoy** [comment]
hello,

You are also getting a 6003 error. This is a fingerprint error. Is this a newly released game?

**Comment by dmichalke2** [comment]
hello, yes actually it is a newly released game in our company, but not for huawei yet because we have these issues.

**Comment by alihan98ersoy** [comment]
Okay, So I believe there is problem with your [fingerprint certificate](https://evilminddevs.gitbook.io/hms-unity-plugin/getting-started/quick-start/register-your-app-at-huawei-developer#add-fingerprint-certificate-to-appgallery-connect) in AppGallery connect.  
![Screenshot_6](https://user-images.githubusercontent.com/39373386/187212518-5adff46d-5d87-4a78-8c4c-eeda66306405.jpg)


Also releasing with aab requires App signing. When you are releasing your app can you follow [these links](https://evilminddevs.gitbook.io/hms-unity-plugin/releasing-the-game/releasing-the-game/app-bundle-format-aab-packages)?

**Comment by alihan98ersoy** [comment]
And additionally, I believe there is a bug in the fingerprint problem situation, I will test it. But when you fix the fingerprint problem. Probably you won't see this error again.

**Comment by dmichalke2** [comment]
we checked it and do have a fingerprint added in the huawei console. we got that sha256 fingerprint from the google play console after uploading our app and checking the fingerprint there. I have to mention though that I tried to extract the fingerprint again of our keystore file considering the alias we used in the keystore and the sha256 fingerprint is different to the one that we entered in the huawei console, so I'm a bit confused. 
we now entered this key to test in the huawei console but the approval will probably take some time for the build we uploaded there (at least after just saving the fingerprint, our local debug builds still dont work with this changed fingerprint).
additionally I think that 2 weeks ago the plugin was working, without even a fingerprint being added to the console, but I am not 100% sure.

**Comment by alihan98ersoy** [comment]
You need to remove your game from your phone and clear the cache of the HMS Core app.

**Comment by dmichalke2** [comment]
I always do this currently before installing test builds but it doesnt make a difference

**Comment by alihan98ersoy** [comment]
Can you build an APK and then confirm it's SHA 256 same as your project's SHA 256?

https://stackoverflow.com/a/11331951

**Comment by dmichalke2** [comment]
we just made the check and can confitm that the SHA256 of the apk is identical with the SHA256 we have entered in the project in huawei console.

**Comment by alihan98ersoy** [comment]
are you still getting 6003 error or 6003 error solved?

**Comment by dmichalke2** [comment]
it seems like when we tested today that we did not get the 6003 error. Maybe something was wrong with the SHA in the end, we are not really sure. according to the information I got from the huawei console manager, it was the one we used.. but so far it looks like it is working again

**Comment by alihan98ersoy** [comment]
Thank you for your interest in our project. You may give us a star to support and follow up on the project. You can also join our discord channel to follow changes and ask any kind of question about the plugin, gaming ecosystem, etc. You may access it from here: https://discord.io/hmsunityplugin
Thank you and stay tuned!

**Comment by PromanSEW** [comment]
> Hello, I wanted to re-open this if possible, because we are having the same issue now.
> 
> Since 1 week, our huawei build fails again because of this error
> 
> ` java.lang.ClassNotFoundException: org.m0skit0.android.hms.unity.base.StatusBridge`
> 
> Unity version: 2021.1.28f1 Plugin version: HMS Unity Plugin v2.2.4
> 
> We do NOT use a custom proguard file.
> 
> But we also tried to activate use custom proguard file and add the lines that the issue creator mentioned
> 
> ```
> -keep class org.m0skit0.android.hms.unity.** {*;}
> -keep class com.huawei.hmf.** {*;}
> ```
> 
> in both cases the error of the screenshot attached appears.
> 
I got the same error, 2021. 3.37f1 / 2.3.7
Proguard entries do not help

**Comment by Andronovo-bit** [comment]
Hi @PromanSEW , I tried 2021.3.21f (Unity version) and 2.3.7 (plugin version), and I didn't get this error. 
Can you try again?

- Do you have any special settings for your project?
 
- Was your project working before this? Did you just start getting the error?

- Which kits gives this error ?

**Comment by PromanSEW** [comment]
I try this plugin in the first time for IAP. I get this error maybe here:
```csharp
if (HMSAccountKitManager.Instance.IsSignedIn) SignInSuccess(HMSAccountKitManager.Instance.HuaweiId);
else HMSAccountKitManager.Instance.SilentSignIn();
```
I just copy-pasted code from demos to my project. I found that you should sign in to get purchases info (prices, etc), before I got another error about empty list. When i added code above, this error about class appeared.
I tried also to enable Account Kit, but error is still here. Rebuilding and clear Library/Bee also didn't give anything.
This package is absent in classes.dex

**Comment by Andronovo-bit** [comment]
I understood. If didn't see this page and video, can you look at ? Perhaps, you can see if there is a place you missed.

[Getting Started Plugin](https://evilminddevs.gitbook.io/hms-unity-plugin/getting-started/quick-start)

You may be getting these errors because you are missing something you should be doing or not doing it at all.

**Comment by PromanSEW** [comment]
Fixed this error, but now get another:
```
java.lang.ClassNotFoundException: com.huawei.hms.support.account.request.AccountAuthParams
```

**Comment by Andronovo-bit** [comment]
Did you activate "Account Kit"?

 
![image](https://github.com/EvilMindDevs/hms-unity-plugin/assets/24398592/b31d63ef-6190-432f-9dd0-98732d25391e)

**Comment by PromanSEW** [comment]
Thanks, now it works. But only with ProGuard rules:
```
-keep class org.m0skit0.android.hms.unity.** {*;}
-keep class com.huawei.hmf.** {*;}
```

**Comment by Andronovo-bit** [comment]
You're welcome. Have a good day.
