### ISSUE TITLE
Сan we check if subscription has ended?

### ISSUE THREAD

**Issue by Micro4lik** [EvilMindDevs/hms-unity-plugin#118]
I see this issue, but is out to date (26 Jun 2020):
https://github.com/EvilMindDevs/hms-unity-plugin/issues/36

Any changes or plans to implement this feature? Or another way?

**Comment by Micro4lik** [comment]
I tried this:
<img width="815" alt="Снимок экрана 2021-02-15 в 11 24 55" src="https://user-images.githubusercontent.com/34659658/107905179-94549400-6f80-11eb-8b82-829ed3be1f8f.png">

I get string, looks like something what im need, but then i get error:
<img width="865" alt="Снимок экрана 2021-02-15 в 11 25 19" src="https://user-images.githubusercontent.com/34659658/107905481-4db36980-6f81-11eb-82a5-438a0a986a45.png">

**Comment by sametguzeldev** [comment]
> I tried this:
> 
> ```
>         public void CheckSubscriptions()
>         {
>             OwnedPurchasesReq ownedPurchasesReq = new OwnedPurchasesReq()
>             {
>                 PriceType = 2
>             };
>             
>             ITask<OwnedPurchasesResult> task = iapClient.ObtainOwnedPurchases(ownedPurchasesReq);
>             task.AddOnSuccessListener((result) =>
>             {
>                 if (result.InAppPurchaseDataList != null)
>                 {
>                     Debug.Log($"there is {result.InAppPurchaseDataList.Count} purchased items");
>                     foreach (var item in result.ItemList)
>                     {
>                         Debug.Log(item);
>                     }
>                 }
> 
>                 foreach (string inAppPurchaseData in result.InAppPurchaseDataList)
>                 {
>                     Debug.Log(inAppPurchaseData);
> 
>                     InAppPurchaseData inAppPurchaseDataBean = new InAppPurchaseData(inAppPurchaseData);
> 
>                     if (inAppPurchaseDataBean.SubValid)
>                     {
>                         Debug.Log($"Subscription {inAppPurchaseDataBean.ProductName} is valid.");
>                     }
>                 }
>             });
>         }
> ```
> 
> I get string, looks like something what im need, but then i get error:
> <img alt="Снимок экрана 2021-02-15 в 11 25 19" width="865" src="https://user-images.githubusercontent.com/34659658/107905481-4db36980-6f81-11eb-82a5-438a0a986a45.png">

Hello there.
I've run the same code as you pasted here and I got not errors. Are you using the latest version ?

![image](https://user-images.githubusercontent.com/6827857/108440375-0f10fe00-7264-11eb-9821-a33e7abda2f8.png)

**Comment by Micro4lik** [comment]
I used HMS Plugin version 1.2.0.
Unity version 2019.4.14f1.

Not a very good solution, but for now I just check inAppPurchaseData.Contains("subIsvalid": true")

**Comment by sametguzeldev** [comment]
Yeah not a decent solution but still works :)
We are currently updating the plugin so tune in for updates.

Since issue is resolved. Closing it.
