### ISSUE TITLE
AdvertisingIdClient class not found

### ISSUE THREAD

**Issue by AdCCooN** [EvilMindDevs/hms-unity-plugin#123]
Hello guys,

Regarding the ads service I am interested in using the AdvertisingIdClient class in order to obtain the OAID of the client. While the AdvertisingIdClient is available in the SDK I get a runtime exception:

`AndroidJavaException: java.lang.ClassNotFoundException: com.huawei.hms.ads.identifier.AdvertisingIdClient [...]`

We are using pro-guard obfuscation and I tried adding the lines for pro-guard as they suggest at: https://developer.huawei.com/consumer/en/doc/development/HMSCore-Guides-V5/identifier-service-config-obfuscation-scripts-0000001055860586-V5

```
-keep class com.huawei.hms.ads.** { *; }
-keep interface com.huawei.hms.ads.** { *; }
```

I had no luck with those and I also tried to add specific 
`-keep class com.huawei.hms.ads.identifier.AdvertisingIdClient { *; } `
and still no luck.

This took me further and while looking on the native documentation I saw that this class requires **com.huawei.hms:ads-identifier** dependency which I don't think that it exists in the current SDK.

This should be the reason why I still get the exception?

**Comment by sametguzeldev** [comment]
Hello there!
Currently in our plugin, we don't have com.huawei.hms:ads-identifier aar file inside the project so that is why you are getting that error. I'll attach the file on this comment. Put this file under Assets >Plugins > Android folder. Currently our plugin doesn't have gradle build so you have to put this file manually. But we are updating our plugin to 2.0 version which has gradle build! We'll add this identifier into there as well!

**Comment by AdCCooN** [comment]
Thank you @sametguzeldev!

Also, I have another question. Shouldn't **ads-installreferrer** be integrated in the ads service kit of the SDK? since it is an important aspect from HUAWEI's Ads Kit.

https://developer.huawei.com/consumer/en/doc/development/HMSCore-Guides-V5/identifier-service-obtaining-installreferrer-sdk-0000001050066937-V5

**Comment by sametguzeldev** [comment]
Hmm not really. We did not have anyone asking for this feature :)

**Comment by sametguzeldev** [comment]
I am closing this issue since the main problem is solved. Please open a new one for further questions :)
