### ISSUE TITLE
Error after importing the plugin

### ISSUE THREAD

**Issue by Delcin1** [EvilMindDevs/hms-unity-plugin#124]
https://imgur.com/a/NhmTjHt
What is the problem?

**Comment by sametguzeldev** [comment]
> https://imgur.com/a/NhmTjHt
> What is the problem?

Can you download the whole repo rather than using the release package? That is outdated at the moment.
![image](https://user-images.githubusercontent.com/6827857/110965854-b1089f80-8365-11eb-83a8-d6541623c002.png)

**Comment by Delcin1** [comment]
> > https://imgur.com/a/NhmTjHt
> > В чем же проблема?
> 
> Можно ли загрузить весь репозитарий, а не использовать пакет выпуска? На данный момент это устарело.
> ![изображение](https://user-images.githubusercontent.com/6827857/110965854-b1089f80-8365-11eb-83a8-d6541623c002.png)

it didn't help

**Comment by Delcin1** [comment]
on version 2020.2.7f1, the same error occurs

**Comment by Delcin1** [comment]
Problem solved. I forgot that I already had the "Reward" script"
