### ISSUE TITLE
How can I integrate Huawei Anayltics kit in 2018

### ISSUE THREAD

**Issue by OlaruCosmin** [EvilMindDevs/hms-unity-plugin#125]
I have tried to integrate analytics in unity 2018 without success. These are the errors I get.
 
HiAnalyticsInstanceManager=> CE-001|Cannot find url from agconnect-service.json
HiAnalyticsInstance=> SE-001|Failed to initialize the Analytics Kit,other exception: analytics url is empty
 HiAnalyticsInstanceManager=> IE-003|The Analytics Kit is not initialized.

**Comment by sametguzeldev** [comment]
Hello there. Have you enabled Analytics Service from AppGallery Connect and downloaded the latest agconnect-service.json file into the project ?

**Comment by OlaruCosmin** [comment]
Hello. yes I've done that. I have followed the instructions from the documentation. I tried with the plugin v1.1.1 and v 1.2.0, same result.

**Comment by sametguzeldev** [comment]
Where did you put your agconnect-services.json file ?

**Comment by OlaruCosmin** [comment]
Currently is in "master/Assets/Plugins/Android", but I tried in "master/Assets/Plugins/Android/assets" to. 
![Screenshot 2021-03-31 093550](https://user-images.githubusercontent.com/24961171/113100837-9b6bf480-9204-11eb-84a3-aeb714b99844.png)

**Comment by sametguzeldev** [comment]
@OlaruCosmin do you still have this issue ?

**Comment by sametguzeldev** [comment]
Closed due to inactivity. Please re-open if the issue still persists.
