### ISSUE TITLE
Redundant permissions

### ISSUE THREAD

**Issue by gadzilka** [EvilMindDevs/hms-unity-plugin#126]
HuaweiMobileServices.dll in the project automatically adds some permissions to the final AndroidManifest.xml:
- ACCESS_COARSE_LOCATION
- ACCESS_FINE_LOCATION
- READ_PHONE_STATE
- WRITE_EXTERNAL_STORAGE

I'm not using location in my app, so **ACCESS_COARSE_LOCATION** and **ACCESS_FINE_LOCATION** are redundant. I assume HuaweiMobileServices.dll mentions Input.location somewhere and Unity adds this permissions automatically. 
**READ_PHONE_STATE** and **WRITE_EXTERNAL_STORAGE** are adding by HuaweiEditor.cs. Why do I need this permissions?
Is there any way to get rid of these permissions?

It's very important to me because an AppGallery reviewer asked me to explain the existence of these permissions to release the app in mainland China.

**Comment by sametguzeldev** [comment]
Hello there. Do you still have this issue?
