### ISSUE TITLE
Banner POSITION_BOTTOM_LEFT does not work

### ISSUE THREAD

**Issue by desouse** [EvilMindDevs/hms-unity-plugin#128]
Unity version - 2018.4.17f1
Plugin version (package or commit) - Commit: [c94368a], Branch: 2018
Mono or IL2CPP - IL2CPP
Test device model - P40 (Cloud Debugging)

Hello. I tried to use POSITION_BOTTOM_LEFT for displaying the banner, but it shows up in the bottom center.

I also tried other options and looks like the plugin supports only center:
POSITION_TOP_LEFT, POSITION_TOP_RIGHT - top center
POSITION_BOTTOM_RIGHT - bottom center

Could you please tell me how can I set my desired position for the banner?

**Comment by sametguzeldev** [comment]
Hello there. Right now according to my tests, currently; POSITION_BOTTOM, POSITION_TOP and POSITION_CENTER is working. LEFT or RIGHT for these positions are not working. We are working on this issue.

**Comment by alihan98ersoy** [comment]
We fixed the issue with the new version.
