### ISSUE TITLE
Banners are not positioned within the safeArea

### ISSUE THREAD

**Issue by norcmc** [EvilMindDevs/hms-unity-plugin#129]
Banners are not positioned within the safeArea.
  How could I solve this problem? Thanks

![Captura de Pantalla 2021-04-02 a la(s) 15 19 52](https://user-images.githubusercontent.com/60022843/113451213-21379d80-93c7-11eb-8afd-f73c2e7047b1.png)

**Comment by sametguzeldev** [comment]
Hello there. We are looking into this. I've tested and confirmed that it is not in safe area as well. I'll update this issue as soon as it is fixed.

**Comment by alihan98ersoy** [comment]
We fixed the issue with the new version.
