### ISSUE TITLE
v2.0 no version for Unity 2018 - not working on Unity 2018

### ISSUE THREAD

**Issue by pacoelayudante** [EvilMindDevs/hms-unity-plugin#130]
Hello
The new v2.0 package seems to not support Unity 2018
Is it planned to be supported?

In Unity 2018, there is no Android JNI package in the package manager.

cheers

**Comment by sametguzeldev** [comment]
Hello there. 2018 will be supported next week under 2.0-2018 branch.

**Comment by pacoelayudante** [comment]
great! thank you
sorry for my impatience
