### ISSUE TITLE
Release 2.0.1 Compile Error in Unity 2019

### ISSUE THREAD

**Issue by EastAsh** [EvilMindDevs/hms-unity-plugin#131]
Assets\Huawei\Scripts\IAP\UnityPurchase\HuaweiStore.cs(250,58): error CS1503: Argument 1: cannot convert from 'HuaweiMobileServices.IAP.InAppPurchaseData' to 'string'

Please fix it. Thank you very much.

**Comment by sametguzeldev** [comment]
Hello there.
Released a new version and fixed this issue. Please look for 2.0.2 version in releases section.

**Comment by EastAsh** [comment]
Ok, problem has been solved, Thank you very much.
