### ISSUE TITLE
Question: Splash Screen Ad ¿supported?¿future support?

### ISSUE THREAD

**Issue by pacoelayudante** [EvilMindDevs/hms-unity-plugin#133]
Hola, I wanted to check the state of the Splash Ad on the plugin
I believe it is not currently supported ¿right?
And I was also wondering if it's planned to have it supported on the plugin at some point in the future. I can guess it might be hard or impossible since loading is almost exclusively controlled by the Unity Engine, so I wanted to know if there are plans about this feature.
Best Regards

**Comment by sametguzeldev** [comment]
Hello there,
Right now we are supporting Banner, Interstitial and Rewarded Ads. I believe the next supported ad will be Native Ads. After that we can check into Splash Ads.
