### ISSUE TITLE
Banner Test Ad with Smart Size on Landscape - failed to load (code 3)

### ISSUE THREAD

**Issue by pacoelayudante** [EvilMindDevs/hms-unity-plugin#134]
Hola,
sorry to keep bothering jaja

I have a situation that I am not sure if it is a problem with the Unity plugin or with the HMS
(using Unity 2020.3.4)
Trying to load a Banner Ad with Smart Size when the app is in landscape mode results in the Code Error 3, which according to Huawei docs is "The ad request is successful, but the server does not return any available ad asset"

However, when using one of the fixed sizes (the default one, for example: 320x50) the banner loads correctly, and it looks fine in portrait, but it looks disproportionate in landscape, rather large.
Another useful info is that loading the Banner Smart Size when the app is in portrait, it loads is successfully, but when changing the app to landscape again, the banner seems disproportionate as in the fixed size case.

This is all with test ads, I have yet to test it with normal ads, but I haven't been able to get those working yet
(the interstitial, and rewarded test ads work normally, btw)

Here are some screenshots of the resulting size in portrait and in landscape. Notice how much space the ad covers in landscape
![Screenshot_20210419-143731_borrame](https://user-images.githubusercontent.com/9141115/115285104-dc7c6800-a123-11eb-95bf-ec87a87dbeda.jpg)
![Screenshot_20210419-143743_borrame](https://user-images.githubusercontent.com/9141115/115285107-dd14fe80-a123-11eb-945f-d96bf946b331.jpg)

Best Regards

**Comment by pacoelayudante** [comment]
I just found in another repo (HSM Core Java) an issue that seems to be the same and the conclusion is that there may not be a Test Ad for the size the Smart Banner ends up requesting
https://github.com/HMS-Core/hms-ads-demo-java/issues/10
This would confirm the issue is not with this plugin, but I propose leaving this issue for documentation purposes

**Comment by sametguzeldev** [comment]
Yes I am actually aware of this issue. If you want to use banner ads landscape without bug, you need to change HMSGradleWorker and use older version of ads-banner. You can use ads-banner-13.4.28.305 which doesn't have this problem. We've updated to the latest version and it has a bug unfortunately :)

**Comment by xdorf88** [comment]
> Yes I am actually aware of this issue. If you want to use banner ads landscape without bug (visual bug that covers entire bottom screen), you need to change HMSGradleWorker and use older version of ads-banner. You can use ads-banner-13.4.28.305 which doesn't have this problem. I also changed the ads-base one that is matching with ads-banner version but I am not sure if that is necessary. We've updated to the latest version and it has a bug unfortunately :)



Hello, 
I  want to confirm that it's working what you suggested   "change HMSGradleWorker and use older version of ads-banner. You can use ads-banner-13.4.28.305" 

Thank you so much!

**Comment by sametguzeldev** [comment]
I think we'll update it to use the older version until the newer version fixes this issue.

**Comment by pacoelayudante** [comment]
Well, actually, there is this thing: It seems that in order to use Test Devices (like with real ad units) there is a version requirement above 13.4.36.300
> The device testing service requires the app SDK version to be 13.4.36.300 or later and HMS Core (APK) version to be 5.1.0.300 or later.

Docs: https://developer.huawei.com/consumer/en/doc/distribution/monetize/release-0000001050961874

**Comment by sametguzeldev** [comment]
> Well, actually, there is this thing: It seems that in order to use Test Devices (like with real ad units) there is a version requirement above 13.4.36.300
> 
> > The device testing service requires the app SDK version to be 13.4.36.300 or later and HMS Core (APK) version to be 5.1.0.300 or later.
> 
> Docs: https://developer.huawei.com/consumer/en/doc/distribution/monetize/release-0000001050961874

Yeah that is true. If I downgrade it, users will have to test it with testIds that are included in the plugin rather than testing with real ad Ids. I just tried the newer version 13.4.40.302 but banner issue is still there.

**Comment by xdorf88** [comment]
> Well, actually, there is this thing: It seems that in order to use Test Devices (like with real ad units) there is a version requirement above 13.4.36.300
> 
> > The device testing service requires the app SDK version to be 13.4.36.300 or later and HMS Core (APK) version to be 5.1.0.300 or later.
> 
> Docs: https://developer.huawei.com/consumer/en/doc/distribution/monetize/release-0000001050961874

I am testing it in the Cloud debugging and it's working but not smart banner.  I am talking about the standard banner size.
I also tried the real ads ids in the could debugging and it worked for me.

**Comment by pacoelayudante** [comment]
> > Well, actually, there is this thing: It seems that in order to use Test Devices (like with real ad units) there is a version requirement above 13.4.36.300
> > > The device testing service requires the app SDK version to be 13.4.36.300 or later and HMS Core (APK) version to be 5.1.0.300 or later.
> > 
> > 
> > Docs: https://developer.huawei.com/consumer/en/doc/distribution/monetize/release-0000001050961874
> 
> I am testing it in the Cloud debugging and it's working (in landscape) but not smart banner. I am talking about the standard banner size.
> I also tried the real ads ids in the could debugging and it worked for me.

yes, I can confirm too.
@sametguzeldev you were right about downgrading. Maybe there should be a note or something in the docs about this regardless.

**Comment by sasa2701** [comment]
Hi im also having banner landscape problem, my banner is to big, im not so expirience in coding so i must open HMSGradleWorker and change ads-lite xx.x.xx.xxx  to ads-lite-13.4.28.305???
so my code code part looks like this:
 { AdsToggleEditor.AdsKitEnabled, new string[]{ "com.huawei.hms:ads-lite:13.4.28.305", "com.huawei.hms:ads-consent:3.4.39.302", "com.huawei.hms:ads-identifier:3.4.39.302" } }, now seems ok when i run test ads, will it work for real ads??

**Comment by sametguzeldev** [comment]
If test ads are working, real ads should work too. But real ads can fail to load due to filling rate issue on some countries.

**Comment by sasa2701** [comment]
Yes i looked at the stats and in my country it does not works, i have many ad requests but 0 returned ads. And i see in other countries that it working fine, so you are right seems its filling rate or Huawei side issue.

**Comment by imtiaz791** [comment]
Hi,
   Banner ad show large size, i am use 320*50 ad size but banner ad cover half screen. My HMS version V2.0.8-2019-2020.
