### ISSUE TITLE
Methods of IStoreCallback are not called on the main thread

### ISSUE THREAD

**Issue by gadzilka** [EvilMindDevs/hms-unity-plugin#136]
For example, OnPurchaseSucceeded in HuaweiStore.PurchaseInitentCreated is not called on the main thread. It can crash if you try to do something with GameObjects in implementation of IStoreLister.ProcessPurchase.

Stack Trace:
```
    IAPManagerUnity:ProcessPurchase(PurchaseEventArgs)
    UnityEngine.Purchasing.PurchasingManager:ProcessPurchaseIfNew(Product)
    System.Action`1:Invoke(T)
    System.Reflection.MonoMethod:Invoke(Object, BindingFlags, Binder, Object[], CultureInfo)
    UnityEngine.AndroidJavaProxy:Invoke(String, Object[])
    UnityEngine._AndroidJNIHelper:InvokeJavaProxyMethod(AndroidJavaProxy, IntPtr, IntPtr)
```

**Comment by sametguzeldev** [comment]
Hello there.
Currently, our SDK's success and failure callbacks are not getting called from Unity's main thread. We are looking into this problem.

**Comment by sametguzeldev** [comment]
Hello there. We've recently updated our plugin to 2.0.6 version that could resolve this error. Are you using 1.x version or 2.x version of the plugin ?

**Comment by sametguzeldev** [comment]
This is fixed on newer versions.
