### ISSUE TITLE
The callback OnAdClosed never called

### ISSUE THREAD

**Issue by perekstig** [EvilMindDevs/hms-unity-plugin#14]
There is a typo in InterstitialAdsManager, line 29, it should say      mAdsManager.OnAdClosed?.Invoke();
and not
mAdsManager.OnAdClicked?.Invoke();

**Comment by m0skit0** [comment]
Correct, fixed in commit 46f08f745bf49723ca899332c5f3f92eb2774f92

Next time you might consider creating a pull request :)
