### ISSUE TITLE
IAP Cancelling Purchase (on sandbox testing) Error

### ISSUE THREAD

**Issue by pacoelayudante** [EvilMindDevs/hms-unity-plugin#140]
I'm using Unity 2020.3.6, IL2CPP
When doing a buy operation the code throws an error
> purchaseResultInfo.InAppPurchaseData Attempt to invoke virtual method 'int java.lang.String.length()'

I tracked it to this portion of code
https://github.com/EvilMindDevs/hms-unity-plugin/blob/7028d8a6a7533081fdd49022067d9cd1c7ae53a1/Assets/Huawei/Scripts/IAP/HMSIAPManager.cs#L254-L255
The error is triggered when I cancel a purchase intent. I only tested this on Sandbox Testing, no idea if it also happens on Production.

I solved it by commenting those lines (which are just logs so no problem). My guess is that when the purchase is cancelled, there should not be attempts to retrieve that data.

**Comment by sametguzeldev** [comment]
Hello there.
Those log lines should be in OrderStatusCode.ORDER_STATE_SUCCESS if actually. Thank you for pointing this out.
We'll fix this issue on the new version.

**Comment by sametguzeldev** [comment]
This issue has been solved on #142 / #141
