### ISSUE TITLE
Is the source of HuaweiMobileServices.dll available?

### ISSUE THREAD

**Issue by ltomov** [EvilMindDevs/hms-unity-plugin#144]
Hi, I'd like to implement a stripped-down version of this plugin into my project and I see that the code relies on this .dll: 
https://github.com/EvilMindDevs/hms-unity-plugin/blob/master/Assets/Huawei/Dlls/HuaweiMobileServices.dll

Is the source code of this file available somewhere?

Thanks!

**Comment by sametguzeldev** [comment]
Hello there.
Yes it is available here : https://github.com/EvilMindDevs/hms-sdk-unity

**Comment by ltomov** [comment]
Awesome, thanks a lot!
