### ISSUE TITLE
IAP Error on envReady

### ISSUE THREAD

**Issue by FoolishEL** [EvilMindDevs/hms-unity-plugin#148]
Hi there. I'v faced an error "HMSPlugin]: Error on EnvReady".
And I have no clue what's wrong.
there is no more info so I can't work with.
I did all the readme says.
Could you help me determin where's problem.
also theres an error "[HMSDispatcher] An instance is needed in the scene and no existing..."
and almost the same time some black screen appears and it won't disappear til I press back.

**Comment by sametguzeldev** [comment]
Hello there. "[HMSDispatcher] An instance is needed in the scene and no existing..." this is not an error actually. It is to tell you that a dispatcher is getting created. Could you please share your device log via logcat so we can go from there?

**Comment by FoolishEL** [comment]
[Log.txt](https://github.com/EvilMindDevs/hms-unity-plugin/files/6583826/Log.txt)

**Comment by sametguzeldev** [comment]
Could you please share the whole log without filtering it?

**Comment by FoolishEL** [comment]
[Log.txt](https://github.com/EvilMindDevs/hms-unity-plugin/files/6583857/Log.txt)
Sorry. Here you go

**Comment by sametguzeldev** [comment]
Do you have AndroidManifest.xml file in your unity project? Also, make sure to have your agconnect-services.json file under Assets/StreamingAssets folder.
It seems like HMSSDK cannot read client/appid that is in agconnect-services.json file.

**Comment by FoolishEL** [comment]
I do have AndroidManifest.xml and agconnect-services.json in right folder.

**Comment by FoolishEL** [comment]
I'v imported 2.05v and updated to 2.06v

**Comment by FoolishEL** [comment]
it seems that problem was in Unity Version.
I used 2019.2.21f1
after update to 2019.4.15f problem with agconnect-services.json file gone
but Error on envReady still exists

**Comment by sametguzeldev** [comment]
Can you share a new log with us in 2019.4.15f version ?

**Comment by FoolishEL** [comment]
[Log.txt](https://github.com/EvilMindDevs/hms-unity-plugin/files/6589786/Log.txt)
here you go

**Comment by sametguzeldev** [comment]
Okay it seems like you are getting 6003 error. Now you have something to work on 😄 
![image](https://user-images.githubusercontent.com/6827857/120606898-565c7c80-c458-11eb-8ec2-b8006cbc851c.png)
There are several causes for this error to happen.
Can you change the line 60 in HMSIAPManager.cs file from ` Debug.Log("[HMSPlugin]: Error on EnvReady");` to `Debug.LogError("[HMSPlugin]: Error on EnvReady. " + exception.WrappedCauseMessage + ", " + exception.WrappedExceptionMessage);`
https://github.com/EvilMindDevs/hms-unity-plugin/blob/0539a824af66b45fdbc0f4ee905b862af416f280/Assets/Huawei/Scripts/IAP/HMSIAPManager.cs#L55-L65

After this change, send me a log again and lets see if it is the same 6003 error. We are currently changing all of our error logs to have better explanation about them.

Also, are you signing your app with the same SHA256 key that you've registered to AGC ?
![image](https://user-images.githubusercontent.com/6827857/120608493-eea73100-c459-11eb-8e65-fa7a9f81206f.png)

**Comment by FoolishEL** [comment]
Iv got it.
Some postprocessing scripts messed it up.
And json file were in wrong folder

**Comment by FoolishEL** [comment]
But it wasn't so obvious.
I guess more detailed logs would be really helpfull.
Thanks for helping!

**Comment by sametguzeldev** [comment]
You are welcome!
