### ISSUE TITLE
Problems with Game Services and Plugin Dll not work with il2cpp

### ISSUE THREAD

**Issue by mrkaratechamp** [EvilMindDevs/hms-unity-plugin#15]
Hi, first, thanks for this plugin!, really need!.
I notice that it's impossible to run in il2cpp unity config, that's means only will work to make armv7 builds.

second, I succefull test the login part (using my own game create on huawei gallery app), but after login, I try to connect to game services, I already create achievements and leaderdboards, using that ids, but no matter what I always got an error callback, no errors during the services initialitation (player info works), but when I try to get achivemenents or unlock achievement or got a leaderboard,  I always got this callback:
ShowAchievements ERROR Exception of type 'HuaweiMobileServices.Utils.HMSException' was thrown. 

someone experienced this? is a plugin problem? or maybe some other thing?

ps: I already try all plugins, the release one, and dowload current build, test with both dlls, 2018, and 2019, over unity 2018.3.7 and 2019.3.0f5 and same results

thanks!

**Comment by mrkaratechamp** [comment]
hi again!.   I fix the il2cpp problem, using the source code from your reppo @m0skit0 , so thanks!, using only the source files (without unity dlls), and no compiled dll, can make a 64 bits build!

but the problem with leaderboards and achivements is still there, I tried everything, I'm 100% sure my data is correct because I already login succefull, I can get player Data too, but show or trying to bring achivements info, is always same callback error, and no info, can this be a plugin failure or there's something I'm missing? is someone working with achivements and leaderboards succefull??
please let me know, and if there's something I can test to help, just let me know

thanks!

**Comment by m0skit0** [comment]
Hmmm that's strange. DLLs here are actually generated from that repository. Maybe the generated DLLs are not 64-bits? If you're using the source code from my repo maybe you can log the actual exception being thrown by the Java HMS SDK? I was planning to check this today since other people reported the same but I had no time, sorry.

**Comment by m0skit0** [comment]
Did you check if latest packages solve your problem?

**Comment by luckynamal** [comment]
> hi again!. I fix the il2cpp problem, using the source code from your reppo @m0skit0 , so thanks!, using only the source files (without unity dlls), and no compiled dll, can make a 64 bits build!
> 
> but the problem with leaderboards and achivements is still there, I tried everything, I'm 100% sure my data is correct because I already login succefull, I can get player Data too, but show or trying to bring achivements info, is always same callback error, and no info, can this be a plugin failure or there's something I'm missing? is someone working with achivements and leaderboards succefull??
> please let me know, and if there's something I can test to help, just let me know
> 
> thanks!

Hi Bro. bro i am trying to sign in but this exception is being thrown "'HuaweiMobileServices.Utils.HMSException' was thrown." how can i handle this please guide me

**Comment by songtri** [comment]
> > hi again!. I fix the il2cpp problem, using the source code from your reppo @m0skit0 , so thanks!, using only the source files (without unity dlls), and no compiled dll, can make a 64 bits build!
> > but the problem with leaderboards and achivements is still there, I tried everything, I'm 100% sure my data is correct because I already login succefull, I can get player Data too, but show or trying to bring achivements info, is always same callback error, and no info, can this be a plugin failure or there's something I'm missing? is someone working with achivements and leaderboards succefull??
> > please let me know, and if there's something I can test to help, just let me know
> > thanks!
> 
> Hi Bro. bro i am trying to sign in but this exception is being thrown "'HuaweiMobileServices.Utils.HMSException' was thrown." how can i handle this please guide me

try setting SHA-256 certificate fingerprint from your Project setting at AppGallery Connect. I had the same issue but after I set the fingerprint I could sign in.
