### ISSUE TITLE
Sandbox IAP testing

### ISSUE THREAD

**Issue by FoolishEL** [EvilMindDevs/hms-unity-plugin#150]
I'v faced an issue that I can't test IAP purchasing in sandbox. Window with purchase shown properly and display all info, but theres nothing about sandbox and I can only buy it for full price.
After some research in HUAWEI developer page
https://developer.huawei.com/consumer/en/doc/development/HMSCore-References-V5/iapclient-0000001050137587-V5#EN-US_TOPIC_0000001050137587__section236817311277
I found some code that able to display info about sandbox. Also in your other project hms-sdk-unity is code that allow to do the same. 
So after all I have some questions. 
Does this plugin allow to sandbox buy IAP? 
And if so is there some opportunity to know what's wrong with sandbox?

**Comment by sametguzeldev** [comment]
Hello there.
Yes our plugin supports Sandbox testing.
Before testing, you need to add test accounts which are real Huawei IDs. You can add under Users and permissions in App Gallery Connect.
![image](https://user-images.githubusercontent.com/6827857/121651376-373a9c00-caa3-11eb-8e62-953092bef54e.png)


More detailed docs are here : https://developer.huawei.com/consumer/en/doc/development/HMSCore-Guides/sandbox-testing-0000001050035039

**Comment by FoolishEL** [comment]
Thanks, but what about second question?
Does this plugin can do thomething like this:
https://github.com/EvilMindDevs/hms-sdk-unity/blob/master/hms-sdk-unity/HuaweiMobileServices/IAP/IsSandboxActivatedResult.cs

**Comment by sametguzeldev** [comment]
Partly yes, since It was me who implemented IsSandboxActivatedResult class 😄 
But right now it is not added to the manager of the plugin. I'll be adding it today and probably releasing a new version tomorrow.

**Comment by FoolishEL** [comment]
Thanks a lot!!

**Comment by FoolishEL** [comment]
Well, that's what I got
E/Unity: AndroidJavaException: java.lang.NoSuchMethodError: no non-static method with name='isSandboxActivated' signature='()Ljava/lang/Object;' in class Ljava.lang.Object;

**Comment by sametguzeldev** [comment]
Can you open this as a new issue since it is a different error? So people who get this error can find the solution?

**Comment by sametguzeldev** [comment]
Also, can you provide logs so we can look into it better?

**Comment by FoolishEL** [comment]
I just try it now.
[log.txt](https://github.com/EvilMindDevs/hms-unity-plugin/files/6661028/log.txt)

**Comment by sametguzeldev** [comment]
Yes I've checked it and you are correct. This is an issue on the SDK side actually. I've fixed it. Probably I'll release a new version today and you can check 2.0.7(new version).

**Comment by FoolishEL** [comment]
thanks
