### ISSUE TITLE
In-apps Unity 2020.3 (LTS)

### ISSUE THREAD

**Issue by Frizord** [EvilMindDevs/hms-unity-plugin#151]
![photo_2021-06-15 12 41 44](https://user-images.githubusercontent.com/33530101/122031267-383b3880-cdd7-11eb-9aab-5b9217440338.jpeg)
![photo_2021-06-15 12 41 49](https://user-images.githubusercontent.com/33530101/122031284-3b362900-cdd7-11eb-9444-0b06b8032250.jpeg)
![photo_2021-06-14 18 11 31](https://user-images.githubusercontent.com/33530101/122027414-c6152480-cdd3-11eb-9c63-475e080fa2af.jpeg)

Hello.
I am integrate an in-app service for my game, completed the steps with filling in the information on the account, set up bundles, added bundles to Unity, added a sha-265 key. When I try to make a purchase on my phone, I get an error:
Specified: "bundleID" could not be found in retrieved product list!
After initialization the service in the logs "success".
Also the project without unity purchasing and UDP.
Any ideas?
Thanks!

**Comment by sametguzeldev** [comment]
Hello there.
Have you added your products via editor? You can reference the picture below.
![Capture](https://user-images.githubusercontent.com/6827857/122044445-2eb8cd00-cde5-11eb-9bd3-c67d784b3f19.PNG)

**Comment by Frizord** [comment]
Hello!
Yes, I am added product at editor
![photo_2021-06-14 18 13 01](https://user-images.githubusercontent.com/33530101/122044754-8bb48300-cde5-11eb-80ae-b0583a63f16f.jpeg)

**Comment by sametguzeldev** [comment]
Nice.

**Comment by Frizord** [comment]
Yes.
![photo_2021-06-15 14 28 40](https://user-images.githubusercontent.com/33530101/122045122-02518080-cde6-11eb-884b-aa4c0676f6c4.jpeg)

**Comment by sametguzeldev** [comment]
Okay, everything seems fine. Can you provide me logs from the device so we can check this part on the image? It should get more products from AGC.

Also you replaced the Assets/StreamingAssets/agconnect-services.json file with your own project's json file right ?

![image](https://user-images.githubusercontent.com/6827857/122045606-a3403b80-cde6-11eb-8087-810cdfc6af92.png)

**Comment by Frizord** [comment]
Also you replaced the Assets/StreamingAssets/agconnect-services.json file with your own project's json file right ?
Yes, Im download the .json file from console at website.

**Comment by sametguzeldev** [comment]
Okay if you can provide some logs that I can look into, would be wonderful.

**Comment by Frizord** [comment]
Im edit my message upper, sorry.

**Comment by sametguzeldev** [comment]
That log does not contain anything about HMSPlugin unfortunately 😢 
But I suggest you to use Android Logcat package provided by Unity.
Go to PackageManager. Then Unity Registry. Select AndroidLogcat and install.
![Untitled](https://user-images.githubusercontent.com/6827857/122047267-9886a600-cde8-11eb-9672-3cb4b5c8b0fc.png)

After that, Press Alt + 6 or go to Window > Analysis > Android Logcat.
![Untitled2](https://user-images.githubusercontent.com/6827857/122047379-c23fcd00-cde8-11eb-9e7d-acd7140fd920.png)

In this editor, select the device that you plugged into your PC(1). then select your unity application(2). Right click to editor and press Select All or press Ctrl + A on your keyboard. Again right click with your mouse and press Save Selection. Upload your saved log here again 😄 
![Untitled3](https://user-images.githubusercontent.com/6827857/122047640-0af78600-cde9-11eb-88df-7e4c8d74a98d.png)

**Comment by Frizord** [comment]
Found an error, the types of purchases do not match in Unity and in the console :(
Thanks a lot!!!

**Comment by sametguzeldev** [comment]
Ahaha yes I did not check that actually :D your product types does not match 😄 

![image](https://user-images.githubusercontent.com/6827857/122048921-87d72f80-cdea-11eb-8141-1c59fe3a0d09.png)

**Comment by Frizord** [comment]
Thanks for help!
Bye!)
