### ISSUE TITLE
Enabling App Messaging causes crash during build

### ISSUE THREAD

**Issue by catinjar** [EvilMindDevs/hms-unity-plugin#156]
Hi!

I enabled App Messaging in plugin's settings and tried to build my project. I ended up with getting a crash during execution of build's preprocessor:
```
public void PrepareGradleFile()
{
    Settings settings = HMSMainEditorSettings.Instance.Settings;
    List<string> gradle = new List<string>(CoreGradles());
    for (int i = 0; i < settings.Keys.Count(); i++)
    {
        if (settings.Values.ElementAt(i) == true.ToString())
        {
            gradle.AddRange(gradleSettings[settings.Keys.ElementAt(i)]);
        }
    }
    CreateGradleFiles(gradle.ToArray());
}
```

It happened because **gradleSettings** doesn't contain a key for App Messaging. I got it fixed by adding following data to **gradleSettings**:
`{ AppMessagingToggleEditor.AppMessagingEnabled, new string[] { "com.huawei.agconnect:agconnect-appmessaging:1.4.2.301" } }`

**Comment by sametguzeldev** [comment]
Hello there.
Yes you are correct. We forgot to add it 😄 If you want you can make a PR about this to contribute into the repo or I can make a push about this :)

Thank you again for finding this issue!

**Comment by catinjar** [comment]
Hello,

Sorry for a very late response. I think, it's better for you to fix this issue by yourself and check other parts of plugin for thind kind of problem.

**Comment by sametguzeldev** [comment]
Fixing this is 2.0.9 version.
