### ISSUE TITLE
Exception: Field currentActivity or type signature  not found

### ISSUE THREAD

**Issue by zqbxniu** [EvilMindDevs/hms-unity-plugin#157]
Hello, I made an error while debugging the ad.
Tried unity2020 and unity2019 will produce this error
I am debugging in accordance with the process given here, but this error still occurs.
https://github.com/EvilMindDevs/hms-unity-plugin/
 How can I solve this problem? The detailed tips are as follows:

**Exception: Field currentActivity or type signature  not found
UnityEngine._AndroidJNIHelper.GetFieldID (System.IntPtr jclass, System.String fieldName, System.String signature, System.Boolean isStatic) (at <b69cf5685dff454c8f3ed00ac9525a17>:0)
UnityEngine.AndroidJNIHelper.GetFieldID (System.IntPtr javaClass, System.String fieldName, System.String signature, System.Boolean isStatic) (at <b69cf5685dff454c8f3ed00ac9525a17>:0)
UnityEngine._AndroidJNIHelper.GetFieldID[ReturnType] (System.IntPtr jclass, System.String fieldName, System.Boolean isStatic) (at <b69cf5685dff454c8f3ed00ac9525a17>:0)
UnityEngine.AndroidJNIHelper.GetFieldID[FieldType] (System.IntPtr jclass, System.String fieldName, System.Boolean isStatic) (at <b69cf5685dff454c8f3ed00ac9525a17>:0)
UnityEngine.AndroidJavaObject._GetStatic[FieldType] (System.String fieldName) (at <b69cf5685dff454c8f3ed00ac9525a17>:0)
UnityEngine.AndroidJavaObject.GetStatic[FieldType] (System.String fieldName) (at <b69cf5685dff454c8f3ed00ac9525a17>:0)
HuaweiMobileServices.Utils.AndroidContext.get_ActivityContext () (at <27364de07bd74b13a408b9210debe6ba>:0)
HuaweiMobileServices.Ads.HwAds.Init () (at <27364de07bd74b13a408b9210debe6ba>:0)
HMSAdsKitManager.Init () (at Assets/Huawei/Scripts/Ads/HMSAdsKitManager.cs:33)
HMSAdsKitManager.Start () (at Assets/Huawei/Scripts/Ads/HMSAdsKitManager.cs:27)**

**Comment by zqbxniu** [comment]
unity 2020, 2019 or 2018.
Android SDK min 21 Net 4.x.

i try this but it still not wrok
<img width="1113" alt="华为ads" src="https://user-images.githubusercontent.com/41951478/125161533-7ac51a80-e1b5-11eb-89c9-efadcf11e5a6.png">

**Comment by sametguzeldev** [comment]
Hello there.
Can you provide us some device logs ?
Also when it happens ? What method do you call ?

**Comment by sametguzeldev** [comment]
Oh, you need to Enable Banner Ads to see Banner ads. That goes for the other ad types as well.

**Comment by zqbxniu** [comment]
This is unity's entire blog about this error at the moment：


Exception: Field currentActivity or type signature&nbsp; not found
UnityEngine._AndroidJNIHelper.GetFieldID (System.IntPtr jclass, System.String fieldName, System.String signature, System.Boolean isStatic) (at <e2fcf4f110424f58ac607d4fd98ed223&gt;:0)
UnityEngine.AndroidJNIHelper.GetFieldID (System.IntPtr javaClass, System.String fieldName, System.String signature, System.Boolean isStatic) (at <e2fcf4f110424f58ac607d4fd98ed223&gt;:0)
UnityEngine._AndroidJNIHelper.GetFieldID[ReturnType] (System.IntPtr jclass, System.String fieldName, System.Boolean isStatic) (at <e2fcf4f110424f58ac607d4fd98ed223&gt;:0)
UnityEngine.AndroidJNIHelper.GetFieldID[FieldType] (System.IntPtr jclass, System.String fieldName, System.Boolean isStatic) (at <e2fcf4f110424f58ac607d4fd98ed223&gt;:0)
UnityEngine.AndroidJavaObject._GetStatic[FieldType] (System.String fieldName) (at <e2fcf4f110424f58ac607d4fd98ed223&gt;:0)
UnityEngine.AndroidJavaObject.GetStatic[FieldType] (System.String fieldName) (at <e2fcf4f110424f58ac607d4fd98ed223&gt;:0)
HuaweiMobileServices.Utils.AndroidContext.get_ActivityContext () (at <215ffb40c29c4bf19276ccbd420e921a&gt;:0)
HuaweiMobileServices.Ads.HwAds.Init () (at <215ffb40c29c4bf19276ccbd420e921a&gt;:0)
HMSAdsKitManager.Init () (at Assets/Huawei/Scripts/Ads/HMSAdsKitManager.cs:33)
HMSAdsKitManager.Start () (at Assets/Huawei/Scripts/Ads/HMSAdsKitManager.cs:27)





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "EvilMindDevs/hms-unity-plugin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月13日(星期二) 晚上8:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [EvilMindDevs/hms-unity-plugin] Exception: Field currentActivity or type signature  not found (#157)





 
Oh, you need to Enable Banner Ads to see Banner ads. That goes for the other ad types as well.

**Comment by zqbxniu** [comment]
This is the demo that I have not made any configuration, directly using the demo you gave


New information has emerged


[HMS] AdsDemoManager ShowRewardedAd
UnityEngine.Debug:Log(Object)
AdsDemoManager:ShowRewardedAd() (at Assets/Huawei/Demos/Ads/AdsDemoManager.cs:33)
UnityEngine.EventSystems.EventSystem:Update() (at E:/program files/unity201/Editor/Data/Resources/PackageManager/BuiltInPackages/com.unity.ugui/Runtime/EventSystem/EventSystem.cs:376)















------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "流云"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月13日(星期二) 晚上9:07
***@***.******@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;回复： [EvilMindDevs/hms-unity-plugin] Exception: Field currentActivity or type signature  not found (#157)



This is unity's entire blog about this error at the moment：


Exception: Field currentActivity or type signature&nbsp; not found
UnityEngine._AndroidJNIHelper.GetFieldID (System.IntPtr jclass, System.String fieldName, System.String signature, System.Boolean isStatic) (at <e2fcf4f110424f58ac607d4fd98ed223&gt;:0)
UnityEngine.AndroidJNIHelper.GetFieldID (System.IntPtr javaClass, System.String fieldName, System.String signature, System.Boolean isStatic) (at <e2fcf4f110424f58ac607d4fd98ed223&gt;:0)
UnityEngine._AndroidJNIHelper.GetFieldID[ReturnType] (System.IntPtr jclass, System.String fieldName, System.Boolean isStatic) (at <e2fcf4f110424f58ac607d4fd98ed223&gt;:0)
UnityEngine.AndroidJNIHelper.GetFieldID[FieldType] (System.IntPtr jclass, System.String fieldName, System.Boolean isStatic) (at <e2fcf4f110424f58ac607d4fd98ed223&gt;:0)
UnityEngine.AndroidJavaObject._GetStatic[FieldType] (System.String fieldName) (at <e2fcf4f110424f58ac607d4fd98ed223&gt;:0)
UnityEngine.AndroidJavaObject.GetStatic[FieldType] (System.String fieldName) (at <e2fcf4f110424f58ac607d4fd98ed223&gt;:0)
HuaweiMobileServices.Utils.AndroidContext.get_ActivityContext () (at <215ffb40c29c4bf19276ccbd420e921a&gt;:0)
HuaweiMobileServices.Ads.HwAds.Init () (at <215ffb40c29c4bf19276ccbd420e921a&gt;:0)
HMSAdsKitManager.Init () (at Assets/Huawei/Scripts/Ads/HMSAdsKitManager.cs:33)
HMSAdsKitManager.Start () (at Assets/Huawei/Scripts/Ads/HMSAdsKitManager.cs:27)





------------------ 原始邮件 ------------------
发件人:                                                                                                                        "EvilMindDevs/hms-unity-plugin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月13日(星期二) 晚上8:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [EvilMindDevs/hms-unity-plugin] Exception: Field currentActivity or type signature  not found (#157)





 
Oh, you need to Enable Banner Ads to see Banner ads. That goes for the other ad types as well.

**Comment by sametguzeldev** [comment]
> Thank you for your reply, I just imported the package, opened the demo, and then followed your tutorial to appear this I tried different unity versions 2019 and 2020, and I also tried importing only package v2.0.8 - Unity 2019/2020, and then opening demo would report the same error, and besides, are you this project supported by Huawei officials, because I'm in China, I've also approached Huawei officials, who say they don't support unity version of sdk in China yet Because this error has always been, I guess it should be and unity has some kind of incompatibility, should have nothing to do with the game code itself, should be and unity settings, and plug-in settings have something to do with Looking forward to your reply, thank you very much
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "EvilMindDevs/hms-unity-plugin" ***@***.***&gt;; 发送时间:&nbsp;2021年7月13日(星期二) 晚上8:42 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [EvilMindDevs/hms-unity-plugin] Exception: Field currentActivity or type signature not found (#157) Oh, you need to Enable Banner Ads to see Banner ads. That goes for the other ad types as well. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

This Plugin is not official yet but we are working on it to make it official and changing stuff based on Huawei HQ wants. 

But this error is not tied to Unity actually. Are you using this plugin on an empty project ?

**Comment by sametguzeldev** [comment]
> This is the demo that I have not made any configuration, directly using the demo you gave New information has emerged [HMS] AdsDemoManager ShowRewardedAd UnityEngine.Debug:Log(Object) AdsDemoManager:ShowRewardedAd() (at Assets/Huawei/Demos/Ads/AdsDemoManager.cs:33) UnityEngine.EventSystems.EventSystem:Update() (at E:/program files/unity201/Editor/Data/Resources/PackageManager/BuiltInPackages/com.unity.ugui/Runtime/EventSystem/EventSystem.cs:376)
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "流云" ***@***.***&gt;; 发送时间:&nbsp;2021年7月13日(星期二) 晚上9:07 ***@***.******@***.***&gt;; ***@***.***&gt;; 主题:&nbsp;回复： [EvilMindDevs/hms-unity-plugin] Exception: Field currentActivity or type signature not found (#157) This is unity's entire blog about this error at the moment： Exception: Field currentActivity or type signature&nbsp; not found UnityEngine._AndroidJNIHelper.GetFieldID (System.IntPtr jclass, System.String fieldName, System.String signature, System.Boolean isStatic) (at <e2fcf4f110424f58ac607d4fd98ed223&gt;:0) UnityEngine.AndroidJNIHelper.GetFieldID (System.IntPtr javaClass, System.String fieldName, System.String signature, System.Boolean isStatic) (at <e2fcf4f110424f58ac607d4fd98ed223&gt;:0) UnityEngine._AndroidJNIHelper.GetFieldID[ReturnType] (System.IntPtr jclass, System.String fieldName, System.Boolean isStatic) (at <e2fcf4f110424f58ac607d4fd98ed223&gt;:0) UnityEngine.AndroidJNIHelper.GetFieldID[FieldType] (System.IntPtr jclass, System.String fieldName, System.Boolean isStatic) (at <e2fcf4f110424f58ac607d4fd98ed223&gt;:0) UnityEngine.AndroidJavaObject._GetStatic[FieldType] (System.String fieldName) (at <e2fcf4f110424f58ac607d4fd98ed223&gt;:0) UnityEngine.AndroidJavaObject.GetStatic[FieldType] (System.String fieldName) (at <e2fcf4f110424f58ac607d4fd98ed223&gt;:0) HuaweiMobileServices.Utils.AndroidContext.get_ActivityContext () (at <215ffb40c29c4bf19276ccbd420e921a&gt;:0) HuaweiMobileServices.Ads.HwAds.Init () (at <215ffb40c29c4bf19276ccbd420e921a&gt;:0) HMSAdsKitManager.Init () (at Assets/Huawei/Scripts/Ads/HMSAdsKitManager.cs:33) HMSAdsKitManager.Start () (at Assets/Huawei/Scripts/Ads/HMSAdsKitManager.cs:27)
> ------------------ 原始邮件 ------------------ 发件人: "EvilMindDevs/hms-unity-plugin" ***@***.***&gt;; 发送时间:&nbsp;2021年7月13日(星期二) 晚上8:42 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [EvilMindDevs/hms-unity-plugin] Exception: Field currentActivity or type signature not found (#157) Oh, you need to Enable Banner Ads to see Banner ads. That goes for the other ad types as well. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

This log is to tell you that ShowRewardedAds called actually.

**Comment by zqbxniu** [comment]
Yes, I currently import this SDK directly into an empty project, and then run the demo
I still report this error when I run it for the first time

Then, click the button
This error will occur









------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "EvilMindDevs/hms-unity-plugin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月13日(星期二) 晚上9:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [EvilMindDevs/hms-unity-plugin] Exception: Field currentActivity or type signature  not found (#157)





  
This is the demo that I have not made any configuration, directly using the demo you gave New information has emerged [HMS] AdsDemoManager ShowRewardedAd UnityEngine.Debug:Log(Object) AdsDemoManager:ShowRewardedAd() (at Assets/Huawei/Demos/Ads/AdsDemoManager.cs:33) UnityEngine.EventSystems.EventSystem:Update() (at E:/program files/unity201/Editor/Data/Resources/PackageManager/BuiltInPackages/com.unity.ugui/Runtime/EventSystem/EventSystem.cs:376)
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "流云" @.&gt;; 发送时间:&nbsp;2021年7月13日(星期二) 晚上9:07 @.@.&gt;; @.&gt;; 主题:&nbsp;回复： [EvilMindDevs/hms-unity-plugin] Exception: Field currentActivity or type signature not found (#157) This is unity's entire blog about this error at the moment： Exception: Field currentActivity or type signature&nbsp; not found UnityEngine._AndroidJNIHelper.GetFieldID (System.IntPtr jclass, System.String fieldName, System.String signature, System.Boolean isStatic) (at <e2fcf4f110424f58ac607d4fd98ed223&gt;:0) UnityEngine.AndroidJNIHelper.GetFieldID (System.IntPtr javaClass, System.String fieldName, System.String signature, System.Boolean isStatic) (at <e2fcf4f110424f58ac607d4fd98ed223&gt;:0) UnityEngine._AndroidJNIHelper.GetFieldID[ReturnType] (System.IntPtr jclass, System.String fieldName, System.Boolean isStatic) (at <e2fcf4f110424f58ac607d4fd98ed223&gt;:0) UnityEngine.AndroidJNIHelper.GetFieldID[FieldType] (System.IntPtr jclass, System.String fieldName, System.Boolean isStatic) (at <e2fcf4f110424f58ac607d4fd98ed223&gt;:0) UnityEngine.AndroidJavaObject._GetStatic[FieldType] (System.String fieldName) (at <e2fcf4f110424f58ac607d4fd98ed223&gt;:0) UnityEngine.AndroidJavaObject.GetStatic[FieldType] (System.String fieldName) (at <e2fcf4f110424f58ac607d4fd98ed223&gt;:0) HuaweiMobileServices.Utils.AndroidContext.get_ActivityContext () (at <215ffb40c29c4bf19276ccbd420e921a&gt;:0) HuaweiMobileServices.Ads.HwAds.Init () (at <215ffb40c29c4bf19276ccbd420e921a&gt;:0) HMSAdsKitManager.Init () (at Assets/Huawei/Scripts/Ads/HMSAdsKitManager.cs:33) HMSAdsKitManager.Start () (at Assets/Huawei/Scripts/Ads/HMSAdsKitManager.cs:27)
 ------------------ 原始邮件 ------------------ 发件人: "EvilMindDevs/hms-unity-plugin" @.&gt;; 发送时间:&nbsp;2021年7月13日(星期二) 晚上8:42 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [EvilMindDevs/hms-unity-plugin] Exception: Field currentActivity or type signature not found (#157) Oh, you need to Enable Banner Ads to see Banner ads. That goes for the other ad types as well. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
This log is to tell you that ShowRewardedAds called actually.

**Comment by zqbxniu** [comment]
Now how can I solve this mistake? Then let the ad load normally


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "EvilMindDevs/hms-unity-plugin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月13日(星期二) 晚上9:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [EvilMindDevs/hms-unity-plugin] Exception: Field currentActivity or type signature  not found (#157)





  
This is the demo that I have not made any configuration, directly using the demo you gave New information has emerged [HMS] AdsDemoManager ShowRewardedAd UnityEngine.Debug:Log(Object) AdsDemoManager:ShowRewardedAd() (at Assets/Huawei/Demos/Ads/AdsDemoManager.cs:33) UnityEngine.EventSystems.EventSystem:Update() (at E:/program files/unity201/Editor/Data/Resources/PackageManager/BuiltInPackages/com.unity.ugui/Runtime/EventSystem/EventSystem.cs:376)
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "流云" @.&gt;; 发送时间:&nbsp;2021年7月13日(星期二) 晚上9:07 @.@.&gt;; @.&gt;; 主题:&nbsp;回复： [EvilMindDevs/hms-unity-plugin] Exception: Field currentActivity or type signature not found (#157) This is unity's entire blog about this error at the moment： Exception: Field currentActivity or type signature&nbsp; not found UnityEngine._AndroidJNIHelper.GetFieldID (System.IntPtr jclass, System.String fieldName, System.String signature, System.Boolean isStatic) (at <e2fcf4f110424f58ac607d4fd98ed223&gt;:0) UnityEngine.AndroidJNIHelper.GetFieldID (System.IntPtr javaClass, System.String fieldName, System.String signature, System.Boolean isStatic) (at <e2fcf4f110424f58ac607d4fd98ed223&gt;:0) UnityEngine._AndroidJNIHelper.GetFieldID[ReturnType] (System.IntPtr jclass, System.String fieldName, System.Boolean isStatic) (at <e2fcf4f110424f58ac607d4fd98ed223&gt;:0) UnityEngine.AndroidJNIHelper.GetFieldID[FieldType] (System.IntPtr jclass, System.String fieldName, System.Boolean isStatic) (at <e2fcf4f110424f58ac607d4fd98ed223&gt;:0) UnityEngine.AndroidJavaObject._GetStatic[FieldType] (System.String fieldName) (at <e2fcf4f110424f58ac607d4fd98ed223&gt;:0) UnityEngine.AndroidJavaObject.GetStatic[FieldType] (System.String fieldName) (at <e2fcf4f110424f58ac607d4fd98ed223&gt;:0) HuaweiMobileServices.Utils.AndroidContext.get_ActivityContext () (at <215ffb40c29c4bf19276ccbd420e921a&gt;:0) HuaweiMobileServices.Ads.HwAds.Init () (at <215ffb40c29c4bf19276ccbd420e921a&gt;:0) HMSAdsKitManager.Init () (at Assets/Huawei/Scripts/Ads/HMSAdsKitManager.cs:33) HMSAdsKitManager.Start () (at Assets/Huawei/Scripts/Ads/HMSAdsKitManager.cs:27)
 ------------------ 原始邮件 ------------------ 发件人: "EvilMindDevs/hms-unity-plugin" @.&gt;; 发送时间:&nbsp;2021年7月13日(星期二) 晚上8:42 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [EvilMindDevs/hms-unity-plugin] Exception: Field currentActivity or type signature not found (#157) Oh, you need to Enable Banner Ads to see Banner ads. That goes for the other ad types as well. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
This log is to tell you that ShowRewardedAds called actually.

**Comment by zqbxniu** [comment]
Yes, I currently import this SDK directly into an empty project, and then run the demo
I still report this error when I run it for the first time

Then, click the button
This error will occur




Now how can I solve this mistake? Then let the ad load normally

**Comment by zqbxniu** [comment]
I still report this error when I run it for the first time
<img width="833" alt="2" src="https://user-images.githubusercontent.com/41951478/125466908-c6aaa868-9c3f-44c1-b421-1f8b6a7ab0e4.png">
Then, click the button
This error will occur
<img width="826" alt="1" src="https://user-images.githubusercontent.com/41951478/125467023-ca1538b8-6613-41ca-9643-b1ea8f65ca6f.png">
I just want to be able to load ads normally right now, and that's what I should do

**Comment by sametguzeldev** [comment]
Oh 😄 You cannot run this plugin on editor. You need to run this on android device.
