### ISSUE TITLE
IAP DEMO: When I purchase a subscription product, a black screen is shown

### ISSUE THREAD

**Issue by gtoto007** [EvilMindDevs/hms-unity-plugin#158]
Hi guys, 

I'm testing  Unity's **Iapdemo** scene  with  **Huawei's Cloud Debugging emulator** on the P40 device. I've already configured the Unity project and AppGallery Connected.  I've  tried to buy a product consumable and non-consumable and it's works. **But when I try to purchase a subscription product, a black screen is shown.** 

I reproduced the issue in this [video](https://user-images.githubusercontent.com/6715157/125662210-e85e3340-2e2c-4c7d-9b99-1e312d9841c3.mp4) and you can download the apk with issue on this [link](https://drive.google.com/file/d/1KB6muo_cIdv2ky_vOYw5ae2fiIkvG0M_/view?usp=sharing)

The latest product "PREMIUM" is linked as annual subscription 
You can notice that when I go back from the black screen, a screen with credit card information seems to appear for a few milliseconds

**_MORE INFO:_**
I've created a new unity project 2020.3.8 and imported the package **[HMSUnityPackageV2.0.8-2019-2020.unitypackage](https://github.com/EvilMindDevs/hms-unity-plugin/releases/tag/v2.0.8-2019-2020#:~:text=HMSUnityPackageV2.0.8-2019-2020.unitypackage)**

I created different products in Product Management. In particular I created the **Premium Product** as a Subscription and it doesn't work. Instead, other products work:

<img width="1614" alt="product-Management" src="https://user-images.githubusercontent.com/6715157/125661838-9adda9bd-8f13-4ba2-a86a-279cae39ee38.png">

**Comment by gtoto007** [comment]
I have tested the apk with a real device and can complete the purchase of a premium subscription without errors.
So I think the problem lies with the emulator.
In fact, the black screen no longer appears when I touch the final subscription button and the screen requesting credit card information is displayed correctly.

**Comment by sametguzeldev** [comment]
Hello there. Yes this is an issue on cloud debugging. Cloud debugging sometimes does not show some pop up screens properly and user sees that as a black screen.
