### ISSUE TITLE
BannerAdLoadFailed. Error Code: 3

### ISSUE THREAD

**Issue by antoniotonev** [EvilMindDevs/hms-unity-plugin#159]
Hello, 
I had tried to show the banner ad but isn't shown. On every app start the SDK return BannerLord Failed. Error Code: 3. 
Any ideas ? Thank you 🥇 

<img width="1040" alt="Screen Shot 2021-07-26 at 1 41 49 PM" src="https://user-images.githubusercontent.com/25726751/126976845-9d4376c5-b4c3-4799-9702-3c3c4c028d80.png">

**Comment by sametguzeldev** [comment]
Hello there. Error code is the filling rate issue. In which country you are trying to show the ad ?
Also for real ads to be shown, the app needs to be released in AppGallery (In case your real ads does not shown on non-released app).

**Comment by antoniotonev** [comment]
Thank you for your fast answer. 👍 I'm trying to show the ads from Bulgaria. I had tried with test ads - Interstitial, Reward and everything is fine, only the banner ad missing. 
Okay I understand the error code is filing rate issue. I can release my update safely. Thank you again! 🥇

**Comment by flashmandv** [comment]
@sametguzeldev what is error code 0 for interestitial ad fail? I'm getting it, even in test mode

**Comment by sametguzeldev** [comment]
Error code : 0 seems like inner error. Check your hms core version.
You can find details [here](https://developer.huawei.com/consumer/en/doc/development/HMSCore-References/android-error-code-0000001130129080) about error codes.
