### ISSUE TITLE
is bannerAdManager missing?

### ISSUE THREAD

**Issue by IamFarCry4** [EvilMindDevs/hms-unity-plugin#16]
i can see interstitial and rewardAd manager in there but i didnt see bannerAd manager. Does banner ad implementation doesnot require bannerAdManager? or is there is any way of implementing banner ads in game if yes how can we do that? hoping to see helpful information from you. Thank you

**Comment by m0skit0** [comment]
Hi, thanks for your feedback!

BannerAd is not implemented because the underlying Android SDK implements it as an Android View to be added in the Android layout, so we chose to skip this one for now. If you're interested in having this View so you can add it programmatically we can consider it for future releases. Or you can explain how you're expecting to use it so we can find a better solution.

**Comment by EtsaiDev** [comment]
Hi, I´m really interested of course. We´re porting games previously released on GooglePlay, and the idea is to keep the whole functionality, including the Ad system (banners, interstitials and rewardedAds)

**Comment by m0skit0** [comment]
@EtsaiDev Thanks, how do you embed banner ads from Google Play? Do you have an example?

**Comment by EtsaiDev** [comment]
I use Admob sdk for unity as a mediator. it´s just a couple of lines once ads system is initialized:

`BannerView bannerView = new BannerView(admobBannerID, AdSize.SmartBanner, AdPosition.Bottom);
this.bannerView.LoadAd(AdRequest.Builder().Build());
bannerView.Show();`

**Comment by jmercado86** [comment]
I also would like to request for an update to support Banner please. Thank you!

**Comment by bene25** [comment]
+1 for banner ad

**Comment by gimoneto** [comment]
+1 for banner ad support

**Comment by robertorebollo** [comment]
+1 for banner ad support

Same here, we would need banner support to keep the same functionality in our apps

**Comment by smuttleralph** [comment]
+1 banner ad support would be great!

**Comment by EtsaiDev** [comment]
Any progress with this?

**Comment by m0skit0** [comment]
We are listening to your feedback and working on it :)

**Comment by EtsaiDev** [comment]
https://github.com/EvilMindDevs/hms-unity-plugin/pull/59
is this verified?

**Comment by gmYusuf** [comment]
it verified, in the next version will be in the package.

**Comment by VergilUa** [comment]
Latest package is missing this feature. Probably worth repacking it.

**Comment by sametguzeldev** [comment]
Latest version has banner ads implemented.
