### ISSUE TITLE
Get Profile Picture from Account Kit?

### ISSUE THREAD

**Issue by chinmaygawande123** [EvilMindDevs/hms-unity-plugin#165]
Is there a way to get profile picture and display it on Texture2D via AuthAccount Class? 

![Screenshot 2021-08-22 at 8 17 55 PM](https://user-images.githubusercontent.com/44647335/130359514-313d27de-38f9-4d3e-ad8e-0e1b2001e6a0.png)

![Screenshot 2021-08-22 at 8 14 34 PM](https://user-images.githubusercontent.com/44647335/130359444-4e11bd85-f4da-4e2c-ad2e-90e683c6696d.png)

**Comment by sametguzeldev** [comment]
Hello there,

AuthAccount has a property called AvatarUriString which returns profile picture url.
You can create a UnityWebRequest for that url and you can get the picture.
Here unity docs for example : https://docs.unity3d.com/Manual/UnityWebRequest-RetrievingTexture.html

**Comment by chinmaygawande123** [comment]
Got it! Thanks
