### ISSUE TITLE
Add a way to get raw InAppPurchaseData

### ISSUE THREAD

**Issue by xAdamQ** [EvilMindDevs/hms-unity-plugin#166]
In the backend server the `InAppPurchaseData` is used alongside `InAppDataSignature` to verify the purchase, but the data must be the same as what is given from Huawei because the serialization changes the InAppPurchaseData it.

**Comment by sametguzeldev** [comment]
Hello,
Do you need the raw JSON that returns in InAppPurchaseData?

**Comment by xAdamQ** [comment]
any news?

**Comment by sametguzeldev** [comment]
Yes, I've pushed the changes on #167 and I'll be releasing it as a unity package in 1 hour.

**Comment by sametguzeldev** [comment]
I've released the new package. Check releases section :)

**Comment by sametguzeldev** [comment]
Did that solve your problem? @xAdamQ

**Comment by sametguzeldev** [comment]
Fixed in #169
