### ISSUE TITLE
 Since your app has not been integrated with HMS yet, It cannot be used or displayed on the HMS.

### ISSUE THREAD

**Issue by gtoto007** [EvilMindDevs/hms-unity-plugin#168]
Hi,
I'm a developer of Marshmallow Games SRL.

We have released our app Smart Tales  on store  appgallery "https://appgallery.huawei.com/#/app/C104663029" .
We have used Unity 2020.3.8f1 + HMS Unity plugin 2.0.8 for integration HMS Services.
We have implemented the HMS IPA service to allow the user to purchase an annual or monthly subscription.

Before the release we have installed and tested it on device Huawei P40 and Huawei p30  and it works correctly.

Even if the app has been approved  the reviewers tell us:
*****
_"Your app has been approved. [Test Environment]: Wi-Fi networking, multilingual environment. EMUI 11.00.0 (P30), EMUI 11.00.0 (P40 Pro) ­Notes: **Since your app has not been integrated with HMS yet, It cannot be used or displayed on the HMS. If integration of HMS is needed**, please refer to: https://developer.huawei.com/consumer/en/doc/development/HMSCore-Library-V5/android-sdk-download-0000001064112371-V5"_
*****
Although we used your plugin for IAP service and this works correctly on our test devices (Huawei P40 and Huawei P30), we don't understand why the reviewers tell us that app not been integrated with HMS.

Furthermore If we open direct link the app on appgallery with P40 Lite device, the button "install" is disabled. Instead If we open the direct link of the app with device Huawei P30 the button install is enable and we can install it.

**Comment by sametguzeldev** [comment]
Hello there.
Can you mail me the exact conversation on samet.guzel@huawei.com? I want to deal with this internally to have a faster solution.
Also please attach/upload the apk to the mail so I can check what is inside regarding HMS libraries.

**Comment by gtoto007** [comment]
Hello! Thank you for your support. I've just written you an email with more details.

**Comment by sametguzeldev** [comment]
I've got it thanks. It is a national holiday tomorrow here so probably I can start to work on it internally by Tuesday and contact you afterward.

**Comment by gtoto007** [comment]
@sametguzeldev The problem has just been fixed by a  Huawei team member and it depended by a problem on the  appgallery store. Now the app works correctly on HMS devices.
