### ISSUE TITLE
Custom Ads ID not working

### ISSUE THREAD

**Issue by m0skit0** [EvilMindDevs/hms-unity-plugin#17]
As reported: 

> We configured Ad Unit id: ”xxxxxxxxx" for interstitials. See all details in the screenshot below. 
> It does not load or show any interstitials. It still works fine if I use the test unit id ”testb4znbuh3n2”.

Shared AGC configuration looks correctly set up.

**Comment by m0skit0** [comment]
Reporter reported that app is not live yet and ads only start working after app goes live, closing.

**Comment by RcSpoon** [comment]
We have some problem. Test ads shows fine but our block return no_ads every time. Application is released
