### ISSUE TITLE
IAP not working when tested on phone

### ISSUE THREAD

**Issue by Osman-Kilic** [EvilMindDevs/hms-unity-plugin#173]
Problem occurs when running IAP.
HMS Core opens as a blank screen on the phone.
There is a product id not found error in UnityEditor. I defined the products on the app connect page and in UnityEditor.
my second problem is that the package name was not found when publishing my game on the app connect page.
How can I fix.
Thanks

**Comment by sametguzeldev** [comment]
Hello there.
Can you share logs with logcat from your device?

**Comment by Osman-Kilic** [comment]
thanks for your answer.
loguct on application launch:
https://i.resmim.net/t3DVq.jpg
When IAP starts:
https://i.resmim.net/t3mY3.gif
phone screenshot
https://i.resmim.net/t3WWQ.png

**Comment by sametguzeldev** [comment]
According to logs, your signing key's fingerprint(SHA256) does not match the one on AGC.
Please follow these steps [here](https://github.com/EvilMindDevs/hms-unity-plugin#add-fingerprint-certificate-to-appgallery-connect)

**Comment by Osman-Kilic** [comment]
I fixed that problem but "altin1000 could not be found in retrieved product list!" error is not resolved. I added products everywhere.

**Comment by sametguzeldev** [comment]
Can you show me your Product list on Unity like in the image below?
![image](https://user-images.githubusercontent.com/6827857/131500065-6682a27d-310a-491a-a563-d762ba7fb91b.png)

Also, send another screenshot from your AGC that holds all of your products.
![image](https://user-images.githubusercontent.com/6827857/131500224-c1e9a165-bda0-4439-a3e9-e6d50dedea61.png)

**Comment by Osman-Kilic** [comment]
![logcat](https://user-images.githubusercontent.com/89778499/131552331-e32f6f3f-5716-42ea-a34b-63443465d016.gif)
![unity](https://user-images.githubusercontent.com/89778499/131552339-db4987e6-4d40-46dd-b14f-782380698f23.gif)
![Ekran görüntüsü 2021-08-31 205242](https://user-images.githubusercontent.com/89778499/131552340-ab5d5156-3ebf-423e-b9f3-a263b9ae5375.gif)

If the problem will not be fixed, let's close the issue. I have now published the game.

**Comment by sametguzeldev** [comment]
We can solve the problem. Can you send me the whole log?
Right click on the logcat then Select all, after that right click again then save selection. It should give you a txt file. Can you upload it to here so I can take a look?
![image](https://user-images.githubusercontent.com/6827857/131554848-d0987894-a080-4495-95c8-052cd01f82b6.png)

**Comment by Osman-Kilic** [comment]
[araba.huawei-logcat.txt](https://github.com/EvilMindDevs/hms-unity-plugin/files/7086086/araba.huawei-logcat.txt)

**Comment by Osman-Kilic** [comment]
ok it worked late loading
now the problem is solved

**Comment by sametguzeldev** [comment]
That's good news!

**Comment by PrabhakaranHfg** [comment]
I have same issue too ,how you have resolved
