### ISSUE TITLE
Error on EnvReady

### ISSUE THREAD

**Issue by vbodzio** [EvilMindDevs/hms-unity-plugin#174]
Hi

I have followed all the instruction to implement huawei IAP Purchases into unity3D project. I 'm getting error:
[HMSIAPManager]: Error on EnvReady
AndroidJavaException: java.class.ClassNotFoundException:
org.m0skit0.android.hms.unity.base.StatusBridge

My Unity version is 2020.3.11f1.533. I've used HMSUnityPackageV2.0.10-2019-2020 file to import plugin into Unity.
In Unity->Project Settings->Player->Minify: "Use R8", "Release" and "Debug" -> all are DISABLED

Moreover I had to remove "com.android.support:appcompat-v7:28.0.0" library dependency from build.gradle, because I had a lot of "duplicate class error" (More specifically: I removed "com.android.support:appcompat-v7:28.0.0" string entry from HMSGradleWorker.cs->CoreGradles() array)

I have no idea how to fix ClassNotFoundException error

**Comment by sametguzeldev** [comment]
Hello there. Probably the app-debug.aar in Assets/Plugins/Android is not included in your build. Can you export project and then check if app-debug.aar file is in libs folder?
![image](https://user-images.githubusercontent.com/6827857/131550424-9ed6a00a-58bd-41f7-9557-b2e9eb6c26b4.png)

**Comment by vbodzio** [comment]
Hello again,

You were right. There was no app-debug.aar in Assets/Plugins/Android. I have reimported plugin and now everything is working fine. Thank you!
