### ISSUE TITLE
Install referrer

### ISSUE THREAD

**Issue by pax83** [EvilMindDevs/hms-unity-plugin#177]
Hi. Is it possible to get a install referrer on huawei device with this plugin?

**Comment by sametguzeldev** [comment]
No, our plugin does not support install referrer atm.
But we can add this to our roadmap.

**Comment by pax83** [comment]
> But we can add this to our roadmap.

That would be great!

**Comment by alihan98ersoy** [comment]
Hello,
Install referrer is now supported with the new version.
