### ISSUE TITLE
When Huawei Plugin is disabled and  an Unity Error is launched, the assembly Huawei is enabled 

### ISSUE THREAD

**Issue by gtoto007** [EvilMindDevs/hms-unity-plugin#179]
In that condition, I expect the Huawei Assembly is always disabled .

Instead when there is an exception in build, the OnBuildError callback is thrown and the assembly definition is always enabled.
I think you check the error in class HMSGrandleWorkers.cs, line code 200:
<img width="964" alt="Schermata 2021-09-10 alle 16 32 24" src="https://user-images.githubusercontent.com/6715157/132870507-92db44fc-6d7d-4901-ac99-4748858cd238.png">

**Comment by sametguzeldev** [comment]
Yes, this is actually an error from my side. It should be false as you've mentioned.

**Comment by gtoto007** [comment]
In this class, in line 18, is there the same error? should the input parameter be false?
![Uploading Schermata 2021-09-13 alle 11.38.16.png…]()

**Comment by sametguzeldev** [comment]
Yes that should be also false.

**Comment by gtoto007** [comment]
OK thanks. I have found another point causing the problem
<img width="674" alt="Schermata 2021-09-13 alle 15 51 11" src="https://user-images.githubusercontent.com/6715157/133098296-c0b2a148-d6a3-4674-903b-15ce37feefc5.png">

**Comment by sametguzeldev** [comment]
I'll fix all of these on the next version.
I copied and pasted so all those places are wrong 😄

**Comment by gtoto007** [comment]
Thank you very much!

**Comment by sametguzeldev** [comment]
Fixed in #193.
