### ISSUE TITLE
Sign in failed

### ISSUE THREAD

**Issue by pax83** [EvilMindDevs/hms-unity-plugin#181]
Hi!

I got next message when I do sign in operation:
[HMSAccountManager]: Sign in failed. CauseMessage: , ExceptionMessage: 28:

This happens on some devices. Where can I find information about this error?

**Comment by gmYusuf** [comment]
Hi,

Can send your full logs?
When you start your app do have something like this error "certificate fingerprint error"?

**Comment by pax83** [comment]
I need time to get these logs. These are not our devices. I'll try. I cannot find error code 28 in the documentation.

**Comment by pax83** [comment]
What kind of certificate do you mean?

**Comment by gmYusuf** [comment]
So you mean just for some devices cause this error. 
If it like this, that devices HMS Core version can be very old

**Comment by pax83** [comment]
Can we somehow figure out that HMS Core version is out of date?

**Comment by gmYusuf** [comment]
- We need to update plugin, for now we have not supporting.
- We need to add functions to ServiceHelp class.
  https://github.com/EvilMindDevs/hms-sdk-unity/blob/master/android-wrapper/app/src/main/java/org/m0skit0/android/hms/unity/helper/ServiceHelper.java
  Reason is callling HmsApiAvailability - HMS_SDK_VERSION_CODE
  https://developer.huawei.com/consumer/en/doc/development/HMS-Plugin-References-V1/hms-api-availability-0000001127929951-V1
- Last step, we need to write for this wrapper.
We wrote this to our roadmap, we can add as soon as possible this feature.

**But for your case we need to be sure and if we can see full log its much more better.**

**Comment by pax83** [comment]
Thanks. I'm waiting for the logs. I'll send them soon as I get them.

**Comment by pax83** [comment]
Here is full log ([][][]][[[[][ strings it is obfuscation, but HmsPlugin namespace is in ignore list and proguard configured as in documentation).
[huawei_auth_log.txt](https://github.com/EvilMindDevs/hms-unity-plugin/files/7187916/huawei_auth_log.txt)

**Comment by gmYusuf** [comment]
I couldnt find something in this log file, we will try to add HMS Core Version check function.
Can you share apk?
Or you can add me from skype we can look your project short term. skype id: yusufaltun47

**Comment by pax83** [comment]
Hi, I will write to you on skype.

**Comment by hajimeku** [comment]
Hey! I have the same issue I think. I cant login with huawei at all.
I attached my logs.

[HuaweiLoginLogcat.txt](https://github.com/EvilMindDevs/hms-unity-plugin/files/7238726/HuaweiLoginLogcat.txt)
``

**Comment by hajimeku** [comment]
I managed to fix it by downloading the latest Huawei services from Aptoid
