### ISSUE TITLE
InAppPurchaseDataRawJSON in OwnedPurchasesResult

### ISSUE THREAD

**Issue by user1767** [EvilMindDevs/hms-unity-plugin#184]
For the same reasons as discussed in https://github.com/EvilMindDevs/hms-unity-plugin/issues/166, can we get raw json InAppPurchaseData in OwnedPurchaseResult? Or is there another way to implement the purchase signature verification step in https://developer.huawei.com/consumer/en/doc/development/HMSCore-Guides/redelivering-consumables-0000001051356573?

**Comment by sametguzeldev** [comment]
Hello there.
I can add the raw JSON into OwnedPurchaseResult as well. I will deliver a new version having this change this week.

**Comment by user1767** [comment]
Thank you, I appreciate it.

**Comment by sametguzeldev** [comment]
Added in #193.
