### ISSUE TITLE
Buy consumable innap multiple

### ISSUE THREAD

**Issue by Black-Earl** [EvilMindDevs/hms-unity-plugin#189]
Hello. I have a problem like this, I have multiple consumables. And I can't buy them twice on a test account, they have not been tested on a combat one. When you try to buy several times, the store is opened and immediately closes and an error falls into the application. "AndroidJavaExceprion: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference" Where could I have made a mistake?

**Comment by sametguzeldev** [comment]
Hello there,
Can you give the logs to us so we can check on them?

**Comment by Black-Earl** [comment]
Hello.

Log: [log.txt](https://github.com/EvilMindDevs/hms-unity-plugin/files/7258429/log.txt)

Is it normal that when restoring purchases, information about replenished goods also comes?
I fixed the problem this way:
When I launch the application, I make a restore and see if goods of the consumable type have arrived, then I call the ConsumePurchaseWithToken method for them and pass the product token. After that I manage to buy several times

**Comment by sametguzeldev** [comment]
I think your problem lies with not consuming the purchase after buying it. By default, our method in HMSIAPManager consuming the purchase after buying it as you can see below.
![image](https://user-images.githubusercontent.com/6827857/135430081-231b5e26-c1c0-4414-b682-0bcce3fb32b8.png) 

Did you write your own buying procedure?

**Comment by Black-Earl** [comment]
No, I used your methods, changing the code a bit. But the main method chain remains the same.
[code.txt](https://github.com/EvilMindDevs/hms-unity-plugin/files/7258636/code.txt)

**Comment by Black-Earl** [comment]
Также заметил подобную ошибку если отменить покупку. Как я понимаю в этом случае результат этой строки  PurchaseResultInfo purchaseResultInfo = iapClient.ParsePurchaseResultInfoFromIntent(androidIntent); будет null и дальше уже невозможно выполнить код

**Comment by sametguzeldev** [comment]
Can you upload your device log as well?

**Comment by Black-Earl** [comment]
Error log when canceling a purchase, line 1816
[log_cancel_buy.txt](https://github.com/EvilMindDevs/hms-unity-plugin/files/7263961/log_cancel_buy.txt)

`AndroidJavaException: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
    java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
        at org.json.JSONTokener.nextCleanInternal(JSONTokener.java:116)
        at org.json.JSONTokener.nextValue(JSONTokener.java:94)
        at org.json.JSONObject.<init>(JSONObject.java:159)
        at org.json.JSONObject.<init>(JSONObject.java:176)
        at com.huawei.hms.iap.entity.InAppPurchaseData.<init>(Unknown Source:5)
        at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
        at com.unity3d.player.UnityPlayer.access$300(Unknown Source:0)
        at com.unity3d.player.UnityPlayer$e$1.handleMessage(Unknown Source:95)
        at android.os.Handler.dispatchMessage(Handler.java:108)
        at android.os.Looper.loop(Looper.java:216)
        at com.unity3d.player.UnityPlayer$e.run(Unknown Source:20)
      at UnityEngine.AndroidJNISafe.CheckException () [0x00000] in <0000000000000000000000000000000`

**Comment by Black-Earl** [comment]
I can fix this error only by adding a check for the presence of `purchaseResultInfo`

**Comment by Black-Earl** [comment]
Sorry, the cancellation error was on my part. But the problem with replenished goods remained.

**Comment by sametguzeldev** [comment]
Does it give the same error without modifying the code?

**Comment by Black-Earl** [comment]
Regarding the renewable items, this solution helped me. When restoring purchases, I see if the replenished goods arrived, then I call the ConsumePurchaseWithToken method and pass the product token there. After these steps, I can buy several times executable products.

**Comment by sametguzeldev** [comment]
Can you check that when the BuyProduct method gets executed it also consumes the product after a successful purchase?

**Comment by sametguzeldev** [comment]
Closed due to inactivity. Please re-open if the issue still persists.
