### ISSUE TITLE
Attribute collision

### ISSUE THREAD

**Issue by 40123262** [EvilMindDevs/hms-unity-plugin#19]
![image](https://user-images.githubusercontent.com/25100630/83732142-eac8af00-a64b-11ea-95e8-36090055c2dc.png)

Hey, I'm stuck on this for 2 days now, trying to add rewarded ads to my project. It worked before with hms plugin 2.6.1:300 provided by huawei, as i used it for IAP, but now we need to implement the ads kit and i used your plugin for that, but i keep getting this error.

**Comment by 40123262** [comment]
After some time i managed to build the app however how i'm getting this
![image](https://user-images.githubusercontent.com/25100630/83742123-5107fe80-a659-11ea-8488-83c2d46c38b7.png)

**Comment by m0skit0** [comment]
Hi @40123262 

I think this error was fixed before. How are you using the plugin? Through the released package?

**Comment by m0skit0** [comment]
Closed due to inactivity
