### ISSUE TITLE
ObtainOwnedPurchases calls OnObtainProductInfoFailure on failure

### ISSUE THREAD

**Issue by user1767** [EvilMindDevs/hms-unity-plugin#190]
Hey, shouldn't it call OnObtainOwnedPurchasesFailure instead?

**Comment by sametguzeldev** [comment]
Yes it should be, we'll be fixing it and releasing a new version tomorrow with several fixes. Thank you for pointing it out! <3

**Comment by sametguzeldev** [comment]
Fixed in #193.
