### ISSUE TITLE
HMSException.WrappedExceptionMessage == 6003 when trying to init IAP

### ISSUE THREAD

**Issue by Whaledevelop** [EvilMindDevs/hms-unity-plugin#191]
Hello!

I am trying to connect your plugin to my project, but I can not configure IAP initialization in any way. When trying to `iapClient.EnvReady`, an error callback is called with log : `"[HMSIAPManager]: Error on EnvReady"`, I added exception.WrappedExceptionMessage - there is only ` "6003"` and exception.WrappedCauseMessage - there is nothing. Attached log. 
[iapdemolog.txt](https://github.com/EvilMindDevs/hms-unity-plugin/files/7256752/iapdemolog.txt)

Initially I tried it in my project, tried both `HuaweiStore` and `HMSIAPManager`, there was the same error, then I created an empty project with only your plugin - I also tried your demo scene `IapDemo` and created my own empty one, where there was only a call to `HMSIAPManager.Instance.CheckIapAvailability()`, nothing helps.

Followed all instructions from [main page](https://github.com/EvilMindDevs/hms-unity-plugin)
1. Registered, created an app, generated a keystore, indicated in the project, the SHA-256 values are the same as in AppGallery Connect
2. Imported your plugin
3. Updated agconnect-services.json
4. Checked IAP in HMS Settings, HMSIAPManager is on scene.

I tried Account Kit from other Kit Managers, there is the same error in the callback when `HMSAccountManager.Instance.SignIn()`; same HMSException.WrappedExceptionMessage == 6003

Found error 6003 in [this article](https://developer.huawei.com/consumer/en/doc/development/HMS-2-References/hmssdk_jointOper_api_reference_errorcode) , this means non consistent First Signed Certificate - checked, I have equal in both my APK and App Services.

I found an article with the same error 6003 and the [answer](https://githubmemory.com/repo/EvilMindDevs/hms-unity-plugin/issues/148?page=2) of the developer @sametguzeldev, I checked the SHA256 key, everything converges. There is a message there : "Iv got it. Some postprocessing scripts messed it up. And json file were in wrong folder" - I don’t know which postprocessing scripts are meant; agconnect-services.json is in `Assets/StreamingAssets/agconnect-services.json` - which seems to be the right place.

One more point - in the failure callback of the `iapClient.EnvReady` in the HMSIAPManager there is an `iapEx.Status.StartResolutionForResult` with error and success callbacks,I never get either one or the other.

P.S. I have Huawei App Gallery and HMS Core on my device

Thanks, I will be grateful for any help!

**Comment by sametguzeldev** [comment]
Hello there,
Thank you for the beautiful explanation.
Do you have Huawei App Signing enabled in your project by any chance?
Also, make sure to sign your application with your keystore, export keystore's SHA256 with keytool, and update your Project Settings in AppGallery Connect with the SHA256 string.

Your agconnect file seems to be okay because it would give you a different error while trying to build your apk.
StartResolutionForResult won't even start for 6003 error because SDK cannot resolve that issue since it is a certificate issue most likely.

**Comment by Whaledevelop** [comment]
Hello. sorry for taking a long time to response. You were right, the problem was in SHA-256, it was cleared up somehow
