### ISSUE TITLE
Support of other Ad Types?

### ISSUE THREAD

**Issue by GameDevs1337** [EvilMindDevs/hms-unity-plugin#198]
When will this plugin support other Ad types like Native Ads and Splash Ads?

**Comment by Lenzan** [comment]
When will this plugin support Native Ads

**Comment by alihan98ersoy** [comment]
Hello, 
We have added Splash ads to our plugin. We will also add native ads.
 It is on our roadmap.

**Comment by eozdemir90** [comment]
Hi there! Native ads will be ready at the beginning of December with the new version.
Thank you for your interest in our project. You may give a star to support us and follow up on the project. You can also join our discord channel to follow changes and ask any kind of question about the plugin, gaming ecosystem, etc. You may access it from here : https://discord.io/hmsunityplugin
Thank you and stay tuned!

**Comment by alihan98ersoy** [comment]
Hello, Our plugin now supporting [Native Ads](https://evilminddevs.gitbook.io/hms-unity-plugin_/kits-and-services/ads-kit/guides-and-references/native-ads) with its new version v2.2.8.
