### ISSUE TITLE
error CS0012: The type `System.Object' is defined in an assembly that is not referenced

### ISSUE THREAD

**Issue by pengjipan** [EvilMindDevs/hms-unity-plugin#2]
hi, my unity version is 2017.4.30f when i use this plugin,
scripting runtime version i switch to .net 4.6 equlvalent.
there is an error:Assets/Huawei/Demos/Account/AccountDemoManager.cs(38,32): error CS0012: The type `System.Object' is defined in an assembly that is not referenced. Consider adding a reference to assembly `System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
i want know what's your unity version?

**Comment by m0skit0** [comment]
We're currently using 2018.4.20f1, please try with this version and let us know if problem is fixed.

**Comment by pengjipan** [comment]
i fixed, thanks
