### ISSUE TITLE
Cant load advertisemant

### ISSUE THREAD

**Issue by RcSpoon** [EvilMindDevs/hms-unity-plugin#21]
Advertisemant for test blocks work fine, but for created blocks its not working. 

Manifest contains correct values com.huawei.hms.client.appid, com.huawei.hms.client.cpid and com.huawei.hms.version.
Blocks ids match with id from console

**Comment by RcSpoon** [comment]
adb contains error " java.lang.SecurityException: Permission denial: writing to settings requires:android.permission.WRITE_SECURE_SETTINGS" reports from HMS
![image](https://user-images.githubusercontent.com/26477070/84034615-02899580-a9b4-11ea-81d0-6934f852eb6d.png)

**Comment by RcSpoon** [comment]
On another device (huawei p20 light) no exceptions but NO_ADS error every time

[log.txt](https://github.com/EvilMindDevs/hms-unity-plugin/files/4746550/log.txt)

**Comment by m0skit0** [comment]
Make sure your app is released and not on draft for ad id to be valid.

NO_ADS simply means there are no more ads available from the ads server.

**Comment by RcSpoon** [comment]
Application is released, or you means this version must be released?

`NO_ADS simply means there are no more ads available from the ads server.`
This answer come every time for a week long. There is no one successful ads request

And how about security exceptions  on some devices? May be i need add special permissions in manifest?

**Comment by UlMuse** [comment]
I also wanted to create a ticket about advertising, in my case test advertising doesn't work. I created a new project, downloaded this plugin, opened a test scene with an advertising manager and this doesn't work. While loading ads, I get an error with code 2 all the time . And similar messages as in the example above - "  call reqRewardAd code: -1 msg: cmd not allowed to access in region 0 " . Why the test application may not work ? Checked for huawei p20 light , Unity 2019.2.21f

**Comment by m0skit0** [comment]
In which region are you?

**Comment by UlMuse** [comment]
> In which region are you?

Ru. The application was tested in  Russia.

**Comment by UlMuse** [comment]
I found a problem! This was related with HMS version on my device. The maximum version 3.0 is available in the market, but 4.0> is needed. After the update, everything was fine. The question is closed, I think)

**Comment by m0skit0** [comment]
Thanks a lot for reporting the solution!

**Comment by m0skit0** [comment]
@RcSpoon can you please confirm solution proposed by UIMuse works for you too?

**Comment by RcSpoon** [comment]
On both devices HMS Core version 4.0.4.xxx. and this is still not working (but test works)
 Region of tests devices Russia and Germany through VPN

**Comment by RcSpoon** [comment]
oh, maybe i'm found what's the problem. Advertisement work only if build version code is match with current released build. But in same time purchasing sandbox required version code bigger than released.
If change version code on older value advertisement will works.
You cant test purchasing and advertisement in same build
