### ISSUE TITLE
Support for RewardAd callbacks onRewardAdLeftApp() and onRewardAdCompleted()

### ISSUE THREAD

**Issue by user1767** [EvilMindDevs/hms-unity-plugin#214]
With the current set of callbacks for RewardAd I think it's impossible to know when the ad has exited after the user has clicked the ad because none of the current callbacks are called on that situation. I think making it possible to add listeners for onRewardAdLeftApp and maybe for onRewardAdCompleted for completeness would fix the issue.

Thank you for all the fixes so far.

**Comment by sametguzeldev** [comment]
Hello there.
As you've said, apparently there is RewardAdListener class on the Java side that has the callbacks you are asking for. They had RewardAdLoadListener and RewardAdStatusListener classes but it seems like they will deprecate in the future. 

I did not see the usage of RewardAdListener in documents or codelab that is why I missed it. I'll be putting those callbacks for the next version.

**Comment by sametguzeldev** [comment]
Hello there.
These callbacks are added on the 2.0.13 version. Please check that release.

**Comment by user1767** [comment]
I see they are included, thanks. I didn't see OnRewardAdLeftApp being called but I think I just haven't received the right kind of adds.
