### ISSUE TITLE
Easier way to programmatically enable/disable the plugin

### ISSUE THREAD

**Issue by user1767** [EvilMindDevs/hms-unity-plugin#215]
Our app needs to be build for multiple stores and we cannot include huawei sdk in other stores except AppGallery. However, removing the plugin for other stores is messy because the plugin creates gameobjects automatically if it's enabled. Currently we are manually removing the gameobjects from the scene in the editor and then recreating them at runtime. However, after opening the plugin settings the gameobjects are always recreated in the editor and need to be removed again. We cannot disable the whole plugin by default because then the huawei sdks aren't included in the built apk.

To support multiple build variants, would it be a good idea to include an option that disabled the automatic creation of gameobjects on the scene without disabling the whole plugin?

**Comment by sametguzeldev** [comment]
Hello there.
Are you saying that game objects are created while the plugin is not enabled?

**Comment by sametguzeldev** [comment]
I just tested it and came across to a bug when several kits are enabled, I disabled the plugin and it removed all gameobjects in the scene. I closed the Kit Settings window and re-opened, even though plugin is disabled, gameobjects got created again. If this is your case, I can resolve it. But I feel like you are talking about something else?

**Comment by user1767** [comment]
What I'm looking for is a way to programmatically enable the plugin for other builds while disabling it for others. Enabling/Disabling the plugin through the editor's Kit Settings is not enough. IIt might be enough if the bug is fixed so that the gameobjects are not recreated when the plugin is disabled. The I could have the plugin disabled in the editor by default and then use `HMSPluginSettings.Instance.Settings.SetBool(PluginToggleEditor.PluginEnabled, true);` in some build preprocess function for AppGallery build, but I'm not sure if it's then enabled soon enough for the huawei plugin to run its own build preprocess functions.

**Comment by user1767** [comment]
What I'm looking for is a way to programmatically enable the plugin for other builds while disabling it for others. Enabling/Disabling the plugin through the editor's Kit Settings is not enough.

I now noticed that it might be enough if the bug is fixed so that the gameobjects are not recreated when the plugin is disabled. Then I could have the plugin disabled in the editor by default and use `HMSPluginSettings.Instance.Settings.SetBool(PluginToggleEditor.PluginEnabled, true)` in a build preprocess function for AppGallery build, but I'm not sure if the plugin is then always enabled soon enough for the huawei plugin to run its own build preprocess functions. It seems to work though.

My first idea was that the huawei plugin could be enabled by default without the gameobjects and then I could just remove the huawei plugin's files before running the build for other stores. That solution feels bit hackish but it has worked.

**Comment by user1767** [comment]
So to summarize, please fix the recreation of gameobjects when the plugin is disabled and if you know a way to programmatically enable the plugin, please tell.

**Comment by sametguzeldev** [comment]
Are you using your own managers for the plugin and you don't need the gameobjects created by the plugin?

**Comment by user1767** [comment]
We have been creating the managers like this:

**Comment by user1767** [comment]
We have been creating the managers like how the huawei unity plugin creates them in the editor scripts:
```
			if (GameObject.FindObjectOfType<HMSAdsKitManager>() == null)
			{
				var obj = new GameObject("HMSAdsKitManager");
				obj.AddComponent<HMSAdsKitManager>();
			}

```

**Comment by sametguzeldev** [comment]
Hmm, I see. You have custom script-defined symbols and usage of preprocessor directives in your scripts.
I am thinking about a way to programmatically enable the plugin with having a parameter asking the developer to create the gameobjects or not.

Because some developers might still need to have game objects created at the scene.

**Comment by user1767** [comment]
Thank you. I also think it's best to have an option.

I also think making the plugin work without gameobjects could simplify things. For example, with gameobjects we also sometimes have to wait one frame after creating one before we can use it so that there has been time for its MonoBehavior initialization methods to be called.

Also if there is going to be a new API my early wish for it is that it take into account restarting of the game because it seems that the way unity supports restarting a game is that it supports clearing all instance data but it cannot clear static data. So if the new api relied on static variables/methods it would help if there was a way to know if it's already initialized for example. Or maybe it could rely more on instance variables/methods, I don't know.

**Comment by sametguzeldev** [comment]
Since Unity itself is not getting killed while restarting/switching to another scene, static data will not disappear. This is where most leaks come from. Our new API will subscribe to MonoBehaviour lifecycles (such as OnDestroy or similar that we need) and the plugin will clear the data that needs to be cleared in the memory.

**Comment by user1767** [comment]
To remove the plugin for other stores it would also help if all the plugin's files were under one directory. Now I need to manually remove all the files in Resources and Plugins. I think at least Resources could be moved under Assets/Huawei (see https://docs.unity3d.com/ScriptReference/Resources.Load.html) and I think you can move Plugins too, but the files in Assets/Huawei/Plugins directory then maybe need to be manually set as android plugins, I'm not sure.

**Comment by sametguzeldev** [comment]
Why you are in need of removing those files? They are not getting included in the build.

**Comment by user1767** [comment]
I was also under the impressions that everything in the Resources do get included in the build. We also have so many assets that we need to maintain that if we don't keep their files in order they easily leave the code base messy. It might also be easy to confuse those assets to one of our own. I think this policy of ours might have also other reasons behind it.

**Comment by sametguzeldev** [comment]
Resources yes but Plugins no.
The plugin is automatically stripping all native stuff in the Plugins folder if they are not used.
Nonetheless, I am moving the Plugins and Resources folder into the Huawei directory. But since developers will import the new package into their existing project, the files under the Resources and Plugins folder needs to be removed. I think I'll write another script just for this version to remove those files automatically when updating from 2.0.x version to 2.0.13 version.

**Comment by sametguzeldev** [comment]
Hello there.
Please check the 2.0.13 version about these issues. Plugins and Resources folders are moved under the Huawei folder and added HMSEditorUtils.SetHMSPlugin(bool,bool) function to enable/disable plugin programmatically with the option of creating/destroying managers.

**Comment by user1767** [comment]
Thanks for the directory clean up and  "Enable plugin without Managers" helps, although I have to use it after every time I have opened the kit settings, but it's ok.

**Comment by AntonPetrov83** [comment]
I have excluded HMS by defining a compiler symbols for that. But I still am getting a gradle error around `org.m0skit0.android.hms.unity` what looks like the android plugin is not stripped away. At least during the gradle build progress.

**Comment by alihan98ersoy** [comment]
This issue seems very old. You can disable the plugin from the kit settings if you want to exclude HMS. 
![image](https://user-images.githubusercontent.com/39373386/215421777-dcad460a-58ee-4f7e-b5ed-184fd3db74fc.png)
