### ISSUE TITLE
photoUrl is null

### ISSUE THREAD

**Issue by flashmandv** [EvilMindDevs/hms-unity-plugin#218]
Hello,

So finally I integrated the SDK with IAP, Huawei ID and game services.
After many difficulties, errors and stuff - it is all working now (except for the avatar photoUrl).

`authServiceManager.OnSignInSuccess` succeeds with users Uid and DisplayName (which are correct), but no PhotoUrl is provided (it returns null although the account has one). HMS core is latest version, Unity SDK is also the latest from release section.
My Unity is 2019.4.30 if it matters. 

I'm not sure if this is SDK issue or huawei not allowing the avatar anymore.

Any help is welcome, thanks!

**Comment by sametguzeldev** [comment]
Hello there.
I'll check into this and get back to you.

**Comment by flashmandv** [comment]
Thank you!
I posted 2 issues about my problems..and closed them, because I've found the cause. You can check them out. Surely some new error messages in Unity could have saved me couple of hours of headbanging (especially the old HMS core version that I had).

**Comment by sametguzeldev** [comment]
Hello there.
Sorry for the late reply.
I've just tested your case and it works for me.
I used AuthService demo that is included In the project and I printed Displayname, UID and photoURL
![image](https://user-images.githubusercontent.com/6827857/141476573-ca4bd476-3922-4931-afac-e88458bb2fbb.png)
