### ISSUE TITLE
Testing non-consumable products

### ISSUE THREAD

**Issue by Black-Earl** [EvilMindDevs/hms-unity-plugin#219]
Hello. I have a question, how can I check the recovery of non-consumable products on a test account? When reinstalling the application, all products are considered not purchased, although I bought them (on a test account). And when the purchases are restored from the server, 0 purchased goods come. Also, if I buy a non-consumable product, and then
  Without restarting the game, I will press the restoration of purchases, I will also receive information about 0 purchased goods from the server.

**Comment by sametguzeldev** [comment]
Hello there,
Unfortunately, that is how the sandbox environment works. You can check this [link](https://developer.huawei.com/consumer/en/doc/development/HMSCore-Guides/sandbox-testing-0000001050035039) for more details.
It states that;
``` In the sandbox testing environment, to facilitate testing, you can purchase a non-consumable product, consume it, and then purchase another. ```

But if you want, I can open a ticket and ask the team about this behavior of sandbox testing.

**Comment by Black-Earl** [comment]
Thank you, we ourselves wrote a request to support Huawei. It's just that you have a lot of experience and I wanted to clarify this issue, suddenly I did something wrong.
