### ISSUE TITLE
When installing the application, a message from Google protection appears.

### ISSUE THREAD

**Issue by Black-Earl** [EvilMindDevs/hms-unity-plugin#221]
When installing the application, a message from Google protection appears. Which tells you that it was not possible to check the application, and prompts you to either install or cancel the installation. What could be the problem?

**Comment by sametguzeldev** [comment]
Do you have the same issue without using the plugin?

**Comment by MustafaCQN** [comment]
I understand that you are getting this error while downloading the .unitypackage file. Please inform if its wrong

Please provide more explanatory informations like screenshots or direct message from google protection.  Because interpretting the error is not helping us to solve it.

**Comment by Black-Earl** [comment]
I'm not sure if this is my fault. There is an option that when creating a certificate, I used the wrong keystore

**Comment by MustafaCQN** [comment]
Hi again, please try to install your app to your phone without using the plugin. Because it seems this issue is not related with the plugin
