### ISSUE TITLE
detection updating interface

### ISSUE THREAD

**Issue by Abolfazl597** [EvilMindDevs/hms-unity-plugin#222]
I have received this message from Huawei review team. "We found that the detection updating interface isn't called in HMS after the app's startup".
How can I implement 'update interface' when a new app version is released?
Huawei says without this feature the app can not be eligible for distribution in China mainland.

**Comment by alihan98ersoy** [comment]
This feature is not available at the moment, but it is in our roadmap.

**Comment by sametguzeldev** [comment]
@Abolfazl597  Hello there. I've finished implementing this feature. It will be available in the next version. Probably next week the new version is coming!

**Comment by Abolfazl597** [comment]
@sametguzeldev Hello, Thank you so much for your time to implement this feature. It will be great.

**Comment by Abolfazl597** [comment]
@sametguzeldev Hi, I wanted to know when the new version will be available. Thanks

**Comment by sametguzeldev** [comment]
Hello there. Should be here in the morning. We are adding some last changes.

**Comment by sametguzeldev** [comment]
Sorry for the delay, new version should be online in maximum three hours.

**Comment by sametguzeldev** [comment]
Sorry for the delay @Abolfazl597, new version should be online in maximum of three hours.

**Comment by Abolfazl597** [comment]
@sametguzeldev Thank you very much for your efforts.

**Comment by sametguzeldev** [comment]
> @sametguzeldev Thank you very much for your efforts.

I am having electricity problems at the moment. Yesterday was the same. Electricity doesnt want me to publish a new version 😃

**Comment by sametguzeldev** [comment]
Okay it is back, working on the release now 😄

**Comment by Abolfazl597** [comment]
Great. Sometimes something unpredictable happens at the last minute.

**Comment by sametguzeldev** [comment]
I've released the new version for Unity 2019-2020-2021 versions. Working on the 2018 version right now.
I've also changed the readme for the new CheckAppUpdate functionality you've asked.
You can find the details [here](https://github.com/EvilMindDevs/hms-unity-plugin/blob/master/README.md#app-update-in-game-service)
