### ISSUE TITLE
Build failure: FileNotFoundException 

### ISSUE THREAD

**Issue by FunBinge** [EvilMindDevs/hms-unity-plugin#23]
Hi!

We are getting the following build error when building an empty Unity Project with the latest Huawei SDK (downloaded from repo):

FileNotFoundException: Could not find file "UnityProject\Temp\StagingArea\assets\bin\Data\Managed\tempStrip\System.Runtime.dll"
(wrapper remoting-invoke-with-check) System.IO.FileStream..ctor(string,System.IO.FileMode,System.IO.FileAccess,System.IO.FileShare)

**Unity Version:** 2018.3.14f1
**Scripting Backend:** IL2CPP

Any help appreciated.

**Comment by m0skit0** [comment]
Can you please try disabling IL2CPP and try to build, just to know if the problem lies there. Thanks!

**Comment by FunBinge** [comment]
Hi @m0skit0 

Thanks for your help. Yep, looks like setting the scripting backend to mono allows me to build. Unfortunately our main project relies on IL2CPP.

**Comment by m0skit0** [comment]
Sorry, I did not explain myself properly. Please disable IL2CPP temporarily just to check if the error disappears so we can know if the cause is IL2CPP and focus on fixing the problem. I'm not asking you to modify your build permanently :)

**Comment by m0skit0** [comment]
Did you test with latest package release 1.1.1? Other devs report this fixes the error with IL2CPP for Unity 2019.

**Comment by FunBinge** [comment]
@m0skit0 Thanks for the update, yes it builds now!
