### ISSUE TITLE
Exception on Initialization

### ISSUE THREAD

**Issue by obergonsteve** [EvilMindDevs/hms-unity-plugin#234]
**Setting up HMS plugin (Unity 2019.4 on Mac) for the first time.

Defined some consumable products.
Set 'Initialize on Start' flag (although this happens if I initialize manually with CheckIapAvailability()

I get this exception:**

UnityEngine.AndroidJNIHelper.GetConstructorID (System.IntPtr jclass, System.Object[] args) (at /Users/bokken/buildslave/unity/build/Modules/AndroidJNI/AndroidJNI.bindings.cs:134)
UnityEngine.AndroidJavaObject._AndroidJavaObject (System.String className, System.Object[] args) (at /Users/bokken/buildslave/unity/build/Modules/AndroidJNI/AndroidJava.cs:357)
UnityEngine.AndroidJavaObject..ctor (System.String className, System.Object[] args) (at /Users/bokken/buildslave/unity/build/Modules/AndroidJNI/AndroidJava.cs:217)
HuaweiMobileServices.Utils.JavaObjectWrapper..ctor (System.String javaObjectCanonicalName, System.Object[] args) (at <fd8a68f3a8ef4da4818a0e3ee4cbe9fc>:0)
HuaweiMobileServices.Id.Scope..ctor (System.String uri) (at <fd8a68f3a8ef4da4818a0e3ee4cbe9fc>:0)
HuaweiMobileServices.Id.AccountAuthParams..cctor () (at <fd8a68f3a8ef4da4818a0e3ee4cbe9fc>:0)
Rethrow as TypeInitializationException: The type initializer for 'HuaweiMobileServices.Id.AccountAuthParams' threw an exception.
HmsPlugin.HMSAccountManager.Awake () (at Assets/Huawei/Scripts/Account/HMSAccountManager.cs:69)

**and then....**

/Users/bokken/buildslave/unity/build/Modules/AndroidJNI/AndroidJNI.bindings.cs:172)
UnityEngine.AndroidJavaObject._GetStatic[FieldType] (System.String fieldName) (at /Users/bokken/buildslave/unity/build/Modules/AndroidJNI/AndroidJava.cs:664)
UnityEngine.AndroidJavaObject.GetStatic[FieldType] (System.String fieldName) (at /Users/bokken/buildslave/unity/build/Modules/AndroidJNI/AndroidJava.cs:274)
HuaweiMobileServices.Utils.AndroidContext.get_ActivityContext () (at <fd8a68f3a8ef4da4818a0e3ee4cbe9fc>:0)
HuaweiMobileServices.IAP.Iap.GetIapClient () (at <fd8a68f3a8ef4da4818a0e3ee4cbe9fc>:0)
HmsPlugin.HMSIAPManager.CheckIapAvailability () (at Assets/Huawei/Scripts/IAP/HMSIAPManager.cs:53)
HmsPlugin.HMSIAPManager.Start () (at Assets/Huawei/Scripts/IAP/HMSIAPManager.cs:48)

**Any input gratefully received. I am completely stuck here.  If no solution forthcoming, will have to abandon HMS plugin and try something else.**

**Comment by sametguzeldev** [comment]
Hello there.
HMS Unity Plugin only works on android devices. Are you trying to run it on Unity Editor?

**Comment by obergonsteve** [comment]
Yes!  Who uses Unity on Android?

All the instructions refer to Unity Editor - eg. importing package, adding products.

https://github.com/EvilMindDevs/hms-unity-plugin

I can't believe what you just said!!!

**Comment by sametguzeldev** [comment]
To be able to use the kits inside the plugin, you need to build an apk and run it on an Android device.

**Comment by obergonsteve** [comment]
That's so disappointing.

Thanks for your reply.

**Comment by sametguzeldev** [comment]
That goes for most of the same products though. The same goes for google's plugin for Unity. To be able to test it fully, you need to build an apk and run it on an Android device.

**Comment by obergonsteve** [comment]
Ok thanks.

**Comment by obergonsteve** [comment]
How can I stop the HMSAccountManager exception in Unity Editor?

I am not calling this directly, so cannot use  _#if ! UNITY_EDITOR_

On that subject, do I need to call HMSAccountManager.Instance.SignIn() ?  Currently I am not...

**Comment by sametguzeldev** [comment]
You can just disable HMSAccountManager GameObject if you are running it on Unity Editor
