### ISSUE TITLE
Application fails validation. Writes what the Android virus contains: Cynos-BI

### ISSUE THREAD

**Issue by PavelPerelyin** [EvilMindDevs/hms-unity-plugin#235]
What to do?

**Comment by sametguzeldev** [comment]
Can you share more details also a screenshot of the review?

**Comment by sametguzeldev** [comment]
Hello there @PavelPerelyin.
Please download the v2.0.15 version to fix this issue.
Thanks!

**Comment by sametguzeldev** [comment]
Fixed in 2.0.15 version.
