### ISSUE TITLE
Enabling plugin is not adding the assembly in a build

### ISSUE THREAD

**Issue by Migueton** [EvilMindDevs/hms-unity-plugin#236]
Hi, I have a project that supports Google Play and Huawei, and I'm having some troubles only while building. I have a script that starts the building process for every platform and it enables or disables the HMS plugin. The problem I encounter is that even the assembly is added to the Android Platform when building for Huawei and there are no compile errors, the HMS scripts in the scene throws errors at the Start function when running the app.

```
 E/Unity: A scripted object (script unknown or not yet loaded) has a different serialization layout when loading. (Read 52 bytes but expected 60 bytes)
    Did you #ifdef UNITY_EDITOR a section of your serialized properties in any of your scripts?
    UnityEngine.Resources:Load(String)
    ScriptableHelper:Load(String, String)
    HmsPlugin.HMSIAPKitSettings:.ctor()
    System.Reflection.MonoCMethod:InternalInvoke(Object, Object[])
    System.Activator:CreateInstance()
    HMSEditorSingleton`1:get_Instance()
    HmsPlugin.HMSIAPManager:Start()
    
    [ line -25449944]
 E/Unity: Creating ScriptableObjects during runtime is not allowed!
    ScriptableHelper:Create(String, String)
    HmsPlugin.HMSIAPKitSettings:.ctor()
    System.Reflection.MonoCMethod:InternalInvoke(Object, Object[])
    System.Activator:CreateInstance()
    HMSEditorSingleton`1:get_Instance()
    HmsPlugin.HMSIAPManager:Start()
 
  E/Unity: NullReferenceException: Object reference not set to an instance of an object.
      at HmsPlugin.HMSIAPKitSettings..ctor () [0x00000] in <00000000000000000000000000000000>:0 
      at System.Reflection.MonoCMethod.InternalInvoke (System.Object obj, System.Object[] parameters) [0x00000] in <00000000000000000000000000000000>:0 
      at System.Activator.CreateInstance[T] () [0x00000] in <00000000000000000000000000000000>:0 
      at HMSEditorSingleton`1[T].get_Instance () [0x00000] in <00000000000000000000000000000000>:0 
      at HmsPlugin.HMSIAPManager.Start () [0x00000] in <00000000000000000000000000000000>:0 
    Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
      at System.Reflection.MonoCMethod.InternalInvoke (System.Object obj, System.Object[] parameters) [0x00000] in <00000000000000000000000000000000>:0 
      at System.Activator.CreateInstance[T] () [0x00000] in <00000000000000000000000000000000>:0 
      at HMSEditorSingleton`1[T].get_Instance () [0x00000] in <00000000000000000000000000
```

It seems Unity doesn't seem to reload the scripts properly after the assembly is changed. Restarting Unity fixes it, did anybody had this issue with the assemblies or know how to fix this? 

P.S: I am doing AssetDatabase.Refresh() but is still failing.

**Comment by sametguzeldev** [comment]
I think this is due to UnityEditor's cache. I had the same problem and researched a bit, this is a common issue on Unity about not releasing the cache properly.

**Comment by Migueton** [comment]
Does the plugin support removing the Managers GameObjects in the Scene and initialize by code? Maybe that way we could keep the HMS assembly enabled for Google Play builds as well. Do you think is that something that could work?

**Comment by sametguzeldev** [comment]
We support it under Huawei > Utils.
![image](https://user-images.githubusercontent.com/6827857/145000644-aa39b779-ceee-460d-b0b0-369768655a94.png)

And here is how to call it if you have a build pipeline and want to do this activity with a code.

https://github.com/EvilMindDevs/hms-unity-plugin/blob/968291dac51c4f3d4ca57475b1c6251df28dc7a9/Assets/Huawei/Editor/View/MainWindow/HMSMainWindow.cs#L26-L31

**Comment by sametguzeldev** [comment]
Have you tried the solution? @Migueton

**Comment by Migueton** [comment]
Not yet, im going to try today. I'll let you know

**Comment by Migueton** [comment]
After checking the Util tools, still haven't found a solution to my problem.

- Huawei > Utils > Enable Plugin: It doesn't instantiate the plugins until I open Huawei > Kit Settings, at the moment that window opens the game objects are instantiated. Besides that, it works.

- Huawei > Utils > Enable Plugin without Manager: This removes the game objects, but this is just for non-huawei builds (btw it will be nice that Huawei wouldn't need the managers in some game objects inside the scene)

- Huawei > Utils > Disable Plugin: Disabling the plugin will cause a change in the assembly when building, done by HMSGradleFixer or HMSGradleWorker. This is what is causing Unity errors for me, removing the assembly it causes to lose reference to the scripts in the game objects in the scene. 

What I'm trying to do is to keep the plugin disabled and the **assembly enabled always for Android** (avoiding the UnityEditor's cache problem), which is not possible in the current flow. With this, I just want to avoid that `OnPostGenerateGradleAndroidProject` at `HMSGradleFixer.cs` goes through agconnect-services gradle changes.

**Comment by sametguzeldev** [comment]
I see your point.
Currently in our flow, if you disable the plugin our plugin codes also get disabled because we did not want to include any of our code. If I am understanding correctly, you want to keep the plugin disabled which means it should not alter the gradle files, but you want to keep the assembly definitions because your code is referencing them?

**Comment by Migueton** [comment]
exactly, and also enabling and disabling the assembly creates sometimes corrupted builds where the manager scripts in the scene are missing for a Huawei build. Unity doesn't get on so well with updating the assemblies...

**Comment by sametguzeldev** [comment]
Yeah, I've had that issue as well... Restarting Unity fixes it sometimes...

We will be removing the gameobjects for each kits so this problem will fix itself later in the year :)

**Comment by Migueton** [comment]
@sametguzeldev that's nice to hear. Thanks for all the support to the plugin, I am looking forward to the next update. We can close this thread then.
