### ISSUE TITLE
After build apk with this plugin I have next issue from Huawei review team - "your App is detected to carry virus: Android:Cynos-BI [Spy]||mult."

### ISSUE THREAD

**Issue by AndreyMesheryakov** [EvilMindDevs/hms-unity-plugin#237]
Review team says the problem is with this plugin.
Can you please comment this?
Do you have any suggestion how to fix this?
Thanks!

**Comment by sametguzeldev** [comment]
We have big companies using our plugin and haven't heard anything like this before :)
The project is full opensource. If you can find a virus or something, please let me know 😄

**Comment by sametguzeldev** [comment]
Can you share the review from the Huawei team?

**Comment by AndreyMesheryakov** [comment]
> Can you share the review from the Huawei team?

Sure - 
//-----------------------------------------------------------
The new version cannot be released.
Reason for rejection:
[Description]: Your App is detected to carry virus: Android:Cynos-BI [Spy]||mult. Please refer to the rule 2.1 of "AppGallery Review Guidelines": https://developer.huawei.com/consumer/en/doc/distribution/app/50104
­[Suggestion]: Please check the apk file, code, third-party SDK or others to delete the virus-relevant contents.
[Test Environment]: Wi-Fi connection, Mate30 pro with EMUI 10.1.0, P30 with EMUI 10.0.0, multilingual environment.
//-----------------------------------------------------------

I want to point out that I am not using any third-party SDK other than your plugin.
Also I want to point what i tried to check the resulting apk using https://www.virustotal.com. And virustotal.com also showed me that the apk contains a virus.
Should I try to make minimal ( clean project with hms unity plugin ) unity project to reproduce this issue?  Or is there enough information for now?

**Comment by sametguzeldev** [comment]
I will create an empty project that has only the plugin and generate an apk file. Then I will also use virustotal.com to see if there is the same virus warning.

**Comment by sametguzeldev** [comment]
@AndreyMesheryakov which kits are you using in your project?

**Comment by AndreyMesheryakov** [comment]
@sametguzeldev - I used only hms-unity plugin.

Steps to reproduce - 
1. Create new empty unity project
2. Download and import hms plugin
3. Build apk

After that I tested resulted apk file via https://www.virustotal.com - 
![virustotal_results](https://user-images.githubusercontent.com/8198505/144988091-a319300d-05e9-477a-bf31-b190905c27bf.png)

**Comment by sametguzeldev** [comment]
Yes, but which kits are you using?
When I build an apk with the plugin enabled but no kits selected, I am not getting any virus errors.

**Comment by AndreyMesheryakov** [comment]
Account manager + ads + iap

**Comment by sametguzeldev** [comment]
It is really weird. If you build three different apk with only Account, Ads or IAP kit enabled, it does not say that it has a virus. But if you enable all three together, it says there is a virus.

I'll also try putting the same HMS libraries on a java project and see if it still gives the same result.

**Comment by devaliarshad** [comment]
@sametguzeldev having same issue on my end too.

**Comment by sametguzeldev** [comment]
@AndreyMesheryakov hello there.
Can you uncheck the appcompat library, build an apk and see the results from virustotal?
![image](https://user-images.githubusercontent.com/6827857/145024029-c5d1b708-30ce-4e4b-9bd9-d9d5f8eee406.png)

**Comment by sametguzeldev** [comment]
@AndreyMesheryakov @devaliarshad I've released a new version 2.0.15 that should fix this issue. Can you please download that version and give it a try?

**Comment by AndreyMesheryakov** [comment]
@sametguzeldev 
With unchecked checker and minimal repro project the virustotal don't find a virus.
Now I will try on a real project.

**Comment by sametguzeldev** [comment]
> @sametguzeldev With unchecked checker and minimal repro project the virustotal don't find a virus. Now I will try on a real project.

I forgot to update the version number inside the package. Can you also re-download the unitypackage? I just updated the new one.

**Comment by AndreyMesheryakov** [comment]
@sametguzeldev Our game with the latest version of the plugin has been reviewed and passed to the store.
Looks like you fix this issue. Big thanks!

**Comment by sametguzeldev** [comment]
Closing this issue since its resolved.
