### ISSUE TITLE
ads and iap issue

### ISSUE THREAD

**Issue by IamFarCry4** [EvilMindDevs/hms-unity-plugin#24]
hello there i am trying to implement hms ads and iap to my unity game. I did exactly same as demo scene but no ads being shown on my game. And for iap i tried to uncomment IapDemoManager but i faced lots of error. Is there any way to implement iap in my game? Thank you

**Comment by m0skit0** [comment]
Hi, thanks for using our plugin :)
For ads, is the demo working? If so, can you share the logcat output from the device?
For IAP, you can check IapManager prefab, it has all the functions needed for IAP. IAP demo is still being worked on, sorry for the inconveniences.

**Comment by IamFarCry4** [comment]
thanks for your reply. Does the demo ads works even if game is not released?

**Comment by m0skit0** [comment]
No, if the app is not released the ad ids will not work. For that you can use the testing ids (you can find them on the demos).
