### ISSUE TITLE
Resume app after Huawei login throws OnFailureListenerWrapper

### ISSUE THREAD

**Issue by Migueton** [EvilMindDevs/hms-unity-plugin#249]
Hi, I implemented the Huawei login, but some users are getting a NullReferenceException when the app is resumed after the Huawei login popup. Has anyone faced this before? Couldn't find any related issue.

```
NullReferenceException Object reference not set to an instance of an object.      
<00000000000000000000000000000000> HuaweiMobileServices.Base.OnFailureListenerWrapper+<>c__DisplayClass2_0.<onFailure>b__0()    
<00000000000000000000000000000000> System.Action.Invoke()     
<00000000000000000000000000000000> HuaweiMobileServices.Utils.HMSDispatcher.Update()
```

I leave here some breadcrumbs from HMS
```
-HMS GAMES init
-[HMS]: GET AUTH GAME
-[HMS]: AUTHPARAMS GAMEHuaweiMobileServices.Id.AccountAuthParams
-[HMS]: RESULT GAMEHuaweiMobileServices.Id.AccountAuthService
-HMS GAMES: The app has not been authorized
-MessagingUnityPlayerActivity#onPause()

-User fills login data

-MessagingUnityPlayerActivity#onResume()
-NullReferenceException Object reference not set to an instance of an object.      
<00000000000000000000000000000000> HuaweiMobileServices.Base.OnFailureListenerWrapper+<>c__DisplayClass2_0.<onFailure>b__0()    
<00000000000000000000000000000000> System.Action.Invoke()     
<00000000000000000000000000000000> HuaweiMobileServices.Utils.HMSDispatcher.Update()
```

**Comment by alihan98ersoy** [comment]
We are looking into it.

**Comment by alihan98ersoy** [comment]
![signInFailure_notInit](https://user-images.githubusercontent.com/39373386/145280214-30ed7ea0-2fd5-4d39-b79d-2ab93342760b.png)
In HMSGameManager.cs init method 
authService.StartSignIn((auth) => { InitJosApps(auth); SignInSuccess?.Invoke(auth); }, **SignInFailure**);
SignInFailure is not initialized please initialize it.

` public void Init()
        {
            Debug.Log("HMS GAMES init");
            authService = HMSAccountManager.Instance.GetGameAuthService();
            
            ITask<AuthAccount> taskAuthHuaweiId = authService.SilentSignIn();
            taskAuthHuaweiId.AddOnSuccessListener((result) =>
            {
                InitJosApps(result);
                SignInSuccess?.Invoke(result);

            }).AddOnFailureListener((exception) =>
            {
                Debug.Log("HMS GAMES: The app has not been authorized");

                SignInFailure = SignInFailureMethod;
                authService.StartSignIn((auth) => { InitJosApps(auth); SignInSuccess?.Invoke(auth); }, SignInFailure);

                InitGameManagers();
            });
        }

        private void SignInFailureMethod(HMSException obj)
        {
            Debug.Log("0HMS GAMES: SignInFailureMethod obj:" + obj);
        }`

**Comment by Migueton** [comment]
@alihan98ersoy thanks, it works now. Will this be updated in the plugin in the HMSGameManager script?

**Comment by Migueton** [comment]
sorry, after some testing I noticed that the SignInFailure Action was not being invoked. Rather than having a new method SignInFailureMethod(), I think is better just to invoke the Action with `(exc) => SignInFailure?.Invoke(exc)`.

```
  public void Init()
        {
            Debug.Log("HMS GAMES init");
            authService = HMSAccountManager.Instance.GetGameAuthService();

            ITask<AuthAccount> taskAuthHuaweiId = authService.SilentSignIn();
            taskAuthHuaweiId.AddOnSuccessListener((result) =>
            {
                InitJosApps(result);
                SignInSuccess?.Invoke(result);

            }).AddOnFailureListener((exception) =>
            {
                Debug.Log("HMS GAMES: The app has not been authorized");
                authService.StartSignIn((auth) => { InitJosApps(auth); SignInSuccess?.Invoke(auth); }, (exc) => SignInFailure?.Invoke(exc));
                InitGameManagers();
            });
        }
```

**Comment by sametguzeldev** [comment]
> sorry, after some testing I noticed that the SignInFailure Action was not being invoked. Rather than having a new method SignInFailureMethod(), I think is better just to invoke the Action with `(exc) => SignInFailure?.Invoke(exc)`.
> 
> ```
>   public void Init()
>         {
>             Debug.Log("HMS GAMES init");
>             authService = HMSAccountManager.Instance.GetGameAuthService();
> 
>             ITask<AuthAccount> taskAuthHuaweiId = authService.SilentSignIn();
>             taskAuthHuaweiId.AddOnSuccessListener((result) =>
>             {
>                 InitJosApps(result);
>                 SignInSuccess?.Invoke(result);
> 
>             }).AddOnFailureListener((exception) =>
>             {
>                 Debug.Log("HMS GAMES: The app has not been authorized");
>                 authService.StartSignIn((auth) => { InitJosApps(auth); SignInSuccess?.Invoke(auth); }, (exc) => SignInFailure?.Invoke(exc));
>                 InitGameManagers();
>             });
>         }
> ```

Yes, It is already updated on our side just as you've fixed yours. It should be here in the new version.

**Comment by Migueton** [comment]
thanks
