### ISSUE TITLE
Errors after importing package into project.

### ISSUE THREAD

**Issue by nubfight4** [EvilMindDevs/hms-unity-plugin#25]
I received a few errors after importing the package onto my project and unsure how to fix it. I am using Unity 2019.1.13f1.

I am using the 2019 package as well but for some reason I got the first two errors only when I use the 2018 package.

> Assets\Huawei\Scripts\Game\GameManager.cs(46,38): error CS0266: Cannot implicitly convert type 'HuaweiMobileServices.Base.ITask<HuaweiMobileServices.Game.Player>' to 'HuaweiMobileServices.Base.ITask<Player>'. An explicit conversion exists (are you missing a cast?)

>Assets\Huawei\Scripts\Game\AchievementsManager.cs(70,46): error CS0266: Cannot implicitly convert type 'HuaweiMobileServices.Base.ITask<System.Collections.Generic.IList<HuaweiMobileServices.Game.Achievement>>' to 'HuaweiMobileServices.Base.ITask<System.Collections.Generic.IList<Achievement>>'. An explicit conversion exists (are you missing a cast?)

>Assets\Huawei\Scripts\Ads\RewardAdManager.cs(79,28): error CS0012: The type 'AndroidJavaObject' is defined in an assembly that is not referenced. You must add a reference to assembly 'UnityEngine.AndroidJNIModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.

>Assets\Huawei\Scripts\Account\AccountManager.cs(17,38): error CS0012: The type 'AndroidJavaObject' is defined in an assembly that is not referenced. You must add a reference to assembly 'UnityEngine.AndroidJNIModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.

**Comment by m0skit0** [comment]
I'm sorry, I don't quite understand. You're using the 2018 package in Unity 2019? Why?

**Comment by nubfight4** [comment]
I was trying out both the 2019 and 2018 package. But the 2018 package seemed to have less errors.

**Comment by m0skit0** [comment]
If you're using Unity 2019 you should use the 2019 package, there's no way the 2018 package will work even if it shows less errors. Did you try with latest package release? Can you please post the errors you're getting using the 2019 package?
