### ISSUE TITLE
namespace name 'OfficeOpenXml' could not be found 

### ISSUE THREAD

**Issue by IamFarCry4** [EvilMindDevs/hms-unity-plugin#255]
The type or namespace name 'OfficeOpenXml' could not be found (are you missing a using directive or an assembly reference?)
I am getting this error after trying to build the apk, i have facebook and hms plugin imported in my project.

**Comment by sametguzeldev** [comment]
Hello there. Please re-download the package again. I've fixed it and uploaded as same version.

**Comment by sametguzeldev** [comment]
Did that fix it for you ? @IamFarCry4
