### ISSUE TITLE
Checking iap availability Error

### ISSUE THREAD

**Issue by SteliosDaVitzi** [EvilMindDevs/hms-unity-plugin#258]
When trying to check iap availability the following error occurs
![Screenshot_4](https://user-images.githubusercontent.com/35687170/147058535-149f99a6-eb23-425e-ace9-99c9db642615.png)

**Comment by sametguzeldev** [comment]
Hello there.
Please make sure that the app-debug.aar file is under Assets\Huawei\Plugins\Android and not removed.
Also, can you tell me which version of HMS Core is installed on the device?
