### ISSUE TITLE
Cann`t use auth service!

### ISSUE THREAD

**Issue by ranhujia** [EvilMindDevs/hms-unity-plugin#259]
my agconnect-services.json is latest! what`s wrong wiht this?
![4e8275546a9b8647e2171f689cd42d4](https://user-images.githubusercontent.com/6678303/147335221-26c87c39-0676-42e4-b75f-2136ee948085.png)
my plugin version is 2.10-2018
my unity version is 2018.4.36
the test device is MAR-LX1A android 10

**Comment by sametguzeldev** [comment]
Hello there.
Haven't really encountered this kinda error. Is it reproducible?

**Comment by ranhujia** [comment]
Yes, it's reproducible. I asked the developer of huawei, he told me use the latest Huawei HMS AGC Services in the Unity Asset store! https://assetstore.unity.com/packages/add-ons/services/huawei-hms-agc-services-176968?locale=zh-CN

**Comment by sametguzeldev** [comment]
I've tried our demo project for AuthService that is included in the plugin but did not encounter this issue.
It seems like it is failing when trying to read the JSON file.
What is the HMS Core version on your device?

**Comment by ranhujia** [comment]
the cor version is 6.2.0.301, I will test it with Unity's guide later, thanks for your patience!

**Comment by sametguzeldev** [comment]
You are welcome!
