### ISSUE TITLE
Test Ads problem

### ISSUE THREAD

**Issue by Vetrazio** [EvilMindDevs/hms-unity-plugin#261]
There is a problem that I just can't seem to deal with. I do the SDK setup as it is written in the manual. As a result, if I check the "test" checkbox in the Ads, it always says "is not loaded yet". 
If I uncheck the box, then the error java.lang.ClassNotFoundException: org.m0skit0.android.hms.unity.adListener pops up. 

I am testing in Cloud huawei debagger . They have good connection and the versions of the HMS core they have are correct. I can't even run test ads. It can be my stupid mistake somewhere, but i tried everything...

**Comment by sametguzeldev** [comment]
Hello there.
Please make sure to check that you have app-debug.aar file inside Assets/Huawei/Plugins/Android folder.
Also if you are using proguard or stripping android codes, that can make it lose reference as well.
