### ISSUE TITLE
[Ads] Missing IConsentUpdateListener interface in HuaweiMobileServices.dll

### ISSUE THREAD

**Issue by MantasKriksciunas** [EvilMindDevs/hms-unity-plugin#264]
Hi again,

I'm trying to implement a Consent Update Listener as it's required on my end to ask for user's permission, however, there's no ```IConsentUpdateListener``` interface in ```HuaweiMobileServices.Ads``` namespace for handling this logic. As there are other interfaces like ```IAdListener```,  ```IRewardAdLoadListener```, ```IRewardAdStatusListener```, this might be overlooked.

When searching online for more information, I've only come across this forum post, that suggested using ```AndroidJavaProxy``` and defining listener methods to match the existing Java class methods: https://forums.developer.huawei.com/forumPortal/en/topic/0202368285489570330

After repeatedly requesting for consent listener update and using different countries Internet access through a VPN, I always get the ```onFail``` callback with a ```network failed``` error. 

I suspect as the shown approach was posted 2 years back it might be outdated or other actions are required to make this work.

Here's my code snippet:

```c#
private const string JAVA_CONSENT_NAME = "com.huawei.hms.ads.consent.inter.Consent";
private const string JAVA_DEBUG_NEED_CONSENT_NAME = "com.huawei.hms.ads.consent.constant.DebugNeedConsent";
private const string JAVA_CONSENT_STATUS_NAME = "com.huawei.hms.ads.consent.constant.ConsentStatus";
private const string JAVA_CONSENT_UPDATE_LISTENER_NAME = "com.huawei.hms.ads.consent.inter.ConsentUpdateListener";
private const string JAVA_UNITY_PLAYER_NAME = "com.unity3d.player.UnityPlayer";

AndroidJavaClass consent_class;
AndroidJavaClass unity_player_class;
AndroidJavaObject activity_instance;
AndroidJavaObject consent_instance;

private void Start()
{
    consent_class = new AndroidJavaClass(JAVA_CONSENT_NAME);
    unity_player_class = new AndroidJavaClass(JAVA_UNITY_PLAYER_NAME);
    activity_instance = unity_player_class.GetStatic<AndroidJavaObject>("currentActivity");
    consent_instance = consent_class.CallStatic<AndroidJavaObject>("getInstance", activity_instance);

    MConsentListener _consent_listener = new MConsentListener();
    consent_instance.Call("requestConsentUpdate", _consent_listener);

    HwAds.Init();
}

public class MConsentListener : AndroidJavaProxy
{
    public MConsentListener() : base(new AndroidJavaClass(JAVA_CONSENT_UPDATE_LISTENER_NAME))
    {

    }

    public void onFail(string errorDescription)
    {
        Debug.Log("Huawei Ads consent error: " + errorDescription);
    }
            
    public void onSuccess(AndroidJavaObject consentStatus, bool isNeedConsent, AndroidJavaObject adProviders)
    {
        Debug.Log("SUCCESS");
    }
}
```

Perhaps I'm missing something or there are certain conditions/prerequisites needed?

EDIT:
It's not just the interface but the whole Consent class is missing

**Comment by sametguzeldev** [comment]
Hello there @MantasKriksciunas
Consent class and all depending classes are missing because we did not implement the consent library to our wrapper yet :)

Your approach seems fine but there are some methods you might need to call before.
You can check the documents [here](https://developer.huawei.com/consumer/en/doc/development/HMSCore-References/consent-0000001057445071).
There is also a guide [here](https://developer.huawei.com/consumer/en/doc/development/HMSCore-Guides/publisher-service-consent-settings-0000001075342977) that has usage and more information.

You can also request this feature from us and our team will put this in the roadmap to develop and deliver to developers 👍

**Comment by alihan98ersoy** [comment]
Hello,
We added consent with the new version #296
