### ISSUE TITLE
Ads not load yet

### ISSUE THREAD

**Issue by ChipChipsGames** [EvilMindDevs/hms-unity-plugin#268]
Hi everyone
I need everyone's help. I just used Huawei's Kit Ads to include in my game
But I tried many ways but the ad still doesn't show
" Banner is null" , "IntersAds Reward Ads Not Load Yet"
I checked , there is have app-debug file in plugins , I am not using proguard file. I use the latest version of HMSUnityPackageV2.1.1-2019-2020-2021
I don't know what I did wrong. Or am I missing something in the AndroidManifest , Main Manifest , Main Gradle , Laucher Gradle , Base Gradle files. Can anyone give me parameters on how to properly set up each file? What is the correct order to do to make the ad show properly?

But I have tried many ways but still no ads. Please Help me . I don't know what to do anymore
Thank you very much

**Comment by alihan98ersoy** [comment]
Hello Can you please use the adb pull /sdcard/Android/data/com.huawei.hwid/files/Log/HiAdKitLog.log command to obtain the log and send it to us. And are you getting any error?

**Comment by ChipChipsGames** [comment]
Hi @alihan98ersoy  . I instant app in my phone ( LG phone ), /sdcard/Android/data/com.huawei."AppName"/files/  but don't find folder Log in this , i don't know

I use Admod to run ads very easily and simply. But it can't run Huawei ads, I'm working on a brand new Proects, I just want to know how to show ads, I'm new so I don't know if I'm missing something or not
I don't know if there is a complete tutorial that goes from the beginning to the output of the apk file, , all necessary settings
Right now I really need a complete tutorial to set everything up right

**Comment by alihan98ersoy** [comment]
![resim](https://user-images.githubusercontent.com/39373386/150629470-5f6e000d-6a28-4b2b-8b82-9be3a178f8e4.png)
LG not on the list. please use Huawei phones to test your app.
If you do not have an Huawei phone, you can use Cloud Debugging of AppGallery Connect to test it. Cloud Debugging tests your app using mainstream Huawei devices provided by Huawei. You can run your app on the latest and most popular Huawei devices to test app functions.

Also you can check our ads demo scene. https://github.com/EvilMindDevs/hms-unity-plugin/tree/master/Assets/Huawei/Demos/Ads

**Comment by ChipChipsGames** [comment]
Yes . I test app on Cloud Debugging of AppGallery Connect . And I use HMSUnityPackageV2.1.1-2019-2020-2021 and Demo Scene , all the way but still not working .
" Banner is null" , "IntersAds Reward Ads Not Load Yet"
I checked , there is have app-debug file in plugins , I am not using proguard file

I really don't know what to do to be able to run ads
Do you use any special settings? I think I'm missing a setting step that can't connect to the service, can't load ads

**Comment by alihan98ersoy** [comment]
Can you get the Ads Kit logs? There is 2 method for getting logs in question3 https://developer.huawei.com/consumer/en/doc/distribution/monetize/faq-0000001161265851

**Comment by ChipChipsGames** [comment]
Sorry, I try but I'm not good at it so I can't do it :(
I use Unity 2021.1.19f1 (64-bit). Do you have a small project that has run 3 types of Ads successfully . Send it to me so I can see where I'm wrong and different. But now I really don't know how to solve it

**Comment by ChipChipsGames** [comment]
https://drive.google.com/file/d/1oB15h3AWXvEDeQrPjvDsgEakBoT0wMKp/view?usp=sharing
This is my game APK , you can check for me . I try but i don't find Log you want

**Comment by sametguzeldev** [comment]
> https://drive.google.com/file/d/1oB15h3AWXvEDeQrPjvDsgEakBoT0wMKp/view?usp=sharing This is my game APK , you can check for me . I try but i don't find Log you want

Hello there.
Have you configured the Ads section inside Unity Editor? You can access there through menu items. Huawei > Kit Settings
![image](https://user-images.githubusercontent.com/6827857/150636427-18e4788a-96fa-4d01-aafa-bef3ece8cf5c.png)

**Comment by alihan98ersoy** [comment]
![resim](https://user-images.githubusercontent.com/39373386/150639345-9bfaecb9-5da4-4dce-b43c-ed153e614451.png)
Bannerview is null. Please refer to https://github.com/EvilMindDevs/hms-unity-plugin/blob/9c6f7b7853c15cfd36df9d995023ab3cd4431bc5/Assets/Huawei/Scripts/Ads/HMSAdsKitManager.cs

**Comment by sametguzeldev** [comment]
> @sametguzeldev Yes . I made all . But Ads ... . I don't know ![1](https://user-images.githubusercontent.com/98200281/150637865-e1b2b3f5-ccd2-4415-aa5d-10a6e64a7189.jpg) s

You know you can't run it on Unity Editor right? You need to build an apk and run it on your phone. Also if your app is not released and if it's a new app, real ad Ids won't work. You need to use test ads.

**Comment by sametguzeldev** [comment]
Check my comment above. You cannot run the plugin in Unity Editor. You need to build an apk and run it on the phone.

Also, you don't need to do anything with gradle files. The plugin is automatically handling everything.

**Comment by ChipChipsGames** [comment]
@sametguzeldev  yes. I made Apk file , and test in Cloud Debugging of AppGallery Connect , and I always check * Test Ads :( . But Ads don't show . I don't know what I did wrong, maybe something is missing. But can't fix it. First time using HMS so I don't know how :(

**Comment by sametguzeldev** [comment]
Can you make a new apk that contains all unity editor setting stuff included?
Because when I check the logs of your apk, I don't see any error happening. Because the methods that need to request for ads are not being called.

**Comment by ChipChipsGames** [comment]
@sametguzeldev Yes I made new APK according to what you say. But still not showing ADS . This is the Log file when running the new file
But this Kit when starting to run the app . Don't Destroy On Load , HMS Kit Manager ---> Uncheck . So do not run HMS Kit Start . I see you already have Don't Destroy 
![2](https://user-images.githubusercontent.com/98200281/150641299-99e491e1-3019-4af7-b4db-91b83672e2c9.jpg)
On Load, so that's okay. So the problem is HMS Kit Manager ---> Uncheck , but how to fix it when it is the default of HMS Kit Manager ?
[2022-01-22 20_51_44.log](https://github.com/EvilMindDevs/hms-unity-plugin/files/7918468/2022-01-22.20_51_44.log)
oblem is HMS Kit Manager ---> Uncheck , but how to fix it when it is the default of HMS Kit Manager ?

**Comment by sametguzeldev** [comment]
Can you upload the apk here?

**Comment by ChipChipsGames** [comment]
Yes . It still not show Ads .Is it because Don't Destroy On Load , HMS Kit Manager ---> Uncheck . So don't run HMS Kit Start ?
https://drive.google.com/file/d/14HH-cM3U2cgt_8vftjAVzI3OqXO4Tjx6/view?usp=sharing

**Comment by ChipChipsGames** [comment]
@sametguzeldev And I just selected only Ads in Kit , I don't know if there are any other functions to choose from ? I'm afraid I'm missing somethin
![3](https://user-images.githubusercontent.com/98200281/150641757-a0a8eac9-bf3c-4b57-8ca8-902c5acc19f1.jpg)
g

**Comment by sametguzeldev** [comment]
Your apk seems to be working fine for me.
There is an issue with the banner ads though. This issue has been reported to Huawei and they will fix the banner that is taking the whole screen at the bottom.


![image](https://user-images.githubusercontent.com/6827857/150641947-0cfd25ff-613b-454c-9c47-404947ac5d15.png)

![Screenshot_20220122_171333_com ChipChipsGames EggsAndBirds huawei](https://user-images.githubusercontent.com/6827857/150641922-b9831e2c-7ac2-469c-af4c-499de3120687.jpg)

**Comment by ChipChipsGames** [comment]
@sametguzeldev What ? Why I test it not show ? I don't understand, so is my ad running normally? But when I test it, it doesn't show up
So how do I know if it's successful or not if the ad doesn't show up during the test? How did you do that?

**Comment by sametguzeldev** [comment]
I could not make it run in Cloud Debugging as well. It returns error code 0(zero) for banner ads. I'll do some tests and come back to you with results.

**Comment by ChipChipsGames** [comment]
@sametguzeldev thank you . I will Upload apps first

**Comment by sametguzeldev** [comment]
> @sametguzeldev thank you . I will Upload apps first

It seems like it is SIM card issue. For some devices, it actually requires SIM card inserted so it can read the region etc. Since Cloud Debugging devices does not have a SIM card installed, it fails to load the ads.
For instance, it did not work on P40 device but it worked on P30 device.
![image](https://user-images.githubusercontent.com/6827857/150643400-de5268fd-9ec8-47b3-bbcf-c3939699190c.png)

**Comment by sametguzeldev** [comment]
> @sametguzeldev thank you . I will Upload apps first

Don't forget to uncheck "Use Test Ads" checkbox if you are making a release build.

**Comment by ChipChipsGames** [comment]
@sametguzeldev Yes , I know, without your support I don't know what to do. Hope you will give good support to the app development community for App Gallery. Thank you very much <Like>

**Comment by ChipChipsGames** [comment]
@sametguzeldev Bother you one more thing. Do you know where put app-ads.txt is? I don't see where to put the Link in the app and my account . I have created app-ads.txt based on Huawei Ads , but don't know where to put the Link ?

**Comment by sametguzeldev** [comment]
> @sametguzeldev Bother you one more thing. Do you know where put app-ads.txt is? I don't see where to put the Link in the app and my account . I have created app-ads.txt based on Huawei Ads , but don't know where to put the Link ?

I actually don't know what you are talking about 😄 why do you need app-ads.txt?

**Comment by ChipChipsGames** [comment]
![Add](https://user-images.githubusercontent.com/98200281/150790630-695f6c07-899d-42d9-82d9-27012d2eb1c7.jpg)
I run ads on HMS, there must be a file request to confirm the ad serving address, Huawei also requires that . But maybe I don't need to set up this file, but the ad still works normally ? Because Huawei requires this file

**Comment by alihan98ersoy** [comment]
Hello,
 
Not adding the  app-ads.txt file won't make any changes to display your ads or displayed ads or to the revenue.

**Comment by ChipChipsGames** [comment]
@alihan98ersoy  That's too good then. Thank you very much
