### ISSUE TITLE
Constructor on type 'HuaweiMobileServices.Ads.AdParam' not found   il2cpp

### ISSUE THREAD

**Issue by fujisheng** [EvilMindDevs/hms-unity-plugin#27]
Hello i have a problem, my unity version is 2019.3.3f1

**Comment by m0skit0** [comment]
Hello! I think this error has been fixed already. Are you using latest package or commit?

**Comment by m0skit0** [comment]
Fixed in 6c21d0193bb346865dbbd99e081bea4d9d23d163
