### ISSUE TITLE
Move file Error

### ISSUE THREAD

**Issue by GameDevs1337** [EvilMindDevs/hms-unity-plugin#283]
Moving files via the plugin lead to an IOExeption. Please check the attachments. How to fix this? 

Thank you

![Err](https://user-images.githubusercontent.com/92455520/154480376-bde478e3-5452-4e7f-99e1-67d5a07b33d2.PNG)
![Erro](https://user-images.githubusercontent.com/92455520/154480295-4397d607-2b15-4250-b2a7-292b79faa94c.PNG)

**Comment by alihan98ersoy** [comment]
Hello, could you please share more details?
What Unity version are you using, How can I reproduce the issue? What were you doing and which steps should I follow to get the same issue?

**Comment by GameDevs1337** [comment]
I am using Unity version 2019.2.18f1. The issue came after updating the plugin.

**Comment by alihan98ersoy** [comment]
I tested with 2019.2.18f1 but I couldn't get the same issue. You can click move, if anything goes wrong you can delete them and download them again.
