### ISSUE TITLE
 Field currentActivity or type signature  not found

### ISSUE THREAD

**Issue by FallenCoderDown** [EvilMindDevs/hms-unity-plugin#284]
Error upon initializing ads.

**Comment by alihan98ersoy** [comment]
Hello,

Are you trying with our AdsDemo Scene? Also, I found the same issue on [StackOverflow](https://stackoverflow.com/questions/67056017/field-currentactivity-or-type-signature-not-found). Are you trying with The emulator & unity remote 5? You need to test on a physical device.
