### ISSUE TITLE
Sometimes the IAP does not deliver the product to the customer

### ISSUE THREAD

**Issue by Abolfazl597** [EvilMindDevs/hms-unity-plugin#289]
Hi,

Some of our customers have problem with IAP. They do not receive the product after payment. 

We have several apps in AppGallery that have the same IAP implementation structure, and some customers report that they have not received an IAP product only in one of our apps, for example, after purchasing 4 apps.

It seems that **sometimes** the IAP cannot be finalized to deliver the product to customer.

Can you help me in this regard?

**Comment by alihan98ersoy** [comment]
Hello,
I believe Huawei customer service can help with this issue. Can you submit a ticket for [Huawei customer service](https://developer.huawei.com/consumer/en/support/feedback/#/)?

**Comment by Abolfazl597** [comment]
I just received this message from Huawei customer service.

"_If an exception (such as network error or abnormal process termination) occurs after the payment of a consumable, your app will fail to know whether the payment is successful. The purchased product may not be delivered as expected. You need to implement redelivery process for consumables in your apps. For more info, please [refer to the guides](https://developer.huawei.com/consumer/en/doc/development/HMSCore-Guides/redelivering-consumables-0000001051356573)._"

I have used Non-consumable product. I wanted to know if the redelivery process for Non-consumable product has been implemented in this plugin and I must do something in my app for that or it is automatically.
Thanks.

**Comment by alihan98ersoy** [comment]
Hi,
For Non-consumable products, you can refer to [Delivering a Non-Consumable](https://developer.huawei.com/consumer/en/doc/development/HMSCore-Guides/dev-guide-0000001050130254#section1752543164411). And in the plugin we have methods such as: 
ObtainOwnedPurchases(PriceType priceType),
ObtainOwnedPurchaseRecord(PriceType priceType),
ObtainOwnedPurchaseRecord(OwnedPurchasesReq req)
 [HMSIAPManager.cs ](https://github.com/EvilMindDevs/hms-unity-plugin/blob/master/Assets/Huawei/Scripts/IAP/HMSIAPManager.cs#L359). 

Also, do you have an error log?

**Comment by Abolfazl597** [comment]
@alihan98ersoy Could you please explain more?
When does the restore function call?
in the start of the app?
Or I must define a button for it?
Or when the user presses the buy button and the function "BuyProduct(string productID)" runs, the plugin automatically calls restore?
I didn't receive an error log.

**Comment by alihan98ersoy** [comment]
Hi,

In the normal scenario, When you click the buy button, the IAP intent opens and if the purchase is successful, the intent returns [OrderStatusCode.ORDER_STATE_SUCCESS](https://github.com/EvilMindDevs/hms-unity-plugin/blob/master/Assets/Huawei/Scripts/IAP/HMSIAPManager.cs#L288). For the first time when you should deliver the product, IAP not using ObtainOwnedPurchases method. You should deliver the product with [OnBuyProductSuccess ](https://github.com/EvilMindDevs/hms-unity-plugin/blob/master/Assets/Huawei/Demos/IAP/IapDemoManager.cs#L61) method. 

Then If your app provides non-consumables for users, it should call the [obtainOwnedPurchases](https://developer.huawei.com/consumer/en/doc/development/HMSCore-References/iapclient-0000001050137587#section15126153542812) API during app launch to obtain the data about non-consumables that a user has purchased. In our demo, RestorePurchases calls ObtainAllOwnedPurchases() method. So you should use RestorePurchases method onStart. You can refer to it and create your own logic. Also, you can put a button to restore purchases for undesirable situations. This button can call ObtainAllOwnedPurchases() method, too.

**Comment by Abolfazl597** [comment]
@alihan98ersoy Thank you so much for your reply.
So I use RestorePurchases method onStart like this:
```
void Start()
    {
        Debug.Log("[HMS]: IapDemoManager Started");
        HMSIAPManager.Instance.OnBuyProductSuccess += OnBuyProductSuccess;
        HMSIAPManager.Instance.OnCheckIapAvailabilitySuccess += OnCheckIapAvailabilitySuccess;
        HMSIAPManager.Instance.OnCheckIapAvailabilityFailure += OnCheckIapAvailabilityFailure;

        RestorePurchases();
    }
```
and then in OnBuyProductSuccess method I give the user Non-consumable products
```
private void OnBuyProductSuccess(PurchaseResultInfo obj)
    {
        if (obj.InAppPurchaseData.ProductId == ItemID)
        {
            Debug.Log("Purchase Successful");
            
            // Hide banner Ad for example
            PlayerPrefs.SetString("Purchased", "true");
            HiddenObjects.SetActive(true);
        }
    }
```
Is this okay?
Or I should also give the user Non-consumable products in RestorePurchases method in HMSIAPManager.cs or somewhere else?

Sorry for asking so many questions.

**Comment by alihan98ersoy** [comment]
RestorePurchases() method updates productPurchasedList in IapDemoManager.cs. You need to create a custom delivery method. You have to create custom logic to deliver the purchased products.

Example:
![resim](https://user-images.githubusercontent.com/39373386/157057854-0f88f879-d5ac-4225-a4fc-a27f481e3db1.png)
