### ISSUE TITLE
Where to place the agconnect-services.json?

### ISSUE THREAD

**Issue by jokajoka4** [EvilMindDevs/hms-unity-plugin#30]
I've just uploaded the app to appGallery, but Huawei tells me that the agconnect-services.json might not be configured correct. 

I've not placed it in my project yet. Do you have any idea where to place it?
It is used to be placed in the root folder of an Android studio project. Where is the corresponding place in Unity? 

This is the file:

`{
	"client":{
		"cp_id":"xxxx",
		"product_id":"xxxx",
		"client_id":"xxxx",
		"client_secret":"xxxx",
		"app_id":"xxxx",
		"package_name":"com.company.app",
		"api_key":"xxxx"
	},
	"configuration_version":"1.0"
}`

**Comment by manelizzard** [comment]
I did not try to upload the app to AppGallery, but my `agconnect-services.json` is placed under `Assets > Plugins > Android` and HMSDK seems to properly run

**Comment by jokajoka4** [comment]
Thank you very much. I've not yet tested if it does work solve my problem, but do you know if this plugin is reading / using this file?

**Comment by m0skit0** [comment]
Hi! Plugin does not require this file nor is reading it, but AGC might scan the apk for it.

**Comment by jokajoka4** [comment]
Okay. Thank you. In Huaweis documentation to integrate the HMS Core, the agconnect-services.json is a central part. See link below. 


[https://developer.huawei.com/consumer/en/doc/development/HMS-Guides/iap-integrating-hms-sdk-v4](url)

**Comment by m0skit0** [comment]
Yes I know but this JSON is mainly used by the Huawei plugin in Android Studio to generate some auxiliary code. This is not present currently in our Unity plugin and I don't know if it's even possible to change the Gradle build from a plugin.

**Comment by jokajoka4** [comment]
Okay thank you very much! We will give it a go!
