### ISSUE TITLE
Is it possible to use Huawei Ads on non-Huawei devices?

### ISSUE THREAD

**Issue by ltomov** [EvilMindDevs/hms-unity-plugin#301]
Hi, sorry if this is not the right place to ask.

I'm currently using the plugin for Huawei devices (AppGallery), but I'd like to use the ads module on non-Huawei devices also. Is this possible or do you think there's a change I could get them to work at least in Android?

If not, are there any plans to add support for other platforms, like iOS, Android (non-AppGallery), Amazon?

Thank you!

**Comment by alihan98ersoy** [comment]
Hi, no problem every question welcome here:)

According to [developers.huawei](https://developer.huawei.com/consumer/en/doc/development/HMSCore-Guides/publisher-service-introduction-0000001070671805#section16893141102916) non-Huawei devices not supported. But according to my test working on the non-Huawei devices. Please refer to [Adding an App Released on Google Play](https://developer.huawei.com/consumer/en/doc/distribution/monetize/addmedia-gp-0000001149967192) and read other stores' policies carefully.

For ios, our plugin currently does not support ios and currently Ads kit does not support ios according to Ads kit documentation.

**Comment by ltomov** [comment]
Thank you for the quick reply! That page ( https://developer.huawei.com/consumer/en/doc/distribution/monetize/addmedia-gp-0000001149967192 ) gives me some hope that it might be possible, at least in Android, I'll dig into it.
