### ISSUE TITLE
After update 2.1.2 -> 2.2 got errors

### ISSUE THREAD

**Issue by PaXLiCh** [EvilMindDevs/hms-unity-plugin#302]
Unity3D 2020.3.33f1
MacOS, Android target.
After update 2.1.2 -> 2.2 got errors
`Assets/Huawei/Scripts/CloudDB/BookInfo.cs(9,45): error CS7069: Reference to type 'AndroidJavaObject' claims it is defined in 'UnityEngine.CoreModule', but it could not be found`

`Error: Could not load signature of HuaweiMobileServices.Utils.AndroidAccount:.ctor due to: Could not resolve type with token 0100000d (from typeref, class/assembly UnityEngine.AndroidJavaObject, UnityEngine.CoreModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null) assembly:UnityEngine.CoreModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null type:UnityEngine.AndroidJavaObject member:(null) signature:<none>`

`Unloading broken assembly Assets/Huawei/Dlls/HuaweiMobileServices.dll, this assembly can cause crashes in the runtime
`

**Comment by alihan98ersoy** [comment]
Hi, 
I tested and get the same error with updating with v2.2 for the 2018 release. Can you try with the v2.2-2019-2020 release?

**Comment by PaXLiCh** [comment]
release v2.2-2019-2020 work normally.
suggested that the v2.2 - Unity 2018 version is for all versions of the editor starting in 2018.
the serious difference between release assemblies is not obvious.
