### ISSUE TITLE
AppLinking Not available

### ISSUE THREAD

**Issue by muzeitlimited** [EvilMindDevs/hms-unity-plugin#304]
Hey guys, 
I will start by saying that the sdk works great and I've used multiple services and they saved a lot of time.
However, I didn't find an applinking plugin available, is it not added yet? are there plans to add it later on? and what should I do to currently use it in my case.

**Comment by alihan98ersoy** [comment]
Hello, 
AppLinking is not supported in our plugin at the moment, but it is in our roadmap.

**Comment by alihan98ersoy** [comment]
AppLinking is available with our new version.
