### ISSUE TITLE
Restore doesn't work via Unity Purchase

### ISSUE THREAD

**Issue by gadzilka** [EvilMindDevs/hms-unity-plugin#305]
After upgrading the SDK from version 1.x  to version 2.2 our customers report us that restore doesn't work at all. Everything worked fine in the previous version of the SDK.
As I can see in [HuaweiStore.cs](https://github.com/EvilMindDevs/hms-unity-plugin/blob/master/Assets/Huawei/Scripts/IAP/UnityPurchase/HuaweiStore.cs) nobody call method `LoadOwnedConsumables`. Are you sure that it is okay?

**Comment by alihan98ersoy** [comment]
Thanks for bringing it up. We are investigating the issue.

**Comment by alihan98ersoy** [comment]
We are considering preparing a sample scene for Unity purchases.
