### ISSUE TITLE
Acquire IAP info when not logged in.

### ISSUE THREAD

**Issue by jokajoka4** [EvilMindDevs/hms-unity-plugin#32]
Is it possible to acquire information about the IAP's without the user being logged in?

**Comment by m0skit0** [comment]
Hello! What kind of information are you referring to?

**Comment by jokajoka4** [comment]
Information about the IAP, like name, description and price. We have not yet managed to display the correct price, without signing in to Huawei. If we try to acquire name, description and price before we sign in, we'll get an empty error.

**Comment by m0skit0** [comment]
No, you can't acquire any product info without signing-in. The point of IAP kit is more to provide an automated check-in than be a listing of products. You should retrieve this information from your own backend.

**Comment by jokajoka4** [comment]
Okay. Thank you very much!
