### ISSUE TITLE
IAP Sandbox not working with Unity IAP implementation

### ISSUE THREAD

**Issue by Razhagal** [EvilMindDevs/hms-unity-plugin#322]
After updating from plugin version 2.1.1 to 2.2.1 and later to 2.2.2 purchases initialized no longer are under sandbox environment and the store wants to charge for it.
This is by using HuaweiStore Unity IAP implementation. Unity version 2021.1.28 and testing with an account which is already added as a sandbox tester account in AppGallery Connect.
Further testing by initializing Huawei IAP from HMSIAPManager and checking with IsSandboxActivated() returns "Success" result. The returned success object IsSandboxActivatedResult also has SandboxUser property set to true.

Having sandbox testing unavailable when using HuaweiStore.cs implementation would make a big impact on our ability to test our payments further and simply changing the whole payments implementation in our project from the Unity IAP one to HMSIAPManager is not really an option either since we publish to multiple stores and want to keep consistency of the code base.

**Comment by alihan98ersoy** [comment]
Hello, I just tested and IAP Sandbox is working on me. I tested with Unity version 2021.1.28, and Unity IAP Version 4.0.3 with BuyingConsumables sample scene. 

![resim](https://user-images.githubusercontent.com/39373386/170473612-07c3f2c2-7249-476c-8d19-b3fd3b95b0ff.png)

I changed StandardPurchasingModule => HuaweiPurchasingModule and productIds in the demo scene.

![resim](https://user-images.githubusercontent.com/39373386/170473947-868931cf-1f0c-4464-9ba1-a65d57818f4a.png)

Can you explain your steps to I can test? And which version of Unity IAP are you using?

**Comment by Razhagal** [comment]
Hello,
The IAP version we're using is 4.1.4. Before updating the HMS plugin sandbox payments worked, after updating they stopped working in sandbox. As for testing steps they aren't much different than the sample provided by Unity IAP package. I'm testing with our own implementation and own product id's but the setup and initialization is basically the same as the demo screenshotted. I could try testing with the IAP package demo as well.

**Comment by alihan98ersoy** [comment]
Hello, I also tested with 4.1.5. I'm asking to understand exactly what the problem is. The payment screen comes up but there is no sandbox warning, right?
![resim](https://user-images.githubusercontent.com/39373386/170481240-55c3346c-fbb1-4ee4-bf05-eb64c6ae8a02.png)

**Comment by Razhagal** [comment]
Yes, exactly. The sandbox warning is missing.

**Comment by alihan98ersoy** [comment]
This may be a problem with the AGC console. Could you check your console settings?

[Troubleshooting Sandbox Access Issues](https://developer.huawei.com/consumer/en/doc/development/HMSCore-Guides/sandbox-testing-0000001050035039#section97936416250)

**Comment by Razhagal** [comment]
Ok, I did indeed re-add my account as a sandbox account yesterday, just in case but I didn't thought I'll have to increment the build version as well and was testing with already released build version. When I incremented the version sandbox mode activated and now everything is okay...
Well, thanks for your help and sorry for wasting your time :)

**Comment by sametguzeldev** [comment]
I'll just add this here for future if developers are coming into this issue. If you have your app released in AppGallery, you need to increment your version number as it is stated in the documents.
<img width="987" alt="image" src="https://user-images.githubusercontent.com/6827857/170506962-68efc242-9eb6-44ee-b1bc-ee08e7a482bf.png">
