### ISSUE TITLE
AndroidJavaException:java.lang.classNotFoundException com.huawei.iap.Iap Unity

### ISSUE THREAD

**Issue by MushoodMunir** [EvilMindDevs/hms-unity-plugin#323]
Hi I am trying to implement Huawei IAP in unity 2021  I got error "classNotFoundException com.huawei.iap.Iap" when I call HMSIAPManager.Instance.CheckIapAvailability();
Also when I want to purchase something it say "HMSIAPManager] Specified: {productId} could not be found in retrieved product list!".
Note I am making testing this on Android 11 Device.
Any help would be much appreciated.

**Comment by alihan98ersoy** [comment]
Hello, 
could you review the [Connect your game with any HMS Kit](https://github.com/EvilMindDevs/hms-unity-plugin#4---connect-your-game-with-any-hms-kit) and [In-App Purchases](https://github.com/EvilMindDevs/hms-unity-plugin#in-app-purchases) parts in the readme?

I believe You should enable IAP from kit settings and then add your products from the IAP tab.

**Comment by MushoodMunir** [comment]
Hello,
Thanks you for kind reply. Below are the images of kit settings for IAP and Products .
<img width="652" alt="Screenshot 2022-05-30 at 12 43 44 PM" src="https://user-images.githubusercontent.com/10167077/170943117-acb3aa9a-f49e-4eb9-977d-2f57187759ea.png">

<img width="656" alt="Screenshot 2022-05-30 at 12 42 50 PM" src="https://user-images.githubusercontent.com/10167077/170943304-6812d387-d8fb-4d39-89b4-1aa6de7b5469.png">

Facing Same issue on when checking for IAPAvailability.
Here is the Error line
HMSIAPManager.Instance.CheckIapAvailability();

**Comment by alihan98ersoy** [comment]
May I get the error logs for further investigation?

**Comment by MushoodMunir** [comment]
Here is the error logs ,Plz have a look into this

<img width="1420" alt="error_Log" src="https://user-images.githubusercontent.com/10167077/170949012-bb5ae836-e48c-4b2f-891e-58408b38905f.png">

**Comment by alihan98ersoy** [comment]
It looks like Gradle couldn't download the files it should download. Are you using Proguard? Could you check your configurations? Build Settings > Player Settings > Player > Publishing Settings

![resim](https://user-images.githubusercontent.com/39373386/170950205-d3e37334-f78a-4e6b-b432-d6f9f84812dc.png)

**Comment by MushoodMunir** [comment]
<img width="651" alt="Screenshot 2022-05-30 at 1 50 09 PM" src="https://user-images.githubusercontent.com/10167077/170955162-02a39be8-2bb7-452f-ae37-d5d3d49e570e.png">

I have tested with both options enable proguard, disable proguard. But error remains same for both of them.

[proguard-user.txt](https://github.com/EvilMindDevs/hms-unity-plugin/files/8797006/proguard-user.txt)

**Comment by alihan98ersoy** [comment]
Hello again,
can you refer to this issue #174?

**Comment by MushoodMunir** [comment]
Hello again,
I have checked issue #174  .There is a app-debug.aar in Assets/Plugins/Android in my case but same error.
Below is Screenshots
<img width="1439" alt="Screenshot 2022-05-30 at 5 49 09 PM" src="https://user-images.githubusercontent.com/10167077/170996084-f0ffa935-7067-480e-a5b0-53ac62eea491.png">

**Comment by alihan98ersoy** [comment]
Hello,
Can you export project and then check if app-debug.aar file is in libs folder?
![resim](https://user-images.githubusercontent.com/39373386/171017872-38dcc0f6-418f-48c0-9120-6047f486d156.png)

**Comment by MushoodMunir** [comment]
Hello again I have exported build and there is a app-debug.aar file in libs folder
<img width="1370" alt="Screenshot 2022-05-31 at 7 03 51 AM" src="https://user-images.githubusercontent.com/10167077/171078964-f8cb7232-c54c-4515-874d-e5e0c9da2634.png">

**Comment by alihan98ersoy** [comment]
Hello again, 
if you don't mind, can you share these 3 files? If these 3 files are as they should be, the problem may not be caused by the project.

![resim](https://user-images.githubusercontent.com/39373386/171097619-f633cc2a-84a3-47fe-82ed-76f810266d2f.png)

**Comment by MushoodMunir** [comment]
Here are the files
[buidl and hmsBaseProjectTemplate.zip](https://github.com/EvilMindDevs/hms-unity-plugin/files/8802479/buidl.and.hmsBaseProjectTemplate.zip)
[hmsMainTemplate.gradle.zip](https://github.com/EvilMindDevs/hms-unity-plugin/files/8802482/hmsMainTemplate.gradle.zip)

**Comment by alihan98ersoy** [comment]
Your build gradle file is different than it should be, you can fix it manually for now. It may be a different situation for the mac or Unity 2021 version, I will investigate it.

![resim](https://user-images.githubusercontent.com/39373386/171107205-91cbb7a2-936f-471a-81d7-b87159b31665.png)

**Comment by MushoodMunir** [comment]
Hello again,
is that also compulsory to add .huawei or .HUAWEI at end of package name of the game or app bundle ids?
because I did not include .huawei or .HUAWEI  in the package name and bundle ids for ads

**Comment by MushoodMunir** [comment]
Hi,
I have updated my Gradle file but issue remains the same.
<img width="800" alt="Screenshot 2022-05-31 at 1 37 50 PM" src="https://user-images.githubusercontent.com/10167077/171131044-c501ffe2-7e73-4306-b0b9-6359ad1ce728.png">

**Comment by alihan98ersoy** [comment]
Hello again,
Can you share your HMSMainEditorSettings 
![resim](https://user-images.githubusercontent.com/39373386/171592879-fdad28ed-aaaa-4c56-bfda-4b363eb5d652.png)
and preferences for external tools?
![resim](https://user-images.githubusercontent.com/39373386/171593036-89ba6ffd-efa1-49cb-9f46-7285977ab8f4.png)
