### ISSUE TITLE
Testing IAP(Non-cons and subs) & Something strange

### ISSUE THREAD

**Issue by Hungry-Fish-team** [EvilMindDevs/hms-unity-plugin#324]
Hello, our team is trying to release some apps to the AppGallery, but we've run into a few oddities.
1. Shopping test. The bottom line is - after a purchase on a test account, we don’t know if it’s even possible to cancel this purchase on the account itself (analogue like with GooglePlay, where I can just delete it) The question is, is there any way at all not on the client side reset this purchase? (This is not about a subscription) (Wrote to technical support, but no solutions were offered)
2. Subscription problem. We cannot make a full subscription purchase on the same test account. At the time of receiving the callback, we get that this purchase is already available (OWNED_PURCHASE)This is the question, is this normal behavior and do we need to track FailedPurchaseCallback or is there some kind of snag?

plugin ver 2.1, unity 2020.3

Our testers do not want to skip the build until they get answers)

**Comment by alihan98ersoy** [comment]
Hello,
1. [Troubleshooting during the non-consumable test](https://developer.huawei.com/consumer/en/doc/development/HMSCore-Guides/faq-0000001050033126#section195720161699)

    **Will a purchased non-consumable be reset and can it be purchased again when the APK is reinstalled?**

    No. The purchase of the non-consumable is recorded on the Huawei IAP server. Reinstalling the APK does not affect the purchase record.

    **Will the purchase of a non-consumable be automatically canceled after a period of time?**

    No.

    **Can I manually cancel the purchase of a non-consumable to avoid creating a separate test account for each test?**

   In the sandbox testing, you can call the consumption API to consume the non-consumable. After the non-consumable is consumed successfully, you can purchase it again without creating multiple test accounts.


2. [Testing Subscription Renewal](https://developer.huawei.com/consumer/en/doc/development/HMSCore-Guides/sandbox-testing-0000001050035039#section7873953153616)

![resim](https://user-images.githubusercontent.com/39373386/170987568-c8a761c0-7413-45b0-8b62-13b7b4a0f194.png)


2a. We [track the failures](https://github.com/EvilMindDevs/hms-unity-plugin/blob/master/Assets/Huawei/Scripts/IAP/HMSIAPManager.cs#L317) which is a similar way to the [official document](https://developer.huawei.com/consumer/en/doc/development/HMSCore-Guides/dev-guide-0000001050130254#section183174113342). But of course, you can also create your own logic.

**Comment by Hungry-Fish-team** [comment]
Thank you very much for the answer and the reference, but I want to clarify about the "Can I manually cancel the purchase ..." account. As I understand it, the ConsumePurchase method works by default on any successful purchase. I didn't change his call. But on my test account, the purchase remained exactly (non-cons), the same for 2 others. (I'll try to call consume again next time during the test)
I was also wondering if it is possible to at least see this purchase on the account in the AppGallery (it is not there, but it still arrives exactly according to OnObtainOwnedPurchasesSuccess) and if possible, is it possible to cancel it by the administrator?

**Comment by alihan98ersoy** [comment]
Hello, 
I did a little test to be sure again and we already consume it after purchase. But in some cases, problems may occur and it is useful to review the [(Mandatory) Redelivery Process for Consumables](https://developer.huawei.com/consumer/en/doc/development/HMSCore-Guides/redelivering-consumables-0000001051356573) for these cases. You can do the same for non-consumable products during sandbox testing. In addition, if you have encountered such a problem, you can also consume the product for your tests using the [server API](https://developer.huawei.com/consumer/en/doc/development/HMSCore-References/api-purchase-confirm-for-order-service-0000001051066054).

**[In the sandbox environment, will the AppGallery Connect report record the payment success?](https://developer.huawei.com/consumer/en/doc/development/HMSCore-Guides/faq-0000001050033126#section14351071734)**

No. Only real payments are recorded.

I tested buy non-consumable multiple times and successfully buy it. But I failed on purpose for consumables and for this condition I should create **Redelivery Process**. Something like:

![resim](https://user-images.githubusercontent.com/39373386/171017054-a6c320d9-a471-4d12-ae02-8eb95398d03a.png)

**Comment by Hungry-Fish-team** [comment]
Thank you very much for your answers)

**Comment by alihan98ersoy** [comment]
You're welcome. I would appreciate it if you could star the project.
