### ISSUE TITLE
Ads on Specific Non-Huawei

### ISSUE THREAD

**Issue by Hungry-Fish-team** [EvilMindDevs/hms-unity-plugin#325]
Good afternoon. I have a rather strange question about ads. I have a situation like this. My PM requires me to be more specific about why some non-Huawei devices (where iap runs and inited) won't load ads (error code is 0, of course HMSCore > 4 and internet is fine). Are there specific answers why even test ads do not come on such devices?

**Comment by Hungry-Fish-team** [comment]
We a using real device
Redmi note 7 - android 9
Redmi note 8 pro - android 11
ZTE Blade v2020 - android 10
Samsung Tab 7() - android 8

All this device inited IAP and we use they to test ads. And we found one moment that ads appeared on devices after installing an additional appgallery (without updating hms core), but this was only on one.
Testing on test ads)

About com.huawei.hms:ads-prime - we will try on another project)
Thanks for the help)

**Comment by alihan98ersoy** [comment]
This could be a momentary issue. If the problem persists or prime SDK does not solve the problem, you can reopen this issue.
