### ISSUE TITLE
Auto-Renewable Subscriptions???

### ISSUE THREAD

**Issue by Samoscaneckazimir** [EvilMindDevs/hms-unity-plugin#33]
Hi Devs. 

Thank you for giving us opportunity to combine Unity with Huawei :)

Does this plugin support Huawei subscriptions? If it doesn't do you plan to work on it in some time too?

**Comment by m0skit0** [comment]
Hi! Thanks to you for supporting our plugin :)

I think it does support auto-renewable subscriptions as per the SDK documentation here: https://developer.huawei.com/consumer/en/doc/development/HMS-Guides/iap-subscription-functions-v4#h1-1576566915167
