### ISSUE TITLE
There is no prompt box for automatically upgrading HMS core on non Huawei mobile phones.

### ISSUE THREAD

**Issue by koal2** [EvilMindDevs/hms-unity-plugin#334]
Before I upgrade 2.2.3, I will prompt the user to install HMS core, but now there will only be a prompt, "you have not installed HMS core, and the program cannot run."

**Comment by alihan98ersoy** [comment]
Hello, are you having this problem with the Ads kit or a different kit?

**Comment by alihan98ersoy** [comment]
Hello again,
Some kits automatically update the HMS core, causing it to be rejected while being published on google. That's why with the latest versions these kits no longer update automatically. We have integrated this update into the plugin with V2.2.2.

For such a case, you can create your custom logic to check if the HMS core is loaded without initializing the HMS kits. else inform customers that they need to download HMS core
![resim](https://user-images.githubusercontent.com/39373386/176400207-9d58483b-10f1-4390-bbb9-2e33881086ca.png)

**Comment by koal2** [comment]
Thank you for your response, but I can't use "ServiceHelper". 
<img width="827" alt="image" src="https://user-images.githubusercontent.com/23449067/176410853-2616c741-bf1a-4b26-b2fd-630b7d006e32.png">

**Comment by koal2** [comment]
ok, it working, but is there a method to prompt the user to install HMS core in "HuaweiMobileServices"?

**Comment by koal2** [comment]
Sorry, maybe my initial problem description wasn't accurate enough，the problem is:
     When I call "HMSAccountKitManager.Instance.GetGameAuthService().SilentSignIn()" on plugin v2.2，if HMS Core is not installed on the device a prompt box will appear. Which says: "This service requires the latest version of the following applications to be installed HMS Core", and two button the one is "cancel" another is "install". Pressed "install" it will be download HMS Core.
    When I upgrade plugin to v2.2.2 or above do the same, a prompt box will appear which says: "you have not installed HMS core, and the program cannot run.",and only one button with text "I see". so I unable installed HMS Core.

**Comment by alihan98ersoy** [comment]
For example Account Kit: 
![resim](https://user-images.githubusercontent.com/39373386/176616712-2b2aba79-b4f3-499a-8d6b-519169ab6d38.png)

**Deleted the capability of prompting users to install HMS Core (APK).**
When they find a different solution, we will update the plugin with it, but for now, there is no other solution.

**Comment by koal2** [comment]
Thank you very much!

**Comment by eozdemir90** [comment]
Thank you for your interest in our project. You may give a star to support us and follow up on the project. You can also join our discord channel to follow changes and ask any kind of question about the plugin, gaming ecosystem, etc. You may access it from here : https://discord.io/hmsunityplugin
Thank you and stay tuned!
