### ISSUE TITLE
ShowLeaderboards failed. CauseMessage: 7018: call init method first

### ISSUE THREAD

**Issue by VeljkoLukic** [EvilMindDevs/hms-unity-plugin#336]
I called `HMSGameServiceManager.Instance.InitGameManagers();` and `HMSGameServiceManager.Instance.Init();` at multiple places and still receiving not initialized error, is there any documentation on how it's supposed to be initialized?

**Comment by eozdemir90** [comment]
Thank you for your interest in our project. You may give a star to support us and follow up on the project. You can also join our discord channel to follow changes and ask any kind of question about the plugin, gaming ecosystem, etc. You may access it from here : https://discord.io/hmsunityplugin
Thank you and stay tuned!
