### ISSUE TITLE
ads not shown on latest emui

### ISSUE THREAD

**Issue by sunny2714** [EvilMindDevs/hms-unity-plugin#340]
hello sir how are you i am using huawei ads sdk in my games from last 3 month i have noctice that my ads are not showing on emui 11.0 and 10.1.0 not test nor live ads as well as on other mobile like samsung etc. i have question is there is any changing which i not using in my ads  sdk or please suggest me proper team member for my help thanks alot in advanced

**Comment by alihan98ersoy** [comment]
hello 

Are you testing in cloud debugging? Maybe switching account helps. Doesn't work in Cloud Debugging:https://evilminddevs.gitbook.io/hms-unity-plugin-beta/support/faq

If not can you share with me your logs?
