### ISSUE TITLE
Several errors when purchasing due to HMS services not initialized

### ISSUE THREAD

**Issue by RicardoAxes** [EvilMindDevs/hms-unity-plugin#341]
Hello there,

We have several analytics reports in our app for users trying to purchase an item. When HMSIAPManager.instance.BuyProduct(...) is called, a NullReference raises. As the app or AppGallery does not force users to download HMS core, HMSAccountKitManager sign in is failing, hence the IAP is not initializing.

It there any solution for this? I think the conversion funnel for paying users is stretching due to this limitation.

**Comment by alihan98ersoy** [comment]
Hello, this is a known problem we are waiting for the new update. But when I tried I did not get NullReference. Are you sure this is the main reason your users have this problem? Maybe something else can be causing this problem. And also users are warned with dialog about this problem.

![thumbnail_Screenshot_20220720-145747_testUnityPlugin11](https://user-images.githubusercontent.com/39373386/179978355-9f584a59-92ab-4258-b66b-ea718d8208ec.jpg)

![Screenshot_3](https://user-images.githubusercontent.com/39373386/179978407-bd6c6ac2-638e-4331-96f9-e2b145415c2e.jpg)

When I click the buy button:

![Screenshot_1](https://user-images.githubusercontent.com/39373386/179978451-e06a764c-2bdd-4767-93e9-0167f7d2eea9.jpg)

**Comment by alihan98ersoy** [comment]
Hello,
We add Hms Core installer SDK with the new version(v2.2.4). With this new SDK, users can download Hms Core from the AppGallery store.

**Comment by RicardoAxes** [comment]
Hello,
Thanks for your response! I updated the plugin to 2.2.4 and HMS core is installed automatically. Anyway, I am getting an error related to HMSAccountKitManager, trying to get DefaultAuthService:
![Screenshot_20220808_072948_com aim racing huawei](https://user-images.githubusercontent.com/96047321/183364227-5fb10c5c-323f-4fd0-ae62-f7fd71880cd8.jpg)

The Kit settings are as shown below and configuration assets are removed and regenerated from scratch for this version:
![image](https://user-images.githubusercontent.com/96047321/183364308-33a81551-004b-437a-96df-34373ee871da.png)

![image](https://user-images.githubusercontent.com/96047321/183364553-dd40c4dd-8310-47d0-906d-d46f697b07bb.png)

Did something change at initialization?
Regards

**Comment by alihan98ersoy** [comment]
Can you try to disable every kit in the kit setting and then restart unity, then enable kits again? There is a known issue for the editor. We are fixing it. Maybe that's the reason.

**Comment by RicardoAxes** [comment]
We will be reaching soon because are having trouble with libraries at build step, not related to HMS it seems

**Comment by alihan98ersoy** [comment]
Ok, So I am keeping this issue open.

**Comment by CarolineEhabAnwar** [comment]
I have a similar issue when trying to run the AuthServiceDemo. I always get a null pointer exception. 
Steps Done: 

1- Creating an App in the AppConnect

2- Creating Keystore for my Unity Project and adding the SHA key to the App in the AppConnect

3- Enablilng the Auth Service, Game Service, and Account Service Kits

4- Making and API Key

5- Installing Unity HMS Plugin, enabling the kits mentioned, connected the API, and obtained a token

6- Adjusting the AndroidManifest.xml with the app id, cpid, and package name (also updated the package name in Unity) and added the providers (not sure of the variables though as it wasn't clear in any forum or documentation)

7- Re-installing the agconnect-service.json after enabling the kits

What am I missing? Why does it always give me a null pointer exception when trying to call any built in functions from the package such as authServiceManager.GetCurrentUser()

Here is the error: 

NullReferenceException: Object reference not set to an instance of an object

HuaweiMobileServices.Utils.JavaObjectWrapper.Call[T] (System.String methodName, System.Object[] args) (at <d01331c41e7b42f29a927fdf5bb0c9bc>:0)

HuaweiMobileServices.Utils.JavaObjectWrapper.CallAsWrapper[T] (System.String methodName, System.Object[] args) (at <d01331c41e7b42f29a927fdf5bb0c9bc>:0)

HuaweiMobileServices.AuthService.AGConnectAuth.GetCurrentUser () (at <d01331c41e7b42f29a927fdf5bb0c9bc>:0)

HmsPlugin.HMSAuthServiceManager.GetCurrentUser () (at Assets/Huawei/Scripts/AuthService/HMSAuthServiceManager.cs:83)

AuthServiceDemo.Start () (at Assets/Huawei/Demos/AuthService/AuthServiceDemo.cs:50)

Can you please help me with this? I tried disabling the kits, restarting Unity, then enabling them again. Didn't work

**Comment by alihan98ersoy** [comment]
Hello @CarolineEhabAnwar , 
your issue is a little bit different so I create another issue. We can continue there

**Comment by RicardoAxes** [comment]
Hello, back to testing the 2.2.4 version.
I confirm that in newer Huawei devices, HMS core is automatically downloaded and in older Huawei (or Google Android devices) a window alerting that HMS core is needed is prompted 👍 
I assume there is no way to force the Android user to download the core, right? So the only way is manually via link to AppGallery in prompt window

**Comment by alihan98ersoy** [comment]
Thank you for your interest in our project. You may give us a star to support us and follow up on the project. You can also join our discord channel to follow changes and ask any kind of question about the plugin, gaming ecosystem, etc. You may access it from here: https://discord.io/hmsunityplugin
Thank you and stay tuned!
