### ISSUE TITLE
GameObject not creating automatically when i click ads kit

### ISSUE THREAD

**Issue by nexthopestudios** [EvilMindDevs/hms-unity-plugin#343]
Hi there i am integrating ads kit and here are some details
Unity version = 2020.3.17
Plugin version (package or commit) = v2.2.32
Mono or IL2CPP = Il2cpp

I have carefully followed instructions but i am stuck in point 4 which is:
4 - Connect your game with any HMS Kit

This is not adding gameObject to my scene and as a result plugin is not working

**Comment by alihan98ersoy** [comment]
Hi, our readme is outdated. We will release new documentation. After version v2.2 there is now gameObject on the scene. Are you testing with the Ads demo scene?

![resim](https://user-images.githubusercontent.com/39373386/182017657-987192be-f2c8-4b7e-baf2-b7cb8ce4e8de.png)

**Comment by nexthopestudios** [comment]
Yeah the project is working fine. Now the ads are showing.
Thanks

**Comment by eozdemir90** [comment]
Thank you for your interest in our project. You may give a star to support us and follow up on the project. You can also join our discord channel to follow changes and ask any kind of question about the plugin, gaming ecosystem, etc.  You may access from here : https://discord.io/hmsunityplugin 
Thank you and stay tuned!
