### ISSUE TITLE
IAP not working: java.lang.ClassNotFoundException: com.huawei.hms.iap.Iap

### ISSUE THREAD

**Issue by dmichalke2** [EvilMindDevs/hms-unity-plugin#350]
Hello,

We use the plugin since several months (the IAP module) and suddenly it is not working anymore. We are unsure if this is due to a conflict with a new plugin or if anything else has changed, but after the start of our app, following error appears:

HandleException condition AndroidJavaException: java.lang.ClassNotFoundException: com.huawei.hms.iap.Iap stackTrace java.lang.ClassNotFoundException: com.huawei.hms.iap.Iap

We set the huawei plugin up as described in the wiki. We use the latest version 2.2.4 (cc43f8b). and build with IL2CPP. Attached please see the logcat. Test device is: Huawei P8 (but the error appears on all android devices).

![Screenshot_1](https://user-images.githubusercontent.com/103567574/183839849-d78e2a72-e5aa-4db9-b7a3-86fc990a3274.jpg)

a screenshot of the setup:

![Screenshot_2](https://user-images.githubusercontent.com/103567574/183841597-24e52b29-ec90-4d63-bb74-1323fc94ac44.jpg)

**Comment by bunyamineymen** [comment]
Hi

First I have a quick solution.

1- Disable IAP at HMS Kit Settings
2 -Delete all files at Assets/Huawei/Settings/Resources
3- Restart unity
4- Enable IAP at HMS Kit Settings

Can you try it?

**Comment by dmichalke2** [comment]
Yes, I tried all of the steps and built the app again. unfortunately the error message is the same.

**Comment by bunyamineymen** [comment]
Could you please share the screenshot of Assets/Huawei/Settings/Resources/HMSMainEditorSettings.asset detail?

**Comment by dmichalke2** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/103567574/183854526-97de4ccb-75dd-42fc-b270-f9d93dde41d0.jpg)

**Comment by bunyamineymen** [comment]
and HMSKitSettings please at the same directory.

**Comment by dmichalke2** [comment]
here.

I also added the UI overlay which shows no products and that initializing at start is off (we initialize from code and we add the products on runtime when we read them from our server

![Screenshot_1](https://user-images.githubusercontent.com/103567574/183856281-7b529fbc-3082-46e3-aec4-54b4e4a623d3.jpg)
)

**Comment by bunyamineymen** [comment]
Could you refer to https://evilminddevs.gitbook.io/hms-unity-plugin/support/faq ? 

![image](https://user-images.githubusercontent.com/13828988/183856980-997ceacd-9721-40c4-9185-75ce32cd342c.png)

**Comment by dmichalke2** [comment]
to me the settings seem as in their screenshot:
![Screenshot_1](https://user-images.githubusercontent.com/103567574/183858731-eac02d53-ce7f-4e92-8578-fee390aef00b.jpg)

**Comment by bunyamineymen** [comment]
Could you get the android export of the unity project and then share build.gradle file (app level) with ours?

![image](https://user-images.githubusercontent.com/13828988/183859040-62387b9b-6dbb-4eef-a156-2ea5037ee16e.png)

**Comment by dmichalke2** [comment]
```
allprojects {
    buildscript {
        repositories {
            google()
            jcenter()
        }

        dependencies {
            // If you are changing the Android Gradle Plugin version, make sure it is compatible with the Gradle version preinstalled with Unity
            // See which Gradle version is preinstalled with Unity here https://docs.unity3d.com/Manual/android-gradle-overview.html
            // See official Gradle and Android Gradle Plugin compatibility table here https://developer.android.com/studio/releases/gradle-plugin#updating-gradle
            // To specify a custom Gradle version in Unity, go do "Preferences > External Tools", uncheck "Gradle Installed with Unity (recommended)" and specify a path to a custom Gradle version
            classpath 'com.android.tools.build:gradle:4.0.1'
            
        }
    }

    repositories {
        google()
        jcenter()
        flatDir {
            dirs "${project(':unityLibrary').projectDir}/libs"
        }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

apply from: 'hmsBaseProjectTemplate.gradle'

```

**Comment by dmichalke2** [comment]
here the hmsBaseProjectTemplate

allprojects {
	buildscript {
		repositories {
			maven { url 'https://developer.huawei.com/repo/' }
		}

		dependencies {
			classpath 'com.huawei.agconnect:agcp:1.6.5.300'
			
		}
	}

	repositories {
		maven { url 'https://developer.huawei.com/repo/' }
	}
}

seems kind of empty

**Comment by dmichalke2** [comment]
there is a subfolder "launcher" with another build.gradle, not sure if you need that.

**Comment by bunyamineymen** [comment]
Could you please share other build.gradle ?

![image](https://user-images.githubusercontent.com/13828988/183863973-a83487e6-fdfb-4595-ba67-de1ec9d8cad0.png)

**Comment by dmichalke2** [comment]
I dont have android studio installed so I just opened it in explorer, this is the structure I see:

![Screenshot_1](https://user-images.githubusercontent.com/103567574/183865080-dfa54816-4e96-4153-94ec-10771a7ace44.jpg)

![Screenshot_2](https://user-images.githubusercontent.com/103567574/183865098-c78b1da9-409e-4b50-8c78-a563325a8e4f.jpg)

here is the other gradle I mentioned:

```
apply plugin: 'com.android.application'

dependencies {
    implementation project(':unityLibrary')
    }

android {
    compileSdkVersion 30
    buildToolsVersion '30.0.2'

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    defaultConfig {
        minSdkVersion 22
        targetSdkVersion 30
        applicationId 'de.spielepalast.pinochlepalace.huawei'
        ndk {
            abiFilters 'armeabi-v7a', 'arm64-v8a'
        }
        versionCode 153
        versionName '1.3.29'
    }

    aaptOptions {
        noCompress = ['.unity3d', '.ress', '.resource', '.obb', '.bundle', '.unityexp'] + unityStreamingAssets.tokenize(', ')
        ignoreAssetsPattern = "!.svn:!.git:!.ds_store:!*.scc:.*:!CVS:!thumbs.db:!picasa.ini:!*~"
    }

    signingConfigs {
        release {
            storeFile file('X:/Daten/Development/Arbeit/Pinochle/Data/Keystores/pinochle-palast.keystore')
            storePassword 'x5vMe4PgNURvcTQTTWU0'
            keyAlias 'pinochle-palace'
            keyPassword 'x5vMe4PgNURvcTQTTWU0'
        }
    }

    lintOptions {
        abortOnError false
    }

    buildTypes {
        debug {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt')
            signingConfig signingConfigs.release
            jniDebuggable true
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt')
            signingConfig signingConfigs.release
        }
    }

    packagingOptions {
        doNotStrip '*/armeabi-v7a/*.so'
        doNotStrip '*/arm64-v8a/*.so'
    }

    bundle {
        language {
            enableSplit = false
        }
        density {
            enableSplit = false
        }
        abi {
            enableSplit = true
        }
    }
}

apply from: 'hmsLauncherTemplate.gradle'

```

**Comment by bunyamineymen** [comment]
Could you please share SS of launcher/hmsLauncherTemplate.gradle and unityLibrary/hmsMainTemplate.gradle files from export with ours?

**Comment by dmichalke2** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/103567574/183889430-15a04aef-536c-4017-b53f-be72716f9b01.jpg)

**Comment by bunyamineymen** [comment]
Could you please delete all files and folders in root directory except Assets , Packages and ProjectSettings folder then restart unity?

**Comment by dmichalke2** [comment]
now the error is gone, but our app is stuck in the loading screen because the IAP module seems to have problems loading:

<img width="948" alt="chrome_c2iB0pZXla" src="https://user-images.githubusercontent.com/103567574/184074436-952b2c80-7adf-4ce3-9afd-9063129141bf.png">
<img width="940" alt="chrome_fTP0C6WlOW" src="https://user-images.githubusercontent.com/103567574/184074441-df56cd37-82e5-477e-bae1-8cb34f7743a7.png">

**Comment by alihan98ersoy** [comment]
hello, 
6003 error fingerprint error. Did you add your SHA-256 to your project? If you yes could you delete your game from the phone and settings>apps>HMS Core to clear its cache?

and also you can refer to [FAQ](https://developer.huawei.com/consumer/en/doc/development/HMSCore-Guides/faq-0000001050033126#section3517123824210).

**Comment by dmichalke2** [comment]
it seems like this did the trick now. it is working again, thanks
