### ISSUE TITLE
AuthServiceDemo. GetCurrentUser I always get a null pointer exception.

### ISSUE THREAD

**Issue by alihan98ersoy** [EvilMindDevs/hms-unity-plugin#352]
I have a similar issue when trying to run the AuthServiceDemo. I always get a null pointer exception. 
Steps Done: 

1- Creating an App in the AppConnect

2- Creating Keystore for my Unity Project and adding the SHA key to the App in the AppConnect

3- Enablilng the Auth Service, Game Service, and Account Service Kits

4- Making and API Key

5- Installing Unity HMS Plugin, enabling the kits mentioned, connected the API, and obtained a token

6- Adjusting the AndroidManifest.xml with the app id, cpid, and package name (also updated the package name in Unity) and added the providers (not sure of the variables though as it wasn't clear in any forum or documentation)

7- Re-installing the agconnect-service.json after enabling the kits

What am I missing? Why does it always give me a null pointer exception when trying to call any built in functions from the package such as authServiceManager.GetCurrentUser()

Here is the error: 

NullReferenceException: Object reference not set to an instance of an object

HuaweiMobileServices.Utils.JavaObjectWrapper.Call[T] (System.String methodName, System.Object[] args) (at <d01331c41e7b42f29a927fdf5bb0c9bc>:0)

HuaweiMobileServices.Utils.JavaObjectWrapper.CallAsWrapper[T] (System.String methodName, System.Object[] args) (at <d01331c41e7b42f29a927fdf5bb0c9bc>:0)

HuaweiMobileServices.AuthService.AGConnectAuth.GetCurrentUser () (at <d01331c41e7b42f29a927fdf5bb0c9bc>:0)

HmsPlugin.HMSAuthServiceManager.GetCurrentUser () (at Assets/Huawei/Scripts/AuthService/HMSAuthServiceManager.cs:83)

AuthServiceDemo.Start () (at Assets/Huawei/Demos/AuthService/AuthServiceDemo.cs:50)

Can you please help me with this? I tried disabling the kits, restarting Unity, then enabling them again. Didn't work

_Originally posted by @CarolineEhabAnwar in https://github.com/EvilMindDevs/hms-unity-plugin/issues/341#issuecomment-1213074485_

**Comment by alihan98ersoy** [comment]
Hello,
For integration can you follow our [documentation](https://evilminddevs.gitbook.io/hms-unity-plugin/getting-started/quick-start/import-the-plugin-into-your-unity-project)?

Your steps 4, 5, and 6 are not needed.

And the error seems you are trying to [get the current user ](https://developer.huawei.com/consumer/en/doc/development/AppGallery-connect-References/agconnectauth-0000001054482530#section158064585233)before signing in. It shouldn't be returning a null pointer we will fix the crash.

For your problem can you check our demo scenes for [Auth service](https://github.com/EvilMindDevs/hms-unity-plugin/blob/master/Assets/Huawei/Demos/AuthService/AuthServiceDemo.cs#L102) and [GameService](https://github.com/EvilMindDevs/hms-unity-plugin/blob/master/Assets/Huawei/Demos/Game/GameDemoManager.cs)

And you can refer article for [GameService](https://medium.com/huawei-developers/quickly-integrate-hms-to-your-game-using-hms-unity-plugin-2-0-part-2-8c14fde445fe).

Also, you don't need to use AuthService if you are using for Huawei ID. Account kit and game service can work together without auth service.

**Comment by CarolineEhabAnwar** [comment]
Hello, 
Thank you so much for responding. I followed the documentation and it still gave me the Null Pointer error. I checked the Auth service demo and still it game me the same error.
 I read the article of the GameService, and tried to run the demo as well, but it gave me another error which is this 
 Exception: Field currentActivity or type signature  not found
UnityEngine._AndroidJNIHelper.GetFieldID (System.IntPtr jclass, System.String fieldName, System.String signature, System.Boolean isStatic) (at <9d0861ca66fe45e696ddf3e3a8d9ea41>:0)
UnityEngine.AndroidJNIHelper.GetFieldID (System.IntPtr javaClass, System.String fieldName, System.String signature, System.Boolean isStatic) (at <9d0861ca66fe45e696ddf3e3a8d9ea41>:0)
UnityEngine._AndroidJNIHelper.GetFieldID[ReturnType] (System.IntPtr jclass, System.String fieldName, System.Boolean isStatic) (at <9d0861ca66fe45e696ddf3e3a8d9ea41>:0)
UnityEngine.AndroidJNIHelper.GetFieldID[FieldType] (System.IntPtr jclass, System.String fieldName, System.Boolean isStatic) (at <9d0861ca66fe45e696ddf3e3a8d9ea41>:0)
UnityEngine.AndroidJavaObject._GetStatic[FieldType] (System.String fieldName) (at <9d0861ca66fe45e696ddf3e3a8d9ea41>:0)
UnityEngine.AndroidJavaObject.GetStatic[FieldType] (System.String fieldName) (at <9d0861ca66fe45e696ddf3e3a8d9ea41>:0)
HuaweiMobileServices.Utils.AndroidContext.get_ActivityContext () (at <ad46ea4e9fb14836a5afc1bfe0509d8c>:0)
HuaweiMobileServices.Utils.AndroidContext.get_ApplicationContext () (at <ad46ea4e9fb14836a5afc1bfe0509d8c>:0)
HuaweiMobileServices.Base.HuaweiMobileServicesUtil.SetApplication () (at <ad46ea4e9fb14836a5afc1bfe0509d8c>:0)
HmsPlugin.HMSGameServiceManager.OnAwake () (at Assets/Huawei/Scripts/Game/HMSGameServiceManager.cs:43)
HuaweiMobileServices.Utils.HMSDispatcher.InvokeAsync (System.Action action) (at <ad46ea4e9fb14836a5afc1bfe0509d8c>:0)
HmsPlugin.HMSGameServiceManager..ctor () (at Assets/Huawei/Scripts/Game/HMSGameServiceManager.cs:38)
System.Reflection.RuntimeConstructorInfo.InternalInvoke (System.Object obj, System.Object[] parameters, System.Boolean wrapExceptions) (at <e40e5a8f982c4b618a930d29f9bd091c>:0)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.RuntimeConstructorInfo.InternalInvoke (System.Object obj, System.Object[] parameters, System.Boolean wrapExceptions) (at <e40e5a8f982c4b618a930d29f9bd091c>:0)
System.RuntimeType.CreateInstanceMono (System.Boolean nonPublic, System.Boolean wrapExceptions) (at <e40e5a8f982c4b618a930d29f9bd091c>:0)
System.RuntimeType.CreateInstanceSlow (System.Boolean publicOnly, System.Boolean wrapExceptions, System.Boolean skipCheckThis, System.Boolean fillCache) (at <e40e5a8f982c4b618a930d29f9bd091c>:0)
System.RuntimeType.CreateInstanceDefaultCtor (System.Boolean publicOnly, System.Boolean skipCheckThis, System.Boolean fillCache, System.Boolean wrapExceptions, System.Threading.StackCrawlMark& stackMark) (at <e40e5a8f982c4b618a930d29f9bd091c>:0)
System.Activator.CreateInstance[T] () (at <e40e5a8f982c4b618a930d29f9bd091c>:0)
HMSManagerSingleton`1[T].get_Instance () (at Assets/Huawei/Scripts/Utils/HMSSingleton.cs:53)
GameDemoManager.Start () (at Assets/Huawei/Demos/Game/GameDemoManager.cs:48)

As for the AuthService tip, thank you very much, I didn't know that. But I think I'll still need it to give more options for the user to sign in with.

**Comment by alihan98ersoy** [comment]
You need to test with a real device. Most HMS kits work with HMS core. Your test device should have an HMS core app. Also, you can use [cloud debugging](https://developer.huawei.com/consumer/en/agconnect/cloud-adjust/) for your tests.

**Comment by CarolineEhabAnwar** [comment]
The build keeps failing so I can't even test it. I am trying to build the AuthServiceDemo and the GameServiceDemo

UnityEditor.BuildPlayerWindow+BuildMethodException: 5 errors
  at UnityEditor.BuildPlayerWindow+DefaultBuildMethods.BuildPlayer (UnityEditor.BuildPlayerOptions options) [0x002da] in <44a70d1b13cf47e29810e30f45ffae08>:0 
  at UnityEditor.BuildPlayerWindow.CallBuildMethods (System.Boolean askForBuildLocation, UnityEditor.BuildOptions defaultBuildOptions) [0x00080] in <44a70d1b13cf47e29810e30f45ffae08>:0 
0x00007ff6122d930d (Unity) StackWalker::GetCurrentCallstack
0x00007ff6122dffe9 (Unity) StackWalker::ShowCallstack
0x00007ff61324d613 (Unity) GetStacktrace
0x00007ff6138e223d (Unity) DebugStringToFile
0x00007ff6114447e2 (Unity) DebugLogHandler_CUSTOM_Internal_Log
0x000001b7ca9e5003 (Mono JIT Code) (wrapper managed-to-native) UnityEngine.DebugLogHandler:Internal_Log (UnityEngine.LogType,UnityEngine.LogOption,string,UnityEngine.Object)
0x000001b7ca9e4f1b (Mono JIT Code) UnityEngine.DebugLogHandler:LogFormat (UnityEngine.LogType,UnityEngine.Object,string,object[])
0x000001b7ca9e4c60 (Mono JIT Code) UnityEngine.Logger:Log (UnityEngine.LogType,object)
0x000001b7ca540c05 (Mono JIT Code) UnityEngine.Debug:LogError (object)
0x000001b7ca9cdfab (Mono JIT Code) UnityEditor.BuildPlayerWindow:CallBuildMethods (bool,UnityEditor.BuildOptions)
0x000001b7ca721783 (Mono JIT Code) UnityEditor.BuildPlayerWindow:GUIBuildButtons (UnityEditor.Modules.IBuildWindowExtension,bool,bool,bool,UnityEditor.Build.BuildPlatform,UnityEditor.Modules.IBuildPostprocessor)
0x000001b7ca708ca3 (Mono JIT Code) UnityEditor.BuildPlayerWindow:ShowBuildTargetSettings ()
0x000001b7ca6f3943 (Mono JIT Code) UnityEditor.BuildPlayerWindow:OnGUI ()
0x000001b7ca616efa (Mono JIT Code) UnityEditor.HostView:InvokeOnGUI (UnityEngine.Rect)
0x000001b7ca616d13 (Mono JIT Code) UnityEditor.DockArea:DrawView (UnityEngine.Rect)
0x000001b7ca607b7b (Mono JIT Code) UnityEditor.DockArea:OldOnGUI ()
0x000001b7ca4a6b3f (Mono JIT Code) UnityEngine.UIElements.IMGUIContainer:DoOnGUI (UnityEngine.Event,UnityEngine.Matrix4x4,UnityEngine.Rect,bool,UnityEngine.Rect,System.Action,bool)
0x000001b7ca4a5c3b (Mono JIT Code) UnityEngine.UIElements.IMGUIContainer:HandleIMGUIEvent (UnityEngine.Event,UnityEngine.Matrix4x4,UnityEngine.Rect,System.Action,bool)
0x000001b7ca7576db (Mono JIT Code) UnityEngine.UIElements.IMGUIContainer:HandleIMGUIEvent (UnityEngine.Event,System.Action,bool)
0x000001b7ca757543 (Mono JIT Code) UnityEngine.UIElements.IMGUIContainer:HandleIMGUIEvent (UnityEngine.Event,bool)
0x000001b7ca7c2a7b (Mono JIT Code) UnityEngine.UIElements.IMGUIContainer:SendEventToIMGUIRaw (UnityEngine.UIElements.EventBase,bool,bool)
0x000001b7ca7bee03 (Mono JIT Code) UnityEngine.UIElements.IMGUIContainer:SendEventToIMGUI (UnityEngine.UIElements.EventBase,bool,bool)
0x000001b7c6f7c89b (Mono JIT Code) UnityEngine.UIElements.IMGUIContainer:HandleEvent (UnityEngine.UIElements.EventBase)
0x000001b7c6f72478 (Mono JIT Code) UnityEngine.UIElements.CallbackEventHandler:HandleEventAtTargetPhase (UnityEngine.UIElements.EventBase)
0x000001b7ca7bbfab (Mono JIT Code) UnityEngine.UIElements.MouseCaptureDispatchingStrategy:DispatchEvent (UnityEngine.UIElements.EventBase,UnityEngine.UIElements.IPanel)
0x000001b7c6f7067e (Mono JIT Code) UnityEngine.UIElements.EventDispatcher:ApplyDispatchingStrategies (UnityEngine.UIElements.EventBase,UnityEngine.UIElements.IPanel,bool)
0x000001b7c6f7017b (Mono JIT Code) UnityEngine.UIElements.EventDispatcher:ProcessEvent (UnityEngine.UIElements.EventBase,UnityEngine.UIElements.IPanel)
0x000001b7c6f7671b (Mono JIT Code) UnityEngine.UIElements.EventDispatcher:ProcessEventQueue ()
0x000001b7c6f74db3 (Mono JIT Code) UnityEngine.UIElements.EventDispatcher:OpenGate ()
0x000001b7c6f74ceb (Mono JIT Code) UnityEngine.UIElements.EventDispatcherGate:Dispose ()
0x000001b7c6f70403 (Mono JIT Code) UnityEngine.UIElements.EventDispatcher:ProcessEvent (UnityEngine.UIElements.EventBase,UnityEngine.UIElements.IPanel)
0x000001b7c6f6f923 (Mono JIT Code) UnityEngine.UIElements.EventDispatcher:Dispatch (UnityEngine.UIElements.EventBase,UnityEngine.UIElements.IPanel,UnityEngine.UIElements.DispatchMode)
0x000001b7c6f6f79b (Mono JIT Code) UnityEngine.UIElements.BaseVisualElementPanel:SendEvent (UnityEngine.UIElements.EventBase,UnityEngine.UIElements.DispatchMode)
0x000001b7ca464c5b (Mono JIT Code) UnityEngine.UIElements.UIElementsUtility:DoDispatch (UnityEngine.UIElements.BaseVisualElementPanel)
0x000001b7ca464703 (Mono JIT Code) UnityEngine.UIElements.UIElementsUtility:UnityEngine.UIElements.IUIElementsUtility.ProcessEvent (int,intptr,bool&)
0x000001b7ca46451f (Mono JIT Code) UnityEngine.UIElements.UIEventRegistration:ProcessEvent (int,intptr)
0x000001b7ca46443b (Mono JIT Code) UnityEngine.UIElements.UIEventRegistration/<>c:<.cctor>b__1_2 (int,intptr)
0x000001b7ca46428d (Mono JIT Code) UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)
0x000001b7ca464346 (Mono JIT Code) (wrapper runtime-invoke) <Module>:runtime_invoke_void_int_intptr_intptr& (object,intptr,intptr,intptr)
0x00007ffeb5a3e4b4 (mono-2.0-bdwgc) [mini-runtime.c:3445] mono_jit_runtime_invoke 
0x00007ffeb597e764 (mono-2.0-bdwgc) [object.c:3066] do_runtime_invoke 
0x00007ffeb597e8fc (mono-2.0-bdwgc) [object.c:3113] mono_runtime_invoke 
0x00007ff6121fdac4 (Unity) scripting_method_invoke
0x00007ff6121f8644 (Unity) ScriptingInvocation::Invoke
0x00007ff6121f1f65 (Unity) ScriptingInvocation::Invoke<void>
0x00007ff6122faeba (Unity) Scripting::UnityEngine::GUIUtilityProxy::ProcessEvent
0x00007ff612d35e86 (Unity) GUIView::ProcessRetainedMode
0x00007ff61327dceb (Unity) GUIView::OnInputEvent
0x00007ff612d35c9a (Unity) GUIView::ProcessInputEvent
0x00007ff61327ec3b (Unity) GUIView::ProcessEventMessages
0x00007ff61327880c (Unity) GUIView::GUIViewWndProc
0x00007fff4125e858 (USER32) CallWindowProcW
0x00007fff4125e299 (USER32) DispatchMessageW
0x00007ff613253633 (Unity) MainMessageLoop
0x00007ff61325805b (Unity) WinMain
0x00007ff6145db42e (Unity) __scrt_common_main_seh
0x00007fff41d77034 (KERNEL32) BaseThreadInitThunk
0x00007fff42482651 (ntdll) RtlUserThreadStart

**Comment by alihan98ersoy** [comment]
I think this problem is caused by unity, not the plugin. But ı found something on the net that maybe works.

Some Steps To Try

    Go to preferences -> External Tools -> and select regenerate project files.

    Go to File -> Build Settings - > Build and point to a new folder for your output.

Last Resorts

    Restart Unity

    Restart Your PC

I couldn't find the same issue but also I found these:

https://answers.unity.com/questions/1843044/unity-build-error-6.html
https://answers.unity.com/questions/1380921/build-failed-with-errors-at-unityeditorbuildplayer.html

**Comment by CarolineEhabAnwar** [comment]
Thank you very much. I went back to the branch before trying to implement the plugin and redid only the needed steps, the project was build but there was still a Null pointer exception error when trying to run the demo sadly. I will still try it in the Cloud Debugging, but if I understand correctly, it should run with any mobile emulators as I've installed the HMS core with the plugin, isn't that right?

**Comment by alihan98ersoy** [comment]
We recommend testing it with a real device. Cloud debugging offers you the opportunity to test a real device remotely. So I can't guarantee that you can do a proper test with the emulator.

**Comment by CarolineEhabAnwar** [comment]
I tested it with Cloud Debugging today, the app didn't crash, but the Auth Demo didn't work sadly and there was no response when i clicked several sign in buttons.

**Comment by alihan98ersoy** [comment]
Is it possible to log in cloud debugging? If you can share the log with me maybe I can help.
[Viewing and Exporting Logs](https://developer.huawei.com/consumer/en/doc/development/AppGallery-connect-Guides/agc-clouddebug-viewlog-0000001089261141)

**Comment by CarolineEhabAnwar** [comment]
Here are some sample of the logs, I exported both the verbose and the errors log 2 different types when trying logging in with Anonyms Login and Huawei ID
[2022-08-15 22_59_32.log](https://github.com/EvilMindDevs/hms-unity-plugin/files/9339828/2022-08-15.22_59_32.log)
[2022-08-15 23_01_20.log](https://github.com/EvilMindDevs/hms-unity-plugin/files/9339829/2022-08-15.23_01_20.log)
[2022-08-15 23_01_13.log](https://github.com/EvilMindDevs/hms-unity-plugin/files/9339830/2022-08-15.23_01_13.log)
[2022-08-15 22_59_43.log](https://github.com/EvilMindDevs/hms-unity-plugin/files/9339831/2022-08-15.22_59_43.log)

**Comment by CarolineEhabAnwar** [comment]
I also tried with another device that has the HMS label, here are the log
[2022-08-15 23_05_36.log](https://github.com/EvilMindDevs/hms-unity-plugin/files/9339853/2022-08-15.23_05_36.log)
[2022-08-15 23_05_42.log](https://github.com/EvilMindDevs/hms-unity-plugin/files/9339854/2022-08-15.23_05_42.log)
s

**Comment by bunyamineymen** [comment]
We have caught the error cause and will release a bug fix as soon as possible.

**Comment by CarolineEhabAnwar** [comment]
Thank you very much

**Comment by CarolineEhabAnwar** [comment]
Hello, 
I just wanted a follow up about the issue please

**Comment by bunyamineymen** [comment]
Hello
This is in our follow-up.We will release the bug-fix about it at the next release.

**Comment by alihan98ersoy** [comment]
Hello,

Can you check your kit settings? Account kit & Auth Service should be enabled at the same time for our demo scene. Also, can you check AGC for if Auth service is enabled?

![resim](https://user-images.githubusercontent.com/39373386/188559069-5536688b-3d45-4bac-9707-d18c7e7aca05.png)
![resim](https://user-images.githubusercontent.com/39373386/188559174-d9ef7ce4-5aca-4c54-85df-542f13fb6c68.png)
![resim](https://user-images.githubusercontent.com/39373386/188559232-6b39838f-b071-4fc9-a6eb-81d27a9b96eb.png)
 
Also, you should Enable the account kit (HUAWEİ ID) in Auth service.
![resim](https://user-images.githubusercontent.com/39373386/188559413-9fbb850d-6319-40e3-a67e-1a06d4af3220.png)


According to my test, there are a few bugs but these bugs do not cause any problems with Auth service.

**Comment by CarolineEhabAnwar** [comment]
All of these are enabled yes

**Comment by CarolineEhabAnwar** [comment]
The script is not broken
![image](https://user-images.githubusercontent.com/68237645/189306238-2139aff8-3f47-4248-9a1f-05fdfbab3fe0.png)
Here are the logs
[2022-09-09 10_50_40.log](https://github.com/EvilMindDevs/hms-unity-plugin/files/9533909/2022-09-09.10_50_40.log)

I feel that I am missing a step. When I update the appconnect json file, nothing actually changes. I wonder if there might be something that doesn't update the json while when i enable the services for example?

**Comment by alihan98ersoy** [comment]
Hello,
In Your Unity Project folder > Huawei >Settings > Resources > HMSMainEditorSettings Auth & AccountKit should true. When you enable kits it should modify here but somehow it is not working. Can you manually Make AccountKit's value True?
![resim](https://user-images.githubusercontent.com/39373386/189318954-9cd9dde5-f3d0-4527-9a8b-dc1b8733d3f5.png)

I am getting the same error log when AccountKit is false.
![resim](https://user-images.githubusercontent.com/39373386/189319335-f2fa0de0-57b3-461a-a2d8-4b3cd292730e.png)

**Comment by CarolineEhabAnwar** [comment]
They are actually true without modifying them, so i don't think this is the case :(  
![image](https://user-images.githubusercontent.com/68237645/189483264-87c0c15b-33a1-4b4e-aa47-9bae8fc1f1e8.png)

**Comment by alihan98ersoy** [comment]
I will investigate further. If you don't mind can you give me these details?

* Can you confirm that you are not using proguards? (This can be the reason)
![resim](https://user-images.githubusercontent.com/39373386/189586570-c386fde8-bd7d-4101-a9f1-d728011683bb.png)

* Are you testing with a Huawei device or a GMS device?
* HMS core version of your device
* Your unity version
* And can you export your project and manually check for SDKs?

![resim](https://user-images.githubusercontent.com/39373386/189587188-84acfbb9-fcc2-401c-90cb-7b987fcea2b9.png)
![resim](https://user-images.githubusercontent.com/39373386/189588923-b077792a-7c15-4d11-be07-906383edc4a7.png)

**Comment by CarolineEhabAnwar** [comment]
Hello, sorry for my late reply,

- I am not using proguards as shown in the screenshot
![image](https://user-images.githubusercontent.com/68237645/191344673-f54988f3-e8c6-4794-8f0f-33296db0fe39.png)

- I am using this device

![image](https://user-images.githubusercontent.com/68237645/191345155-7738145b-311b-4b39-8db9-8940be2286ae.png)

- I am using Unity Version 2021.3.6f1 and I'm not developing in Mac
- I exported the project and this is my gradle, I can't find the SDKs that you pointed out, what should I do next?
![image](https://user-images.githubusercontent.com/68237645/191346506-bf1a30a8-ba85-42cc-9bc0-31003d8c4e15.png)

**Comment by bunyamineymen** [comment]
Hi

I have a quick solution.

1- Disable Auth at HMS Kit Settings
2 -Delete all files at Assets/Huawei/Settings/Resources
3 -Delete all files and folders in root directory except Assets , Packages and ProjectSettings folder
3- Restart unity
4- Enable Auth at HMS Kit Settings

Can you try it?

**Comment by osmanklc44** [comment]
i had the same problem and then i found solution : edit/playersetting/other/scriptbacket i did mono this problem occurs when illcp is switched

**Comment by alihan98ersoy** [comment]
Thanks for bringing it up

**Comment by alihan98ersoy** [comment]
Despite testing many times, we could not detect the problem.
