### ISSUE TITLE
API - Check if subscribed or not for given product ID

### ISSUE THREAD

**Issue by m0skit0** [EvilMindDevs/hms-unity-plugin#36]
`public bool IsSubscribed(string productId)`

**Comment by Micro4lik** [comment]
Hello!
Thank for plugin!
I am very concerned about this question, how can we check if subscription has ended?

**Comment by Micro4lik** [comment]
Can i just look at OnObtainOwnedPurchasesSuccess Action on start?
ownPurchaseResult.ItemList can contain subscription if it has already expired?
`            iapManager.OnObtainOwnedPurchasesSuccess = (ownedPurchaseResult) =>
            {
                foreach (var item in ownedPurchaseResult.ItemList)
                {`
