### ISSUE TITLE
Banner Ad Size

### ISSUE THREAD

**Issue by diablo85xxx** [EvilMindDevs/hms-unity-plugin#362]
Hi everyone.

There is a way to get precise banner Size?

My problem is that on a huawei tablet it spawn a 50px height banner (this is reported on the test ad text: 320x50), but if i measure the ad (reserving a blank spot, in order to not cover my app buttons) it measure 135px height.

I almost sure that the banner i see is not 50px, but something with 90px*1.5 (this ratio, come from the call BannerAdSize.BANNER_SIZE_320_50.HeightPx, that return me 75px, hence a ratio of 75px/50px = 1.5).

Any help regard this problem?

**Comment by alihan98ersoy** [comment]
This is the calculation for BannerView container size:
```java
int width = activity.getWindow().getDecorView().getWidth();
int height = activity.getWindow().getDecorView().getHeight();

if(width>height) // landscape
{
    bannerViewWidth = (int) (width*0.55);
    bannerViewHeight= (int) (height*0.20);
}
else//portrait
{
    bannerViewWidth = (int) (width*0.8);
    bannerViewHeight= FrameLayout.LayoutParams.WRAP_CONTENT;
}
```
After this calculation, let's say your banner container size is 640_150 and you have loaded BannerAdSize.BANNER_SIZE_320_50 as a banner ad. You'll see the ad for BannerAdSize.BANNER_SIZE_320_50 with dimensions 640_100. It will automatically appear at the largest size for the container, keeping the width and height ratio same.

**Comment by diablo85xxx** [comment]
Hi, thanks for your answer.

I'm using C#, is there any C# code that i can use in order to found the height of the banner in pixel screen, or the activity you mentioned?

**Comment by alihan98ersoy** [comment]
If you want you can check the logs for it. 
![resim](https://user-images.githubusercontent.com/39373386/191243050-26e19bd9-e8d5-42c7-be0a-a204fb739b8e.png)
Or you can refer to https://answers.unity.com/questions/161281/is-there-a-way-to-android-physical-screen-size.html
