### ISSUE TITLE
Native Ads

### ISSUE THREAD

**Issue by tdvip** [EvilMindDevs/hms-unity-plugin#363]
Nice! Thank you very much for the plugin.
When will this plugin support Native Ads
Our project requires native ads, which unfortunately are not supported right now

**Comment by alihan98ersoy** [comment]
Thank you for using our plugin. Native Ads is currently on our roadmap, and we plan to support it towards the end of the year. Could you briefly explain why you need Native ads and why the presently supported ad types do not meet your needs?

**Comment by tdvip** [comment]
Thank you for your reply!

We have a project that needs to integrate native advertising, and can freely promote our other games in the App.
Can you tell me about when native ads will be online, thank you very much.
Looking forward to your reply.

**Comment by alihan98ersoy** [comment]
we will start supporting it at the end of the year

**Comment by eozdemir90** [comment]
Hi there! Native ads will be ready at the beginning of December with the new version.
Thank you for your interest in our project. You may give a star to support us and follow up on the project. You can also join our discord channel to follow changes and ask any kind of question about the plugin, gaming ecosystem, etc. You may access it from here : https://discord.io/hmsunityplugin
Thank you and stay tuned!

**Comment by alihan98ersoy** [comment]
Hello, Our plugin now supporting [Native Ads](https://evilminddevs.gitbook.io/hms-unity-plugin_/kits-and-services/ads-kit/guides-and-references/native-ads) with v2.2.8
