### ISSUE TITLE
The ads Error

### ISSUE THREAD

**Issue by SxmGit** [EvilMindDevs/hms-unity-plugin#364]
Exception: NullReferenceException: Object reference not set to an instance of an object.

HmsPlugin.HMSAdsKitManager+ConsentUpdateListener.HuaweiMobileServices.Ads.IConsentUpdateListener.OnSuccess (HuaweiMobileServices.Ads.ConsentStatus consentStatus, System.Boolean isNeedConsent, System.Collections.Generic.IList`1[T] adProviders) (at <00000000000000000000000000000000>:0)
HuaweiMobileServices.Ads.ConsentUpdateListener.onSuccess (UnityEngine.AndroidJavaObject consentStatus, System.Boolean isNeedConsent, UnityEngine.AndroidJavaObject adProviderList) (at <00000000000000000000000000000000>:0)
System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <00000000000000000000000000000000>:0)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at <00000000000000000000000000000000>:0)
UnityEngine.AndroidJavaProxy.Invoke (System.String methodName, System.Object[] args) (at <00000000000000000000000000000000>:0)
UnityEngine._AndroidJNIHelper.InvokeJavaProxyMethod (UnityEngine.AndroidJavaProxy proxy, System.IntPtr jmethodName, System.IntPtr jargs) (at <00000000000000000000000000000000>:0)
Rethrow as TargetInvocationException: HuaweiMobileServices.Ads.ConsentUpdateListener.onSuccess(UnityEngine.AndroidJavaObject,System.Boolean,UnityEngine.AndroidJavaObject)
UnityEngine.AndroidJavaProxy.Invoke (System.String methodName, System.Object[] args) (at <00000000000000000000000000000000>:0)
UnityEngine._AndroidJNIHelper.InvokeJavaProxyMethod (UnityEngine.AndroidJavaProxy proxy, System.IntPtr jmethodName, System.IntPtr jargs) (at <00000000000000000000000000000000>:0)

**Comment by alihan98ersoy** [comment]
I check the [IConsentUpdateListener.OnSuccess ](https://github.com/EvilMindDevs/hms-unity-plugin/blob/e58e85366476c6783571abebbcd25e5efafbedec/Assets/Huawei/Scripts/Ads/HMSAdsKitManager.cs#L732) for are we checking for null before calling Invoke. Yes, we are. So I believe mAdsManager is null in your case.
![resim](https://user-images.githubusercontent.com/39373386/191489033-357a54bf-760b-4865-9512-c9a10d23aea0.png)

You need to call [RequestConsentUpdate ](https://github.com/EvilMindDevs/hms-unity-plugin/blob/e58e85366476c6783571abebbcd25e5efafbedec/Assets/Huawei/Scripts/Ads/HMSAdsKitManager.cs#L687)method before using consent.

You can refer to our [demo scene](https://github.com/EvilMindDevs/hms-unity-plugin/blob/e58e85366476c6783571abebbcd25e5efafbedec/Assets/Huawei/Demos/Ads/AdsDemoManager.cs#L42).

**Comment by alihan98ersoy** [comment]
Thank you for your interest in our project. You may give us a star to support us and follow up on the project. You can also join our discord channel to follow changes and ask any kind of question about the plugin, gaming ecosystem, etc. You may access it from here: https://discord.io/hmsunityplugin
Thank you and stay tuned!
