### ISSUE TITLE
Push kit

### ISSUE THREAD

**Issue by Ammad6465** [EvilMindDevs/hms-unity-plugin#367]
Could not determine the dependencies of task ':unityLibrary:HMSUnityPushKit.plugin:compileReleaseAidl'.

**Comment by bunyamineymen** [comment]
Hi,
We are starting to analyze this problem.

**Comment by Ammad6465** [comment]
[image: image.png][image: image.png][image: image.png]

**Comment by bunyamineymen** [comment]
Could you please define the problem in more detail and share the logs with us?

**Comment by Ammad6465** [comment]
CommandInvokationFailure: Gradle build failed.
C:/Program
Files/Unity/Hub/Editor/2019.4.7f1/Editor/Data/PlaybackEngines/AndroidPlayer\OpenJDK\bin\java.exe
-classpath "D:\Huawei downlads\gradle-5.6.4\lib\gradle-launcher-5.6.4.jar"
org.gradle.launcher.GradleMain "-Dorg.gradle.jvmargs=-Xmx4096m"
"assembleRelease"

stderr[

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task
':unityLibrary:HMSUnityPushKit.plugin:compileReleaseAidl'.
> Failed to install the following Android SDK packages as some licences
have not been accepted.
     build-tools;28.0.3 Android SDK Build-Tools 28.0.3
  To build this project, accept the SDK license agreements and install the
missing components using the Android Studio SDK Manager.
  Alternatively, to transfer the license agreements from one workstation to
another, see http://d.android.com/r/studio-ui/export-licenses.html

  Using Android SDK: C:\Program
Files\Unity\Hub\Editor\2019.4.7f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or
--debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 24s
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
]
stdout[
Starting a Gradle Daemon, 1 incompatible and 2 stopped Daemons could not be
reused, use --status for details

> Configure project :launcher
WARNING: DSL element 'useProguard' is obsolete and will be removed soon.
Use 'android.enableR8' in gradle.properties to switch between R8 and
Proguard..
WARNING: DSL element 'useProguard' is obsolete and will be removed soon.
Use 'android.enableR8' in gradle.properties to switch between R8 and
Proguard..
--W- Build Environment: AGConnect plugin version is: 1.6.5.300, Gradle
version is: 5.6.4, Android Plugin version is: 3.5.4
--I- Using the AGConnect-Config file: D:\Ongoing Progects\PP FuryShooting
Huawei\Temp\gradleOut\launcher\agconnect-services.json
--W- The variant: debug, Use the json file: D:\Ongoing Progects\PP
FuryShooting Huawei\Temp\gradleOut\launcher\agconnect-services.json
--I- Using the AGConnect-Config file: D:\Ongoing Progects\PP FuryShooting
Huawei\Temp\gradleOut\launcher\agconnect-services.json
--W- The variant: release, Use the json file: D:\Ongoing Progects\PP
FuryShooting Huawei\Temp\gradleOut\launcher\agconnect-services.json
Exception while marshalling C:\Program
Files\Unity\Hub\Editor\2019.4.7f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\build-tools\30.0.2\package.xml.
Probably the SDK is read-only
Exception while marshalling C:\Program
Files\Unity\Hub\Editor\2019.4.7f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\platform-tools\package.xml.
Probably the SDK is read-only
Exception while marshalling C:\Program
Files\Unity\Hub\Editor\2019.4.7f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\platforms\android-29\package.xml.
Probably the SDK is read-only
Exception while marshalling C:\Program
Files\Unity\Hub\Editor\2019.4.7f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\platforms\android-30\package.xml.
Probably the SDK is read-only
Exception while marshalling C:\Program
Files\Unity\Hub\Editor\2019.4.7f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\tools\package.xml.
Probably the SDK is read-only
Exception while marshalling C:\Program
Files\Unity\Hub\Editor\2019.4.7f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\build-tools\30.0.2\package.xml.
Probably the SDK is read-only
Exception while marshalling C:\Program
Files\Unity\Hub\Editor\2019.4.7f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\platform-tools\package.xml.
Probably the SDK is read-only
Exception while marshalling C:\Program
Files\Unity\Hub\Editor\2019.4.7f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\platforms\android-29\package.xml.
Probably the SDK is read-only
Exception while marshalling C:\Program
Files\Unity\Hub\Editor\2019.4.7f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\platforms\android-30\package.xml.
Probably the SDK is read-only
Exception while marshalling C:\Program
Files\Unity\Hub\Editor\2019.4.7f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\tools\package.xml.
Probably the SDK is read-only
Exception while marshalling C:\Program
Files\Unity\Hub\Editor\2019.4.7f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\build-tools\30.0.2\package.xml.
Probably the SDK is read-only
Exception while marshalling C:\Program
Files\Unity\Hub\Editor\2019.4.7f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\platform-tools\package.xml.
Probably the SDK is read-only
Exception while marshalling C:\Program
Files\Unity\Hub\Editor\2019.4.7f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\platforms\android-29\package.xml.
Probably the SDK is read-only
Exception while marshalling C:\Program
Files\Unity\Hub\Editor\2019.4.7f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\platforms\android-30\package.xml.
Probably the SDK is read-only
Exception while marshalling C:\Program
Files\Unity\Hub\Editor\2019.4.7f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\tools\package.xml.
Probably the SDK is read-only
File C:\Users\G\.android\repositories.cfg could not be loaded.
Checking the license for package Android SDK Build-Tools 28.0.3 in
C:\Program
Files\Unity\Hub\Editor\2019.4.7f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\licenses
Warning: License for package Android SDK Build-Tools 28.0.3 not accepted.
]
exit code: 1
UnityEditor.Android.Command.WaitForProgramToRun (UnityEditor.Utils.Program
p, UnityEditor.Android.Command+WaitingForProcessToExit
waitingForProcessToExit, System.String errorMsg) (at
<d265dd4439034d6c9926c590736e62a5>:0)
UnityEditor.Android.Command.Run (System.Diagnostics.ProcessStartInfo psi,
UnityEditor.Android.Command+WaitingForProcessToExit
waitingForProcessToExit, System.String errorMsg) (at
<d265dd4439034d6c9926c590736e62a5>:0)
UnityEditor.Android.Command.Run (System.String command, System.String args,
System.String workingdir,
UnityEditor.Android.Command+WaitingForProcessToExit
waitingForProcessToExit, System.String errorMsg) (at
<d265dd4439034d6c9926c590736e62a5>:0)
UnityEditor.Android.AndroidJavaTools.RunJava (System.String args,
System.String workingdir, System.Action`1[T] progress, System.String error)
(at <d265dd4439034d6c9926c590736e62a5>:0)
UnityEditor.Android.GradleWrapper.Run (UnityEditor.Android.AndroidJavaTools
javaTools, System.String workingdir, System.String task, System.Action`1[T]
progress) (at <d265dd4439034d6c9926c590736e62a5>:0)
Rethrow as GradleInvokationException: Gradle build failed
UnityEditor.Android.GradleWrapper.Run (UnityEditor.Android.AndroidJavaTools
javaTools, System.String workingdir, System.String task, System.Action`1[T]
progress) (at <d265dd4439034d6c9926c590736e62a5>:0)
UnityEditor.Android.PostProcessor.Tasks.BuildGradleProject.Execute
(UnityEditor.Android.PostProcessor.PostProcessorContext context) (at
<d265dd4439034d6c9926c590736e62a5>:0)
UnityEditor.Android.PostProcessor.PostProcessRunner.RunAllTasks
(UnityEditor.Android.PostProcessor.PostProcessorContext context) (at
<d265dd4439034d6c9926c590736e62a5>:0)
Rethrow as BuildFailedException: Exception of type
'UnityEditor.Build.BuildFailedException' was thrown.
UnityEditor.Android.PostProcessor.CancelPostProcess.AbortBuild
(System.String title, System.String message, System.Exception ex) (at
<d265dd4439034d6c9926c590736e62a5>:0)
UnityEditor.Android.PostProcessor.PostProcessRunner.RunAllTasks
(UnityEditor.Android.PostProcessor.PostProcessorContext context) (at
<d265dd4439034d6c9926c590736e62a5>:0)
UnityEditor.Android.PostProcessAndroidPlayer.PostProcess
(UnityEditor.BuildTarget target, System.String stagingAreaData,
System.String stagingArea, System.String playerPackage, System.String
installPath, System.String companyName, System.String productName,
UnityEditor.BuildOptions options, UnityEditor.RuntimeClassRegistry
usedClassRegistry, UnityEditor.Build.Reporting.BuildReport report) (at
<d265dd4439034d6c9926c590736e62a5>:0)
UnityEditor.Android.AndroidBuildPostprocessor.PostProcess
(UnityEditor.Modules.BuildPostProcessArgs args,
UnityEditor.BuildProperties& outProperties) (at
<d265dd4439034d6c9926c590736e62a5>:0)
UnityEditor.PostprocessBuildPlayer.Postprocess
(UnityEditor.BuildTargetGroup targetGroup, UnityEditor.BuildTarget target,
System.String installPath, System.String companyName, System.String
productName, System.Int32 width, System.Int32 height,
UnityEditor.BuildOptions options, UnityEditor.RuntimeClassRegistry
usedClassRegistry, UnityEditor.Build.Reporting.BuildReport report) (at
<6776482ad98c481c9322bc7e45bcbc33>:0)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

**Comment by Ammad6465** [comment]
Is it enough?
Need any more details?

**Comment by Ammad6465** [comment]
Any guid or reference documentation ?

**Comment by bunyamineymen** [comment]
I think your android license files are missing. Can you control them on the android SDK path?

![image](https://user-images.githubusercontent.com/13828988/191962837-49ab5b0d-7789-41b8-b491-a1b9630c88b5.png)

![image](https://user-images.githubusercontent.com/13828988/191963389-bdccab67-f7ad-4954-9570-822cc859ce6d.png)

![image](https://user-images.githubusercontent.com/13828988/191963463-37c2c837-1768-48a3-b871-0cc56158270d.png)

**Comment by bunyamineymen** [comment]
Our documentation: https://evilminddevs.gitbook.io/hms-unity-plugin/

Quick Start: https://www.youtube.com/watch?v=ZskQf4quNhU
FAQ:  https://evilminddevs.gitbook.io/hms-unity-plugin/support/faq

**Comment by Ammad6465** [comment]
but
 my unity version is different 2019.4.7 [image: image.png]

**Comment by Ammad6465** [comment]
[image: image.png]but there is nothing related to push kit

**Comment by bunyamineymen** [comment]
Our documentation doesn't involve the solution to this problem for now and the difference in the unity version is not important.

**Comment by bunyamineymen** [comment]
You should control the license files for now.

**Comment by Ammad6465** [comment]
Thanks for the tip!

**Comment by bunyamineymen** [comment]
After controlling the license files we can continue analyzing them clearly.

**Comment by alihan98ersoy** [comment]
If the problem continues, I have a small demo for you.
How to resolve **Failed to install the following Android SDK packages as some licenses
have not been accepted.**


https://user-images.githubusercontent.com/39373386/192213287-f4826302-ed07-4597-9d95-13c758559a78.mp4

`sdkmanager --licenses`

**Comment by Ammad6465** [comment]
This problem is solved but I can't test the push kit working because when I get the push token and put it in console for test push it shows me the prompt wrong.
my push token is
IAAAAACy0vaHAADQsogg-3tij277yB8SYfoHUXwOv2C20r3fAvoO_Lhi1EtS2nK_hWuWUGDn4mLHwCZdFq8Omd6Zdle-osgINti_vFRk8Vca3VR8Eg
![Screenshot_20220926_173940_com fury shooting strike2020 huawei (1)](https://user-images.githubusercontent.com/88786517/192485778-92aa1519-1145-4464-9f7d-05f837617f5b.jpg)

**Comment by alihan98ersoy** [comment]
can you follow this article: https://forums.developer.huawei.com/forumPortal/en/topic/0201514939243320043

**Comment by Ammad6465** [comment]
I think I am doing the same but the only difference is the plugin version.

**Comment by saadimam08** [comment]
after doing https://github.com/EvilMindDevs/hms-unity-plugin/issues/367#issuecomment-1257569260 I am getting this whenever I try to build the project 
.....................................................................................Error 1
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':unityLibrary:HMSUnityPushKit.plugin:generateReleaseRFile'.
> Failed to install the following SDK components:
      build-tools;28.0.3 Android SDK Build-Tools 28.0.3
  The SDK directory is not writable (C:\Program Files\Unity\Hub\Editor\2019.4.30f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK)


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 15s
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8

UnityEngine.GUIUtility:ProcessEvent (int,intptr)

............................................................--------------------------------Error 2----------------------------------------------------------------

CommandInvokationFailure: Gradle build failed. 
C:/Program Files/Unity/Hub/Editor/2019.4.30f1/Editor/Data/PlaybackEngines/AndroidPlayer\OpenJDK\bin\java.exe -classpath "D:\Saad\Extra Gradels\gradle-5.4.1\lib\gradle-launcher-5.4.1.jar" org.gradle.launcher.GradleMain "-Dorg.gradle.jvmargs=-Xmx4096m" "assembleRelease"

stderr[

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':unityLibrary:HMSUnityPushKit.plugin:generateReleaseRFile'.
> Failed to install the following SDK components:
      build-tools;28.0.3 Android SDK Build-Tools 28.0.3
  The SDK directory is not writable (C:\Program Files\Unity\Hub\Editor\2019.4.30f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK)


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 15s
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
]
stdout[
Starting a Gradle Daemon, 1 incompatible and 4 stopped Daemons could not be reused, use --status for details

> Configure project :launcher
WARNING: DSL element 'useProguard' is obsolete and will be removed soon. Use 'android.enableR8' in gradle.properties to switch between R8 and Proguard..
WARNING: DSL element 'useProguard' is obsolete and will be removed soon. Use 'android.enableR8' in gradle.properties to switch between R8 and Proguard..
--W- Build Environment: AGConnect plugin version is: 1.6.5.300, Gradle version is: 5.4.1, Android Plugin version is: 3.5.4
--I- Using the AGConnect-Config file: D:\Saad\Projects\Huawei US Police Car Transport Truck V 45 (1.0.44)\Temp\gradleOut\launcher\agconnect-services.json
--W- The variant: debug, Use the json file: D:\Saad\Projects\Huawei US Police Car Transport Truck V 45 (1.0.44)\Temp\gradleOut\launcher\agconnect-services.json
--I- Using the AGConnect-Config file: D:\Saad\Projects\Huawei US Police Car Transport Truck V 45 (1.0.44)\Temp\gradleOut\launcher\agconnect-services.json
--W- The variant: release, Use the json file: D:\Saad\Projects\Huawei US Police Car Transport Truck V 45 (1.0.44)\Temp\gradleOut\launcher\agconnect-services.json
Checking the license for package Android SDK Build-Tools 28.0.3 in C:\Program Files\Unity\Hub\Editor\2019.4.30f1\Editor\Data\PlaybackEngines\AndroidPlayer\SDK\licenses
License for package Android SDK Build-Tools 28.0.3 accepted.
Preparing "Install Android SDK Build-Tools 28.0.3 (revision: 28.0.3)".
Warning: Failed to read or create install properties file.
]
exit code: 1
UnityEditor.Android.Command.WaitForProgramToRun (UnityEditor.Utils.Program p, UnityEditor.Android.Command+WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg) (at <a83396a2554740a886f5ffb57e40eb15>:0)
UnityEditor.Android.Command.Run (System.Diagnostics.ProcessStartInfo psi, UnityEditor.Android.Command+WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg) (at <a83396a2554740a886f5ffb57e40eb15>:0)
UnityEditor.Android.Command.Run (System.String command, System.String args, System.String workingdir, UnityEditor.Android.Command+WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg) (at <a83396a2554740a886f5ffb57e40eb15>:0)
UnityEditor.Android.AndroidJavaTools.RunJava (System.String args, System.String workingdir, System.Action`1[T] progress, System.String error) (at <a83396a2554740a886f5ffb57e40eb15>:0)
UnityEditor.Android.GradleWrapper.Run (UnityEditor.Android.AndroidJavaTools javaTools, System.String workingdir, System.String task, System.Action`1[T] progress) (at <a83396a2554740a886f5ffb57e40eb15>:0)
Rethrow as GradleInvokationException: Gradle build failed
UnityEditor.Android.GradleWrapper.Run (UnityEditor.Android.AndroidJavaTools javaTools, System.String workingdir, System.String task, System.Action`1[T] progress) (at <a83396a2554740a886f5ffb57e40eb15>:0)
UnityEditor.Android.PostProcessor.Tasks.BuildGradleProject.Execute (UnityEditor.Android.PostProcessor.PostProcessorContext context) (at <a83396a2554740a886f5ffb57e40eb15>:0)
UnityEditor.Android.PostProcessor.PostProcessRunner.RunAllTasks (UnityEditor.Android.PostProcessor.PostProcessorContext context) (at <a83396a2554740a886f5ffb57e40eb15>:0)
Rethrow as BuildFailedException: Exception of type 'UnityEditor.Build.BuildFailedException' was thrown.
UnityEditor.Android.PostProcessor.CancelPostProcess.AbortBuild (System.String title, System.String message, System.Exception ex) (at <a83396a2554740a886f5ffb57e40eb15>:0)
UnityEditor.Android.PostProcessor.PostProcessRunner.RunAllTasks (UnityEditor.Android.PostProcessor.PostProcessorContext context) (at <a83396a2554740a886f5ffb57e40eb15>:0)
UnityEditor.Android.PostProcessAndroidPlayer.PostProcess (UnityEditor.BuildTarget target, System.String stagingAreaData, System.String stagingArea, System.String playerPackage, System.String installPath, System.String companyName, System.String productName, UnityEditor.BuildOptions options, UnityEditor.RuntimeClassRegistry usedClassRegistry, UnityEditor.Build.Reporting.BuildReport report) (at <a83396a2554740a886f5ffb57e40eb15>:0)
UnityEditor.Android.AndroidBuildPostprocessor.PostProcess (UnityEditor.Modules.BuildPostProcessArgs args, UnityEditor.BuildProperties& outProperties) (at <a83396a2554740a886f5ffb57e40eb15>:0)
UnityEditor.PostprocessBuildPlayer.Postprocess (UnityEditor.BuildTargetGroup targetGroup, UnityEditor.BuildTarget target, System.String installPath, System.String companyName, System.String productName, System.Int32 width, System.Int32 height, UnityEditor.BuildOptions options, UnityEditor.RuntimeClassRegistry usedClassRegistry, UnityEditor.Build.Reporting.BuildReport report) (at <fdb4e7a229ae4ef791f6716e71e93744>:0)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

**Comment by alihan98ersoy** [comment]
The problem here is that the unity editor doesn't have read-write permission. I am using unity hub and unity hub is running unity editor. If you have the same situation, if you run the Unity hub as an administrator, the problem will be solved. (Unity editor needs to run as administrator)

**Comment by saadimam08** [comment]
should I do the same for 2020 unity version?

**Comment by alihan98ersoy** [comment]
I am not sure. It's okay until you get the same problem, but after you get it you can restart the unity and hope the problem goes away or try to fix it. This is how I solved it. There may be other solutions on the internet.

**Comment by Ammad6465** [comment]
Sorry I don't understand.
What can I do

**Comment by alihan98ersoy** [comment]
If you run the unity editor as administrator, I believe the problem will solve
