### ISSUE TITLE
Game services Leaderboard errors

### ISSUE THREAD

**Issue by Ammad6465** [EvilMindDevs/hms-unity-plugin#370]
I enabled the game service kit and added the leaderboard and achievement Ids to the kit settings. I then add the demo game scene to my build. The apk creation succeeds without any errors. When I run the apk and open the game demo scene everything is fine, the result is that when I click on the show leaderboards button in the demo scene it throws an error with exception message code: 60004 Is.

![Capture](https://user-images.githubusercontent.com/88786517/192489457-aa985976-a632-4909-8573-5d048b58bd94.PNG)

**Comment by alihan98ersoy** [comment]
Did you enable game service?
![resim](https://user-images.githubusercontent.com/39373386/192496504-9a8908ec-926b-4e42-8b01-c81b5361e0d1.png)

After enabling the game service you need to 
1. reimport agconnect-services.json
2. Clear the HMS Core (APK) cache and try again.

**Comment by Ammad6465** [comment]
not working

**Comment by Ammad6465** [comment]
Is there a reference project with HMS Unity Plugin 2.2.5, with all Huawei kits and all services enabled?
Please send it to me

**Comment by alihan98ersoy** [comment]
https://github.com/EvilMindDevs/Stack-HmsUnityPlugin-ReferenceGame

**Comment by alihan98ersoy** [comment]
When you enable the service, it may take time to take effect. Maybe it will work if you try again.

**Comment by eozdemir90** [comment]
Thank you for your interest in our project. You may give a star to support us and follow up on the project. You can also join our discord channel to follow changes and ask any kind of question about the plugin, gaming ecosystem, etc. You may access it from here : https://discord.io/hmsunityplugin
Thank you and stay tuned!
