### ISSUE TITLE
ads not shown in unity 2021

### ISSUE THREAD

**Issue by salmanmadni** [EvilMindDevs/hms-unity-plugin#371]
hello i face problem uning v2.2.5 - Unity 2019/2020/2021
https://github.com/EvilMindDevs/hms-unity-plugin/releases/tag/v2.2.5-2019-2020
the build  run successfully but non ads shown even test ads and live ads 
i follow all the procedure 
1==>> import the ads demo scene also when run the game a [HMSDispatcher] is created on run time 

2==>>  go in the huawei tab
3    enable the ads 
4 check the test ads in one try and in 2nd try put the live ads in tabs
5 rename the pakage name in agc file also in build setting
6 apk create successfully when ever i run the apk non ads shown 

show whats the problem please help me to run the ads 
my email address is salmanmadni10@gmail.com

**Comment by alihan98ersoy** [comment]
in 5 if you are changing agc file you are doing wrong. You need to [download and use it](https://evilminddevs.gitbook.io/hms-unity-plugin/getting-started/quick-start/import-the-plugin-into-your-unity-project#obtaining-the-agconnect-services.json-file) without any modification.

Are you testing with a Huawei device? (GMS device ok but you need to have HMS core app)
If not you can refer to [Devices Without HMS Core Installed](https://evilminddevs.gitbook.io/hms-unity-plugin/kits-and-services/ads-kit/guides-and-references#devices-without-hms-core-installed)

Can you share the logs with me? You can get the logs with [Android Logcat](https://docs.unity3d.com/Packages/com.unity.mobile.android-logcat@0.1/manual/index.html).

**Comment by salmanmadni** [comment]
Exception: Field ALLOW_NON_PERSONALIZED or type signature  not found
UnityEngine._AndroidJNIHelper.GetFieldID (System.IntPtr jclass, System.String fieldName, System.String signature, System.Boolean isStatic) (at <d79fd7fd05ec452a9f177312b5255dd1>:0)
UnityEngine.AndroidJNIHelper.GetFieldID (System.IntPtr javaClass, System.String fieldName, System.String signature, System.Boolean isStatic) (at <d79fd7fd05ec452a9f177312b5255dd1>:0)
UnityEngine._AndroidJNIHelper.GetFieldID[ReturnType] (System.IntPtr jclass, System.String fieldName, System.Boolean isStatic) (at <d79fd7fd05ec452a9f177312b5255dd1>:0)
UnityEngine.AndroidJNIHelper.GetFieldID[FieldType] (System.IntPtr jclass, System.String fieldName, System.Boolean isStatic) (at <d79fd7fd05ec452a9f177312b5255dd1>:0)
UnityEngine.AndroidJavaObject._GetStatic[FieldType] (System.String fieldName) (at <d79fd7fd05ec452a9f177312b5255dd1>:0)
UnityEngine.AndroidJavaObject.GetStatic[FieldType] (System.String fieldName) (at <d79fd7fd05ec452a9f177312b5255dd1>:0)
HuaweiMobileServices.Ads.NonPersonalizedAd..cctor () (at <11b6e8db87bf41b1b9dad3c4716f3e6d>:0)
Rethrow as TypeInitializationException: The type initializer for 'HuaweiMobileServices.Ads.NonPersonalizedAd' threw an exception.

**Comment by alihan98ersoy** [comment]
Are you getting this error on an editor or a real device? I am getting this error when I try to run with the editor. 
![image](https://user-images.githubusercontent.com/39373386/192770690-52cadccb-957c-4337-ab06-745cd794f145.png)

You should test it with a real device. And I couldn't see any problem in the logs, but the first logs that should be in the logs are missing. I think the first part of the logs is missing.

**Comment by salmanmadni** [comment]
also i attached log cat file please check this file also

**Comment by alihan98ersoy** [comment]
![image](https://user-images.githubusercontent.com/39373386/192773863-e8373d00-d2a1-4ef2-b9af-ee252acdb1cc.png)
these 3 right. For them

I couldn't see any problem in the logs, but the first logs that should be in the logs are missing. I think the first part of the logs is missing.

**Comment by salmanmadni** [comment]
here is new log cat file sir 

[2022-09-28 17_12_38.log](https://github.com/EvilMindDevs/hms-unity-plugin/files/9664749/2022-09-28.17_12_38.log)

**Comment by alihan98ersoy** [comment]
There is two different version of ads kit. And I am not sure why there is two different ads kit. Are you trying to use the plugin with another solution such as [mediation](https://github.com/Explore-In-HMS/huawei.ads.admob_mediation)?

![image](https://user-images.githubusercontent.com/39373386/192780572-57ddd263-f480-49dd-95e1-f3f9a2316ecf.png)

**Comment by salmanmadni** [comment]
how it is possible i download this plugin and build apk
https://github.com/EvilMindDevs/hms-unity-plugin/releases/tag/v2.2.5-2019-2020

so what is the solution right now :( can you share with me your skype or whats app

**Comment by alihan98ersoy** [comment]
we can discord or I can send you a meeting link via email if you want. https://discord.io/hmsunityplugin

**Comment by salmanmadni** [comment]
its free or paid group

**Comment by alihan98ersoy** [comment]
free

**Comment by salmanmadni** [comment]
ok give me meeting link sir

**Comment by alihan98ersoy** [comment]
I sent it via e-mail.

**Comment by alihan98ersoy** [comment]
Hello
I am in the meeting. [salmanmadni10@gmail.com](mailto:salmanmadni10@gmail.com) is this your e-mail address? We can rearrange a meeting if needed or you can dm me via discord.

**Comment by salmanmadni** [comment]
No i just download the sdk from evilmind devs... Import it in my unity and
build the apk file

**Comment by alihan98ersoy** [comment]
Did you follow our [quick start ](https://evilminddevs.gitbook.io/hms-unity-plugin/getting-started/quick-start)? And did you enable the Ads kit from the AGC console? (This step requires applying for the [Merchant Service](https://developer.huawei.com/consumer/en/doc/start/merchant-service-0000001053025967).)

**Comment by MehranRamzan** [comment]
i am also facing the same issue... please help me to fix it.

**Comment by alihan98ersoy** [comment]
May I get the logs? Maybe I can find the main reason in the logs.

And are you using Unity 2021.3 and above version? Can you try to delete yourProjectFolder/library/bee folder?

Did you get this error after updating the plugin? Can you try to delete the folder and then import the plugin again?

**Comment by alihan98ersoy** [comment]
Despite testing many times, we could not detect the problem.
