### ISSUE TITLE
StreamingAssets folder num files cap?

### ISSUE THREAD

**Issue by diablo85xxx** [EvilMindDevs/hms-unity-plugin#373]
Hi, we recently tried to build a game with this plugin, loading some content from the StreamingAssets folder, but the build fails.

The StreamingAssets contain more then 700 files, and after some trial, we found that if we remove many of this files (let's say 600), the build is done properly.

So i ask, there is any restriction in StreamingAssets folder on the numbers of files can contain (or maybe filesize? The game is approximately 30 MB so, i don't think should be a problem)?

**Comment by alihan98ersoy** [comment]
https://answers.unity.com/questions/1239999/streamingassets-folder-max-size.html I couldn't find the answer on the net. And I don't know the answer. But maybe you can try a different solution for your files.  Such as [cloud storage](https://evilminddevs.gitbook.io/hms-unity-plugin/kits-and-services/cloud-storage).

**Comment by diablo85xxx** [comment]
Ok, i tested again on the same project, and seems it build correctly...

But still, there is something strange in the build... it require like 15 minutes, stuck in "Build gradle project" phase, where usually it need only 1-2 minutes. 
Probably this long time make the build crash sometimes for some reason.

Without the plugin everythings builds as expected in 1-2 minutes.

**Comment by alihan98ersoy** [comment]
I am working with two computers and getting a similar issue on my work PC. Are you using a proxy or VPN maybe these can be blocking. I fix this issue by configuring my gradle.properties. C:\Users\{yourUser}\.gradle\gradle.properties

add these lines:
```
systemProp.https.proxyPassword=
systemProp.http.proxyHost=localhost
systemProp.https.proxyUser={username}
systemProp.https.proxyHost=localhost
systemProp.https.proxyPort={port}
systemProp.http.proxyPort={port}
systemProp.http.proxyPassword=
systemProp.http.proxyUser={username}
```

**Comment by diablo85xxx** [comment]
I'm not using any proxy or VPN.

This is probably something related to gradle build

**Comment by alihan98ersoy** [comment]
The main reason behind this long process is gradle is downloading repositories in background. Maybe this can help https://unity3diy.blogspot.com/2019/10/unity-stuck-on-building-gradle-project.html

**Comment by eozdemir90** [comment]
Thank you for your interest in our project. You may give a star to support us and follow up on the project. You can also join our discord channel to follow changes and ask any kind of question about the plugin, gaming ecosystem, etc. You may access it from here : https://discord.io/hmsunityplugin
Thank you and stay tuned!
