### ISSUE TITLE
Mediation banner size issue 

### ISSUE THREAD

**Issue by PradoParking** [EvilMindDevs/hms-unity-plugin#375]
https://we.tl/t-9iLXwW6g9m

**Comment by alihan98ersoy** [comment]
Bug fixed with new mediation version. implementation 'com.github.Explore-In-HMS:huawei.ads.admob_mediation:2.0.2'

**Comment by eozdemir90** [comment]
Thank you for your interest in our project. You may give a star to support us and follow up on the project. You can also join our discord channel to follow changes and ask any kind of question about the plugin, gaming ecosystem, etc. You may access it from here : https://discord.io/hmsunityplugin
Thank you and stay tuned!
