### ISSUE TITLE
UPM package

### ISSUE THREAD

**Issue by cbraecker** [EvilMindDevs/hms-unity-plugin#376]
It would be really great if you could make a upm package out of you plugin.

**Comment by alihan98ersoy** [comment]
This suggestion is on our table right now. We are considering adding it to our roadmap.

**Comment by eozdemir90** [comment]
Thank you for your interest in our project. You may give a star to support us and follow up on the project. You can also join our discord channel to follow changes and ask any kind of question about the plugin, gaming ecosystem, etc. You may access it from here : https://discord.io/hmsunityplugin
Thank you and stay tuned!
