### ISSUE TITLE
Huawei unity Iap

### ISSUE THREAD

**Issue by BreakerGss** [EvilMindDevs/hms-unity-plugin#377]
Problem occurs when running IAP.
HMS Core opens as a blank screen on the phone.
There is a product id not found error in UnityEditor. I defined the products on the app connect page and in UnityEditor.
my second problem is that the package name was not found when publishing my game on the app connect page.
How can I fix.
Thanks

**Comment by alihan98ersoy** [comment]
Can you export logs and share them with me?

**Comment by alihan98ersoy** [comment]
Issue solved. I'm adding the details here for knowledge. In this case, IAP was disabled on the AGC console.
https://developer.huawei.com/consumer/en/doc/development/HMSCore-Guides/config-agc-0000001050033072#section382112213818

**Comment by eozdemir90** [comment]
Thank you for your interest in our project. You may give a star to support us and follow up on the project. You can also join our discord channel to follow changes and ask any kind of question about the plugin, gaming ecosystem, etc. You may access it from here : https://discord.io/hmsunityplugin
Thank you and stay tuned!
