### ISSUE TITLE
[solved] IAP demo not working.

### ISSUE THREAD

**Issue by AndresCuicui** [EvilMindDevs/hms-unity-plugin#38]
[edit] After tinkering (a lot) with the demo scene we have managed to initiate a purchase, even tried the sandbox mode.
IAP demo still not working out of the box, tho. Needs some fixing. Also docs are outdated.

**Comment by jmercado86** [comment]
How was this solved? Please share. Thank you!

**Comment by AndresCuicui** [comment]
> How was this solved? Please share. Thank you!

Had to uncomment the contents of ShopItem.cs and ShopManager.cs files. Just select all and uncomment once (just once because there are some other functions that can still remain commented, SetNoAds and SetPremium that I'm not using). Then, changed the IapManager references to IapDemoManager inside ShopManager.cs and ShopItem.cs just to make it compile. So far it should at least compile.
In order to make the build, you have to set the correct reference to the scripts within the scene (they may be missing). The Shop prefab is the one with the ShopManager.cs and all the ProductN are the ones with the ShopItem.cs. Then you have to set the productID for each product (I just tried with one product) to the ones you set up in your huawei console.
And then you'll want to **debug the ProductInfoList and check it's not empty when calling the BuyProduct function** inside IapDemoManager.cs. I had to add some safety checks because it crashed without them.
In my case, the ProductInfoList didn't get populated after the first login at the Start function of the IapDemoManager.cs. I believe it was because the login failed and the LoadStore didn't get called or something. It required a manual Sign In button press to load the product data into the ProductInfoList.
Hope it helps.

**Comment by m0skit0** [comment]
I will reopen this because it is valuable information for us to fix the demos. Thanks a lot for the feedback!

**Comment by JariHuomo** [comment]
Would be great if someone would fix the IAP demo.

**Comment by starmindfr** [comment]
seem still broken, i see in red

ProductInfo productInfo = iapManager.GetProductInfo(productID);

inside Shopitem.cs as this method dont exist in IAPManager

**Comment by toycantando** [comment]
the demo still without working, for some reason the authentication manager is not called. and the iapManager still empty.

**Comment by starmindfr** [comment]
yes you have lots of extra works uncomenting samples codes and adding one controler script. so 90 % of code is in, the 10% is not difficult to get on tutorials try google. but it would be great to have it fixed here.

**Comment by AndresCuicui** [comment]
For those of you having trouble, all IapManager references should be changed to IapDemoManager (IapManager should not be used anymore on this demo).

**Comment by toycantando** [comment]
I update the project with the last unity.package, and the follow line of code inside the AccountManager.cs does not work:

authService = DefaultAuthService;

this is the error:

NullReferenceException: Object reference not set to an instance of an object
UnityEngine._AndroidJNIHelper.GetSignature (System.Object obj) (at /Users/builduser/buildslave/unity/build/Modules/AndroidJNI/AndroidJava.cs:1510)
UnityEngine._AndroidJNIHelper.GetSignature (System.Object[] args) (at /Users/builduser/buildslave/unity/build/Modules/AndroidJNI/AndroidJava.cs:1537)
UnityEngine._AndroidJNIHelper.GetConstructorID (System.IntPtr jclass, System.Object[] args) (at /Users/builduser/buildslave/unity/build/Modules/AndroidJNI/AndroidJava.cs:1343)
UnityEngine.AndroidJNIHelper.GetConstructorID (System.IntPtr jclass, System.Object[] args) (at /Users/builduser/buildslave/unity/build/Modules/AndroidJNI/AndroidJNI.bindings.cs:134)
UnityEngine.AndroidJavaObject._AndroidJavaObject (System.String className, System.Object[] args) (at /Users/builduser/buildslave/unity/build/Modules/AndroidJNI/AndroidJava.cs:356)
UnityEngine.AndroidJavaObject..ctor (System.String className, System.Object[] args) (at /Users/builduser/buildslave/unity/build/Modules/AndroidJNI/AndroidJava.cs:217)
HuaweiMobileServices.Utils.JavaObjectWrapper..ctor (System.String javaObjectCanonicalName, System.Object[] args) (at <48d7bb68e1d14c9893e6fd7c425224d3>:0)
HuaweiMobileServices.Id.Scope..ctor (System.String uri) (at <48d7bb68e1d14c9893e6fd7c425224d3>:0)
HuaweiMobileServices.Id.HuaweiIdAuthParams..cctor () (at <48d7bb68e1d14c9893e6fd7c425224d3>:0)
Rethrow as TypeInitializationException: The type initializer for 'HuaweiMobileServices.Id.HuaweiIdAuthParams' threw an exception.
HmsPlugin.AccountManager.OnEnable () (at Assets/Huawei/Scripts/Account/AccountManager.cs:36)
UnityEngine.GameObject:SetActive(Boolean)
MenuManager:ShowCurrencyShop() (at Assets/RaccoonRescue/Scripts/GUI/Menu/MenuManager.cs:96)
AnimationManager:BuyGems() (at Assets/RaccoonRescue/Scripts/GUI/AnimationManager.cs:218)
UnityEngine.EventSystems.EventSystem:Update() (at /Applications/Unity/Hub/Editor/2019.2.21f1/Unity.app/Contents/Resources/PackageManager/BuiltInPackages/com.unity.ugui/Runtime/EventSystem/EventSystem.cs:377)

**Comment by AndresCuicui** [comment]
According to the error message, it looks like there was an error during HuaweiMobileServices initialization.
`Rethrow as TypeInitializationException: The type initializer for 'HuaweiMobileServices.Id.HuaweiIdAuthParams' threw an exception.`
Therefore, DefaultAuthService was probably null and you get the null reference exception. I recomend checking wether the initialization was correct or not. Toss a try/catch surrounding the initialization, just to see what happened.

**Comment by sametguzeldev** [comment]
IAP Demo re-designed and it is working.
