### ISSUE TITLE
is this package  support other mobile those not have hms core

### ISSUE THREAD

**Issue by salman714** [EvilMindDevs/hms-unity-plugin#384]
i want to published games on other store like playstore, samsung, oppo, etc so my question is that how to show ads on those mobile which have hms core. i build many games and test on different mobiles but ads only shown on those mobile which have hms core. so what is the possible way to run ads on different mobile also different platform

**Comment by alihan98ersoy** [comment]
If the device has HMS core this plugin work without any changes. But if you want to show devices that don't have HMS core please refer to [Devices Without HMS Core Installed](https://evilminddevs.gitbook.io/hms-unity-plugin/kits-and-services/ads-kit/guides-and-references#devices-without-hms-core-installed).
