### ISSUE TITLE
How to resolve DuplicateTransaction purchase loop?

### ISSUE THREAD

**Issue by AntonPetrov83** [EvilMindDevs/hms-unity-plugin#386]
Hi!

If you kill an app at AppGallery's purchase confirmation screen then you will have you purchase completed but not consumed.

On the next session trying to initiate the same purchase will fail with `PurchaseFailureReason.DuplicateTransaction`.

If I try to `IStoreController.ConfirmPendingPurchase` then Unity throws an error:

```
Unity Unity IAP: Unable to confirm purchase; Product has missing or empty transactionID
```

Thus it is impossible to consume a purchase.

UPDATE:

I see the difference with how HuawaiStore behaves compared to standard Unity stores:
1. Standard Unity stores usually invoke ProcessPurchase callback if there is pending purchase on start. This is not implemented in HuaweiStore.
2. Standard Unity stores resolve failed transactions on their own. HuaweiStore gets stuck with DuplicateTransaction error instead.

Huawei documentation says it is a mandatory to implement a redelivery process for consumables: https://developer.huawei.com/consumer/en/doc/development/HMSCore-Guides/redelivering-consumables-0000001051356573

It looks like HuaweiStore does not implement this.

**Comment by bunyamineymen** [comment]
Hi,
You should check for non-consumed product at the every beginning of application.If there is a product non-consumed you should consume this product.
Also you can refer https://github.com/EvilMindDevs/hms-unity-plugin/issues/324#issuecomment-1141244938.

**Comment by AntonPetrov83** [comment]
@bunyamineymen I am using `HuaweiStore` class which implements custom `IStore` and not `HMSIAPManager` directly. This is very convinient implementation but looks like it has some issues.

**Comment by bunyamineymen** [comment]
@AntonPetrov83 
I am going to create demo about it then send you as .unitypackage.
Preparing demo has already been in our roadmap.This demo is going to be in next release.

**Comment by AntonPetrov83** [comment]
@bunyamineymen I noticed that owned purchases are not reported to the Uniy, method `HuaweiStore.LoadOwnedConsumables` is not called. And `IStoreCallback.OnAllPurchasesRetrieved` is not called as well.

When I tried to implement it myself I faced a limitation. Created a thread about that: https://forum.unity.com/threads/it-is-not-possible-to-implement-onallpurchasesretrieved-callback-in-a-third-party-store-properly.1368273/

**Comment by AntonPetrov83** [comment]
I did managed to resolve the issue by first calling `HuaweiStore.LoadOwnedConsumables` and only then `HuaweiStore.LoadComsumableProducts`. 

Then `HuaweiStore.ProductsLoaded` creates `ProductDescriptions` with a receipt and transactionId attached. Then Unity invokes `ProcessPurchase` callback for products already owned so owned products get consumed.
