### ISSUE TITLE
IapManager : no PurchaseResultInfo inside OnConsumePurchaseSuccess. 

### ISSUE THREAD

**Issue by Deroido** [EvilMindDevs/hms-unity-plugin#39]
A correct moment for reward extradition in only after Successful Consume.
Right now in IapManager there's no way to verify which product was consumed inside **OnConsumePurchaseSuccess**.

There's a need to add **PurchaseResultInfo** inside **OnConsumePurchaseSuccess**. Or at least add <**string productID**> inside of it.
Now it's impossible to know how to reward after **iapManager.ConsumeOwnedPurchases**();

here's a demo example
![image](https://user-images.githubusercontent.com/201954/86278351-6fcec600-bc02-11ea-91cd-5d5fc4682f99.png)
but no usage of **OnConsumePurchaseSuccess** at all!

Do you suggest rewarding the user during a successful purchase without waiting for consummation ? That does look totally broken. Also in this situation **iapManager.ConsumeOwnedPurchases()** does nothing.

I would be able to consume every 'stuck/frozen' inapp inside **iapManager.OnObtainOwnedPurchasesSuccess**, but this returns only empty lists. (doesn't work at all).

So we need any clarification about product itself inside **OnConsumePurchaseSuccess** or working **OnObtainOwnedPurchasesSuccess** to be able to build a reliable store.

**Comment by Deroido** [comment]
This may be a nice addition, but actually if the store works in "one-puechase-one-callback" mode, it's possible to tune everything fine,
I just block any new purchases until Successful or Failed consumption received. In that case I will know which product to consume, because it's certain.  

@EvilMindDevs you may comment or close this as you wish.

**Comment by m0skit0** [comment]
@Deroido thanks a lot for the feedback. We will look into it and let you know.
