### ISSUE TITLE
HMS Analytic & give me  refence null when i  start the game And make a build it give me Gradle failed....

### ISSUE THREAD

**Issue by usamaManzoor622** [EvilMindDevs/hms-unity-plugin#392]
!)
NullReferenceException: Object reference not set to an instance of an object
UnityEditor.Scripting.ScriptCompilation.CSharpNamespaceParser.FindNamespaceForMono (System.String className, System.String source) (at C:/buildslave/unity/build/Editor/Mono/Scripting/ScriptCompilation/CSharpNamespaceParser.cs:83)
UnityEditor.Scripting.ScriptCompilation.CSharpNamespaceParser.GetNamespace (System.String sourceCode, System.String className, System.String[] defines) (at C:/buildslave/unity/build/Editor/Mono/Scripting/ScriptCompilation/CSharpNamespaceParser.cs:49)
Rethrow as IllegalNamespaceParsing: Searching for classname: 'HMSIAPSettingsDrawer' caused error in CSharpNameParser
UnityEditor.Scripting.ScriptCompilation.CSharpNamespaceParser.GetNamespace (System.String sourceCode, System.String className, System.String[] defines) (at C:/buildslave/unity/build/Editor/Mono/Scripting/ScriptCompilation/CSharpNamespaceParser.cs:53)
UnityEditor.Scripting.Compilers.CSharpLanguage.GetNamespaceNewRuntime (System.String filePath, System.String definedSymbols, System.String[] defines) (at C:/buildslave/unity/build/Editor/Mono/Scripting/Compilers/CSharpLanguage.cs:90)
UnityEditor.Scripting.Compilers.CSharpLanguage.GetNamespace (System.String filePath, System.String definedSymbols) (at C:/buildslave/unity/build/Editor/Mono/Scripting/Compilers/CSharpLanguage.cs:133)
UnityEditor.Scripting.ScriptCompilers.GetNamespace (System.String file, System.String definedSymbols) (at C:/buildslave/unity/build/Editor/Mono/Scripting/ScriptCompilers.cs:112)
2) Unable to parse file Assets/Huawei/Demos/Analytics/AnalyticsDemo.unity.meta: [could not find expected ':'] at line 2
3) before import your package Build make successfully for Android platform, and then import your HMS v2.2.8_2018 Gradle build faild
Please fix it soon this error came in unity 2018

**Comment by alihan98ersoy** [comment]
Hi, We will fix with new version. .Meta files was causing problem. But 
3) before import your package Build make successfully for Android platform, and then import your HMS v2.2.8_2018 Gradle build faild

can you share the problem with us? And which kits and services are you using?

**Comment by alihan98ersoy** [comment]
We have launched the new version for 2018. We fixed the metafiles for bugs in the console.
