### ISSUE TITLE
Crash with "JNI ERROR (app bug): global reference table overflow global reference table dump" due to plugin not Disposing AndroidJavaObjects 

### ISSUE THREAD

**Issue by PetrBodnar** [EvilMindDevs/hms-unity-plugin#398]
We encountered this crash when we increased number of inapps in our app.

Looks like HMS Unity plugin doesnt call Dispose on AndroidJavaObjects.
This leads to exceeding JNI global refs limit.
As mentioned in Unity docs, AndroidJavaObjects need to be disposed.

We fixed this by adding caching of product ids of our inapps on our side (before that we call ProductInfo.ProductId every time we need product Id)
Now we call ProductInfo.ProductId once for each inapp, and issue is gone.
But potentially we can encounter it again, if number of AndroidJavaObject will increase.

Unity 2021.3.14f1, platform Android, HMS Unity Plugin 2.2.7

**Comment by bunyamineymen** [comment]
Hi,
We have just released the new version, can you try the new release for this state ?
