### ISSUE TITLE
Is this project different from official Unity Assets?

### ISSUE THREAD

**Issue by msalihkarakasli** [EvilMindDevs/hms-unity-plugin#4]
Hi guys,

First of all thanks for your valuable contribution to the HMS ecosystem. I used old version of the plugin so many times. I just wonder that Unity Tech. also published **Huawei AppGallery Game Services** on their asset store and as I know they will publish assets also for other services but I am not sure. Do you know any detail about this? Is this project team and project totally different, right?

And if it is possible, I really would like to contribute to this project as a member. Could you please share some contribution guide or communication information in README. 

Thanks again.

**Comment by EvilMindDevs** [comment]
Hi M,

This is an independent iniciative from developers to developers, we don't have any connection with Unity Tech. So we can't give you any details abouth the other initiative.

Sure, happy to have onboard anyone that wishes to contibute to the project. Right now, the best way to collaborate will be to help us test the solution. Later we can organize so we can make this project bigger and better.

**Comment by EvilMindDevs** [comment]
Closed due to inactivity
