### ISSUE TITLE
Login with Huawei ID thows exception 

### ISSUE THREAD

**Issue by flashmandv** [EvilMindDevs/hms-unity-plugin#417]
Hello,

So since I updated our HMS SDK to the latest version 2.3.2, logging in with huawei id is throwing this exception:
```
AndroidJavaException: java.lang.ClassNotFoundException: com.huawei.agconnect.auth.HwIdAuthProvider
    java.lang.ClassNotFoundException: com.huawei.agconnect.auth.HwIdAuthProvider
        at java.lang.Class.classForName(Native Method)
        at
```
The sign in succeeds but on the success handler I have this code, which in runtime fails to find  `HwIdAuthProvider` class:
`private void OnAccountKitLoginSuccess(AuthAccount authHuaweiId)
    {
        AGConnectAuthCredential credential = HwIdAuthProvider.CredentialWithToken(authHuaweiId.AccessToken);
        authServiceManager.SignIn(credential);
    }`

The HuaweiMobileServices.dll file is in the Assets/Huawei/Dlls/ folder..which is ok.
Am I missing some gradle dependencies ?

I have these:
```
implementation 'com.huawei.hms:base:6.6.0.300'
implementation 'com.huawei.agconnect:agconnect-core:1.6.5.300'
implementation 'com.huawei.hms:hmscoreinstaller:6.6.0.300'
```

I'm using Unity 2020.3.43
Any ideas?
Thanks

**Comment by flashmandv** [comment]
Ok, I've fixed the issue by adding these lines to my mainTemplate.gradle and launcherTemplate.gradle:
```
implementation 'com.huawei.agconnect:agconnect-apms:1.6.1.300'
implementation 'com.huawei.agconnect:agconnect-auth:1.6.1.300'
```
does anybody know why are these not added with the hmsMainTemplate.gradle auto generated files?

**Comment by alihan98ersoy** [comment]
Hello,
If you are using our plugin you can add these lines by enabling Accountkit and Auth Service from [HMS kit settings](https://evilminddevs.gitbook.io/hms-unity-plugin/getting-started/quick-start/connect-your-game-with-the-hms-kit-managers).
![image](https://user-images.githubusercontent.com/39373386/234482706-33ffc84d-cd28-4cd4-bb67-a17a73dbc3bc.png)

**Comment by flashmandv** [comment]
Thank you. I was missing the Auth Service checkbox.
Could you please check my other issue with the Ads? I have the Ads Kit checked but ads are not loading [](https://github.com/EvilMindDevs/hms-unity-plugin/issues/418)
