### ISSUE TITLE
Nothing happens after Pressing BuyProduct

### ISSUE THREAD

**Issue by jmercado86** [EvilMindDevs/hms-unity-plugin#42]
I looked at the products list, there seems to be no issues at all.
But after pressing the BuyProduct button for each product, nothing happens.

I traced it and found out that this line under IapManager.cs is not doing anything.

ITask<PurchaseIntentResult> task = iapClient.CreatePurchaseIntent(purchaseIntentReq);

Sorry, am I missing something that I should put in the scene as well?

**Comment by msalihkarakasli** [comment]
I faced a similar issue;

I can retrieve all products there is no issue. But when I triggered BuyProduct function like below;

```
public void Buy(ProductLineComp productLineComp)
        {
            var product = productLineComp.GetProduct();
            
            PurchaseIntentReq purchaseIntentReq = new PurchaseIntentReq
            {
                PriceType = 0,
                ProductId = product.id,
                DeveloperPayload = "dev"
            };
            
            ITask<PurchaseIntentResult> task = _iapClient.CreatePurchaseIntent(purchaseIntentReq);
                
            task.AddOnSuccessListener((intentResult)=>
            {
                if (intentResult != null)
                {
                    Debug.Log("[HMSPlugin]:" + intentResult.ErrMsg + intentResult.ReturnCode.ToString());
                    Debug.Log("[HMSPlugin]: Bought " + purchaseIntentReq.ProductId);
                    Status status = intentResult.Status;
                    status.StartResolutionForResult((androidIntent) =>
                    {
                        PurchaseResultInfo purchaseResultInfo = _iapClient.ParsePurchaseResultInfoFromIntent(androidIntent);

                        Debug.Log("HMSPluginResult: " + purchaseResultInfo.ReturnCode);
                        Debug.Log("HMErrorMssg: " + purchaseResultInfo.ErrMsg);
                        Debug.Log("HMS: HMSInAppPurchaseData" + purchaseResultInfo.InAppPurchaseData);
                        Debug.Log("HMS: HMSInAppDataSignature" + purchaseResultInfo.InAppDataSignature);

                        switch (purchaseResultInfo.ReturnCode)
                        {
                            case OrderStatusCode.ORDER_STATE_SUCCESS:
                                _listener.OnPurchaseSuccess(product.id);
                                break;
                            default:
                                Debug.Log("[HMSPlugin]:startIntent ERROR");
                                break;
                        }

                    }, (exception) =>
                    {
                        Debug.Log("[HMSPlugin]:startIntent ERROR");
                    });

                }
            });
                
            task.AddOnFailureListener((exception) =>
            {
                Debug.Log("[HMSPlugin]:startIntent ERROR: " + exception.Message);
            });
        }
```

It throws an exception;

> 07-06 20:13:44.753: E/Unity(27131): MissingMethodException: Constructor on type 'HuaweiMobileServices.IAP.PurchaseIntentResult' not found.
> 07-06 20:13:44.753: E/Unity(27131):   at System.RuntimeType.CreateInstanceImpl (System.Reflection.BindingFlags bindingAttr, System.Reflection.Binder binder, System.Object[] args, System.Globalization.CultureInfo culture, System.Object[] activationAttributes, System.Threading.StackCrawlMark& stackMark) [0x00000] in <00000000000000000000000000000000>:0 
> 07-06 20:13:44.753: E/Unity(27131):   at System.Activator.CreateInstance (System.Type type, System.Reflection.BindingFlags bindingAttr, System.Reflection.Binder binder, System.Object[] args, System.Globalization.CultureInfo culture, System.Object[] activationAttributes) [0x00000] in <00000000000000000000000000000000>:0 
> 07-06 20:13:44.753: E/Unity(27131):   at HuaweiMobileServices.Utils.AndroidJavaObjectExtensions.AsWrapper[T] (UnityEngine.AndroidJavaObject javaObject) [0x00000] in <00000000000000000000000000000000>:0 
> 07-06 20:13:44.753: E/Unity(27131):   at System.Func`2[T,TResult].Invoke (T arg) [0x00000] in <00000000000000000000000000000000>:0 
> 07-06 20:13:44.753: E/Unity(27131):   at HuaweiMobileServices.Base.OnSuccessListenerConve
> 07-06 20:13:45.270: E/hms_pay(8474): StateCoupon    coupons parseJsonObject jsonObject returnCode is not success.

My Unity Version is: 2019.3.6f1
HMS Unity Plugin Version is v1.1.2

**Comment by jmercado86** [comment]
After using the latest version. I managed to make it work, I get all the respective events I needed while doing a purchase and after a purchase.

**Comment by CavinChang** [comment]
HMS version 1.1.2
Unity 2019.3.15f1
Having same issue when buyProduct MissingMethodException:Constructor on type 'HuaweiMobileServices.IAP.PurchaseIntentResult' not found 

2020/07/23 11:04:45.727 9463 9463 Error Unity MissingMethodException: Constructor on type 'HuaweiMobileServices.IAP.PurchaseIntentResult' not found as above

**Comment by EwgenijGolowko** [comment]
![tempsnip](https://user-images.githubusercontent.com/61007371/88261066-44ee0400-ccce-11ea-8817-2064b2a16d8b.png)
all purchases from the developer console are initialized, but when you click on the buy button, the purchase window does not appear, iapClient.CreatePurchaseIntent (purchaseIntentReq) -> does not work

**Comment by EwgenijGolowko** [comment]
HMS version 1.1.2
Unity 2019.2.14f1

**Comment by robroy07** [comment]
We are having the same issue. Inside IapManager.cs, when we call: 
`ITask<PurchaseIntentResult> task = iapClient.CreatePurchaseIntent(purchaseIntentReq);`

 we get the following error in logcat:
`07-24 11:30:06.332 16567 16567 E Unity   : MissingMethodException: Constructor on type 'HuaweiMobileServices.IAP.PurchaseIntentResult' not found.
07-24 11:30:06.332 16567 16567 E Unity   :   at System.RuntimeType.CreateInstanceImpl (System.Reflection.BindingFlags bindingAttr, System.Reflection.Binder binder, System.Object[] args, System.Globalization.CultureInfo culture, System.Object[] activationAttributes, System.Threading.StackCrawlMark& stackMark) [0x00000] in <00000000000000000000000000000000>:0 
07-24 11:30:06.332 16567 16567 E Unity   :   at System.Activator.CreateInstance (System.Type type, System.Reflection.BindingFlags bindingAttr, System.Reflection.Binder binder, System.Object[] args, System.Globalization.CultureInfo culture, System.Object[] activationAttributes) [0x00000] in <00000000000000000000000000000000>:0 
07-24 11:30:06.332 16567 16567 E Unity   :   at HuaweiMobileServices.Utils.AndroidJavaObjectExtensions.AsWrapper[T] (UnityEngine.AndroidJavaObject javaObject) [0x00000] in <00000000000000000000000000000000>:0 
07-24 11:30:06.332 16567 16567 E Unity   :   at System.Func`2[T,TResult].Invoke (T arg) [0x00000] in <00000000000000000000000000000000>:0 
07-24 11:30:06.332 16567 16567 E Unity   :   at HuaweiMobileServices.Base.OnSuccessListenerConve`

HMS version 1.1.2
Unity 2019.3.14f1

**Comment by m0skit0** [comment]
Thanks @robroy07 , we will update the plugin with the correct DLL asap.

**Comment by m0skit0** [comment]
Updated latest SDK DLL in commit aea9a7218dcc929d9434560ebe7ecae717d50563
