### ISSUE TITLE
Build failure:Plugin with id 'com.huawei.agconnect' not found.

### ISSUE THREAD

**Issue by koal2** [EvilMindDevs/hms-unity-plugin#426]
Hi! I am use Unity2022 to build apk, but I'm get Build failure:Plugin with id 'com.huawei.agconnect' not found. Below is details:
ArgumentException: Version string portion was too short or too long.
Parameter name: input

 "assembleRelease"

Environment Variables:
SSH_AUTH_SOCK = /private/tmp/com.apple.launchd.1rfr6eQC2W/Listeners
BURST_ANDROID_MIN_API_LEVEL = 22
XPC_FLAGS = 0x0
JAVA_TOOL_OPTIONS = -Dfile.encoding=UTF-8
PATH = /Users/kz/Library/Android/sdk/tools:/Users/kz/Library/Android/sdk/tools/bin:/Users/kz/Library/Android/sdk/platform-tools:/opt/homebrew/opt/ruby/bin:/opt/homebrew/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:/Users/kz/.dotnet/tools:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/kz/.rvm/bin

LaunchInstanceID = C73DDF3A-27CC-4771-A298-23C58E4AAAA6
SECURITYSESSIONID = 186b2
TMPDIR = /var/folders/cq/fw4ybxnx1j70z_dx6gz17r8c0000gn/T/
SHELL = /bin/zsh
HOME = /Users/kz
__CFBundleIdentifier = com.unity3d.unityhub
XPC_SERVICE_NAME = application.com.unity3d.unityhub.544468.545251
__CF_USER_TEXT_ENCODING = 0x1F5:0x19:0x34
LOGNAME = kz
ORIGINAL_XDG_CURRENT_DESKTOP = undefined
JAVA_HOME = /Applications/Unity/Hub/Editor/2022.3.0f1/PlaybackEngines/AndroidPlayer/OpenJDK
ANDROID_NDK_ROOT = /Applications/Unity/Hub/Editor/2022.3.0f1/PlaybackEngines/AndroidPlayer/NDK
USER = kz
COMMAND_MODE = unix2003

stderr[
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8

FAILURE: Build failed with an exception.

* Where:
Script '/Users/kz/tank_client/Library/Bee/Android/Prj/IL2CPP/Gradle/unityLibrary/hmsMainTemplate.gradle' line: 1

* What went wrong:
A problem occurred evaluating script.
> Plugin with id 'com.huawei.agconnect' not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
]
stdout[

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.2/userguide/command_line_interface.html#sec:command_line_warnings
]
exit code: 1

Please help me!

**Comment by alihan98ersoy** [comment]
Hi, Can you share the following details with me?
* Which Unity version are you using? 
* And which kit and services did you enable from the KitSettings panel?

**Comment by koal2** [comment]
Yes, here is screenshot
![33a8f977916059ad2f004a42096f75ba](https://github.com/EvilMindDevs/hms-unity-plugin/assets/23449067/d165d227-80dc-44f8-8cfd-46864bffd692)

![fc45b9e90131c81ab0ada9bbfccbd628](https://github.com/EvilMindDevs/hms-unity-plugin/assets/23449067/0ca31be4-a506-4699-adb8-62a586e0852e)

**Comment by koal2** [comment]
![image](https://github.com/EvilMindDevs/hms-unity-plugin/assets/23449067/fe312cf4-69d5-4f98-a615-06821a6efea4)

**Comment by koal2** [comment]
Do you need any other information?

**Comment by alihan98ersoy** [comment]
No need for further information at the moment. I am trying to catch the same issue. If needed I will let you know. Thank you

**Comment by alihan98ersoy** [comment]
There is a bug related to specific Unity and Gradle versions. You could try to lower your Gradle version to 5.4.1 until we release the fix.
![image](https://github.com/EvilMindDevs/hms-unity-plugin/assets/39373386/ef3bf1e2-7a16-4c5d-b97c-65ae815dc848)

**Comment by koal2** [comment]
Thank you.

**Comment by koal2** [comment]
I am using gradle5.4.1 get another error.

![FKI `6H7A 6 {PCC(A}$AV](https://github.com/EvilMindDevs/hms-unity-plugin/assets/23449067/75c0df40-d5b8-4906-826c-fb656818e31b)

**Comment by alihan98ersoy** [comment]
I am working on this issue. 
![image](https://github.com/EvilMindDevs/hms-unity-plugin/assets/39373386/4566a2bf-e009-4581-99d8-867155bcc449)

**Comment by alihan98ersoy** [comment]
Hi, 
I just committed the fix #428. We will release a fix with the new version. If this problem is urgent you can fix it manually before release with the new [HMSGradleFixer.cs](https://github.com/EvilMindDevs/hms-unity-plugin/blob/master/Assets/Huawei/Editor/Utils/HMSGradleFixer.cs)

**Comment by koal2** [comment]
Thank you very much!
