### ISSUE TITLE
hms ads

### ISSUE THREAD

**Issue by salman714** [EvilMindDevs/hms-unity-plugin#427]
hello i want to use hms ads on other mobile platform and i faced problem that the ads are only shown on that mobile that have hms core so my questions is that is there is any way to show ads on all mobile platform with out the support of hms core if yes then how i m using unity 2018 & 2019

**Comment by alihan98ersoy** [comment]
Hello, 
you need to use AdsPrime SDK instead of AdsLite SDK. 
You can refer to "[Devices Without HMS Core Installed](https://evilminddevs.gitbook.io/hms-unity-plugin_/kits-and-services/ads-kit/guides-and-references#devices-without-hms-core-installed)".

**Comment by salman714** [comment]
Can you give me the link from where i download the exact sdk for unity 2019

**Comment by alihan98ersoy** [comment]
You can use this plugin and download [the latest version](https://github.com/EvilMindDevs/hms-unity-plugin/releases/tag/v2.3.3-2019-2022). But you need to make modifications in [HMSGradleWorker.cs](https://github.com/EvilMindDevs/hms-unity-plugin/blob/769542663ecae7c6f3ab305be275f94dfc2bdab7/Assets/Huawei/Editor/Utils/HMSGradleWorker.cs#L27C1-L27C32). For modification you can follow this [part](https://evilminddevs.gitbook.io/hms-unity-plugin_/kits-and-services/ads-kit/guides-and-references#devices-without-hms-core-installed).
