### ISSUE TITLE
Problems with Rewarded Ads

### ISSUE THREAD

**Issue by EtsaiDev** [EvilMindDevs/hms-unity-plugin#43]
Hi,
When tested my app with test ad IDs, both interstitials and Rewarded ads worked correctly. So, just removed test IDs and added mine and launched the app, with no more changes. Interstitials work fine, but nothing happened when pressed the button to show a rewarded Ad. My system enables this button if a Rewarded ad is loaded (info from RewardedAdManager included in this plugin), otherwise remains disabled and not interactable. No errors in logcat.

Unity version: 2019.4.0f1
Plugin version (package or commit): I don't know. App was upladed on June 29th, plugin was downloaded that day.
Mono or IL2CPP: IL2CPP
Test device model: Huawei P40 Lite

**Comment by m0skit0** [comment]
Did you check what error code you get when loading the ad? Maybe there are no ads on the server, other people encountered this issue before.

**Comment by ImP4KTer** [comment]
Hello EtsaiDev. How did you implemented the interstitial? Does you followed a documentation. I tried to implement the interstitial, but without success ( even the test one does't work ). Please if you have time, help me at xsasoftware@gmail.com

**Comment by EtsaiDev** [comment]
> Did you check what error code you get when loading the ad? Maybe there are no ads on the server, other people encountered this issue before.

The rewarded loads correctly, but instead of showing it OnRewardAdFailedToShow is called with a value of 2.

**Comment by EtsaiDev** [comment]
> Hello EtsaiDev. How did you implemented the interstitial? Does you followed a documentation. I tried to implement the interstitial, but without success ( even the test one does't work ). Please if you have time, help me at [xsasoftware@gmail.com](mailto:xsasoftware@gmail.com)

I've just included Interstitial and rewarded managers and follow the instructions. Basically the same way AdDemo is implemented.

**Comment by EtsaiDev** [comment]
@m0skit0 error code 2 is Network problem. Is this a porblem I can fix from my side?

**Comment by m0skit0** [comment]
> @m0skit0 error code 2 is Network problem. Is this a porblem I can fix from my side?

Please make sure you're not behind a proxy or firewall that might be blocking access to the ads server.

**Comment by EtsaiDev** [comment]
I actually have not problems with interstitials. And about firewall and proxies, i'm not using them.

**Comment by m0skit0** [comment]
So the ad is loaded but does not show? Can you please share your code?

**Comment by EtsaiDev** [comment]
hi,
Find 3 files attached: Ads.cs, a kind of "interface" to centralize my Ads system, and a slightly modified RewardedAdmanager and InterstitialAdManager from this plugin.

[Ads.zip](https://github.com/EvilMindDevs/hms-unity-plugin/files/4924486/Ads.zip)

**Comment by EtsaiDev** [comment]
Ok, reviewing my code I see that I was making too many ad requests (both my wrapper and HMS plugin manager were requesting ads). I uploaded a new version and it seems to work. But all ads seems to be test ads, always adevertising Huawei devices and the AppGallery itself. Is HMS serving test ads when are not real available ads?

**Comment by m0skit0** [comment]
Sorry, why would Huawei products ads not be real ads?
