### ISSUE TITLE
NullReferenceException: Failed to load the HMSIAPKitSettings. Please restart Unity Editor

### ISSUE THREAD

**Issue by SteliosDaVitzi** [EvilMindDevs/hms-unity-plugin#436]
Almost every time I'm building the project, this message is shown in the adb logcat while running in the mobile device. In some cases it ignores it, but I haven't been able to find the steps to reproduce it. 

The whole error log

NullReferenceException: Failed to load the HMSIAPKitSettings. Please restart Unity Editor
09-21 16:09:48.787  9168  9218 E Unity   :   at HmsPlugin.HMSIAPKitSettings..ctor () [0x00000] in <00000000000000000000000000000000>:0
09-21 16:09:48.787  9168  9218 E Unity   :   at System.Reflection.RuntimeConstructorInfo.InternalInvoke (System.Object obj, System.Object[] parameters, System.Boolean wrapExceptions) [0x00000] in <00000000000000000000000000000000>:0
09-21 16:09:48.787  9168  9218 E Unity   :   at System.Activator.CreateInstance[T] () [0x00000] in <00000000000000000000000000000000>:0
09-21 16:09:48.787  9168  9218 E Unity   :   at HMSEditorSingleton`1[T].get_Instance () [0x00000] in <00000000000000000000000000000000>:0
09-21 16:09:48.787  9168  9218 E Unity   :   at HmsPlugin.HMSIAPManager.InitControlOfIAP () [0x00000] in <00000000000000000000000000000000>:0
09-21 16:09:48.787  9168  9218 E Unity   :   at HuaweiMobileServices.Utils.HMSDispatcher.InvokeAsync (System.Action action) [0x00000] in <00000000000000000000000000000000>:0
09-21 16:09:48.787  9168  9218 E Unity   :   at System.Reflection.RuntimeConstructorInfo.InternalInvoke (System.Object obj, System.Object[] parameters, System.Boolean wrapExceptions) [0x00000] in <00000000000000000000000000000000>:0
09-21 16:09:48.787  9168  9218 E Unity   :   at System.Activator.CreateInstance

**Comment by alihan98ersoy** [comment]
Hi,
You can try to delete all settings files in the resources folder and then restart Unity. This will recreate the settings files and fix the issue. (Assets/Huawei/Settings/Resources)

**Comment by SteliosDaVitzi** [comment]
Hi, this would require manual setup of the settings again, right? Right now we have a semi-automatic building process and this issue prevent it from executing correctly. Is there another workaround maybe?

**Comment by SteliosDaVitzi** [comment]
@alihan98ersoy I did the workaround you suggested, and now the above error appears in the unity editor when I'm trying to ope Huawei -> Kit Settings, resulting in an empty window. 

Thanks for your time :)

**Comment by alihan98ersoy** [comment]
This error occurs when there is already a settings file in the plugin. Maybe because these files were created in another version, it does not recognize them and tries to create new files, but since they have the same name, it causes problems. If you delete the settings files, the Kit Settings panel will be empty. If you restart Unity, the plugin itself will create the settings files again. And after that, the kit settings panel appears normal. (Manual build)

But We did not test with automatic building so if the problem still exists after this solution. I can work on the problem to create a fix in the new version.

**Comment by alihan98ersoy** [comment]
This should be happening just for once. When you apply this solution it shouldn't be happening again. But automation can be different.
