### ISSUE TITLE
ADS Not Working in HMS 2.3.4 Unity

### ISSUE THREAD

**Issue by HamailAsif** [EvilMindDevs/hms-unity-plugin#438]
I am Using Unity 2020.3.39f1 and tested both Huawei and non-Huawei Devices (With HMS Cored Installed) but i am getting following error and no ads are not showing

2023-10-02 11:36:13.723 28634-28653/? E/Unity: [HMS] HMSAdsKitManager Interstitial Ad Still Not Loaded Yet!
2023-10-02 11:36:24.200 28634-28653/? E/Unity: [HMS] HMSAdsKitManager BannerAdLoadFailed. Error Code: 0
    HmsPlugin.HMSAdsKitManager:BannerAdStatusListener_mOnAdFailed(Object, AdLoadErrorCodeEventArgs)
    System.EventHandler`1:Invoke(Object, TEventArgs)
    System.Action:Invoke()
    HuaweiMobileServices.Utils.HMSDispatcher:Update()

**Comment by alihan98ersoy** [comment]
Hi may I get the full logs? Reason should be written in the logs before these logs.

**Comment by HamailAsif** [comment]
Check out the Complete Log Files.
[LogFile.txt](https://github.com/EvilMindDevs/hms-unity-plugin/files/12780698/LogFile.txt)

**Comment by alihan98ersoy** [comment]
This solution may help ,you can refer to [FAQ](https://evilminddevs.gitbook.io/hms-unity-plugin_/support/faq#why-i-am-getting-0-inner-error-while-using-a-ds-kit)

**Comment by HamailAsif** [comment]
Integration All things was ok but there was no sim in the device I was testing my app So Device with Sim My Ads working now.

**Comment by HamailAsif** [comment]
Integration All things was ok but there was no sim in the device I was testing my app So Device with Sim My Ads working now.
