### ISSUE TITLE
productInfo is null error code: 60001

### ISSUE THREAD

**Issue by gmYusuf** [EvilMindDevs/hms-unity-plugin#44]
I am using IAP demo directly. When I try to click product its failure. 
Root problem, "productInfo" is null.

"2020-07-09 15:37:51.020 30503-30503/? I/Unity: [HMSPlugin]: IAP ObtainProductInfo failed. Exception of type 'HuaweiMobileServices.Utils.HMSException' was thrown. :: 60001: param error"

![image](https://user-images.githubusercontent.com/8115505/87040752-d9019b00-c1f9-11ea-9e0b-bf688ca4214b.png)
After clicking buy buton.
![image](https://user-images.githubusercontent.com/8115505/87041089-5fb67800-c1fa-11ea-9b4b-312b00b7da7f.png)

I am using Unity 2019.4 and lates plugin repo

**Comment by TheHeksiii** [comment]
> Thx, ist work

Hey, do you mind zipping your project-ofcourse without any app IDs and secret strings, and uploading it? If you got purchasing working, it would help us so much. Thanks
