### ISSUE TITLE
Developer payload cannot be passed thru PurchaseProduct method

### ISSUE THREAD

**Issue by am1goo** [EvilMindDevs/hms-unity-plugin#448]
We need to use `developer payload` as `string`, but in 2.3.4 version it is not possible.

**Comment by alihan98ersoy** [comment]
Hi, did you check API? https://developer.huawei.com/consumer/en/doc/HMSCore-References/api-order-verify-purchase-token-0000001050746113

**Comment by am1goo** [comment]
Yes, why?
I have fix for that (and it is works very well!), but also it is modification of third-party code.
![image](https://github.com/EvilMindDevs/hms-unity-plugin/assets/5287406/cbb4814f-bdb2-47ea-9933-b9ae7c973f6a)

**Comment by am1goo** [comment]
https://github.com/EvilMindDevs/hms-unity-plugin/pull/450

**Comment by alihan98ersoy** [comment]
Thank you for your advice and support we will consider and test it.

**Comment by alihan98ersoy** [comment]
Hello again, We added a new callback named OnBuyProductFailurePurchaseResultInfo to return PurchaseResultInfo on purchase failure. We will include your PR in the new version. Thank you for your advice
