### ISSUE TITLE
Consumption of purchases in InitializeIAP should be optional

### ISSUE THREAD

**Issue by am1goo** [EvilMindDevs/hms-unity-plugin#449]
I have the different way to work with non-consume items.
And now I need to ignore invoking `ConsumeControl` method by `HMSIAPKitSettings` and constant `ConsumptionOwnedItemsOnInitialize`

**Comment by alihan98ersoy** [comment]
Hi, for now, you can comment on the consume part. We will consider your request.
![resim](https://github.com/EvilMindDevs/hms-unity-plugin/assets/39373386/63aefb2f-7a4b-44a7-a3ae-d2898ded972d)

**Comment by am1goo** [comment]
Yes, I know that and do it.
But actually, it is injection in third-party code, not so stable to future changes.
![image](https://github.com/EvilMindDevs/hms-unity-plugin/assets/5287406/03674207-f135-497c-b7eb-0842687dfef6)

**Comment by am1goo** [comment]
all changes provided in https://github.com/EvilMindDevs/hms-unity-plugin/pull/451

**Comment by alihan98ersoy** [comment]
Hello, Consume toggle was added to control consumption owned items onInitialize. 
![resim](https://github.com/EvilMindDevs/hms-unity-plugin/assets/39373386/973842dd-937b-42e4-a037-0bb53f7c2bc8)
