### ISSUE TITLE
MissingMethodException: Constructor on type 'HuaweiMobileServices.Id.HuaweiIdAuthService' not found

### ISSUE THREAD

**Issue by anhdung31793** [EvilMindDevs/hms-unity-plugin#45]
Hi,
When I ran my app, I got this log:
MissingMethodException: Constructor on type 'HuaweiMobileServices.Id.HuaweiIdAuthService' not found
I'm using Unity 2018.4 and HMS.Unity.Plugin.for.2018.v1.1.1
Please check it for me. Thanks!

**Comment by m0skit0** [comment]
This has been fixed but not released yet

**Comment by m0skit0** [comment]
Please download the plugin directly from the repo instead of using the packaged one.

**Comment by qbit86** [comment]
> Please download the plugin directly from the repo instead of using the packaged one.

@m0skit0 Could you please clarify exactly which files should we download for Unity 2018 to work around this issue?

@anhdung31793 Do you have any success in handling this bug?
