### ISSUE TITLE
3.2.5 Version on 2020 Unity version is not compling

### ISSUE THREAD

**Issue by wththd** [EvilMindDevs/hms-unity-plugin#455]
According to this [doc](https://docs.unity3d.com/2021.3/Documentation/Manual/CSharpCompiler.html) versions below 2021.3 does not support C#9 features. But in class `HMSKeyToolWindow` there is 
`#if UNITY_2019_3_OR_NEWER
            if (evt is { type: EventType.DragPerform or EventType.DragUpdated })` 
 define, which is not compiling on 2020 version. Edit this define to `#if UNITY_2021_3_OR_NEWER` please

**Comment by alihan98ersoy** [comment]
Hi, Which unity 2020 version I will test

**Comment by wththd** [comment]
> Hi, Which unity 2020 version I will test

2020.3.40f1
This error will appear in empty project

**Comment by alihan98ersoy** [comment]
Problem fixed. You can redownload the latest package. Thank you for raising this issue.
