### ISSUE TITLE
Missing script

### ISSUE THREAD

**Issue by dmitricob** [EvilMindDevs/hms-unity-plugin#46]
Hi, I just want to publish game to the app gallery but I cannot understand how to do this. If I follow this guide I can't find HMS manager in package although it need by guide. What I do wrong ?

**Comment by m0skit0** [comment]
Here's the official documentation how to upload an app to App Gallery: https://developer.huawei.com/consumer/en/doc/distribution/app/agc-create_app

Please note these issues are meant for the Unity plugin itself, not a support for Huawei App Gallery or other products.
