### ISSUE TITLE
请问有没有要使用这个插件接入华为的防沉迷功能应该怎么做？

### ISSUE THREAD

**Issue by NicolasTseJ** [EvilMindDevs/hms-unity-plugin#464]
找了一下好像没有相关的方法，没有搜到与防沉迷相关的方法名之类的

**Comment by alihan98ersoy** [comment]
In our plugin, we have [Game Service:6.2.0.301](https://developer.huawei.com/consumer/en/doc/HMSCore-Guides/version-change-history-0000001050123471). And in the SDK we have the related parts. 
[PlayersClientWrapper.cs](https://github.com/EvilMindDevs/hms-sdk-unity/blob/c0fc12ba04f5488ce159620b5307c58446dd54e5/hms-sdk-unity/HuaweiMobileServices/Game/PlayersClientWrapper.cs#L32) & [IPlayersClient.cs](https://github.com/EvilMindDevs/hms-sdk-unity/blob/c0fc12ba04f5488ce159620b5307c58446dd54e5/hms-sdk-unity/HuaweiMobileServices/Game/IPlayersClient.cs#L29)

But we don't have an example of how to use it. In our roadmap, we are planning to update the Game Service to the latest version. With this update, we can create a demo for it.

For now, you can refer to [Game Trial](https://developer.huawei.com/consumer/en/doc/HMSCore-Guides/game-anti-indulgence-0000001050123479#section180191912012) to integrate the feature.

**Comment by NicolasTseJ** [comment]
这个更新大概什么时候能完成呢？我们项目目前需要用到这个功能

**Comment by alihan98ersoy** [comment]
We plan to update by the end of February.

**Comment by NicolasTseJ** [comment]
防沉迷相关的方法是在插件里面已经有了是吗？我是可以自己根据（[Game Trial](https://developer.huawei.com/consumer/en/doc/HMSCore-Guides/game-anti-indulgence-0000001050123479#section180191912012)）实现的对吗？

**Comment by alihan98ersoy** [comment]
Yes, but this feature is not available."The Game Service SDK of version 6.8.0.300 or later provides the function of automatically detecting minors' played time."
![resim](https://github.com/EvilMindDevs/hms-unity-plugin/assets/39373386/f71ac1e0-197f-4e85-99b2-50ba51d47099)

**Comment by NicolasTseJ** [comment]
好的，我试试先，感谢

**Comment by NicolasTseJ** [comment]
请问2.3.5对应华为的SDK是哪个版本，我按照官网的教程做了（playersClient.GetGamePlayer(true);），但是没办法弹出实名认证的窗口。

**Comment by alihan98ersoy** [comment]
I believe if the user already signed in there will be no display. did you write a debug? is the "IF" or "ELSE" condition triggering? 
![resim](https://github.com/EvilMindDevs/hms-unity-plugin/assets/39373386/89e2ad24-9166-41c7-86bf-0fc622cd9304)

If the problem is not solved, maybe you can send me the logs then I can check the logs.

**Comment by NicolasTseJ** [comment]
这个是游戏试玩方法，已经被废弃了，而且它好像是试玩时间结束才会回调这两个方法。我需要的是当用户登录时，如果没有经过实名认证，就要弹出实名认证的窗口这个功能。该功能是否在当前插件版本是不支持的？目前2.3.5对应的是HUAWEISDK的V6.2.0.301版本吗？

**Comment by alihan98ersoy** [comment]
I will test and try to find a quick solution for you.

**Comment by NicolasTseJ** [comment]
ok, thx

**Comment by NicolasTseJ** [comment]
请问我在插件里面没找到这个方法（ResourceLoaderUtil.setmContext(this);  // Set the game addiction prevention message context, which is mandatory.），是存在的吗？我看教程里面有说这个方法必须加

**Comment by alihan98ersoy** [comment]
Yes, there is no ResourceLoaderUtil. According to my tests, a few parts in SDK should be changed. Uploading GameServices to the latest version is a high priority for us.

**Comment by alihan98ersoy** [comment]
Hello, we have released the new version.
