### ISSUE TITLE
HMS Unity  not working  , create run time error (v2.3.5 - Unity 2019/2020/2021)

### ISSUE THREAD

**Issue by breaksoftdev** [EvilMindDevs/hms-unity-plugin#465]
We are trying to use the HMS Unity plugin for Huawei AppGallary. but it's not working, we tried all the methods and it's not shown in test mode, when we run the code it creates an error on the start screen. 
please review the mentioned error 

Exception: Field currentActivity or type signature  not found
UnityEngine._AndroidJNIHelper.GetFieldID (System.IntPtr jclass, System.String fieldName, System.String signature, System.Boolean isStatic) (at <c3cf75da2dea4762aad5c0272ee7a081>:0)
UnityEngine.AndroidJNIHelper.GetFieldID (System.IntPtr javaClass, System.String fieldName, System.String signature, System.Boolean isStatic) (at <c3cf75da2dea4762aad5c0272ee7a081>:0)
UnityEngine._AndroidJNIHelper.GetFieldID[ReturnType] (System.IntPtr jclass, System.String fieldName, System.Boolean isStatic) (at <c3cf75da2dea4762aad5c0272ee7a081>:0)
UnityEngine.AndroidJNIHelper.GetFieldID[FieldType] (System.IntPtr jclass, System.String fieldName, System.Boolean isStatic) (at <c3cf75da2dea4762aad5c0272ee7a081>:0)
UnityEngine.AndroidJavaObject._GetStatic[FieldType] (System.String fieldName) (at <c3cf75da2dea4762aad5c0272ee7a081>:0)
UnityEngine.AndroidJavaObject.GetStatic[FieldType] (System.String fieldName) (at <c3cf75da2dea4762aad5c0272ee7a081>:0)
HuaweiMobileServices.Utils.AndroidContext.get_ActivityContext () (at <3e917abcbb924450a121c615facfe546>:0)
HuaweiMobileServices.Ads.HwAds.Init () (at <3e917abcbb924450a121c615facfe546>:0)
HmsPlugin.HMSAdsKitManager.Init () (at Assets/Huawei/Scripts/Ads/HMSAdsKitManager.cs:71)
HmsPlugin.HMSAdsKitManager.OnAwake () (at Assets/Huawei/Scripts/Ads/HMSAdsKitManager.cs:57)
HuaweiMobileServices.Utils.HMSDispatcher.InvokeAsync (System.Action action) (at <3e917abcbb924450a121c615facfe546>:0)
HmsPlugin.HMSAdsKitManager..ctor () (at Assets/Huawei/Scripts/Ads/HMSAdsKitManager.cs:50)
System.Reflection.RuntimeConstructorInfo.InternalInvoke (System.Object obj, System.Object[] parameters, System.Boolean wrapExceptions) (at <4a4789deb75f446a81a24a1a00bdd3f9>:0)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.RuntimeConstructorInfo.InternalInvoke (System.Object obj, System.Object[] parameters, System.Boolean wrapExceptions) (at <4a4789deb75f446a81a24a1a00bdd3f9>:0)
System.RuntimeType.CreateInstanceMono (System.Boolean nonPublic, System.Boolean wrapExceptions) (at <4a4789deb75f446a81a24a1a00bdd3f9>:0)
System.RuntimeType.CreateInstanceSlow (System.Boolean publicOnly, System.Boolean wrapExceptions, System.Boolean skipCheckThis, System.Boolean fillCache) (at <4a4789deb75f446a81a24a1a00bdd3f9>:0)
System.RuntimeType.CreateInstanceDefaultCtor (System.Boolean publicOnly, System.Boolean skipCheckThis, System.Boolean fillCache, System.Boolean wrapExceptions, System.Threading.StackCrawlMark& stackMark) (at <4a4789deb75f446a81a24a1a00bdd3f9>:0)
System.Activator.CreateInstance[T] () (at <4a4789deb75f446a81a24a1a00bdd3f9>:0)
HMSManagerSingleton`1[T].get_Instance () (at Assets/Huawei/Scripts/Utils/HMSSingleton.cs:53)
AdsDemoManager.ShowBannerAd () (at Assets/Huawei/Demos/Ads/AdsDemoManager.cs:83)
AdsUIView.ButtonClick_ShowBannerAd () (at Assets/Huawei/Demos/Ads/AdsUIView.cs:67)
UnityEngine.Events.InvokableCall.Invoke () (at <f712b1dc50b4468388b9c5f95d0d0eaf>:0)
UnityEngine.Events.UnityEvent.Invoke () (at <f712b1dc50b4468388b9c5f95d0d0eaf>:0)
UnityEngine.UI.Button.Press () (at Library/PackageCache/com.unity.ugui@1.0.0/Runtime/UI/Core/Button.cs:70)
UnityEngine.UI.Button.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) (at Library/PackageCache/com.unity.ugui@1.0.0/Runtime/UI/Core/Button.cs:114)
UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at Library/PackageCache/com.unity.ugui@1.0.0/Runtime/EventSystem/ExecuteEvents.cs:57)
UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at Library/PackageCache/com.unity.ugui@1.0.0/Runtime/EventSystem/ExecuteEvents.cs:272)
UnityEngine.EventSystems.EventSystem:Update() (at Library/PackageCache/com.unity.ugui@1.0.0/Runtime/EventSystem/EventSystem.cs:514)

**Comment by alihan98ersoy** [comment]
Hello, you should try the plugin with a real device. Huawei recommended. Also, you can use any Android device with HMS Core installed. If you don't have an Android device you can use [Cloud Debugging](https://developer.huawei.com/consumer/en/agconnect/cloud-adjust/).

**Comment by breaksoftdev** [comment]
yes, we tried the APK on Cloud Debugging, even it's not running in Unity, it created the error, we have already mentioned the error when it run in the Unity Editore.

**Comment by alihan98ersoy** [comment]
Can you provide the logs from CloudDebugging ? I need the check the logs

**Comment by breaksoftdev** [comment]
please the all details 
![Screenshot (20)](https://github.com/EvilMindDevs/hms-unity-plugin/assets/18101613/61921f54-ac05-4049-8de2-f6d7a63718b5)


[2024-02-07 19_41_13.log](https://github.com/EvilMindDevs/hms-unity-plugin/files/14195262/2024-02-07.19_41_13.log)

**Comment by alihan98ersoy** [comment]
I couldn't find any log related with unity or our plugin. Did you use any filter? It should be something like this one 
![resim](https://github.com/EvilMindDevs/hms-unity-plugin/assets/39373386/f918d64b-d018-4d8b-95ac-661b5735d3df)

If you want you can sent me your APK and I can test. You can send here or email me alihan98ersoy@hotmail.com

**Comment by breaksoftdev** [comment]
@alihan98ersoy, please review the email.

> I couldn't find any log related with unity or our plugin. Did you use any filter? It should be something like this one ![resim](https://private-user-images.githubusercontent.com/39373386/303251043-f918d64b-d018-4d8b-95ac-661b5735d3df.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc0NzE4MDEsIm5iZiI6MTcwNzQ3MTUwMSwicGF0aCI6Ii8zOTM3MzM4Ni8zMDMyNTEwNDMtZjkxOGQ2NGItZDAxOC00ZDhiLTk1YWMtNjYxYjU3MzVkM2RmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA5VDA5MzgyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhZGIyYjgyMzJjZTU1NDdmOGE0ZmY1MmVjNmIzY2I1MDQ4YWZiNWU1ZjE1ZWEyMTQwODUzN2I1NmViMGYxMzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PrfRbiZbeaT-ASr4Ce76MsCUtnBY8oa7zJvFYTuDcL8)
> 
> If you want you can sent me your APK and I can test. You can send here or email me [alihan98ersoy@hotmail.com](mailto:alihan98ersoy@hotmail.com)

**Comment by alihan98ersoy** [comment]
@breaksoftdev I asked for permission to download the APK.

**Comment by alihan98ersoy** [comment]
Ok, I found the problem you should use your agconnect-services.json File.

Please refer to [Obtaining the agconnect-services.json File](https://evilminddevs.gitbook.io/hms-unity-plugin/getting-started/quick-start/import-the-plugin-into-your-unity-project#obtaining-the-agconnect-services.json-file)
or the [video](https://www.youtube.com/watch?v=ZskQf4quNhU&t=452s).

Also, there are some errors "Error Unity InvalidOperationException: Insecure connection not allowed" I believe you missed the step on quick start. [Adding Fingerprint Certificate to AppGallery Connect](https://evilminddevs.gitbook.io/hms-unity-plugin/getting-started/quick-start/register-your-app-at-huawei-developer#adding-fingerprint-certificate-to-appgallery-connect) Can you follow the quick start?

**Comment by breaksoftdev** [comment]
@alihan98ersoy  i followed all the steps as you mentioned in the video, but when we enabled the test ads and ran on the cloud debugging, it's not show the ads. even it creates errors in the unity editor,  and shoe script errors (signature not found) it's possible, can you share the project with working ads.

> Ok, I found the problem you should use your agconnect-services.json File.
> 
> Please refer to [Obtaining the agconnect-services.json File](https://evilminddevs.gitbook.io/hms-unity-plugin/getting-started/quick-start/import-the-plugin-into-your-unity-project#obtaining-the-agconnect-services.json-file) or the [video](https://www.youtube.com/watch?v=ZskQf4quNhU&t=452s).
> 
> Also, there are some errors "Error Unity InvalidOperationException: Insecure connection not allowed" I believe you missed the step on quick start. [Adding Fingerprint Certificate to AppGallery Connect](https://evilminddevs.gitbook.io/hms-unity-plugin/getting-started/quick-start/register-your-app-at-huawei-developer#adding-fingerprint-certificate-to-appgallery-connect) Can you follow the quick start?

**Comment by alihan98ersoy** [comment]
The package of agconnect-services.json in APK was com.refapp.cubesurfer.huawei. This is the same json that we loaded into the plugin as an example.

1. First, create a project with your own package name in the AppGallery console.
2. Enable ads kit. (Requires [Merchant permission](https://developer.huawei.com/consumer/en/doc/start/merchant-service-0000001053025967))
3. Then add your fingerprint. (SHA-256)

If you use our JSON you will connect your game to our project but you don't have the same fingerprint so it will give a 6003 fingerprint error.

These are the APK: 
[AdsDemoTest.zip](https://github.com/EvilMindDevs/hms-unity-plugin/files/14220907/AdsDemoTest.zip)
