### ISSUE TITLE
Ads not showing in Unity 2022.2.13

### ISSUE THREAD

**Issue by imtiaz791** [EvilMindDevs/hms-unity-plugin#473]
Hi,
  I use HMS Unity plugin version 2.3.6 and I also tried the HMS plugin version 2.3.5. But ads do not Show.
Thanks,

**Comment by alihan98ersoy** [comment]
Hi, May I get your logs?

**Comment by zeeshan0022** [comment]
wait

**Comment by zeeshan0022** [comment]
![issue](https://github.com/EvilMindDevs/hms-unity-plugin/assets/42519518/4c96c32b-d861-420f-9737-56578ebd874f)
