### ISSUE TITLE
About App-Ads.txt

### ISSUE THREAD

**Issue by zeonagames** [EvilMindDevs/hms-unity-plugin#474]
How can I implement App-ads.txt, there is no website section on Huawei AppGallery

**Comment by alihan98ersoy** [comment]
Maybe this link can help: [app-ads.txt](https://developer.huawei.com/consumer/en/doc/monetize/mediamanagement-0000001051201925#section175951750219)

**Comment by alihan98ersoy** [comment]
Can you submit a ticket regarding the issue and contact customer service? They will help you with your problem. 
https://developer.huawei.com/consumer/en/doc/monetize/support-0000001061434261
