### ISSUE TITLE
Huawei Unity IAP Did Not Worked.

### ISSUE THREAD

**Issue by MushoodMunir** [EvilMindDevs/hms-unity-plugin#488]
**Describe the bug & problem**
I am trying to implement Huawei IAP in my Unity Project. However, I am not able to launch Huawei payment flow when clicking on my IAP's button. I followed the online available tutorials and created the IAP products on Huawei app gallery console. According to my understanding everything is configured correctly but receiving error when IAP is initialized. 

**Expected behavior**
IAP should work and payment screen should launch successfully.

**Screenshots & Detailed log**
<img width="791" alt="Screen Shot 2024-04-28 at 1 48 48 PM" src="https://github.com/EvilMindDevs/hms-unity-plugin/assets/10167077/5645b6e8-f280-4dd9-aef0-411bc07faecc">
<img width="568" alt="Screen Shot 2024-04-28 at 1 44 15 PM" src="https://github.com/EvilMindDevs/hms-unity-plugin/assets/10167077/26e32356-2871-4b94-adf9-58d1f385a7c5">
<img width="1438" alt="Screen Shot 2024-04-28 at 2 06 17 PM" src="https://github.com/EvilMindDevs/hms-unity-plugin/assets/10167077/1119d1be-f805-43bf-aa4b-2c592180a214">
<img width="834" alt="Screen Shot 2024-04-28 at 2 06 55 PM" src="https://github.com/EvilMindDevs/hms-unity-plugin/assets/10167077/1a39db0d-a2f9-422c-87c9-f350a35764b1">
<img width="1037" alt="Screen Shot 2024-04-28 at 1 27 35 PM" src="https://github.com/EvilMindDevs/hms-unity-plugin/assets/10167077/5dbd421f-cfa8-459d-a492-77580a5166dc">

**Environment**
 - Unity Version 2021.3.2f1
 - HMS Unity Plugin Version V2.3.4

**Smartphone**
 - Device: Huawei (HONOR 8S)

**Comment by MushoodMunir** [comment]
Is there any update on this?

**Comment by Andronovo-bit** [comment]
Hi @MushoodMunir. We are under review. If you want, you can try the suggestions below until this process is complete.

- Did you use AccountKitManager ? Before any IAP operation, you must sign in. For this you look at this demo scene;

https://github.com/EvilMindDevs/hms-unity-plugin/tree/master/Assets/Huawei/Demos/IAP/Second%20Demo-Menu_Store

**Comment by MushoodMunir** [comment]
No, I didn't use any AccountKitManager before IAP operation. I directly tried to initialize the IAP flow by checking "Initialize On Start" option from Kit Settings -> IAP dialogue. And it failed to Initialize straight away. Is't AccountKitManager will come into play after the purchases are initialized successfully and at the time user will try to buy any IAP? Or AccountKitManager has something to do with the successful Initialization of IAP's? If there is some kind of dependency between these two can you please guide me to workflow of it?

**Comment by Andronovo-bit** [comment]
Basically, if the user can't login, they can't do any IAP operations. This is normal, because this transaction has to belong to an account.

The purpose of the "Initialize On Start" option is to prepare your IAP products for use. Don't be related to any account or user operation.

If you look at the at the below demo scene file, you can see the guide in the code file. Writes in comment line what you need to do, and you can also see how to do user operations or start operations.

https://github.com/EvilMindDevs/hms-unity-plugin/blob/master/Assets/Huawei/Demos/IAP/Second%20Demo-Menu_Store/MainMenuManager.cs

**Comment by MushoodMunir** [comment]
Got it, As you said that The purpose of the "Initialize On Start" option is to prepare your IAP products for use. Don't be related to any account or user operation. Here i get the problem as products are not being Initialized at all and i get some error code in response visible in screenshots that i attached.

**Comment by Andronovo-bit** [comment]
Did you follow the 5-step instructions in the code file I shared above and the structure in the "Start" method? Are you still getting an error?

**Comment by MushoodMunir** [comment]
It worked with singing in using AccountKit before performing any IAP operations.
