### ISSUE TITLE
App force update

### ISSUE THREAD

**Issue by atheer10** [EvilMindDevs/hms-unity-plugin#489]
**Describe the bug & problem**

We are trying to force update in our game, we have looked into the [documentation ](https://developer.huawei.com/consumer/en/doc/AppGallery-connect-Guides/appgallerykit-game-update-0000001055756860 ), and we have integrated the the update SDK in our game prior. 
We have released a new version to the store, and we are testing with an older version to see if the pop-up appears but it doesn't. Both versions when released "force update" button on the Huawei AppGallery was turned on, our understanding is there's no additional calls required or steps aside from the integration and store check. 

When we visit the store, we can see that an update is available.
When the auto-update for the store was on, the app updated on it's own, we have turned it off in order to test, but the no results. 
Currently, we do not see the force update pop-up panel or any indicator that the update sdk is working. 

We have provided screenshots of the code, Can you please guide us to any missing steps ? 

**Expected behavior**
A new version is available pop-up shows up when the game is booted. 

**Screenshots & Detailed log**
If applicable, add screenshots and a Log to help explain your problem.

![image (2)](https://github.com/EvilMindDevs/hms-unity-plugin/assets/43179208/61b04e5e-bbd8-4bbe-af8d-cca58148b28f)
<img width="727" alt="update_huawei_3" src="https://github.com/EvilMindDevs/hms-unity-plugin/assets/43179208/9fb933c1-3314-4a1f-b5c6-f6ec21879e2b">
<img width="635" alt="update_huawei_2" src="https://github.com/EvilMindDevs/hms-unity-plugin/assets/43179208/ac6e57d6-8770-41e3-8015-0161c616b352">
<img width="495" alt="update_huawei_1" src="https://github.com/EvilMindDevs/hms-unity-plugin/assets/43179208/93bb63f2-90cc-4423-b0f0-0418196c3672">
<img width="701" alt="update_huawei" src="https://github.com/EvilMindDevs/hms-unity-plugin/assets/43179208/1fcf6195-4a89-4855-8cf1-4e82b7e1951b">
<img width="646" alt="update_huawei_4" src="https://github.com/EvilMindDevs/hms-unity-plugin/assets/43179208/6f39da21-2d86-4063-b297-6f5821a89530">

**Environment (please complete the following information):**
 - Unity Version [2021.3.22f1]
 - HMS Unity Plugin Version [2.3.4] (we cannot update it as it creates many issues with our integrations

**Smartphone (please complete the following information):**
 - Device: [e.g. Huawei, Non-Huawei, Cloud Debugging]
Huawei 

**Additional context**

**Comment by Andronovo-bit** [comment]
Hi @atheer10 . We are under review. If you want, you can try the suggestions below until this process is complete.

- Can you try to make it "true" this line? (**HMSGameManagerService.cs**) (After this update, you may need to do an update to try this code.)

![K2xjw8o87t](https://github.com/EvilMindDevs/hms-unity-plugin/assets/24398592/247e1704-3d4f-4ec2-8fee-aad8a5d2f469)

- Did you release a new version directly or did you try it using a closed test?

**Comment by atheer10** [comment]
@Andronovo-bit  

- Have created a build with that fix, will keep you updated on the results once it is approved from the store. 

- No, we have always created a new release version, as the option for force update is not available on closed testing.

**Comment by atheer10** [comment]
@Andronovo-bit 
We have created a new build with the fix above of changing the CheckAppUpdate values to true and installed it on the device, then uploaded another newer version to the store, we can see from the store/notification that there's an update available, however nothing shows up within the app to prompt an update.

**Comment by Andronovo-bit** [comment]
@atheer10 
Ok I understood. I should have asked before. Did you activate the game service on AppGallery panel ? And also, did you enable gamekit in unity-plugin? Like the below images.

![image](https://github.com/EvilMindDevs/hms-unity-plugin/assets/24398592/5f090d35-8434-4494-a160-181bcf632448)

![image](https://github.com/EvilMindDevs/hms-unity-plugin/assets/24398592/b68c5373-2e05-4243-9693-5b67f7efdbe3)

![image](https://github.com/EvilMindDevs/hms-unity-plugin/assets/24398592/e970a61c-4715-47ea-bad7-fce98feeba7c)

Do you mind if can you send a game url or apk for review?

**Comment by atheer10** [comment]
@Andronovo-bit 
Looks like those settings were off ! I will make a new build and share it 
This is the URL of the game : https://appgallery.huawei.com/app/C105911883

**Comment by Andronovo-bit** [comment]
I tried to download this app, but I couldn't see it in the gallery. Is released this app or can we accessable in Turkey ?

**Comment by atheer10** [comment]
@Andronovo-bit 

- We a made two new releases with the game services enabled both in Unity project and in app gallery, but the pop-up doesn't show up. We get a notification that there's a new update as shared above, but no in-game pop-up. 

- Yes, the game is not available there, I will update the release to include it.

**Comment by Andronovo-bit** [comment]
@atheer10 

- Okay, we wait for release in our region to test your application.

- Can you share the log records of the scenario where the update popup should appear in our application?

**Comment by atheer10** [comment]
@Andronovo-bit 

- We've updated the app and added Turkey, you should be able to find it in the App Gallery store. We will release a newer update so we can test the force update function . 
- In terms of where it should appear, since the logic is mostly in the awake, and init methods, it should appear at the loading screen of the game.

**Comment by Andronovo-bit** [comment]
@atheer10 

Hi, we checked the game with logs, but we didn't see any "game service and update function triggered" logs. You should enable game service and use HMSGameServiceManager for force updating.

For instance;

If you want to use it in a starting scene, you can add the below code.

```
HMSGameServiceManager.Instance.InitGameManagers()
HMSGameServiceManager.Instance.CheckAppUpdate(true,true)
```

OR 

If you already use HMSGameServiceManager in your scene, you can change the InitGameManager's function's body like below.
```

 public void InitGameManagers()
     {
             ...
             ...
            CheckAppUpdate(true, true);
      }
```

After calling this function, you will be automatically callback to the '`OnUpdateInfo`' methods in HMSGameService and the Update Dialogue will be opened in your game.

**Comment by atheer10** [comment]
@Andronovo-bit 
- Correct , there was a setting that was turning off the game service, we enabled that again and just released a new version 4494, but perhaps it's not going to show as there's no newer version yet. 
- We are using the second method to call the update 

![image](https://github.com/EvilMindDevs/hms-unity-plugin/assets/43179208/fd7a0a33-936e-4a17-91c6-4b686d221c37)
![image](https://github.com/EvilMindDevs/hms-unity-plugin/assets/43179208/43dce986-e600-4e08-a30d-c2818dc5a2ac)

**Comment by Andronovo-bit** [comment]
- It looks everthing is OK @atheer10, on code side. 
- After this code releasing, if you do new update we can see what's going on background in log records.

**Comment by atheer10** [comment]
@Andronovo-bit 
We have a newer release with those implemented, and we still don’t see the update prompt. Do you mind looking at the logs to see why ?

**Comment by Andronovo-bit** [comment]
@atheer10 Hello again,

We checked it but we didn't find any game service log record in Logcat.

For example, we able to see IAP kit log records like this;

![image](https://github.com/EvilMindDevs/hms-unity-plugin/assets/24398592/7047f572-2edf-43dc-8519-d9c5deb70565)

But we can't see any game service log record like this;

![image](https://github.com/EvilMindDevs/hms-unity-plugin/assets/24398592/4384a97e-dfd5-4abc-8f81-8d484e965a88)

You didn't enable or initialize the game service kit in your project start, as we can see.

You should trigger game service kit during game starting.

**Comment by atheer10** [comment]
@Andronovo-bit 
Can you please check if it's still the case in the newest build ?

**Comment by Andronovo-bit** [comment]
@atheer10 
We didn't see any log again after installed latest version your game.

Can you check below steps in images ?

**1-) Activate Game Service in Huawei Plugin**

![image](https://github.com/user-attachments/assets/dabf47bb-70c6-4887-95e3-9d2a6fd99a80)

**2-) Enable "Initiliaze On Start" in Game Service Tab**

![image](https://github.com/user-attachments/assets/84f76585-2521-4734-a911-1da6b61eed45)

3-) You should add game service script that you wrote to object in your loading or opening game scene.

![image](https://github.com/user-attachments/assets/bf165d24-ebef-4015-8380-cb55eb50b92f)

4-) After all things , you should be able to see  "HMS GAMES" in your log.

![image](https://github.com/user-attachments/assets/761680cb-ae66-4135-848f-62c5a4d23eb2)
