### ISSUE TITLE
Issue when Obtaining Product info on LoadStore()

### ISSUE THREAD

**Issue by skrpeta** [EvilMindDevs/hms-unity-plugin#49]
Hi,
need help with IAPS. I manage to sign in to the app when installed but next steps are throwing erros. Here is the log:

07-24 19:35:52.063  2319  2319 I Unity   : [HMS]: SignedIn
07-24 19:35:52.063  2319  2319 I Unity   : (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
07-24 19:35:52.063  2319  2319 I Unity   :
07-24 19:35:52.619  2319  2319 I Unity   : HMSP: checkIapAvailabity SUCCESS
07-24 19:35:52.619  2319  2319 I Unity   : (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
07-24 19:35:52.619  2319  2319 I Unity   :
07-24 19:35:52.624  2319  2319 I Unity   : [HMS]: LoadStore
07-24 19:35:52.624  2319  2319 I Unity   : (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
07-24 19:35:52.624  2319  2319 I Unity   :
07-24 19:35:52.738  2319  2319 I Unity   : [HMSPlugin]: ERROR Consumable ObtainInfoException of type 'HuaweiMobileServices.Utils.HMSException' was thrown.
07-24 19:35:52.738  2319  2319 I Unity   : (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
07-24 19:35:52.738  2319  2319 I Unity   :
07-24 19:35:52.739  2319  2319 I Unity   : [HMSPlugin]: IAP ObtainProductInfo failed. Exception of type 'HuaweiMobileServices.Utils.HMSException' was thrown.
07-24 19:35:52.739  2319  2319 I Unity   : (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

I created 3 differrent types iaps(consumable, nonconsumable, and auto-subs type of iaps just for test for now) inside app connect galery. Also added SHA256 to the app galerry console. Imported also agconnect-services.json to unity project replacing that of your plugin. Also I believe android manifest is correctly configured to my app ids.

Am I missing something. Can somebody help? Anything I should do on app gallery connect site.
Thanks in advance.

**Comment by TheHeksiii** [comment]
I have the same problem, @EvilMindDevs any ideas?

**Comment by m0skit0** [comment]
Can you please log the WrappedExceptionMessage from the exceptions thrown by the SDK?

**Comment by skrpeta** [comment]
Hi, first thank you taking time to help :) 
I couldnt find that WrapperExceptionMessage in my log. Used this line in cmd to log: adb logcat –v time > C:\hwlocation.log
Is that ok? here is the whole log in the attachment
[hwlocation.log](https://github.com/EvilMindDevs/hms-unity-plugin/files/5003707/hwlocation.log)

Here is short snippet:
07-30 22:21:53.706 I/HMSSDK_HmsClient(17163): receive msg status_code:0, error_code0, api_name:iap.isBillingSupported, app_id:102481109|, pkg_name:com.ziaproduction.pricalica.huawei, session_id:*, transaction_id:102481109ported20200730222153122571901, resolution:null
07-30 22:21:53.713 I/HMSSDK_IsEnvReadyTaskApiCall(17163): onResult, success
07-30 22:21:53.720 I/Unity   (17163): HMSP: checkIapAvailabity SUCCESS 
07-30 22:21:53.720 I/Unity   (17163): (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
07-30 22:21:53.720 I/Unity   (17163): 
07-30 22:21:53.720 D/        (17163): addLayerName, tid:17191
07-30 22:21:53.723 I/Unity   (17163): [HMS]: LoadStore 
07-30 22:21:53.723 I/Unity   (17163): (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
07-30 22:21:53.723 I/Unity   (17163): 
07-30 22:21:53.736 D/        (17163): addLayerName, tid:17191
07-30 22:21:53.749 W//system/bin/netd(  569): A binder object at 0xe74483a0 is being transacted on, however, this object is in the same process as its proxy. Transacting with this binder is expensive compared to just calling the corresponding functionality in the same process.
07-30 22:21:53.749 I/PreDnsController(  569): canPreDnsQuery,persist.sys.predns is false!
07-30 22:21:53.753 D/        (17163): addLayerName, tid:17191
07-30 22:21:53.771 D/        (17163): addLayerName, tid:17191
07-30 22:21:53.780 I/HMSSDK_HuaweiApiManager(17163): sendRequest
07-30 22:21:53.781 I/HMSSDK_HmsClient(17163): post msg api_name:iap.getSkuDetails, app_id:102481109|, pkg_name:com.ziaproduction.pricalica.huawei, sdk_version:40001300, session_id:*, transaction_id:102481109etails20200730222153778748064, kitSdkVersion:40001300, apiLevel:1
07-30 22:21:53.784 I/HMSSDK_BaseAdapter(17163): in baseRequest + uri is :iap.getSkuDetails, transactionId is : 102481109etails20200730222153778748064
07-30 22:21:53.787 I/HMSSDK_PendingResultImpl(17163): init uri:iap.getSkuDetails
07-30 22:21:53.789 I/HMSSDK_PendingResultImpl(17163): setResultCallback
07-30 22:21:53.799 D/        (17163): addLayerName, tid:17191
07-30 22:21:53.808 D/        (17163): addLayerName, tid:17191
07-30 22:21:53.820 D/        (17163): addLayerName, tid:17191
07-30 22:21:53.830 I/HMSSDK_PendingResultImpl(17163): setResult:0
07-30 22:21:53.832 I/HMSSDK_BaseAdapter(17163): baseCallBack.onComplete
07-30 22:21:53.833 I/HMSSDK_HmsClient(17163): receive msg status_code:0, error_code60001, api_name:iap.getSkuDetails, app_id:102481109|, pkg_name:com.ziaproduction.pricalica.huawei, session_id:*, transaction_id:102481109etails20200730222153778748064, resolution:null
07-30 22:21:53.836 I/HMSSDK_ProductInfoTaskApiCall(17163): onResult, returnCode: 60001
07-30 22:21:53.837 D/        (17163): addLayerName, tid:17191
07-30 22:21:53.850 I/Unity   (17163): [HMSPlugin]: ERROR Consumable ObtainInfoException of type 'HuaweiMobileServices.Utils.HMSException' was thrown. 
07-30 22:21:53.850 I/Unity   (17163): (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
07-30 22:21:53.850 I/Unity   (17163): 
07-30 22:21:53.851 I/Unity   (17163): [HMSPlugin]: IAP ObtainProductInfo failed. Exception of type 'HuaweiMobileServices.Utils.HMSException' was thrown. 
07-30 22:21:53.851 I/Unity   (17163): (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
07-30 22:21:53.851 I/Unity   (17163): 

If this is not what you needed can you please direct me in the right direction. Steps i need to take so i can help you help me :D

**Comment by m0skit0** [comment]
Yes, that error code is what I was asking for. I will check and get back to you.

**Comment by m0skit0** [comment]
This is the same issue as #44 , I will close this one, anything you can comment on there, thanks.
