### ISSUE TITLE
Assets/Huawei/Plugins/Android/hmsMainTemplate.gradle is absent

### ISSUE THREAD

**Issue by PromanSEW** [EvilMindDevs/hms-unity-plugin#491]
**Describe the bug & problem**
When I try to build APK, I got this error:
```
Copying D:/TrueFishingUnity/Assets/Huawei/Plugins/Android/hmsMainTemplate.gradle to D:\TrueFishingUnity\Library\Bee\Android\Prj\IL2CPP\Gradle\unityLibrary/hmsMainTemplate.gradle: The specified file cannot be found
```
I looked in package, filesystem and this repository, but there is no this file anywhere. Please provide this file
**Environment (please complete the following information):**
 - Unity Version 2021.3.37f1]
 - HMS Unity Plugin Version 2.3.7

**Comment by alihan98ersoy** [comment]
In normal situation it should create the specific files when building the APK.
![image](https://github.com/EvilMindDevs/hms-unity-plugin/assets/39373386/1a4c3174-50b2-4e73-b81f-24804a07258f)

Then the files are moved to the bee folder. This bee folder works like a cache and makes the creation process faster.

However, there is problem that blocks this process. I believe it can work normally when you try it next time. If it doesn't work, you can try deleting the Library\Bee folder.
