### ISSUE TITLE
Plugins not create HMSAccountManager and HMSGameManager in Hierarchy.

### ISSUE THREAD

**Issue by kh12358** [EvilMindDevs/hms-unity-plugin#496]
**Describe the bug & problem**
I have import this plugins and select Game Service ,close the kit setting window.HMSAccountManager and HMSGameManager not create in Hierarchy.

**To Reproduce**
1. import plugins.
2. Click on huawei>kit Settings->Game Service，close windows.
3. Look the Hierarchy,HMSAccountManager and HMSGameManager not create.
4. Because my app is in review,so i change Assets>StreamingAssets>agconnect-services.json>packagename.Not change agconnect-services.json file.I'm not sure this operation is allow.
5. And open AccountDemo.When I play this screen,I have the second error.whatever Unity Editor or Android phone.
<img width="1507" alt="hw error" src="https://github.com/EvilMindDevs/hms-unity-plugin/assets/46120184/e17a27a4-04b5-4be7-a97a-5247f33b01ca">

**Expected behavior**

**Screenshots & Detailed log**
If applicable, add screenshots and a Log to help explain your problem.

**Environment (please complete the following information):**
 - Unity Version [e.g. 2021.3.6f1]
 - HMS Unity Plugin Version [e.g. V2.3.7]

**Smartphone (please complete the following information):**
 - Device: [e.g. Huawei, Non-Huawei, Cloud Debugging]

**Additional context**
- Are there any 3rd party solutions you use that may be linked to the problem?

**Comment by Andronovo-bit** [comment]
Hi @kh12358,

Actually, the answer is hidden in the picture that you sent. Huawei Mobile Services (HMS) just runs on mobile devices; therefore, you can switch to the Android platform in Unity and try on your mobile device.

![image](https://github.com/EvilMindDevs/hms-unity-plugin/assets/24398592/821629f1-5c79-4721-89d1-be93a815a2ab)

You can follow the documentation at the below link:

https://evilminddevs.gitbook.io/hms-unity-plugin/getting-started/quick-start

**Comment by kh12358** [comment]
Thanks for you help.I‘ll try it again.

**Comment by kh12358** [comment]
Hi@Andronovo-bit,I have reslove this question.The video is very good! Thank you!

**Comment by Andronovo-bit** [comment]
@kh12358 You're welcome :)

**Comment by Andronovo-bit** [comment]
@kh12358  you're welcome :)
