### ISSUE TITLE
HMS Manager missing?

### ISSUE THREAD

**Issue by AndresCuicui** [EvilMindDevs/hms-unity-plugin#5]
Hi,
We made some tests with the previous version of the plugin and are now migrating towards the one available at the Releases section. In this new version, there's no HMSManager script, so we don't know where to add the Key that was required to connect to the IAP system.
We manage to sign in correctly, but whenever we call function ObtainProductInfo we always get the iapAvailable == false. Is there a new way of connecting to the IAP system?
Thanks.

[EDIT]: Ok, just saw the Full Demos release date for 14/05/2020, so we can wait until then for the new way of using the IAP system.

**Comment by Deroido** [comment]
yes we all wait for working demos or at least some actual documentation.

**Comment by m0skit0** [comment]
Hi, thanks for the feedback. Do you still have problems with IAP? Please check IapManager. We hope to have a working IAP demo soon, sorry for the lateness :(

**Comment by EvilMindDevs** [comment]
Hi,

You can find the IAPDemo on this commit e3913a2f6f03931ccb756f5646b9cf7e0183f8c4
