### ISSUE TITLE
"Failed to load the HMSGameServiceSettings. Please restart Unity Editor." It happens in v2.3.8, worked in v2.3.7

### ISSUE THREAD

**Issue by lxwgogogo** [EvilMindDevs/hms-unity-plugin#504]
**Describe the bug & problem**
The v2.3.7 works well on my phone. But after I upgrade to v2.3.8, it throws error: 
```
A scripted object (script unknown or not yet loaded) has a different serialization layout when loading. (Read 56 bytes but expected 64 bytes)
Did you #ifdef UNITY_EDITOR a section of your serialized properties in any of your scripts?
```

I debugged and found the `ScriptableHelper.Load` has `var asset = Resources.Load<T>(filename);` which the asset is `null`. I wonder if I should copy the Assets/Huawei/Settings/Resources folder to my Assets/Resources folder?

**Comment by lxwgogogo** [comment]
Let me answer to myself. After I copy the `Assets/Huawei/Settings/Resources folder` to my `Assets/Resources folder?`, now it works.  Is this a required step after the upgrade to v2.3.8?

**Comment by Andronovo-bit** [comment]
Hello @lxwgogogo ,  We tried the game service and didn't faced any errors like the ones you're getting with the settings. 

Actually setting's file path is right. It needs to be in Huawei > Settings > Resources.

Maybe, this error is one shot. Can you tell which use Unity version ?

Just try this;
Rollback last changes that about settings path and then make Assets > Import All in Unity. Open again and run your project.

**Comment by lxwgogogo** [comment]
I am using 2022.3.14f1

**Comment by Andronovo-bit** [comment]
The Unity plugin has automatically created its own settings file in` "Huawei > Settings > Resources."`

![image](https://github.com/user-attachments/assets/3a17c81e-0bca-4a35-9c3c-6ff1ab1d5588)

Can you check again this folder ? 

The plugin already won't use files that you copied in "Assets/Resources.". You can delete them.

**Comment by qinhanlei** [comment]
I also encountered this issue once. 
When I ran `git clean -fdx` in my project and then reopened Unity 2022.3.39f1, the issue disappeared.
Still don't know why.

**Comment by amatveev** [comment]
i have same error in android build  Unity 2022.3.39f1

<pre>
A scripted object (script unknown or not yet loaded) has a different serialization layout when loading. (Read 52 bytes but expected 60 bytes)
Did you #ifdef UNITY_EDITOR a section of your serialized properties in any of your scripts?

UnityEngine.Resources:Load(String)
HmsPlugin.ScriptableHelper:Load(String, String)
HmsPlugin.HMSIAPKitSettings:.ctor()
System.Activator:CreateInstance()
HmsPlugin.HMSEditorSingleton`1:get_Instance()
HmsPlugin.HMSIAPManager:InitControlOfIAP()
HuaweiMobileServices.Utils.HMSDispatcher:InvokeAsync(Action)
System.Lazy`1:CreateValue()
Gameplay.Billing.Factories.Android.Huawei.ControllerFactory:Create(IAuthTokenSource, IGame, BillingEvents, CurrencyConverter)
.....
</pre>

**Comment by Andronovo-bit** [comment]
@amatveev and @qinhanlei Can you try other Unity version ?

We tried 2022.3.18f1, and we didn't face any errors that you faced. 

In the meantime, we will try the Unity version that you used. After that, let's we compare results together.

**Comment by amatveev** [comment]
> @amatveev Can you try other Unity version ?
> 
> We tried 2022.3.18f1, and we didn't face any errors that you faced.
> 
> In the meantime, we will try the Unity version that you used. After that, let's we compare results together.

We upgrade project from 2020.3.41f1 to 2022.3.39f1.
After unity editor upgrade we are upgrade hms-unity-plugin 2.3.4 -> 2.3.8 and 2.3.8 + 2020.3.41f1 wok fine

summary:
 2.3.8 +  2020.3.41f1 - ok
2022.3.39f1 - error
2022.3.40f1 - error

<pre>
A scripted object (script unknown or not yet loaded) has a different serialization layout when loading. (Read 52 bytes but expected 60 bytes)
Did you #ifdef UNITY_EDITOR a section of your serialized properties in any of your scripts?

UnityEngine.Resources:Load(String)
HmsPlugin.ScriptableHelper:Load(String, String)
HmsPlugin.HMSIAPKitSettings:.ctor()
System.Activator:CreateInstance()
HmsPlugin.HMSEditorSingleton`1:get_Instance()
HmsPlugin.HMSIAPManager:InitControlOfIAP()
HuaweiMobileServices.Utils.HMSDispatcher:InvokeAsync(Action)
System.Lazy`1:CreateValue()
Gameplay.Billing.Factories.Android.Huawei.ControllerFactory:Create(IAuthTokenSource, IGame, BillingEvents, CurrencyConverter)
</pre>

![hms-unity-p-2 3 8](https://github.com/user-attachments/assets/947247c3-36b7-4f0a-8201-e0822daef1b5)

**Comment by qinhanlei** [comment]
@Andronovo-bit @amatveev 
I encountered this issue again. 
Our project uses version 2022.3.39f1, and the issue disappears upon restarting Unity. 
It seems to be a bug in Unity that occurs when something is cached during multiple builds.

**Comment by Andronovo-bit** [comment]
@amatveev @qinhanlei 
 

1.  You should never modify the settings file manually. This file has a format.

2. If you have rarely encountered this error, you can;   
     - Go to Assets > Reimport All in the Unity Editor.

3. If second solution don't solve your problem, you can;
    - Close Unity.
    - Delete the Library folder in your project directory (this folder will be recreated when you reopen the project).
    - Reopen Unity and let it recompile everything.
 
4. As a final step, if your problem persists, could you replace the following code in the ScriptableHelper.cs file?

   - [ScriptableHelper](https://hastebin.skyra.pw/awuwojinoy.csharp)

**Comment by PavelPerelygin** [comment]
I solved the problem in the following way. In my case, there were no settings in this file and you can do it like this.

using System;
using UnityEngine;

```
namespace HmsPlugin
{
    public class HMSIAPKitSettings : HMSEditorSingleton<HMSIAPKitSettings>
    {
        private const string SettingsFilename = "HMSIAPKitSettings";
        public const string InitializeOnStart = "InitializeOnStart";
        public const string ConsumptionOwnedItemsOnInitialize = "ConsumptionOwnedItemsOnInitialize";
        private SettingsScriptableObject loadedSettings;

        private HMSSettings _settings;
        public HMSSettings Settings => _settings;

        public HMSIAPKitSettings()
        {
            loadedSettings = ScriptableObject.CreateInstance<SettingsScriptableObject>();
            //loadedSettings = ScriptableHelper.Load<SettingsScriptableObject>(SettingsFilename, "Assets/Huawei/Settings/Resources");
            if (loadedSettings == null)
            {
                throw new InvalidOperationException($"Failed to load the {SettingsFilename}. Please restart Unity Editor");
            }
            _settings = loadedSettings.settings;
            _settings.OnDictionaryChanged += _settings_OnDictionaryChanged;
        }

        private void _settings_OnDictionaryChanged()
        {
            loadedSettings.Save();
        }

        public void Reset()
        {
            _settings.Dispose();
            _instance = null;
        }
    }
}
```

**Comment by flashmandv** [comment]
For me the errors came because in HMSEditorUtils, HuaweiMobileServices.Core.asmdef is set to have the Editor value.
This is my fix:
```
//coreAssemblyDefinition.includePlatforms = enable ? new List<string> { "Editor", "Android" } : new List<string> { "Editor" };
coreAssemblyDefinition.includePlatforms = enable ? new List<string>() : new List<string> { "Editor" };
```

**Comment by JoseMarioPerezCotes** [comment]
@Andronovo-bit 

Hello, sorry for revive this post, I'm facing this issue, I test Pavel, and flashmandv solution but is not works, as you mention some times is necesary reset Unity, but also I want check the change that you do in the scriptable helper because this problem persist a lot, and is anoying restar unity or delete the library folder, because take a lot of time to rebuild all.
