### ISSUE TITLE
IAP Service force the screen orientation to be `LandscapeLeft`

### ISSUE THREAD

**Issue by lxwgogogo** [EvilMindDevs/hms-unity-plugin#505]
**Describe the bug & problem**
A clear and concise description of what the problem is.
After enable IAP, the game is forced to be `LandscapeLeft`, which is very weird. My game was always in portrait mode, but now Huawei IAP force it to be LandscapeLeft. Could I just override it to Portrait in the code? Or Huawei IAP has some feature requires Landscape mode?

**Comment by Andronovo-bit** [comment]
Hello, @lxwgogogo.

Did you try it on your own scene or on our demo scene ?

If you tried our deme scene, yes, it forcing it to be LandScapeLeft because scene is landscape. But if you have created your own scene, LandScapeLeft should not force it to be.

**Comment by lxwgogogo** [comment]
I'm on my own scene. I defined a HuaweiIAPManager in one of my script on a gameobject in my scene.

**Comment by Andronovo-bit** [comment]
You don't supposed to face any problem, if you did like that. IAP works potrait mode, normally.

Can you give screen record when you are faced this problem ?
