### ISSUE TITLE
Got 2 errors after I imported this plugin 

### ISSUE THREAD

**Issue by qinhanlei** [EvilMindDevs/hms-unity-plugin#508]
Hi,

Thanks for creating such a convenient plugin :)

I got 2 errors after I imported this plugin as below:
```
Assets/Huawei/Demos/NearbyService/NearbyDemoManager.cs(175,51): error CS0118: 'Data' is a namespace but is used like a type
Assets/Huawei/Demos/NearbyService/NearbyDemoManager.cs(123,83): error CS0535: 'NearbyDemoManager.NearbyManagerListener' does not implement interface member 'IDataCallback.onReceived(string, Data)'
```

**Environment:**
- HMS Unity Plugin Version: V2.3.8
 - macOS 14.5 
   - Unity Version 2022.3.36f1
- Windows 11
  - Unity Version 2021.3.29f1

I hope it helps.

**Comment by Andronovo-bit** [comment]
Hi @qinhanlei,

We will look into it and get back to you. Thank you for reporting the error. :)

**Comment by qinhanlei** [comment]
> Hi @qinhanlei,
> 
> We will look into it and get back to you. Thank you for reporting the error. :)
> 
> Did you get the error while trying demo scenes or did you have a problem while trying the scene you created?

Hi @Andronovo-bit ,

Thanks for your reply.

The plugin imports the demo scenes, so I tried it in my project.
Even if I switch to the demo scenes, the error still exists.

**Comment by Andronovo-bit** [comment]
Hi again, @qinhanlei;

We tested plugin by creating new project and we faced no problem. Everything was okay.

If your problem continues, can you record short video how you added   plugin in your project and it gives error and send it to us ?

**Comment by qinhanlei** [comment]
Hi, @Andronovo-bit 

We figured out that there is a third-party DLL in our project that covers `HuaweiMobileServices.Nearby.Transfer.Data`. 

Thank you for your help, and I am so sorry for wasting your time.

**Comment by Andronovo-bit** [comment]
@qinhanlei, You are welcome. No problem, we are here to help :)
