### ISSUE TITLE
AndroidJNIModule

### ISSUE THREAD

**Issue by AceViralKyle** [EvilMindDevs/hms-unity-plugin#52]
Imported latest plugin version: v1.1.2 for 2019
Unity Version: 2019.1.14
Mono

`Assets\Huawei\Scripts\Account\AccountManager.cs(18,38): error CS0012: The type 'AndroidJavaObject' is defined in an assembly that is not referenced. You must add a reference to assembly 'UnityEngine.AndroidJNIModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'`.

I am getting the same error in RewardAdManager also.
I can't find the AndroidJNI module in package manager which seems to be what it's wanting. Should I use the 2018 version of the plugin instead?

**Comment by m0skit0** [comment]
Hi! It seems you're using the wrong plugin version for your Unity version, please double check you're using the 2019 plugin for Unity 2019. If you had the plugin before, please make sure you delete all DLLs under Assets\Huawei\Dlls and import again.

**Comment by AceViralKyle** [comment]
Yeah I was using 2019.1.14 and it seems the JNI Module didn't come into Unity until 2019.2 so I have updated to that Unity version and all is well. Thanks :)

**Comment by m0skit0** [comment]
Oh I didn't know that, thanks for clarifying it.
