### ISSUE TITLE
Latest version of AppAssistant

### ISSUE THREAD

**Issue by AceViralKyle** [EvilMindDevs/hms-unity-plugin#53]
Unity Version: 2019.2.21
Mono
Test Device: Oppo A37fw & Huawei Y7
Plugin Version: 1.1.2

When I try and Show Leaderboards I get a pop up telling me I need the latest version of AppAssistant. After looking in Huawei App Gallery AppAssistant isn't available for the devices. I have Games Services Turned on (Which seems to be App Assistants predecessor) but that doesn't seem to work.

Any advice? Thanks in advance

**Comment by m0skit0** [comment]
Can you please specify what are the versions for EMUI and AppGallery on the phones?

**Comment by AceViralKyle** [comment]
The Huawei is on EMUI 5.1 and AppGallery v10.5.0.303
The Oppo runs ColorOS (v3.0.0) and I have AppGallery v10.5.0.301

**Comment by m0skit0** [comment]
Can you please update the EMUI on the Huawei phone and see if that fixes the problem?

**Comment by sametguzeldev** [comment]
Closed due to inactivity.
