### ISSUE TITLE
UnityPurchasing

### ISSUE THREAD

**Issue by AceViralKyle** [EvilMindDevs/hms-unity-plugin#54]
Hello,

Sorry for the many questions I'm asking haha.

So I'm trying to get our game which is currently set up to work with Android and iOS to work with Huawei/App Gallery. We have scripts that are made to work with Unity's IAP package. I've noticed in your plugin that there may be some functionality for this with Huawei's store.
I've changed the builder to what is in the code comments:
```
`/*
 * Use UnityPurchasing.Initialize(this, ConfigurationBuilder.Instance(HuaweiPurchasingModule.Instance())); 
 * to bind HmsPlugin as store module for builtin purchasing API
 * */`
```

However our billing script is failing to initialise. Is there more I need to change/add in to make this work with App Gallery or do I need to change our IAPs to work with the IAP Managers? I can't see anything about this in the Readme.

**Comment by m0skit0** [comment]
No worries, questions and feedback are welcome :)

Can you please specify which API are you using exactly for IAP?

**Comment by AceViralKyle** [comment]
I'm using Unity IAP version 2.0.6 :)

**Comment by m0skit0** [comment]
Sorry, I'm confused. What does that have to do with our plugin?

**Comment by AceViralKyle** [comment]
Ohh did you mean what version of your plugin I'm using? I'm using v1.1.2. In the file structure there is the HuaweiPurchasingModule and HuaweiStore files which seem to have functionality to work with Unity IAP. Am I incorrect here?

**Comment by m0skit0** [comment]
Yes, ok so you're using UDP IAP through our plugin, that's what I needed to know. That part was collaborated by a third-party developer, I really don't know anything about UDP IAP, sorry. What I know is some other devs already successfully incorporated it. Note that UDP IAP is pretty limited and it doesn't have support for everything Huawei SDK actually offers.

**Comment by AceViralKyle** [comment]
We only have Consumables and Non-Consumables so hopefully UDP can work okay for us. Could you possibly point me in the direction of those devs who got it working so I can ask them how they did it? Or to the third party who implemented the UDP functionality? :)

**Comment by FodderMK** [comment]
We don't have subscriptions or non-consumable products in our game, and it looks like you can't send an empty list to `ObtainProductInfo`.  This is what I was seeing in the logs:

```
I hms_pay : hms_pay    SkuDetailRequest, enter onRequest(s)
I hms_pay : hms_pay    SkuDetailRequest, enter onRequest
I hms_pay : hms_pay    isReqValid, skuIds is null or empty.
I hms_pay : hms_pay    SkuDetailRequest onRequest, request is null
I hms_pay : hms_pay    returnCode: 60001, message: param error
```

According to the [Common Result Code](https://developer.huawei.com/consumer/en/doc/development/HMS-References/iap-ExceptionHandlingAndGeneralErrorCodes-v4) error 60001 is `OrderStatusCode.ORDER_STATE_PARAM_ERROR`.  I'm just guessing that the empty list of skus is considered invalid and that's why 60001 is being returned.

I was able to get the store initialized by adding the following code to `HuaweiStore.CreateProductRequest()`:

```csharp
// If there are no ids then continue
if (consumablesIDs.Count == 0) {
	onSuccess();
	return;
}
```

**Comment by TheHeksiii** [comment]
> We don't have subscriptions or non-consumable products in our game, and it looks like you can't send an empty list to `ObtainProductInfo`. This is what I was seeing in the logs:
> 
> ```
> I hms_pay : hms_pay    SkuDetailRequest, enter onRequest(s)
> I hms_pay : hms_pay    SkuDetailRequest, enter onRequest
> I hms_pay : hms_pay    isReqValid, skuIds is null or empty.
> I hms_pay : hms_pay    SkuDetailRequest onRequest, request is null
> I hms_pay : hms_pay    returnCode: 60001, message: param error
> ```
> 
> According to the [Common Result Code](https://developer.huawei.com/consumer/en/doc/development/HMS-References/iap-ExceptionHandlingAndGeneralErrorCodes-v4) error 60001 is `OrderStatusCode.ORDER_STATE_PARAM_ERROR`. I'm just guessing that the empty list of skus is considered invalid and that's why 60001 is being returned.
> 
> I was able to get the store initialized by adding the following code to `HuaweiStore.CreateProductRequest()`:
> 
> ```cs
> // If there are no ids then continue
> if (consumablesIDs.Count == 0) {
> 	onSuccess();
> 	return;
> }
> ```

Hey, is this plugin usable with Unity IAP service? Just by changing Purchasing Module? There's tutorials everywhere for using IAPManager and other plugin specific code. But HuaweiPurchasingModule is present, so it should work with Unity IAP right?

**Comment by catinjar** [comment]
@FodderMK Your fix was actually helpful, thank you! I think, it should be added to the plugin.
