### ISSUE TITLE
ERROR on Consumable ObtainInfo

### ISSUE THREAD

**Issue by TheHeksiii** [EvilMindDevs/hms-unity-plugin#55]
Hello there, i can't seem to get IAP product info. 
I'm using Release v1.1.2 on Unity 2019.4.1f1.
Login succeeds. 
Private key is set on huawei's side.
I have placed agconnect-services.json into Assets/Huawei folder.
i'm building with build number 1 above the store one,
In Unity Project Settings at the end, i only have checked "Custom Main Manifest". Built with IL2CPP, .Net4 or .net standard 2.0(no difference in error).
I have also created new project and imported the hms plugin, i have the same problem. We checked the product list on huawei dashboard, IAP is enabled too.

Is there any way to get more helpful error so we know what's the cause of our problem? Thanks

![image](https://user-images.githubusercontent.com/16806036/89399931-737ace80-d713-11ea-99e4-3b9ae1fc2911.png)

**Comment by volvoxgames** [comment]
Still continue your issue? I faced same trouble at my project 👎

**Comment by TheHeksiii** [comment]
Yes, no matter in what Unity version i import the plugin, IAP doesnt work. Seems strange that login works but i cant access products. If plugin developer doesnt respond, we're gonna contact AppGallery support and try to resolve the issue.

**Comment by TheHeksiii** [comment]
Update
Unity project still doesn't work, but obtaining product info from huawei's example android app (https://developer.huawei.com/consumer/en/codelab/HMSInAppPurchase/index.html#8) works well.

**Comment by volvoxgames** [comment]
> Update
> Unity project still doesn't work, but obtaining product info from huawei's example android app (https://developer.huawei.com/consumer/en/codelab/HMSInAppPurchase/index.html#8) works well.
> Update 2
> I'm dealing with other problems now, BUT i can now obtain product info in our game. All i had to do was build the project with "Export project" checkbox checked, open it in Android Studio, add agconnect.json to the "launcher" project and build.

Did you add your json file or add example project's json file?

**Comment by TheHeksiii** [comment]
> > Update
> > Unity project still doesn't work, but obtaining product info from huawei's example android app (https://developer.huawei.com/consumer/en/codelab/HMSInAppPurchase/index.html#8) works well.
> > Update 2
> > I'm dealing with other problems now, BUT i can now obtain product info in our game. All i had to do was build the project with "Export project" checkbox checked, open it in Android Studio, add agconnect.json to the "launcher" project and build.
> 
> Did you add your json file or add example project's json file?

I added my own agconnect.json file i downloaded from the AppGallery Connect Project page.

**Comment by luckynamal** [comment]
> Hello there, i can't seem to get IAP product info.
> I'm using Release v1.1.2 on Unity 2019.4.1f1.
> Login succeeds.
> Private key is set on huawei's side.
> I have placed agconnect-services.json into Assets/Huawei folder.
> i'm building with build number 1 above the store one,
> In Unity Project Settings at the end, i only have checked "Custom Main Manifest". Built with IL2CPP, .Net4 or .net standard 2.0(no difference in error).
> I have also created new project and imported the hms plugin, i have the same problem. We checked the product list on huawei dashboard, IAP is enabled too.
> Is there any way to get more helpful error so we know what's the cause of our problem? Thanks
Hello Bro. bro I am trying to Login but I don't know why login is creating error. I followed the official toturial by the way. I think there is problem from AppGallary Console.

**Comment by luckynamal** [comment]
Hi There. 
![error1](https://user-images.githubusercontent.com/5052916/90771941-68c45a00-e30d-11ea-8944-296b20af3ef2.PNG)
![error2](https://user-images.githubusercontent.com/5052916/90771955-6eba3b00-e30d-11ea-82da-2f912e46b8f4.PNG)
![error3](https://user-images.githubusercontent.com/5052916/90771967-724dc200-e30d-11ea-951e-aa9a735dfc01.PNG)

I am facing the login issue. can anyone help? I followed the official tutorial by the way.

**Comment by TheHeksiii** [comment]
> Hi There.
> 
> I am facing the login issue. can anyone help? I followed the official tutorial by the way.

Try using the 2019 version. When i used the 2018 version of the plugin, i couldn't login either

**Comment by gmYusuf** [comment]
> Hi There.
> ![error1](https://user-images.githubusercontent.com/5052916/90771941-68c45a00-e30d-11ea-8944-296b20af3ef2.PNG)
> ![error2](https://user-images.githubusercontent.com/5052916/90771955-6eba3b00-e30d-11ea-82da-2f912e46b8f4.PNG)
> ![error3](https://user-images.githubusercontent.com/5052916/90771967-724dc200-e30d-11ea-951e-aa9a735dfc01.PNG)
> 
> I am facing the login issue. can anyone help? I followed the official tutorial by the way.

Can you share AccountSignIn.cs codes?
