### ISSUE TITLE
Problem setting setNonPersonalizedAd

### ISSUE THREAD

**Issue by perekstig** [EvilMindDevs/hms-unity-plugin#56]
I try to set the personalized ads with this code:

       HwAds.RequestOptions.ToBuilder().SetNonPersonalizedAd(NonPersonalizedAd.ALLOW_ALL).Build();  

And it generates an exception:
AndroidJavaException: java.lang.NoSuchMethodError: no non-static method with name='setNonPersonalizedAd' signature='(I)Ljava/lang/Object;' in class Ljava.lang.Object;
08-13 10:37:24.293 10754 24546 E Unity   : java.lang.NoSuchMethodError: no non-static method with name='setNonPersonalizedAd' signature='(I)Ljava/lang/Object;' in class Ljava.lang.Object;
08-13 10:37:24.293 10754 24546 E Unity   : 	at com.unity3d.player.ReflectionHelper.getMethodID(Unknown Source:167)
08-13 10:37:24.293 10754 24546 E Unity   : 	at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
08-13 10:37:24.293 10754 24546 E Unity   : 	at com.unity3d.player.UnityPlayer.c(Unknown Source:0)
08-13 10:37:24.293 10754 24546 E Unity   : 	at com.unity3d.player.UnityPlayer$e$2.queueIdle(Unknown Source:72)
08-13 10:37:24.293 10754 24546 E Unity   : 	at android.os.MessageQueue.next(MessageQueue.java:465)
08-13 10:37:24.293 10754 24546 E Unity   : 	at android.os.Looper.loop(Looper.java:176)
08-13 10:37:24.293 10754 24546 E Unity   : 	at com.unity3d.player.UnityPlayer$e.run(Unknown Source:32)
08-13 10:37:24.293 10754 24546 E Unity   :   at UnityEngine._AndroidJNIHelper.GetMethodID (System.IntPtr jclass, System.String methodName, System.String signature, System.Boolean isStatic) [0x00041] in <d71499eab75645c19df09ba17af9a506>:0 
08-13 10:37:24.293 10754 24546 E Unity   :   at UnityEngine.AndroidJNIHelper.GetMethodID (System.IntPtr javaClass, System.String methodName

**Comment by WrobelKrakow** [comment]
With out it we can show ads in European Union

**Comment by mmontesinos81** [comment]
HI

Please make sure you have the updated DLL for this. If possible replace it and make sure to delete the meta files as it sometimes prevents from updating the file.

Also find here an example on how to set the Builder
HwAds.RequestOptions = HwAds.RequestOptions.ToBuilder().SetTagForChildProtection(1).SetNonPersonalizedAd(0).Build();

**Comment by WrobelKrakow** [comment]
Ok, clearing meta files and project library folder solved this problem.
