### ISSUE TITLE
iapClient.ParsePurchaseResultInfoFromIntent Fails

### ISSUE THREAD

**Issue by TheHeksiii** [EvilMindDevs/hms-unity-plugin#57]
Hey there, my purchasing is not working. The purchase intent is loading, and after half a second of loading, it closes.
![image](https://user-images.githubusercontent.com/16806036/90663114-87f9b380-e249-11ea-81ad-0cd55b9d271b.png)

Result.ErrMsg is "success" and result.ReturnCode is "0", but in the status.StartResolutionForResult((androidIntent)=>...), purchaseResultInfo.ReturnCode is -1;
![image](https://user-images.githubusercontent.com/16806036/90664034-be83fe00-e24a-11ea-8143-f2edfe127b85.png)
![image](https://user-images.githubusercontent.com/16806036/90731391-ed8d8480-e2c9-11ea-9a2f-23010c661487.png)

This happens on every product-consumable and nonconsumable.
Login and retrieving product info works. I'm building for min api level 19, IL2CPP. Unity 2019.4.1f1. Using latest release. Exporting project and in Android Studio i'm adding agconnect.json because that's the only way i could get this to work.

Thanks

**Comment by TheHeksiii** [comment]
These logs might help. It seems like we're getting a response from Huawei iap's backend
![image](https://user-images.githubusercontent.com/16806036/90776442-63114900-e2fa-11ea-810e-62493227cdd0.png)

![image](https://user-images.githubusercontent.com/16806036/90776236-280f1580-e2fa-11ea-8f0d-8969db30bcd5.png)

**Comment by Sempe4** [comment]
Hi. You mantioned that you are using the latest release. Do you mean unitypackage "HMS.Unity.Plugin.for.2019.v1.1.2.unitypackage"? I also had an issue close to yours till I found out that this release contains not the latest HuaweiMobileServices.dll. Try to download plugin from "code" section here, find HuaweiMobileServices.dll there and put it to your project.

**Comment by TheHeksiii** [comment]
> Hi. You mantioned that you are using the latest release. Do you mean unitypackage "HMS.Unity.Plugin.for.2019.v1.1.2.unitypackage"? I also had an issue close to yours till I found out that this release contains not the latest HuaweiMobileServices.dll. Try to download plugin from "code" section here, find HuaweiMobileServices.dll there and put it to your project.

Hi, thanks for the tip, but sadly it didn't work. Did you experience the same behaviour (The purchase intent closes in an instant without errors)? If so, do you mind sending us your HuaweiMobileServices.dll?
