### ISSUE TITLE
Game services Exception 'HuaweiMobileServices.Utils.HMSException'

### ISSUE THREAD

**Issue by Sempe4** [EvilMindDevs/hms-unity-plugin#58]
Hello! I managed to implement iap part using this plugin but now I got stuck with game services.
Currently I managed to signin player just after launching the game,  I can see the game services greetings at the top of the screen but when I try to call methods like ShowLeaderboards, SubmitScore, ShowAchievements I get an exception on logcat:

08-20 14:37:59.291 I/Unity   (8544): [HMS GAMES] ShowLeaderboards ERROR
08-20 14:37:59.293 I/Unity   (8544): HMS Games: ShowLeaderboards ERROR Exception of type 'HuaweiMobileServices.Utils.HMSException' was thrown.

Here is how I'm trying to do it from logcat:

08-20 15:12:21.628 I/Unity   (12446): [HMS]: AWAKE AUTHSERVICE
08-20 15:12:21.630 I/Unity   (12446): [HMS]: GET AUTH
08-20 15:12:21.640 I/Unity   (12446): [HMS]: AUTHPARAMS AUTHSERVICEHuaweiMobileServices.Id.HuaweiIdAuthParams
08-20 15:12:21.783 I/Unity   (12446): [HMS]: RESULT AUTHSERVICEHuaweiMobileServices.Id.HuaweiIdAuthService
08-20 15:12:21.785 I/Unity   (12446): [HMSPlugin]: IAPP manager Init
08-20 15:12:21.929 I/Unity   (12446): [HMS]: Started
08-20 15:12:21.930 I/Unity   (12446): AccountManager (HmsPlugin.AccountManager)
08-20 15:12:21.930 I/Unity   (12446): [HMS]: Sign in HuaweiMobileServices.Id.HuaweiIdAuthService
08-20 15:12:26.030 I/Unity   (12446): [HMS]: SignedIn
08-20 15:12:26.042 I/Unity   (12446): HMS GAMES: Game init
08-20 15:12:26.054 I/Unity   (12446): HMS GAMES init
08-20 15:12:26.054 I/Unity   (12446): HMS GAMES: Setted app
08-20 15:12:26.062 I/Unity   (12446): HMS GAMES: jossClient
08-20 15:12:26.068 I/Unity   (12446): HMS GAMES: jossClient init
08-20 15:12:26.082 I/Unity   (12446): HMS GAMES: Leaderboards init
08-20 15:12:26.086 I/Unity   (12446): HMS GAMES: Achievements init
08-20 15:12:26.646 I/Unity   (12446): HMSP: checkIapAvailabity SUCCESS
08-20 15:12:26.647 I/Unity   (12446): [HMS]: LoadStore
08-20 15:12:26.725 I/Unity   (12446): [HMSP:] GetPlayerInfo Success
08-20 15:12:26.867 I/Unity   (12446): [HMSPlugin]:success0
08-20 15:12:26.872 I/Unity   (12446): [HMSPlugin]: Found 4consumable products
08-20 15:12:27.172 I/Unity   (12446): [HMSPlugin]:success0
08-20 15:12:27.173 I/Unity   (12446): [HMSPlugin]: Found 1 non consumable products
08-20 15:12:29.554 I/Unity   (12446): [HMS GAMES] ShowLeaderboards ERROR
08-20 15:12:29.554 I/Unity   (12446): HMS Games: ShowLeaderboards ERROR Exception of type 'HuaweiMobileServices.Utils.HMSException' was thrown.

Tried a lot but no luck, what have I missed?

**Comment by SnowKrown** [comment]
Same here, no more information just Exception of type` 'HuaweiMobileServices.Utils.HMSException' was thrown. ` when i call SignIn of AccountManager

**Comment by harunuysali07** [comment]
Same here, `'HuaweiMobileServices.Utils.HMSException'` was thrown. when i call ObtainProductInfo from IapManager

**Comment by harunuysali07** [comment]
> Same here, `'HuaweiMobileServices.Utils.HMSException'` was thrown. when i call ObtainProductInfo from IapManager

It's seems you have to at least one item on all product types to proceed ObtainProductInfo function

**Comment by PetrBodnar** [comment]
@SnowKrown  can you tell please, did you solve this? and if yes, how did you do this?

**Comment by Sempe4** [comment]
I didn't solve this issue, still need help

ср, 4 лист. 2020 о 10:44 PetrBodnar <notifications@github.com> пише:

**Comment by PetrBodnar** [comment]
May be you forgot to add fingerprint to Huawei console? (see how to do this here https://developer.huawei.com/consumer/en/doc/development/HMS-Guides/iap-configuring-appGallery-connect)

**Comment by Sempe4** [comment]
I have added the fingerprint. That was needed to make in-app purchasing
work. I managed to implement the iap part.

чт, 5 лист. 2020 о 08:51 PetrBodnar <notifications@github.com> пише:
