### ISSUE TITLE
Interstitial ad clicked but still not loaded

### ISSUE THREAD

**Issue by Noman3869** [EvilMindDevs/hms-unity-plugin#62]
![Capture](https://user-images.githubusercontent.com/29145148/90885549-76f29480-e366-11ea-84a2-6fe6abaa3a39.PNG)
I am using unity 2018.4 with HMS Unity Plugin v1.1.1 2018 release after running it on phone or unity editor i get same log messages and no ad is shown

**Comment by melikeeroglu** [comment]
Hi @Noman3869,
Can I learn the model of the device you are trying to? Did you solve this issue or still continue?

**Comment by Noman3869** [comment]
@melikeeroglu Thanks for response. I was not able to solve the issue and project was published without ads and IAP
