### ISSUE TITLE
CPID 

### ISSUE THREAD

**Issue by Shahab-Mirza** [EvilMindDevs/hms-unity-plugin#67]
I am trying to find out from where i can get the value of the CPID. 
<img width="320" alt="Screen Shot 2020-08-31 at 3 26 54 PM" src="https://user-images.githubusercontent.com/16739602/91711210-f837fb80-eb9e-11ea-8f50-4d8b7b049142.png">

**Comment by TheHeksiii** [comment]
You can find cp_id field in your agconnect-services.json, or in AppGallery Connect Project Setting
![image](https://user-images.githubusercontent.com/16806036/91711679-9075b680-eb86-11ea-91f5-2cbddd774ffa.png)

**Comment by Shahab-Mirza** [comment]
In agconnect-services.json  , It is already written according to package but could not be able to find my CPID.   I am unable to find in AppGallery Connect Project setting.  Can you explain second method in detail ? Thanks !

**Comment by tamorage** [comment]
anyone help us please where to found the CPID id step by step
I write all the necessary information id 
and give me that error 
FileNotFoundException: C:\Program Files\Unity\Hub\Editor\2019.2.12f1\Editor\Data\PlaybackEngines\AndroidPlayer\Apk\UnityManifest.xml does not exist
System.IO.File.Copy (System.String sourceFileName, System.String destFileName, System.Boolean overwrite) (at <567df3e0919241ba98db88bec4c6696f>:0)
System.IO.File.Copy (System.String sourceFileName, System.String destFileName) (at <567df3e0919241ba98db88bec4c6696f>:0)
HmsPlugin.HuaweiEditor.prepareManifest () (at Assets/hms-unity-plugin-master/Assets/Huawei/Scripts/Editor/HuaweiEditor.cs:171)
HmsPlugin.HuaweiEditor.OnGUI () (at Assets/hms-unity-plugin-master/Assets/Huawei/Scripts/Editor/HuaweiEditor.cs:96)
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <567df3e0919241ba98db88bec4c6696f>:0)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.

**Comment by TheHeksiii** [comment]
> Can you explain second method in detail ? Thanks !

Go to https://developer.huawei.com/consumer/en/service/josp/agc/index.html#/myProject
Select your project
Copy the Developer ID
