### ISSUE TITLE
Not working in Unity 2019

### ISSUE THREAD

**Issue by WrobelKrakow** [EvilMindDevs/hms-unity-plugin#7]
Tested Unity 2019.3.13f
In empty project after importing plugin, I have this errors:

`Unloading broken assembly Assets/Huawei/Dlls/HuaweiMobileServices.dll, this assembly can cause crashes in the runtime

Error: Could not load signature of HuaweiMobileServices.Utils.AndroidAccount:.ctor due to: Could not resolve type with token 0100000d (from typeref, class/assembly UnityEngine.AndroidJavaObject, UnityEngine.CoreModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null) assembly:UnityEngine.CoreModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null type:UnityEngine.AndroidJavaObject member:(null) signature:<none>`

**Comment by WrobelKrakow** [comment]
In Unity 2018.4.22f1 it has no errors but it is very hard to downgrade projects

**Comment by WrobelKrakow** [comment]
i find the problem:
UnityEngine.AndroidJavaObject, was moved UnityEngine.AndroidJNIModule meanwhile in Unity 2019.2 so we need other dlls for Unity 2019

**Comment by m0skit0** [comment]
Hello @WrobelKrakow 

Thanks for the feedback. Yes, as you're stating AndroidJavaObject is no longer available in 2019.2. We're working on updating the assembly for 2019 version. We will let you know through here when the DLL is fixed.

**Comment by EstebanVargasR** [comment]
Hello @m0skit0 , first of all thanks for this awesome github repo.

We have the same problem as @WrobelKrakow and we are gonna publish an Unity 2019.3 game to App Gallery in the next few days.

Could you please tell me if you have an estimate time to upload a new version fixing this issue?

Anyways, if you make open source this .dll or tell us where to find its source code we can help you to fix this problem and others that might appears in the future :) 

Kind regards

**Comment by WrobelKrakow** [comment]
You should check when You provide dll's for Unity 2019 if this will still works in 2018(probably not), if no You should prepare different dll's(releases/branches) for Unity 2018/19 versions or drop 2018 support

**Comment by EvilMindDevs** [comment]
Hello,

Yes we are going to need two different Dlls, one for 2018, one for 2019. So we will make two releases one for each version.

We are testing already 2019 version dll, expect to have it soon.

**Comment by m0skit0** [comment]
@EstebanVargasR Will probably upload the dlls tomorrow. The DLLs and the AAR are generated from this repo: https://github.com/m0skit0/hms-sdk-unity. 

You're welcome!

**Comment by m0skit0** [comment]
Uploaded separate DLLs for 2018 and 2019 versions (https://github.com/EvilMindDevs/hms-unity-plugin/commit/097d57df93e1c1d11299185821da0123dc6e4b51). You will need to delete/rename the  DLL you're not using to avoid clashes in compilation.

**Comment by WrobelKrakow** [comment]
Ok, thanks it's working
