### ISSUE TITLE
failed to get merchant info, createOrder fail, returnCode: 6

### ISSUE THREAD

**Issue by TheHeksiii** [EvilMindDevs/hms-unity-plugin#70]
Hello, we're getting an error when trying to make a purchase.
We're getting this error
![image](https://user-images.githubusercontent.com/16806036/92881681-7e5e0880-f40f-11ea-981c-7e2450f775cb.png)
Has anyone here experienced this too? The merchant account is set up, because our other games are working well, and we had the support check it too. agconnect file is up to date.
If you had this error and you fixed it/or your inapps are working well, please share your sdk dll. Thank you

**Comment by sametguzeldev** [comment]
Hello there @TheHeksiii. Have you fixed your issue on this ?
