### ISSUE TITLE
ads issue

### ISSUE THREAD

**Issue by arndom** [EvilMindDevs/hms-unity-plugin#76]
I followed every step but the demo isn't working I keep getting this:

Exception: Field currentActivity or type signature  not found
UnityEngine._AndroidJNIHelper.GetFieldID (System.IntPtr jclass, System.String fieldName, System.String signature, System.Boolean isStatic) (at <38f5bf63e91b4a34816606844fee3a05>:0)

**Comment by gmYusuf** [comment]
Which version do you use Unity?

**Comment by arndom** [comment]
I use version Unity 2019.3.1. sorry about not closing the issue i fixed it
by removing the duplicate providers in my manifest
