### ISSUE TITLE
[Bug] Intent of HuaweiIdAuthService gets stuck and cannot be closed via CancelAuthorization, plus missing failed callback

### ISSUE THREAD

**Issue by VergilUa** [EvilMindDevs/hms-unity-plugin#79]
WTR:
 - Open a Unity Application;
 - Start a sign-in process w/o credentials;
 - Swith to the background on login screen;
 - Open application through the app icon;

 Expected Result: Sign-in failed callback should be sent;
 Actual Result: No callback is sent back to the Unity Application, and it blocks authentication process in background to a halt.

Its possible to catch this situation via Unity OnApplicationFocus, but, its impossible to cancel authorization process. 
(I've tried CancelAuthorization, and its task returns Success - false) 

Which means user will never be able to call authorization after switching back to the Unity application.

**Comment by VergilUa** [comment]
The only way to fix this, was to set UnityActivity launchMode to standard instead of singleTask. 
In this case activities on top aren't destroyed avoiding the issue completely.

Here's details:
[https://forum.unity.com/threads/android-launchmode-why-does-unity-have-it-as-singletask.992683/#post-6448306](url)

**Comment by sametguzeldev** [comment]
I'll test this out and provide a fix if this still persists.
