### ISSUE TITLE
Ads not showing but Test ads shown properly

### ISSUE THREAD

**Issue by younesokok** [EvilMindDevs/hms-unity-plugin#80]
My game show test ads properly but not show real ads
Unity version: 2018.3.17f1
Plugin version (package or commit): HMS.Unity.Plugin.for.2018.v1.1.1.unitypackage
Mono or IL2CPP: IL2CPP
Test device model: Huawei P30
[2020-11-01 12_52_12.log](https://github.com/EvilMindDevs/hms-unity-plugin/files/5470737/2020-11-01.12_52_12.log)

**Comment by VergilUa** [comment]
You need to upload your application to the store first, and setup ads in the console (afaik).

**Comment by younesokok** [comment]
> You need to upload your application to the store first, and setup ads in the console (afaik).

the app is live, and real ads still not showing

**Comment by Guddeisr** [comment]
I had the same problem weeks ago. In the cloud debugging on the Huawei Console you can install your app, simulate an HMS device and display the console while you run it. I figure that I had an error with number 2, that it's problem of network connection. I didn't know what to do, but, actually, today I opened the app and the ads were OK. Maybe was an error of the platform or some like that.

The lists of errors and descriptions are on the link bellow.
https://developer.huawei.com/consumer/en/doc/development/HMS-Guides/ads-sdk-faq

**Comment by younesokok** [comment]
> I had the same problem weeks ago. In the cloud debugging on the Huawei Console you can install your app, simulate an HMS device and display the console while you run it. I figure that I had an error with number 2, that it's problem of network connection. I didn't know what to do, but, actually, today I opened the app and the ads were OK. Maybe was an error of the platform or some like that.
> 
> The lists of errors and descriptions are on the link bellow.
> https://developer.huawei.com/consumer/en/doc/development/HMS-Guides/ads-sdk-faq

thank you Guddeisr,
after using cloud debugging on the Huawei Console and after clicking reward button i get this:
[HMS] Reward ad clicked but still not loaded

**Comment by sametguzeldev** [comment]
> > I had the same problem weeks ago. In the cloud debugging on the Huawei Console you can install your app, simulate an HMS device and display the console while you run it. I figure that I had an error with number 2, that it's problem of network connection. I didn't know what to do, but, actually, today I opened the app and the ads were OK. Maybe was an error of the platform or some like that.
> > The lists of errors and descriptions are on the link bellow.
> > https://developer.huawei.com/consumer/en/doc/development/HMS-Guides/ads-sdk-faq
> 
> thank you Guddeisr,
> after using cloud debugging on the Huawei Console and after clicking reward button i get this:
> [HMS] Reward ad clicked but still not loaded

This means that rewarded ad not loaded yet. Are you calling LoadNextRewardedAd method ?

**Comment by AdCCooN** [comment]
Hello guys,

I was just struggling with this issue of receiving the network error code while me and my team were testing the app that we are developing. For some of us the ads were working and for other they were not. It looks like the problem was the fact the devices which received network error didn't had HMS Core >= 4.0 which is a requirement for Ads to work.

**Comment by sametguzeldev** [comment]
Hello there,
As you've said, unfortunately, HMS Core 4.0 is one of the requirements.
![image](https://user-images.githubusercontent.com/6827857/109646008-af222d80-7b68-11eb-800f-023beadb78b6.png)

**Comment by sametguzeldev** [comment]
@younesokok  what is the HMS Core version on your device?

**Comment by sametguzeldev** [comment]
Closed due to inactivity. Please re-open if issue still persists.
