### ISSUE TITLE
Problem with ads

### ISSUE THREAD

**Issue by SoraKenji** [EvilMindDevs/hms-unity-plugin#81]
Hey, sometime ago I used this library in order to see Interstitial ads on my game. First time worked, but now it's not working at all. I follow all steps and even tried to see if some solutions on others issues worked for me, but no luck.

Can someone help me out? Thank you !

**Comment by gmYusuf** [comment]
Could you please share details logs here?
Thank you

**Comment by sametguzeldev** [comment]
No further info. Closing it.
