### ISSUE TITLE
Typo in InterstitalAdManager

### ISSUE THREAD

**Issue by qbit86** [EvilMindDevs/hms-unity-plugin#83]
There is a typo in the name of the class [InterstitalAdManager](https://github.com/EvilMindDevs/hms-unity-plugin/blob/a7c74f898a6e6c641a847399655a39d8071dbd6b/Assets/Huawei/Scripts/Ads/InterstitalAdManager.cs#L7). Should be:
```
InterstitialAdManager
         ^
```

**Comment by gmYusuf** [comment]
Thank you we will update name of the object.

**Comment by sametguzeldev** [comment]
Typo fixed. Closing it.
