### ISSUE TITLE
Unable to get user informations

### ISSUE THREAD

**Issue by raziel229** [EvilMindDevs/hms-unity-plugin#84]
Hi,
Sorry for my bad english.

Unity 2020.1.0f1
IL2CPP
Plugin 1.1.2
Huawei P40 on cloud debugging

I have : 
 - create new project with AccountDemo scene .
 - Import the package
 - Configure the manifest
 - Add SHA key

When i try log in, the Huawei panel opens correctly and I accept the permissions.
After this, the diplay name is my email masked (with ***)
All informations are empty : email, gender etc... (I try to see it with debug.Log ) 
![image](https://user-images.githubusercontent.com/11391100/98725557-8e558280-2395-11eb-833b-44434267abb8.png)

In logcat (attached file) i have : 
[E/HMSCore/CheckPermissionRequest 28638:6422 :73] Failed to check the permission, appID: 103244777, permission: com.huawei.android.hms.common.jos.off, checkExpiredTimeFlag: 1

In Huawei console the API Account KIT is active
In Unity I uncheck minimify release and Debug

[log.txt](https://github.com/EvilMindDevs/hms-unity-plugin/files/5519872/log.txt)

**Comment by raziel229** [comment]
It may not be related another test on a samsung device with Huawei Mobile Services installed I have an additional error:

11-10 21:05:18.736: E/ModuleLoader(7083): [E/HMSCore/ModuleLoader 7083:2 :112] Instancing module HuaweiIdentity.API failed. java.lang.ClassNotFoundException: com.huawei.hms.identity.AttachBaseContext

[log.txt](https://github.com/EvilMindDevs/hms-unity-plugin/files/5519914/log.txt)

**Comment by gmYusuf** [comment]
Hi for user informations you should update Account Manager script.
This object neede to update parameters "DefaultAuthService"
For example for email information you should set mail.

```
        private static HuaweiIdAuthService DefaultAuthService
        {
            get
            {
                Debug.Log("[HMS]: GET AUTH");
                var authParams = new HuaweiIdAuthParamsHelper(HuaweiIdAuthParams.DEFAULT_AUTH_REQUEST_PARAM).SetEmail().CreateParams();
                Debug.Log("[HMS]: AUTHPARAMS AUTHSERVICE" + authParams);
                var result = HuaweiIdAuthManager.GetService(authParams);
                Debug.Log("[HMS]: RESULT AUTHSERVICE"+ result);
                return result;
            }
        }
```

**Comment by raziel229** [comment]
Thanks very much,
Its working 👍 
You can solve :)
