### ISSUE TITLE
Minors packages content updates

### ISSUE THREAD

**Issue by starmindfr** [EvilMindDevs/hms-unity-plugin#86]
hello

just a suggestion but seems for few people issues could occurs when importing current 1.12 content  : 

-Androidmanifest from package included will delete manifest of application (will be ok on a test project but not on an active project)
-maingradletemplate . DISABLED i dont know what use of this

Compatibility : is this compatible with il2cpp ? could be good to have it written on first page if it's not compatible.

**Comment by sametguzeldev** [comment]
Hello there. We are currently updating the plugin. New version will build with gradle and it won't be needing to modify the AndroidManifest file anymore.
It is and it will continue to be compatible with il2cpp.

Any further questions ? :)

**Comment by sametguzeldev** [comment]
This issue has been solved in newer versions.
