### ISSUE TITLE
Instancing module HuaweiIdentity.API failed. java.lang.ClassNotFoundException: com.huawei.hms.identity.AttachBaseContext

### ISSUE THREAD

**Issue by starmindfr** [EvilMindDevs/hms-unity-plugin#87]
Tried few hours to log in even with demo package it fail 

i am using unity 2019.2.6f1

build done with Mono / net 4.0 on android

i see recuring errors  

`E/ModuleLoader: [E/HMSCore/ModuleLoader 7388:1 :112] Instancing module HuaweiIdentity.API failed. java.lang.ClassNotFoundException: com.huawei.hms.identity.AttachBaseContext`

i app i see

Exeption of type "Huaweimobileservice.utils.hmsexeption" was raised

i dont use minify / proguard 

Edit : login process is still working anyway (figured out i were missing the 256 bits key on store)

**Comment by j4m4lk** [comment]
what key ? do u mean the SHA key required for making signing certificate ?

**Comment by sametguzeldev** [comment]
> what key ? do u mean the SHA key required for making signing certificate ?

He is talking about the key that you need to provide to AppGallery Connect. You need to put your signing key's SHA-256.
Since this issue is resolved. Closing it.
![image](https://user-images.githubusercontent.com/6827857/108496482-29c29180-72bb-11eb-9741-6790478509f4.png)

**Comment by Pkopeckypetr1988c** [comment]
N
