### ISSUE TITLE
Analytic working in current plugin ?

### ISSUE THREAD

**Issue by starmindfr** [EvilMindDevs/hms-unity-plugin#88]
hello i am using the full content of the latest release and i want to enable Analytics in order to start to test it

but when i added the provided code in Editor then i could not get the expected commands like 

HiAnalyticsTools.EnableLog();

As no source match the commands, seems kit is not enable / complete even whith all files in assets/plugins/android

including all files + agconnect-credential-1.0.0.300.aa hianalytics-5.0.3.300.aar" from "...Assets\Plugins\Android"

do i need extra step ?

Also  i see in provided code sample for Analytics : 
AndroidJavaClass("com.unity3d.player.UnityPlayer");
AndroidJavaObject activity = jc.GetStatic<AndroidJavaObject>("currentActivity");

should this be updated to another class ?

**Comment by gmYusuf** [comment]
Did you try Analytics sample?

**Comment by sametguzeldev** [comment]
No further info about the topic. Closing it.
