### ISSUE TITLE
Archive class missing Summary and Details

### ISSUE THREAD

**Issue by patgalfuero** [EvilMindDevs/hms-unity-plugin#90]
Hi, I'm working on game saves currently, and I notice that the Archive class is missing GetSummary and GetDetails method/fields.

I'm working on the 2018 version, but I see the same issue with the 2019 package.

If it weren't a dll, I would add it myself

**Comment by gmYusuf** [comment]
Its not exist now, it will come with next bach soon

**Comment by gmYusuf** [comment]
I have unapproved fork in that we have that functions
https://github.com/gmYusuf/hms-unity-plugin

**Comment by sametguzeldev** [comment]
This properties has been added. Closing int.
