### ISSUE TITLE
ERROR non  Consumable ObtainInfoException of type 'HuaweiMobileServices.Utils.HMSException' was thrown.

### ISSUE THREAD

**Issue by Micro4lik** [EvilMindDevs/hms-unity-plugin#92]
I use latest version plugin - HMS Unity Plugin v1.2.0 and 2019.4.14f1 version of unity.

Test ads working fine, but inap gives errors:
[HMSPlugin]: ERROR non  Consumable ObtainInfoException of type 'HuaweiMobileServices.Utils.HMSException' was thrown.
[HMSPlugin]: IAP ObtainProductInfo failed. Exception of type 'HuaweiMobileServices.Utils.HMSException' was thrown.

<img width="800" alt="thrown" src="https://user-images.githubusercontent.com/34659658/99961278-b1822800-2dc0-11eb-80dc-9367c038994f.PNG">

When looking of IapManager in examples, i can see "// TODO Obtain non-consumables too!".
Does this mean non-consumable purchases just don't work yet, or am I doing something wrong? Please, help.

Added:
Also added SHA256 to the app gallery console; Imported agconnect-services.json to unity project; Also I believe android manifest is correctly configured to my app ids.

**Comment by Micro4lik** [comment]
Ok. I do not know why, but the type of purchase is consumable, although the purchase was created non-consumable.

**Comment by gmYusuf** [comment]
non-consumable purchases also working well. 
Did you add your products to AppGallery with correct type?  If type not match it will fail.
Can you share your IAP scripts?
