### ISSUE TITLE
Analytic is not working

### ISSUE THREAD

**Issue by akirayui** [EvilMindDevs/hms-unity-plugin#98]
Debug mode is on but I can't see any data on AGC App Debugging.
I just realized that the analytics provider has been changed on AndroidManifest.
So I updated the row in same way
`<provider android:name="org.m0skit0.android.hms.unity.provider.AnalyticsContentProvider" android:authorities="com.evilmind.huawei" android:exported="false" android:grantUriPermissions="true"/>`

However, nothing changed.  
Am I missing something?

Edit: I saw this error on log:
E/HiAnalyticsSDK: HiAnalyticsInstanceManager=> IE-003|The Analytics Kit is not initialized.

Why?

**Comment by gmYusuf** [comment]
Hi,
- Update this with your package name > android:authorities="com.evilmind.huawei" 
- Put your agconnect-services.json file to Assets\Plugins\Android\assets path
- Check your AGC configs https://developer.huawei.com/consumer/en/doc/development/HMSCore-Guides/android-config-agc-0000001050163815

**Comment by gmYusuf** [comment]
Analytics lib dependency is like this:
![image](https://user-images.githubusercontent.com/8115505/101374858-c3cf8c00-38bf-11eb-97be-b34a85f1743e.png)
You can find sdk here:
https://github.com/gmYusuf/hms-unity-plugin/tree/master/Assets/Plugins/Android
We will fix this bug

**Comment by sametguzeldev** [comment]
This bug is fixed and this will not be needed on 2.0 version of this plugin. Closing it.
